### ISSUE TITLE
How to Schedule ModelSaver after X iterations not X epochs?

### ISSUE THREAD

**Issue by Neltherion** [ppwwyyxx/tensorpack#101]
I'm trying to use the ILSVRC 2012 dataset on Tensorpack and I want to see Tensorboard image summaries while the network is learning but since there are so many images I can't wait for `PeriodicCallback` to call `ModelSaver()` after each epoch and I want to check the outputs every X iterations (for example after a hundred iterations).

is this possible?

**Comment by PatWie** [comment]
You can use

````python
step_per_epoch=500
````

Then the callbacks will be trigger. This is also related to #39

**Comment by Neltherion** [comment]
Great! Thanks...

by the way, I wanted to use steps_per_epoch so that I could see the image summaries in Tensorboard but this ends up pretty costly... for example after every 5 epochs the logfile `events.out.tfevents.148441180....` gets updated with the summaries but we also end up with huge model files like `model-5.data-00000-of-00001` which is in my case a 670MB file... now this gets repeated and after 10 epochs we have 10x670MB less storage...

can we update the summaries just fine while just overwriting the model file so that in the end we end up with one model instead of one for every step of the way?

**Comment by PatWie** [comment]
How many images do you want to dump after each epoch?

I use something related in my private examples to generate an animation from image files. 
There is a small writeup how I export Images directly to JPEG without `tf.summary` in  [OnlineExporter](http://tensorpack.readthedocs.io/en/latest/casestudies/colorize.html#callbacks). There are two ways:
- preload some images
- use another dataflow instance

**Comment by ppwwyyxx** [comment]
@Neltherion You can use for example `PeriodicCallback(ModelSaver(), 10)` to let ModelSaver get triggered less frequently.
A better solution will be there after step-callbacks are ready.

**Comment by Neltherion** [comment]
> A better solution will be there after step-callbacks are ready.

Then I'll be waiting... Thanks!

**Comment by ppwwyyxx** [comment]
@Neltherion  Now you can use `PeriodicTrigger(ModelSaver(), every_k_steps=100, every_k_epochs=1)` to trigger the saver every epoch, and also every 100 steps (the counter was reset every epoch).

Also, [ModelSaver](http://tensorpack.readthedocs.io/en/latest/modules/tensorpack.callbacks.html#tensorpack.callbacks.ModelSaver) has some other options to automatically delete old checkpoints to save disk space.
