### ISSUE TITLE
Tensorpack output graph format

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#106]
What is the output graph format from tensorpack?
I was trying out code from https://petewarden.com/2016/05/03/how-to-quantize-neural-networks-with-tensorflow/ and I am getting errors on the input format.

bazel-bin/tensorflow/tools/quantization/quantize_graph --input=graph-0109-190626.meta --output_node_names="softmax" --output=quantized_graph.pb --mode=eightbit

Error is in
File "/home/uid/.cache/bazel/_bazel_uid/655463b6d20ac8353a5d5c1bdf71ab9c/execroot/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/tools/quantization/quantize_graph.runfiles/protobuf/python/google/protobuf/internal/decoder.py", line 469, in _ConvertToUnicode
    return local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 138: 'utf8' codec can't decode byte 0x80 in position 138: invalid start byte in field: tensorflow.NodeDef.op

**Comment by ppwwyyxx** [comment]
The xxx.meta generated by tensorpack is a MetaGraphDef protobuf.
The scripts expects a GraphDef protobuf.

You can take GraphDef from a MetaGraphDef like this:
```python
from tensorflow.core.protobuf import meta_graph_pb2
G = meta_graph_pb2.MetaGraphDef()
data = open('input.meta.pb', 'rb').read()
G.ParseFromString(data)
G = G.graph_def
open('graph.pb', 'wb').write(G.SerializeToString())
```.

I'm not sure if it will work for the script then. I don't know what that script is doing.
