### ISSUE TITLE
Inception final trained model files

### ISSUE THREAD

**Issue by thadpasce16** [ppwwyyxx/tensorpack#109]
Any chance you could upload the final trained Inception models (bn and v3)? Will be helpful for fine tuning and transfer learning studies. 
Thanks

**Comment by ppwwyyxx** [comment]
They are available in the [model zoo](https://drive.google.com/drive/u/3/folders/0B9IPQTvr2BBkM0dUYTdZdm1YenM).

Btw, I read that simpler architectures like VGG/resnet is better in terms of transfer learning than inception.
