### ISSUE TITLE
Is there a bug in imgaug

### ISSUE THREAD

**Issue by lsy643** [ppwwyyxx/tensorpack#11]
Hi, I have been recently using your great tensorpack, but I think the imgaug part may seem exists some bug.
The code below just flip a dataflow, and the result is rather confusing. Perhaps you can try and see the result?

`
%matplotlib inline
import matplotlib.pyplot as plt
from tensorpack import *
from tensorpack.tfutils.symbolic_functions import *
from tensorpack.tfutils.summary import *

cifar10 = dataset.Cifar10('train', shuffle=False)
cifar10.reset_state()
for img_label in cifar10.get_data():
    plt.figure()
    plt.imshow(img_label[0])
    break

flip_cifar10 = AugmentImageComponent(cifar10, [imgaug.Flip(horiz=True, prob=1.0),])
flip_cifar10.reset_state()    
for img_label in flip_cifar10.get_data():
    plt.figure()
    plt.imshow(img_label[0])
    break  
`

**Comment by ppwwyyxx** [comment]
haven't had a chance to look. is there still an issue?
