### ISSUE TITLE
IFM and OFM sizes

### ISSUE THREAD

**Issue by thadpasce16** [ppwwyyxx/tensorpack#111]
Need help. For some reason the input and output activation map sizes are not printed for me. I am importing a model definition from tf-slim and using everything else from inceptionv3.py file

Here is what I am doing:

```
#inception_resnet_v2 file is from https://github.com/tensorflow/models/blob/master/slim/nets/inception_resnet_v2.py
from inception_resnet_v2 import *

##everything is similar to inceptionv3.py

 def _build_graph(self, input_vars):
          image, label = input_vars
          image = image / 255.0
 
          #model define
          is_training = get_current_tower_context().is_training
          arg_scope = inception_resnet_v2_arg_scope
          with slim.arg_scope(arg_scope()):
                logits, end_points = inception_resnet_v2(image, is_training=is_training)
 
                if 'AuxLogits' in end_points:
                   loss1 = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=end_points['AuxLogits'], l    abels=label)
                   loss1 = tf.reduce_mean(loss1, name='loss1')
```

When I start the training process the input and output shapes are not printed (the way they are printed for alexnet-imagenet for instance).

What am I doing wrong here?

**Comment by ppwwyyxx** [comment]
The printing only happens if you use the layers defined in [tensorpack.models](http://tensorpack.readthedocs.io/en/latest/modules/tensorpack.models.html).

You can use slim but slim doesn't have the print feature.

**Comment by a-maci** [comment]
Hi -- I am following the method you described here to restore the inception_resnet_v2 checkpoint but getting some errors. See issue #148 

Did you face any such problems? Were you able to train the network end-to-end?

Thanks

**Comment by thadpasce16** [comment]
No, sorry. I didnt work on this. I was setting up for training rather than
resuming from a checkpoint.
I couldnt get the training process to work back then.
