### ISSUE TITLE
Continuous A3C implementation

### ISSUE THREAD

**Issue by flashgm** [ppwwyyxx/tensorpack#113]
I seem to get very good results with your current A3C demo. I was wondering if you had any plans on implementing an example of the continuous A3C as documented here. https://arxiv.org/abs/1602.01783

I am interested in seeing how it performs on some of the GYM enabled continous control problems and MuJoCo systems.

**Comment by ppwwyyxx** [comment]
Thanks. I don't have plans for that in the near future.

**Comment by andrewliao11** [comment]
hi @flashgm , I just implemented continuous a3c in pytorch [here](https://github.com/andrewliao11/pytorch-a3c-mujoco).
Looking forward to your comments

**Comment by ppwwyyxx** [comment]
We don't take "paper implementation request". Closing now.
