### ISSUE TITLE
Error whe using Callback for the Colorization example

### ISSUE THREAD

**Issue by Neltherion** [ppwwyyxx/tensorpack#116]
I'm trying to use a callback for the colorization example but I get the `[NotImplementedError]` when this line runs:

`        self.trainer.get_predict_func(input_names=['luminance'], output_names=['gen/prediction'])
`

it calls the method from `tensorpack-master/tensorpack/train/base.py` and the method returns the `[NotImplementedError]`. 

What should I do to be able to make a normal callback class? is my Tensorpack version old?

**Comment by ppwwyyxx** [comment]
The documents only contain snippets but not a complete script, so there might be confusions.
What trainer are you using? It looks like you're using "Trainer" , but "Trainer" is just a base class. You should use "SimpleTrainer" or "QueueInputTrainer".
Since there isn't a complete script you might meet other problems as well. Currently all the tutorial pages are just drafts, that's why there isn't a link to the tutorial. You can take a look at examples/ to find some actual scripts.

**Comment by Neltherion** [comment]
Thanks... I'll take a look and hopefully will close the issue soon...

**Comment by Neltherion** [comment]
Right now I'm using the Image2Image example for colorization and just want to add a callback for converting the LAB images and saving them. I've made modifications so that the code accepts LAB images but the last part is to modify it for the callback...right now I don't know how to modify Image2Image to accept the Callback...

**Comment by ppwwyyxx** [comment]
Yes the GAN trainer doesn't implement the interface so it's using the base class.
One simple way to make GANTrainer support inference, is:
```
--- i/examples/GAN/GAN.py
+++ w/examples/GAN/GAN.py
@@ -7,7 +7,8 @@ import tensorflow as tf
 import numpy as np
 import time
 from tensorpack import (FeedfreeTrainerBase, TowerContext,
-                        get_global_step_var, QueueInput, ModelDesc)
+                        get_global_step_var, QueueInput, ModelDesc,
+                        MultiPredictorTowerTrainer)
 from tensorpack.tfutils.summary import add_moving_summary
 from tensorpack.tfutils.gradproc import apply_grad_processors, CheckGradient
 from tensorpack.dataflow import DataFlow
@@ -68,9 +69,10 @@ class GANModelDesc(ModelDesc):
         return [CheckGradient()]


-class GANTrainer(FeedfreeTrainerBase):
+class GANTrainer(FeedfreeTrainerBase, MultiPredictorTowerTrainer):
     def __init__(self, config):
         self._input_method = QueueInput(config.dataflow)
+        self._setup_predictor_factory()
         super(GANTrainer, self).__init__(config)

     def _setup(self):
```
Then you'll be able to use "get_predict_func".

**Comment by Neltherion** [comment]
Sorry for dragging this but running `self._setup_predictor_factory()` results in calling `self._predictor_factory = PredictorFactory(self.sess, self.model, self.config.predict_tower)` but then I get this error : `'GANTrainer' object has no attribute 'sess'`

**Comment by PatWie** [comment]
I use 
````
self._predictor_factory = PredictorFactory(self.sess, self.model, [0])
````

**after** the `super.init`.

**Comment by Neltherion** [comment]
Thanks so much... The problem is gone and the only thing that remains is that there's some sort of scope added to the prediction tensor's name based on the tower.

Here's what I'm calling:

`self.trainer.get_predict_func(input_names=['luminance'], output_names=['gen/prediction'])`

and here's the naming error:

`"The name 'towerp0/gen/prediction:0' refers to a Tensor which does not exist. The operation, 'towerp0/gen/prediction', does not exist in the graph."`

I read your tutorial on how to get the name of tensors in Tensorpack but how should we do it when they are combined in one scope like the code below:

```
 with argscope(Deconv2D, nl=BNReLU, kernel_shape=4, stride=2):
                return (LinearWrap(e8)
                        .Deconv2D('deconv1', NF * 8)
                        .Dropout()
                        .ConcatWith(3, e7)
                        .Deconv2D('deconv2', NF * 8)
                        .Dropout()
                        .ConcatWith(3, e6)
                        .Deconv2D('deconv3', NF * 8)
                        .Dropout()
                        .ConcatWith(3, e5)
                        .Deconv2D('deconv4', NF * 8)
                        .ConcatWith(3, e4)
                        .Deconv2D('deconv5', NF * 4)
                        .ConcatWith(3, e3)
                        .Deconv2D('deconv6', NF * 2)
                        .ConcatWith(3, e2)
                        .Deconv2D('deconv7', NF * 1)
                        .ConcatWith(3, e1)
                        .Deconv2D('prediction', OUT_CH)())
```

**Comment by ppwwyyxx** [comment]
You can use 
```
.Conv2D(....)
.print_tensor()
.Conv2D(...)
```
