### ISSUE TITLE
Problem somehow disappears...

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#126]
Just found a regression.
From the record, `train-atari.py` can run at 9it/s or even faster. (with commit c98f23512, gym0.6.0 release and TF12.0rc0 release).
But with latest tensorpack and TF1.0 it now runs very slow.
Need investigation.

**Comment by PatWie** [comment]
I hope the TF get things fixed. I am a little bit afraid of doing `git pull origin master` inside the TensorFlow-repo to build an updated version.

**Comment by ppwwyyxx** [comment]
This issue is very strange because I'm seeing different speed on two similar machines. May not be a TF issue this time.
