### ISSUE TITLE
Bug OpenCV does not preserve image shape of grayscale images.

### ISSUE THREAD

**Issue by Skylion007** [ppwwyyxx/tensorpack#129]
When I call imaug.GaussianBlur on grayscale images, instead of returning (batch_size, 256, 256, 1) it truncates the grayscaling and just returns an image of shape (batch_size, 256, 256). This is inconsistent with imaug.crop() and imgaug.resize(). I solved my issue by manually resizing the image to be the same dimensions of the input image. I suspect this is an issue with OpenCV in general though, so imaugs that use OpenCV should make sure to explicitly restore the shape of the image.

This leads to errors when feeding the images into the tensor into models.

**Comment by PatWie** [comment]
This is not an issue of tensorpack or `imaug.GaussianBlur`. OpenCV already removes the last dimension

````python
import cv2
img = cv2.imread("original.jpg")
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print grey.shape # is (H, W) instead of (H,W, 1)
````


You should use something like
````python
ds = AugmentImageComponent(ds, [imgaug.MapImage(lambda x: x[..., None])])
````
To get the last axis back.

**Comment by PatWie** [comment]
While I also use grayscale mappings often, I am not sure if it is really a good idea to include this because it depends on the image format rgb or bgr.
You can copy
````python
class Grayscale(ImageAugmentor):
    """
    Convert image to grayscale.
    """

    def __init__(self, keep_dim=False):
        """
        Args:
            keep_dim: return image of shape [H, W, 1] or [H, W]
        """
        self._init(locals())

    def _augment(self, img, _):
        grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        if self.keep_dim:
            grey = grey[..., None]
        return grey
````

into your script.

**Comment by ppwwyyxx** [comment]
Though this is due to opencv, I think it's good to do a reshape inside GaussianBlur to make it less surprising to users (including me).

**Comment by PatWie** [comment]
It is **not** inside GaussianBlur. It is the rgb2gray. At least with opencv 3.1.0.

**Comment by Skylion007** [comment]
Also another point, I am actually not working with grayscale augments, but actually working on a dataset that has grayscale images. Any opencv function call appears to remove the last dimension (not just converting it to grayscale). I am well aware of ways to get the last dimension back and am using them, but I agree with @ppwwyyxx . Unless the operation explicitly changes the shape of an image, it should have the same behavior for multichannel and grayscale images.
