### ISSUE TITLE
Could you teach me how to know the  test accuracy?

### ISSUE THREAD

**Issue by hamuchu** [ppwwyyxx/tensorpack#13]
Thank you for reading my issue.
Could you teach me how to know the test accuracy?
I could know about validation error but I couldn't know how to test the new data which are not used in training phase.

I am trying to use DoReFa Net

**Comment by ppwwyyxx** [comment]
Thanks. https://github.com/ppwwyyxx/tensorpack/blob/master/examples/load-alexnet.py#L60 has a function to load an existing model (through the `session_init` option) and run the model on new data.
In the example it's loading from a dict. You could use `session_init=SaverRestore('train_log/xxx/model-xxx")` if you're loading from a TF-format checkpoint.

DoReFa net examples also contain such functions at [here](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/DoReFa-Net/alexnet-dorefa.py#L246). 
Feel free to ask if it's not clear enough.

**Comment by hamuchu** [comment]
Thank you for your replying.
Your explanation is very clear so that I got confidence to implement it.

I have one more question.
I want to use the function of run_image() in DoReFa  net.
But, I couldn't understand how to specify the argument to run it.
I put the  the command like this.
---------------------------------------------------------------
python alexnet-dorefa.py --run
---------------------------------------------------------------
But it did't work well because the training was started.

Thanks a lot!

**Comment by ppwwyyxx** [comment]
You can see an example in the docstring in `alexnet-dorefa.py`. Something like `--load path/to/model --run a.jpg b.jpg c.jpg`.
Also see `alexnet-dorefa.py --help`.

**Comment by hamuchu** [comment]
Finally I understand the method to use it.
Thank you for your kindness.
