### ISSUE TITLE
InferenceRunner with data parallel

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#139]
Large evaluation tasks such as ImageNet can benefit a lot from data parallel evaluation with multi GPU.

**Comment by PatWie** [comment]
Isn't this already implemented in `DataParallelOfflinePredictor`?

**Comment by ppwwyyxx** [comment]
But currently it's very hard to use it during training. Now there is unfortunately only little code reuse between "predict during training" and "predict after training" (offline predict).

**Comment by ppwwyyxx** [comment]
None of the prefetching technique was applied, therefore the performance of `DataParallelInferenceRunner` is very pool. It's becoming a bottleneck for my training. Reopen.

**Comment by ppwwyyxx** [comment]
- [ ] make a fast dataflow for inference (with epoch-preserving prefetch)
- [x] let InferenceRunner support QueueInput
- [ ] let DataParallelInferenceRunner support QueueInput
