### ISSUE TITLE
Improve the data loading pipeline with stage operators

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#140]
TensorFlow has stage/unstage operators which may further reduce the data feeding overhead, by hiding the latency of one CPU->GPU copy.

Relevant commit: https://github.com/tensorflow/tensorflow/commit/85acf52a

**Comment by PatWie** [comment]
A quick test reveals a speedup factor of ~1.8 on `imagenet-resnet.py`  here when using `StagingTrainer`. But for a proper benchmark the output of tqdm is to unstable.

````python
class PutThread(threading.Thread):
    def __init__(self, trainer, queue, ds, input_placehdrs):
        super(PutThread, self).__init__()
        self.op = self.queue.put(self.placehdrs)


class StageInput(FeedfreeInput):
    def _setup(self, trainer):
        from tensorflow.python.ops import data_flow_ops
        self.input_placehdrs = trainer.model.get_input_vars()
        assert len(self.input_placehdrs) > 0, \
            "STageInput can only be used with input placeholders!"
        if self.queue is None:
            self.queue = data_flow_ops.StagingArea([x.dtype for x in self.input_placehdrs], name='input_queue')
        self.thread = PutThread(
            trainer, self.queue, self.ds, self.input_placehdrs)
        trainer.config.callbacks.append(StartProcOrThread(self.thread))


class StagingTrainer(SyncMultiGPUTrainer):

    def __init__(self, config, input_queue=None, predict_tower=None):
        super(StagingTrainer, self).__init__(config)
        self._input_method = StageInput(config.dataflow, input_queue)

        if predict_tower is not None:
            logger.warn("[Deprecated] Argument `predict_tower` is deprecated for trainer. "
                        "Use TrainConfig.predict_tower instead!")
            config.predict_tower = predict_tower

        self._setup_predictor_factory()
        assert len(config.tower) >= 1, "MultiGPUTrainer must be used with at least one GPU."
        assert tf.test.is_gpu_available()
````

**Comment by PatWie** [comment]
When using ResNet-training it sometimes gives CUDA_OUT_OF_MEMORY:
https://github.com/PatWie/tensorpack-fork/tree/staging

**Comment by ppwwyyxx** [comment]
The result looks very promising!
While writing the tutorial I found the dataflow in imagenet-resnet can be written more efficiently -- should use uint8 image instead of float32, I'll benchmark the dataflow more carefully before looking at integrating staging operators.

StagingArea is on GPU, unlike the queue. So you cannot put too many tensors to it.

**Comment by PatWie** [comment]
I also notice that the `QueueInput` is coupled to all trainers directly and StageInput as simple drop-in replacement (argument) is not possible without using `hasattr` since it lacks many features. 
So this might be only interesting for inference or when using small datasets (MNIST).

**Comment by ppwwyyxx** [comment]
To avoid OOM, we have to pre-fill the staging area with some data, and run stage_op together with train_op (instead of in a separate thread). This will avoid staging area growing too large. This is from tensorflow/benchmarks.
I'm trying this but haven't got any faster yet..

**Comment by ppwwyyxx** [comment]
Able to see some improvements on multigpu training.
ResNet18, batch per GPU=128. Use float32 image. 
Compare StageInputWrapper(QueueInput) with QueueInput:
Each epoch is 50steps. Listing per-epoch time (not including warm up epoch):
1GPU: 17.92s. about the same
2GPU: 18.5s vs 19.6s. 6% faster
4GPU: 19.26s vs 21.6s. 12% faster
6GPU: 20.55s vs 22.9s. 11.5% faster

Ugly code: https://gist.github.com/ppwwyyxx/4e45ab862e0589e2941edc490187ba17

It probably will run faster by getting rid of python threads and use TF pipeline.

**Comment by Skylion007** [comment]
The staging contrib module does not appear to be in the pip build on Google's website. 
from tensorflow.contrib import staging is failing even though I have the latest version of Tensorflow.
