### ISSUE TITLE
Allow distributed training accross multiple machines

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#144]
A good reference might be
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py

**Comment by ahundt** [comment]
I suggest looking at http://pipeline.io/ but I haven't used it.

**Comment by PatWie** [comment]
This issue is about re-implementing the mentioned distributed version within TensorPack and not adding more dependencies. Probably the most straight-forward way is something like a `multiple-devices-sync-trainer`.

**Comment by ahundt** [comment]
Sure, I was only trying to provide a helpful reference. :-)

**Comment by PatWie** [comment]
I seems that this requires much many changes. Current I am not sure how the incoming data can be handle in the "tensorpack" way.

But I managed to produce a minimal working example
https://gist.github.com/PatWie/89950d3f8491a9f0d84125dca0945afa

which I actually tested on the following settings:
- machineA: ps + worker, machineB: worker
- machineA: ps + worker + worker

I will try to add a "distributed.py" to the trainer section.

**Comment by ppwwyyxx** [comment]
Thanks for looking at this!
Frankly I haven't looked at tensorflow distributed training in depth yet. Because I found now it's still hard to feed 8 GPUs on one machine, let alone multiple machines. That's why I'm working on data recently.

btw, TF say they'll publish a "good" example code of distributed training very soon, with the use of GPU StageArea. It'll include the best practice so I guess we can refer to that (rather than finding it out by ourselves) when it come out.

**Comment by ahundt** [comment]
Cool do you have a link to where they reference this?

Also, one advantage of distributed training is you can amortize io to ease feeding the GPUs. Also, as an example in my case I have access to many 2 GPU machines and zero 8 GPU machines.

**Comment by PatWie** [comment]
I looks like there was an annoucement at the devSummit. I rarely see machines that handle 8GPUs and each machine could locally read from the SSD. So the bottleneck would be at some other point.

**Comment by ppwwyyxx** [comment]
Official code and benchmarks were released:
https://www.tensorflow.org/performance/performance_models
https://www.tensorflow.org/performance/benchmarks

I'll study it when I have time and see how much we can integrate them.

**Comment by PatWie** [comment]
Why did you remove the `examples/distributed.py`?

**Comment by ppwwyyxx** [comment]
Just feel mnist is too boring..

**Comment by PatWie** [comment]
But an imagenet Resnet example to just get the usage would be nice.

**Comment by ppwwyyxx** [comment]
Will add some examples.
Note that the code actually doesn't scale very well, neither does the official benchmark in my tests. Their benchmark number appears good but that's on slow K80s so communication is less of a problem. I'll bring the issue to them.

**Comment by PatWie** [comment]
Well, they do have benchmarks on the NVIDIA® Tesla® P100!

**Comment by ppwwyyxx** [comment]
I think that's only on a single machine?

**Comment by PatWie** [comment]
Ah, I see. The NVIDIA® DGX-1 is the $129,000 US monster :scream::laughing:
