### ISSUE TITLE
Integrate tf.train.SessionRunHook into callbacks.

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#147]
The design of `tf.train.SessionRunHook` exactly matches the design of callbacks:
1. begin()  -- setup_graph()
2. after_create_session() -- before_train()
3. before_run() -- extra_fetches()
4. after_run() -- trigger_step()
5. end() -- after_train()

There is no epoch triggers because "epoch" is just a human-defined number of steps. Actually no callbacks in tensorpack now is really relying on "trigger_epoch()" -- they use "trigger()" instead. 

Possible directions:

- [x] Allow wrapping a SessionRunHook to become a callback. This way we can reuse some code there. However I haven't seen really helpful hooks.
- [x] Implement extra_fetches() and trigger_step() with hooks. This way we reuse TF's internal hooks mechanism. Will also solve #125. Not sure how efficient it is.
- [ ] Remove "trigger_epoch" from user callbacks completely. And only allow "triggerable" callbacks which can be triggered either every_k_steps, every_k_epochs or every_k_seconds (the last one borrowed from hooks).

**Comment by ppwwyyxx** [comment]
It seems good to just use `SessionRunHook` to implement callback. Probably will also rename `extra_fetches` and `trigger_step` to `before_run` and `after_run` with similar API.

1. Calling `before_run` every step doesn't have visible overhead.
2. The way `_HookedSession` is implemented is better: it injects the `run` call directly, so the hook is transparent. However with how callback is implemented, you need to use `get_extra_fetches()` and return the results in every `run_step` call.
3. I'll keep both `trainer.sess` and `trainer.monitored_sess` (or add an alias to `trainer.hooked_sess`), so that a custom trainer can choose whether to trigger the hooks in a specific call, just like how it is done in WGAN now. 

A tricky issue:
4. It's better to allow users to trigger the hooks multiple times in one `run_step` call. 
Then how should `global_step` be updated? How should a user customize how `global_step` is updated? This is tricky under the assumption that `global_step` variable should be consistent with `trainer.global_step` as well as `steps_per_epoch`.

**Comment by ppwwyyxx** [comment]
I think `setup_graph` and `before_train` are better names than `begin` and `after_create_session`. Won't do more renaming.

**Comment by ppwwyyxx** [comment]
Just realized there is `tf.contrib.learn.monitors`, also with similar design.

**Comment by PatWie** [comment]
So you are using monitors? They will be deprecated:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/contrib.learn.monitors.md

> DEPRECATED FUNCTION
> THIS FUNCTION IS DEPRECATED. It will be removed after 2016-12-05. Instructions for updating: > Monitors are deprecated. Please use tf.train.SessionRunHook.

https://www.tensorflow.org/versions/master/api_docs/python/contrib.learn.monitors/other_functions_and_classes

> Monitor is deprecated in favor of SessionRunHook. If you're using a monitor, you can wrap it with a hook using function. It is recommended to implement hook version of your monitor.

**Comment by ppwwyyxx** [comment]
I'm not using monitors from tf.contrib. My "monitors" mean something different.
