### ISSUE TITLE
How many steps are there in one epoch in DQN.py

### ISSUE THREAD

**Issue by babanhuihui** [ppwwyyxx/tensorpack#149]
In  DQN, or DDQN papers, they trained it for more 200M. I am just wondering how long would that take? And if I want to totally reproduce the DDQN paper, shall I train for 20000 epochs? 

Thank you so much!

**Comment by ppwwyyxx** [comment]
It was 200M frames if I recalled correctly.
Each iteration here is a batch of 64 frames. It would take about 2.5 days to run 200M frames.

**Comment by ppwwyyxx** [comment]
But this implementation uses different (larger) network architecture and different batch size. To reproduce the score (not the number of frames) you'll only need to run it for about one day.

**Comment by babanhuihui** [comment]
Thanks for your reply. After reading the human level control papaer, I think that in ddqn case. The frame means adding a new transition tuple   (s,a,r,s'). Thus, each step is 4 frames (action repeat). and the system update itself by a minibatch(32). 

Therefore, in our case, I think that we still need to run 50,000,000 steps (5000 epochs ) to get  the result.

**Comment by ppwwyyxx** [comment]
Here, a minibatch was trained after obtaining 4 new transition tuples. This is the "update frequency" parameter in the original paper.
So then I guess you should expect 12500000 steps to be equivalent to 200M frames in the paper, assuming all parameters (batch size, etc) are consistent with the paper.
