### ISSUE TITLE
Image segmentation code available?

### ISSUE THREAD

**Issue by gnujimmik** [ppwwyyxx/tensorpack#15]
Hello,

Thank you very much for sharing your codes, very impressive! Now I am using resnet for some implementation and wondering if you already have image segmentation codes or examples. If you have, would you let me know where to find, please?

Appreciate on your help already!

**Comment by ppwwyyxx** [comment]
I don't have available segmentation code for now. Will have some later.

**Comment by ppwwyyxx** [comment]
I had an example [script](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/HED/hed.py) to reproduce an edge detection paper. Not completely finished but it already trains well. The same architecture (FCN) is supposed to work for image segmentation as well.
