### ISSUE TITLE
problem with git  tensorpack

### ISSUE THREAD

**Issue by Gin8787** [ppwwyyxx/tensorpack#152]
Hi, I am starting to learn about Reinforcement Learning and python. So I tried to git your tensorpack. However, when I execute the instruction: pip install --user -U git+https://github.com/ppwwyyxx/tensorpack.git
I got an error. And the error log is copied to the error_log.txt file.
I've tried to google what's wrong, but I didn't get a good solution. 
So I want to ask if this is caused by my machine. I use a PC with 8G memory, and ubuntu 16.04 os.
And I would appreciate it if you can help me. Thank you~~

[error_log.txt](https://github.com/ppwwyyxx/tensorpack/files/784936/error_log.txt)

**Comment by ppwwyyxx** [comment]
The most likely reason this happens to you is that you installed different versions of some packages at different places and they got messed up. You'll need to google more.
A suggestion is to never run `sudo pip install` on anything. 
One way that might solve your current problem is to `sudo pip uninstall` everything under /usr/local/lib/python2.7/dist-packages/. Not sure if it will work.

**Comment by ppwwyyxx** [comment]
An update after email communication with the user:
on some systems `pip install --user -U pip setuptools` is needed to update pip&setuptools. Otherwise you may see UNKNOWN as the package name.
