### ISSUE TITLE
Aborted (core dumped) when I run the example of GAN

### ISSUE THREAD

**Issue by pzz2011** [ppwwyyxx/tensorpack#157]
print tf.__version__ => 0.12.head
ubuntu version : 16.04
GeForce GTX 1080

while I ran command 
"""
./Image2Image.py --data ./demo --mode AtoB
"""
aborted cames and the message is the following:
"""
I tensorflow/compiler/xla/service/service.cc:180] XLA service executing computations on platform Host. Devices:
I tensorflow/compiler/xla/service/service.cc:187]   StreamExecutor device (0): <undefined>, <undefined>
I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 2 visible devices
I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 56 visible devices
I tensorflow/compiler/xla/service/service.cc:180] XLA service executing computations on platform CUDA. Devices:
I tensorflow/compiler/xla/service/service.cc:187]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
I tensorflow/compiler/xla/service/service.cc:187]   StreamExecutor device (1): GeForce GTX 1080, Compute Capability 6.1
python: external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:218: void Eigen::GpuDevice::memcpy(void*, const void*, size_t) const: Assertion `err == cudaSuccess' failed.
Aborted (core dumped)
"""
I don't know how to solve it now...any advice?thanks.

**Comment by ppwwyyxx** [comment]
It's either a hardware or a cuda/driver problem. That's not something I can solve.
Possible things you can try:
upgrade/reinstall cuda or driver
run with only 1 of the GPU (with CUDA_VISIBLE_DEVICES=0 or 1)
use a newer version of tensorflow (0.12 is not supported by tensorpack) 
reboot

**Comment by pzz2011** [comment]
Sorry, I missed the requirement >= 1.0
I switch to the tf1.0, all things goes well. 
thanks.
