### ISSUE TITLE
Google Drive link is dead

### ISSUE THREAD

**Issue by themissingpieces** [ppwwyyxx/tensorpack#16]
Your google drive link to the pretrained is dead
https://drive.google.com/a/%20megvii.com/folderview?id=0B308TeQzmFDLa0xOeVQwcXg1ZjQ
Please re-up them. Thanks in advanced.

**Comment by ppwwyyxx** [comment]
Could you try again? I can access the link even in google incognito mode.

**Comment by themissingpieces** [comment]
> Could you try again? I can access the link even in chrome incognito mode.

Tried that again. Looks like it's on my side. Sorry for this. Thanks for your respond.
