### ISSUE TITLE
Custom Label for Runs

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#163]
It would be nice to allow a custom label for a specific run rather than the timestamp when choosing "new". This is particular helpful when dealing with different training-sets.

**Comment by ppwwyyxx** [comment]
OK. I think we can ask for a new name when "new" is chosen.

**Comment by PatWie** [comment]
I do not really like the interactive prompt. I would do the following way #164. There should also be a way to not produce any train-logs (something like a debug-mode). Is there any elegant way to handle the entire thing "keep/new/backup/delete" via command line arguments?

**Comment by PatWie** [comment]
I think these are two different information:
- user-defined label
- timestamp from current run

Maybe something like `[scriptname]-[userlabel | default:"default"]-[timestamp]`?

**Comment by ppwwyyxx** [comment]
To not producing any train-logs, just remove ModelSaver from callbacks, and do not set logger dir. The rest should run as usual.

You can just add your action to the argument parser, and both `auto_set_dir` and `set_logger_dir` have the option `action`.

**Comment by PatWie** [comment]
There is a small bug, when loading a check point from the current file and choosing "delete" the loaded checkpoint is delete. Good that I always set my best models to read-only ;-)

**Comment by ppwwyyxx** [comment]
lol I've been there as well deleting my models....
But directory is set at the very beginning before loading the models. I wonder how this can be detected and warned.
