### ISSUE TITLE
image2image does not rescale to 256 at test time 

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#169]
The pix2pix paper scales to 286 and crops to 256 at train time, and just scales to 256 at test time. the latter is missing in the image2image example.

**Comment by ppwwyyxx** [comment]
This is what's done in `sample()`.

**Comment by ppwwyyxx** [comment]
Oh I see. Will add it soon.

**Comment by eyaler** [comment]
fastest response ever!
better use your SHAPE parameter instead of hard-coding 256.
btw, do you think pix2pix could work well for larger images if we change say, 256->512 and 286->572. or would you also change something in the architecture?

**Comment by ppwwyyxx** [comment]
The shape is not very helpful in the script, because the network definitely need some changes if working with a different shape.
Simple extension is to add one more layer and use 512x512 images.

**Comment by ppwwyyxx** [comment]
Relevant discussion about using different shapes: https://github.com/phillipi/pix2pix/issues/56
