### ISSUE TITLE
add random shifts and 90 deg rotations to imageaugmentor (feature request)

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#170]
i suggest adding these 2 common augmentations which i could not find:
random horizontal and/or vertical shifts with arbitrary cv2 border behavior 
90 degree rotations or more generally added a "step" param to Rotation (but make sure that 90 deg rotations are exact)

**Comment by ppwwyyxx** [comment]
The second one is just `imgaug.MapImage(lambda x: cv2.transpose(x))` ?

The first one does look like something others may need, but this probably won't come to top of my todo list very soon. Contributions are welcome.

**Comment by eyaler** [comment]
For the second one we want random 90 deg rotations to 0, 90, 180, 270

I will make a PR
