### ISSUE TITLE
Use TFRecord as a sequential data source

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#174]
LMDB supports random access but is often not useful when you want speed.
TFRecord should be supported as it is a default tensorflow data format.

+ [x] a dataflow which produces raw string or deserialized data from a TFRecord file (use tf.python_io.tf_record_iterator)
+ [x] a function to dump a dataflow to TFRecord file (tf.python_io.TFRecordWriter)
+ [x] benchmark

**Comment by PatWie** [comment]
Please Note, that TF-record files do not support random-access as they contain only compressed information. Even for the number of entries, one need to iterate over the entire DB (similar to the LMDB without having a __keys__ entry).

**Comment by ppwwyyxx** [comment]
On a HDD RAID with 1GB/s bandwidth, running the equivalent of:
```python
ds = LMDBData('/path/to/ILSVRC-train.lmdb', shuffle=False)
ds = BatchData(ds, 256, use_list=True)
```
LMDB sequential: 42it/s
TFRecord sequential 35it/s.

**Comment by asanakoy** [comment]
@ppwwyyxx, interestng. Is LMDB always faster than TFRecord?

**Comment by ppwwyyxx** [comment]
That's what I observed at least. After all LMDB has more low level optimizations.

**Comment by bradyz** [comment]
This is awesome!
