### ISSUE TITLE
Resuming a crashed run

### ISSUE THREAD

**Issue by thadpasce16** [ppwwyyxx/tensorpack#179]
Sometimes while running the application my GPUs crash. How do I resume the run from the last saved model file?
 I saw there is a --load option and choosing "k" for keeping the previous models, but when I use this the resumed run is not exactly the continuation of the previous run. The error rates are off compared to case had the run not crashed.

**Comment by ppwwyyxx** [comment]
It is supposed to be exactly the continuation of the last saved checkpoint. 
Could you provide more information (command, logs)?

**Comment by thadpasce16** [comment]
You are correct. 
I re-checked and its a mistake on my part. I was comparing accuracies across different resnet depth runs.
