### ISSUE TITLE
simple ? - tensorpack not importing

### ISSUE THREAD

**Issue by frolf** [ppwwyyxx/tensorpack#180]
I know this is a simple question, but after trying to resolve it for a good bit I have become too frustrated, as I have had no issues with any other dependencies and I am eager to muck about with tensorpack.

I am running Anaconda virtual env on a local machine. While logged into my tensorflow environment, I installed tensorpack via pip as posted:

pip install --user -U git+https://github.com/ppwwyyxx/tensorpack.git

Installs successfully, and after conda list, the package is listed as installed along with all of the others.

Then when trying to run any of your code examples, or even simply entering python from the terminal and trying "import tensorpack", depending on which directory I am in, the following 3 outcomes happen:

1)   ~ directory where I originally cloned tensorpack:  import tensorpack executes, without opening my cuda library

2)  ~/tensorpack directory:  import tensorpack executes, and successfully opens my CUDA library

and 

3) when in ~/tensorpack/examples/A3C-Gym and trying to either run code or simply import tensorpack , I receive ImportError: No module named 'tensorpack'.

Any suggestion?  Of course when i run conda list regardless of the directory I am currently in, tensorpack is listed as correctly installed via pip.

**Comment by ppwwyyxx** [comment]
Could you post the log of the pip command?
Also, anaconda probably itself does something tricky about packages and import path, though I never used it. I may try it later to see if I can reproduce the problem. 
Meanwhile could you make sure you're using both pip and python from anaconda but not from the system? http://stackoverflow.com/questions/21201003/anaconda-not-finding-my-packages-installed-with-pip

**Comment by frolf** [comment]
running your pip command again from within the virtual environment i wish to use ( universe-starter-agent ), yielded an uninstall and reinstall, then again failing to import (even being run from the tensorpack/examples/A3C-Gym directory)

-----

(universe-starter-agent) shannon@frolfcuda:~/tensorpack/examples/A3C-Gym$ pip install --user -U git+https://github.com/ppwwyyxx/tensorpack.git
Collecting git+https://github.com/ppwwyyxx/tensorpack.git
  Cloning https://github.com/ppwwyyxx/tensorpack.git to /tmp/pip-vtqoc3px-build
  Ignoring subprocess32: markers 'python_version < "3.0"' don't match your environment
  Ignoring functools32: markers 'python_version < "3.0"' don't match your environment
Requirement already up-to-date: numpy in /home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages (from tensorpack==0.1.6)
Requirement already up-to-date: six in /home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages (from tensorpack==0.1.6)
Requirement already up-to-date: termcolor in /home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages (from tensorpack==0.1.6)
Requirement already up-to-date: tqdm>4.11.1 in /home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages (from tensorpack==0.1.6)
Requirement already up-to-date: msgpack-python in /home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages (from tensorpack==0.1.6)
Requirement already up-to-date: msgpack-numpy in /home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages (from tensorpack==0.1.6)
Requirement already up-to-date: pyzmq in /home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages (from tensorpack==0.1.6)
Installing collected packages: tensorpack
  Found existing installation: tensorpack 0.1.6
    Uninstalling tensorpack-0.1.6:
      Successfully uninstalled tensorpack-0.1.6
  Running setup.py install for tensorpack ... done
Successfully installed tensorpack-0.1.6
(universe-starter-agent) shannon@frolfcuda:~/tensorpack/examples/A3C-Gym$ pythonPython 3.5.3 |Continuum Analytics, Inc.| (default, Feb 22 2017, 21:13:27) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorpack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorpack'

**Comment by frolf** [comment]
Also I just created a new environment with conda, same error.

- created brand new environment using conda create -n packin python=3.5
-launched environment

- installed opencv via 'conda install opencv'

-installed tensorflow 1.0 via 'pip install tensorflow-gpu'

- installed tensorpack via 'pip install --user -U git+https://github.com/ppwwyyxx/tensorpack.git'  and received the following output:

(packin) shannon@frolfcuda:~/tensorpack/examples/A3C-Gym$ pip install --user -U git+https://github.com/ppwwyyxx/tensorpack.git
Collecting git+https://github.com/ppwwyyxx/tensorpack.git
  Cloning https://github.com/ppwwyyxx/tensorpack.git to /tmp/pip-qf6uz9ca-build
  Ignoring subprocess32: markers 'python_version < "3.0"' don't match your environment
  Ignoring functools32: markers 'python_version < "3.0"' don't match your environment
Collecting numpy (from tensorpack==0.1.6)
  Using cached numpy-1.12.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already up-to-date: six in /home/shannon/anaconda3/envs/packin/lib/python3.5/site-packages (from tensorpack==0.1.6)
Collecting termcolor (from tensorpack==0.1.6)
Collecting tqdm>4.11.1 (from tensorpack==0.1.6)
  Using cached tqdm-4.11.2-py2.py3-none-any.whl
Collecting msgpack-python (from tensorpack==0.1.6)
Collecting msgpack-numpy (from tensorpack==0.1.6)
  Using cached msgpack_numpy-0.3.9-py2.py3-none-any.whl
Collecting pyzmq (from tensorpack==0.1.6)
  Downloading pyzmq-16.0.2-cp35-cp35m-manylinux1_x86_64.whl (3.0MB)
    100% |████████████████████████████████| 3.0MB 495kB/s 
Installing collected packages: numpy, termcolor, tqdm, msgpack-python, msgpack-numpy, pyzmq, tensorpack
  Found existing installation: tensorpack 0.1.6
    Uninstalling tensorpack-0.1.6:
      Successfully uninstalled tensorpack-0.1.6
  Running setup.py install for tensorpack ... done
Successfully installed msgpack-numpy-0.3.9 msgpack-python-0.4.8 numpy-1.12.0 pyzmq-16.0.2 tensorpack-0.1.6 termcolor-1.1.0 tqdm-4.11.2

------

However when I run 'conda list' in this environment, tensorpack is not in the list now?

Also of course same general error of not importing with no module found.

**Comment by frolf** [comment]
I have since tried uninstalling both from within the environment and outside of it, reinstalling within, etc.   It claims to install successfully, but when using conda list, the package does not come up. And cannot be imported.

But it can be installed, but when it is uninstalled, it shows that the directory is /.local/lib/python3.5/site-packages/tensorpack-0.1.6-py3.5.egg-info

Which is not the virtual environment directory where other packages become installed to and can be uninstalled from.

**Comment by ppwwyyxx** [comment]
Check the stackoverflow link. Does `which pip` give you the correct pip location?

**Comment by ppwwyyxx** [comment]
The problem seems to be:
1. don't use `--user` in anaconda
2. setuptools in anaconda is too old. I upgrade it with `pip install -U setuptools`.

**Comment by frolf** [comment]
I was using the proper pip that was associated with the virtual environment the whole time as evidenced from 'which pip' occasionally.

I have managed to get tensorpack working properly in the virtual environment after a number of uninstalls and reinstalls.  I believe it was resolved by omitting the -user as recommended above.

Thanks for your help!, and you may consider appending the main readme re: installation with noting conda users of virtual environment should omit the --user

**Comment by jeb2112** [comment]
Had a recent issue of this nature, and did not find any direct explanation so leaving this brief comment in case it may help someone. I had an Anaconda 2018.12 Python 3.7.1 environment (not virtual) and attempting to import tensorpack 0.9.1 that was installed via pip but not using --user option. tensorpack would import in python started from command line, and via jupyter notebook, but not in VS2017 community or VS code. A virtual env with Python 3.6.8 was the answer, though not sure if either or both.
