### ISSUE TITLE
Building a model from saved model.data & index

### ISSUE THREAD

**Issue by frolf** [ppwwyyxx/tensorpack#181]
Using the A3C examples:

I am able to run the pre-built models downloaded from the model zoo, say for Breakout with the supplied example command.

I am also able to train my own fresh model via the supplied example, with the training saving to train_log/train-atari

However I am wondering how to go about taking the model-####.data-00000-of-00001 file and the moodel-#####.index information, and creating my own Breakout-v0.tfmodel file which I can then run and record to observe the behavior, as with the downloaded tfmodel from the model zoo.

What is necessary in order to run my own model from said files in order to test/observe it?

**Comment by ppwwyyxx** [comment]
Just --load your `model-xxx.data-xxx` file.
They are not the same format, but `--load` option in the script takes care of both.

**Comment by frolf** [comment]
The following error was returned:

shannon@frolfcuda:~/Desktop/tensorpack/examples/A3C-Gym$ ENV=Breakout-v0; ./run-atari.py --load model-24000.data-00000-of-00001 --env "$ENV" --episode 10 --output /home/shannon/Desktop/trashoutput
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
[0307 14:04:13 @run-atari.py:97] Environment Name: Breakout-v0
[2017-03-07 14:04:13,878] Making new env: Breakout-v0
[0307 14:04:13 @varmanip.py:162] WRN [SaverRestore] ./model-24000.data-00000-of-00001 is corrected to ./model-24000 when restoring the model.
Traceback (most recent call last):
  File "./run-atari.py", line 106, in <module>
    session_init=SaverRestore(args.load),
  File "/home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/tensorpack/tfutils/sessinit.py", line 90, in __init__
    model_path = get_checkpoint_path(model_path)
  File "/home/shannon/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/tensorpack/tfutils/varmanip.py", line 164, in get_checkpoint_path
    assert os.path.isfile(model_path) or os.path.isfile(model_path + '.index'), model_path
AssertionError: ./model-24000

**Comment by ppwwyyxx** [comment]
If you move it out you have to move the index file as well. That's tensorflow requirements.

**Comment by frolf** [comment]
That fixed it and is running properly now. Thanks so much for your quick help and for your impressive contributions to the community.
