### ISSUE TITLE
Resnet new version of code vs old version

### ISSUE THREAD

**Issue by thadpasce16** [ppwwyyxx/tensorpack#182]
The new resnet file does tf.transpose(image, [0, 3, 1, 2]) on the image. This was not done in the previous version of the code.
I have trained resnet model which I had collected a while back using the previous version of the code. If I want to use those models does it suffice to remove this tf.transpose(image, [0, 3, 1, 2]) line from the new code?

**Comment by ppwwyyxx** [comment]
The new version does equivalent computations, but faster. You don't need to do anything.

**Comment by thadpasce16** [comment]
The new one does this tf.transpose(image, [0, 3, 1, 2]) transformation. The old version didnt and the model was produced without this transformation. 
In the new version, when reading the old model, is this transformation handled somewhere internally now?

**Comment by ppwwyyxx** [comment]
The new one uses transpose and NCHW format. The old one uses NHWC format.
