### ISSUE TITLE
some image augmentations fail for single channel

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#184]
some image augmentations (eg flip, shift rotate) fail when image is single channel. we need to add:

`        if img.ndim == 3 and ret.ndim == 2:
            ret = ret[:, :, np.newaxis]
 `

to all image augmentations as it is implemented in resize (perhaps this could be added generically to base)

i also found a similar code in convert:
`
        if self.keepdims:
            if len(transf.shape) is not len(img.shape):
                transf = transf[..., None]
`

**Comment by ppwwyyxx** [comment]
Right. This fix has to be added as long as opencv is involved.
