### ISSUE TITLE
SavedModelBundle

### ISSUE THREAD

**Issue by loweew** [ppwwyyxx/tensorpack#186]
Would be great to allow exporting saved_model format since deployment with cloud ml desires that format. imagenet-resnet.py would be a great example for its utilization.

**Comment by ppwwyyxx** [comment]
Now it saves the variables by `tf.train.Saver` and also save a `MetaGraphDef` protobuf file. These are exactly what a `SavedModel` is saving.
Apart from these, a `SavedModel` also saves assets, tag names for different metagraphs, signatures, etc. These are specific to applications and users, and I don't think I can make decision for users what to save and what not to save. 
If you need these extra features, you can write a new callback just like `ModelSaver` and save what you'd like to save.

**Comment by ppwwyyxx** [comment]
Closing for now.
If you find anything you think is "very common" that should be saved with `ModelSaver` by default you're welcome to reopen.

**Comment by ppwwyyxx** [comment]
Added in #290 a while ago.
