### ISSUE TITLE
how to utilize GPU for image to image translation with conditional GAN

### ISSUE THREAD

**Issue by yanjidriveai** [ppwwyyxx/tensorpack#187]
Hi, I notice in examples/GAN/Image2Image.py, there is this argument

> parser.add_argument('--gpu', help='comma separated list of GPU(s) to use.')

However, when I set it, it seems that no GPU is being utilized by tensorpack. It seems that GANTrainer inherits from FeedfreeTrainerBase, not from SyncMultiGPUTrainer. Does this prevent the training from happening on GPUs?

**Comment by ppwwyyxx** [comment]
The parameter is used to set available gpus and one gpu will be used.
It doesn't support multiple gpus.
