### ISSUE TITLE
How to convert the trained tensorflow model to numpy format that you provided in the DoReFa demo.

### ISSUE THREAD

**Issue by Junsong-Wang** [ppwwyyxx/tensorpack#19]
How to convert the trained tensorflow model to numpy format that you provided in the DoReFa demo? thanks.

**Comment by ppwwyyxx** [comment]
`./scripts/dump-model-params.py --meta train_log/alexnet-dorefa/graphxxxx.meta train_log/alexnet-dorefa/model-xxx output.npy`

**Comment by erdollar** [comment]
Hi,can you help me with my problem during using dump-model-params?
(tensorflow) xxxxx-Precision-Tower-7910:~/tensorflow/DoReFa-Net$ ./dump-model-params.py --meta train_log/alexnet-dorefa1118-000755/graph-1118-000802.meta train_log/alexnet-dorefa1118-000755/model out.npy
Failed to load OpenCL runtime (expected version 1.1+)
Traceback (most recent call last):
  File "./dump-model-params.py", line 35, in <module>
    init = get_model_loader(args.model)
  File "/home/xxxxx/.local/lib/python2.7/site-packages/tensorpack/tfutils/sessinit.py", line 261, in get_model_loader
    return SaverRestore(filename)
  File "/home/xxxx/.local/lib/python2.7/site-packages/tensorpack/tfutils/sessinit.py", line 106, in __init__
    model_path = get_checkpoint_path(model_path)
  File "/home/xxxx/.local/lib/python2.7/site-packages/tensorpack/tfutils/varmanip.py", line 167, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: train_log/alexnet-dorefa1118-000755/model

**Comment by ppwwyyxx** [comment]
I said `model-xxx`, not `model`.

**Comment by erdollar** [comment]
What xxx stands for?

**Comment by ppwwyyxx** [comment]
`model-xxx` means files whose names start with `model-`.

**Comment by erdollar** [comment]
Thank you for your patience. 👍

**Comment by pribadihcr** [comment]
look like .npy not supported now?

**Comment by ppwwyyxx** [comment]
The script itself has documented how to use it. It now uses npz.

**Comment by thlinh** [comment]
@ppwwyyxx : Does tensorpack support reading the *.pb files? If not, could you recommend other tools that can also extract the nets' weights to numpy arrays? Many thanks in advance!

**Comment by ppwwyyxx** [comment]
You should in general read a file by referring to the library that creates the file.
Specifically, if you mean "pb files" created by tensorflow, then tensorflow will have the tool to read it, not tensorpack.
