### ISSUE TITLE
Image Augmentors

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#2]
- [x] Saturation / Hue
- [x] Gaussian noise
- [x] Salt-Pepper noise
- [x] Rotation
- [ ] Perspective

**Comment by PatWie** [comment]
What do you mean by perspective? Something like:

````python
import cv2
import numpy as np

img = cv2.imread("original.jpg")
imageplane_coords = np.float32([[-30, -60],[368,52],[28,387],[389,390]])
worldplane_coords = np.float32([[0,0],[300,0],[0,300],[300,300]])
M = cv2.getPerspectiveTransform(imageplane_coords,worldplane_coords)
dst = cv2.warpPerspective(img,np.random.rand(3,3),(300,300))
cv2.imwrite("output.jpg", dst)
````
?
Should this use a random transformation matrix?

**Comment by ppwwyyxx** [comment]
I was thinking something like that, but I don't know if there is a good way to parameterize this as an augmentor.

**Comment by ppwwyyxx** [comment]
"perspective" may not be very important to use plus I don't have a clear idea what it is or how to parameterize it for people to use. Closing.
