### ISSUE TITLE
A3C batch modification

### ISSUE THREAD

**Issue by hholst80** [ppwwyyxx/tensorpack#20]
I wonder what kind of modification to the original A3C algorithm you have made in your Batch A3C variant? Could you describe it in pseudo code?

**Comment by ppwwyyxx** [comment]
I've released the code for [Atari in Gym](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/OpenAIGym/train-atari.py).
Don't have much document.. but maybe it'll help.

**Comment by revilokeb** [comment]
@ppwwyyxx many thanks your code is really great: out-of-the box learning Pong-v0 on moderately recent hardware (6cores + GPU) in ~11h to a mean score of ~20. Most efficient publicly available A3C (variant) implementation I have come across so far...
