### ISSUE TITLE
problem with BNRelu

### ISSUE THREAD

**Issue by prashantsingh905** [ppwwyyxx/tensorpack#201]
Getting the following error when tryinh to embed Resnet18 to perform regression.
`File "/notebooks/deeppose_tf/scripts/alexnet.py", line 148, in __create_architecture     .Conv2D('conv0', 64, 7, stride=2, nl=BNReLU)   File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/linearwrap.py", line 49, in f     net = layer(name, self._t, *args, **kwargs)   File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/common.py", line 97, in wrapped_func     outputs = func(*args, **actual_args)   File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/conv2d.py", line 72, in Conv2D     return nl(tf.nn.bias_add(conv, b, data_format=data_format) if use_bias else conv, name='output')   File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/common.py", line 106, in wrapped_func     outputs = func(*args, **actual_args)   File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/nonlin.py", line 79, in BNReLU     x = BatchNorm('bn', x)   File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/common.py", line 97, in wrapped_func     outputs = func(*args, **actual_args)   File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/batch_norm.py", line 186, in BatchNorm     use_local_stat = ctx.is_training AttributeError: 'NoneType' object has no attribute 'is_training' root@cc657adc61e7:/notebooks/deeppose_tf/examples# `

**Comment by ppwwyyxx** [comment]
Are you using tensorpack models without tensorpack trainer?

This is not a intended usage. If you really want that you can wrap your model with 
```python
with TowerContext(tower_name='', is_training=True):
```
to let the model work properly.
