### ISSUE TITLE
Better utilities for distributed data processing

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#202]
When 1 machine is not fast enough to process data (due to limited disk speed / cpu speed), distributed data processing can be important.

- [x] Allow PrefetchData to open either IPC socket or TCP socket or both
- [x] A utility function to start a DataFlow and feed to specific zmq socket

This would also allow starting several dataflow instances on a single machine in independent processes, which might be easier to manage. 
A future solution would be #138.

**Comment by ppwwyyxx** [comment]
Brief Documentation: http://tensorpack.readthedocs.io/en/latest/tutorial/efficient-dataflow.html#more-efficient-dataflow

**Comment by byronyi** [comment]
I am interested in providing peer direct DMA support to TF data feeding, following the same spirit of my GDR patch. It seems to be a bottleneck transferring tensors from either network or disk to GPU;
as better and faster GPUs become available in-stock, it would become an important feature for actual deployment, which is often ignored during benchmarking with synthetic data.

With proper hardware (rNIC or NVMe SSD) peer direct DMA could bypass CPU and host memory and feed tensors to GPU directly. 

The tentative design would be re-using the current ZMQ operator to setup control plane, and avoid serialisation and memory copies using direct DMA in the data plane. Batching and pipelining would be helpful to reduce the latency and increase the throughput.

If your cluster has IB/NVMe available, let me know! We are interested in deployments of peer direct DMA in realistic applications, and we'd love to help.

**Comment by byronyi** [comment]
@PatWie Any comments? https://github.com/tensorflow/tensorflow/pull/11392 is our PR to improve model update efficiency during training. It improves `RecvTensor`'s throughput of large tensors (>100MB) from 0.8GB/s to 3.6GB/s on a single machine. I am wondering if the same technique could be applied in data feeding as well.

**Comment by ppwwyyxx** [comment]
Thanks byron for your work in GDR!
We don't use IB in clusters and for data feeding the use of IB could be limited. It reduces the copy latency, but in practice I was never bounded by copy since the latency can usually be hidden.

**Comment by byronyi** [comment]
While copying itself might not be the bottleneck, serialisation might be :) See https://github.com/tensorflow/tensorflow/issues/10530 for the rationale. Removing protobuf serialisation of tensors improves the throughput from 0.5GB/s to 1.5GB/s, so it could be quite significant. In fact, even the gRPC runtime has specialised implementation to avoid serialisation; see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_tensor_coding.h#L51).

**Comment by ppwwyyxx** [comment]
Yes. We didn't use protobuf either.
Our zeromq receiver in Python uses msgpack to deserialize, and our zeromq receiver op just uses memcpy to deserialize.

And deserialization is also just a pre-processing stage -- it can always run asynchronously. As long as it's not too slow it doesn't affect training speed from my experience. But I think there will be scenarios (e.g. much faster GPUs as you said) where it matters.
