### ISSUE TITLE
typo in imgaug.FixedCrop

### ISSUE THREAD

**Issue by byangderek** [ppwwyyxx/tensorpack#205]
There's a typo [here](https://github.com/ppwwyyxx/tensorpack/blob/a9958037ed9f00172e34f447bac3547ee2b1f78f/tensorpack/dataflow/imgaug/crop.py#L79):

`    def _augment(self, img, _):
        return img[self.rect.y0: self.rect.y1 + 1,
                   self.rect.x0: self.rect.x0 + 1]`

should be

`    def _augment(self, img, _):
        return img[self.rect.y0: self.rect.y1 + 1,
                   self.rect.x0: self.rect.x1 + 1]`

**Comment by ppwwyyxx** [comment]
Thanks!
