### ISSUE TITLE
Bug in inference get_output_tensors method

### ISSUE THREAD

**Issue by sujaynarumanchi** [ppwwyyxx/tensorpack#21]
1. _get_output_vars method is not defined, should be _get_output_tensors. 
2. InferenceRunner should call "vc.get_output_tensors()" as opposed to "vc._get_output_tensors()" in line 94.

**Comment by ppwwyyxx** [comment]
Thanks! Fixed in latest commit.

**Comment by ppwwyyxx** [comment]
Oh! I didn't know you had a PR already. Thanks again!

**Comment by sujaynarumanchi** [comment]
My pleasure !
