### ISSUE TITLE
With (W,A,G) set to (1,1,32), it is not equivalent to XNOR-Net. But how to implement the XNOR-Net based on the DoReFa-Net? Could anyone tell me?

### ISSUE THREAD

**Issue by iridescent303** [ppwwyyxx/tensorpack#210]

**Comment by ppwwyyxx** [comment]
This is just a question of how to implement XNOR-Net in tensorflow. You'll have more supports from tensorflow communities.

Basically just first quantize things to 0 and 1 (with tf.sign), and transform it to -1 and 1 (with x * 2 - 1). And use tf.stop_gradient trick to make the backward correct.

**Comment by ppwwyyxx** [comment]
Oops. My mistake. Just realized that tf.sign outputs {-1, 0, 1} already.

**Comment by iridescent303** [comment]
Thanks! Let me try it.
