### ISSUE TITLE
CNN 3D for 3D images

### ISSUE THREAD

**Issue by tmquan** [ppwwyyxx/tensorpack#211]
Hi tensorpack, 

I have a collection of 3D image (multi-page tiff file) and would like to perform classification using 3D CNN. 
My model in original keras code is fine since I reshape the data to (num, dimz, dimy, dimx, dimc). 
Is it possible to have this feature in tensorpack dataflow?

Best regards,

**Comment by ppwwyyxx** [comment]
I don't understand what exactly you want to do here. But you need to implement "how to load the data" yourself anyway, so you can do whatever to your data.

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you still have questions.
