### ISSUE TITLE
where to find the old version tensorpack which supports tensorflow 0.8.0 ?

### ISSUE THREAD

**Issue by zhyiwei** [ppwwyyxx/tensorpack#213]
now i'm going to train a lstm network in tensorflow 0.8.0, i want to use TIMIT dataset , like this: https://github.com/ppwwyyxx/tensorpack/blob/master/examples/CTC-TIMIT/train-timit.py

but now i can only find tensorpack which need  TensorFlow >= 1.0.0 ...  so, could anyone tell me how to install tensorpack for tensorflow 0.8.0 ?

**Comment by ppwwyyxx** [comment]
TF0.8 was like a year ago (around last April). You can checkout to tensorpack a year ago to see how things work. But it's very likely that either tensorflow or tensorpack at that time don't have the utilities to train timit.

**Comment by zhyiwei** [comment]
thanks, i changed version to 1.0
