### ISSUE TITLE
Better to have a listed index for each image augmentor?

### ISSUE THREAD

**Issue by byangderek** [ppwwyyxx/tensorpack#214]
In [AugmentImageComponent](https://github.com/ppwwyyxx/tensorpack/blob/a6745419982de174a1ce7a1a61b88f2940eadd23/tensorpack/dataflow/image.py#L49), there is an index parameter indicating which image component all augmentors are to apply to. 

I think a more general way of implementation is to have that index parameter to be a list rather than a scalar, and make it a parameter for each augmentor. 

An example case for this feature is as follows:
1. we want to do pixel-wise tasks, so the data has two components, one input image, one output label image.
2. we want to use two augmentors, one from [geometry](https://github.com/ppwwyyxx/tensorpack/blob/a6745419982de174a1ce7a1a61b88f2940eadd23/tensorpack/dataflow/imgaug/geometry.py) (so that every time the same effect should be applied to both image and label) and another from [imgproc](https://github.com/ppwwyyxx/tensorpack/blob/a6745419982de174a1ce7a1a61b88f2940eadd23/tensorpack/dataflow/imgaug/imgproc.py) (so that the effect only applies to image).

I know there can always be work-around solutions to realize the above example given current implementation, I just think that there may be a more general way.

**Comment by byangderek** [comment]
Get it.
So in the example case, I just need one `AugmentImageComponents` for geometry and one `AugmentImageComponent` for imgproc.

**Comment by ppwwyyxx** [comment]
Yes. And that's exactly what the [HED example](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/HED/hed.py) did.

**Comment by byangderek** [comment]
thx!
