### ISSUE TITLE
CTC-TIMIT problem

### ISSUE THREAD

**Issue by zhyiwei** [ppwwyyxx/tensorpack#215]
tensorflow version: 1.0.1
cuda version: 8.0

I followed this Tutorial
https://github.com/ppwwyyxx/tensorpack/tree/4a30d18dd9512319ddbe2e7f1503abe45e1e80cb/examples/CTC-TIMIT

but when i ran "./create-lmdb.py build --dataset ./TRAIN --db train.mdb", it printed:

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
[0401 18:00:04 @create-lmdb.py:86] Found 10 wav files ...
  0%|                                                       |0/10[00:00<?,?it/s][0401 18:00:04 @dftools.py:127] Flushing database ...
100%|##############################################|10/10[00:00<00:00,72.11it/s]
Segmentation fault (core dumped)

i just copy the timit data sets( including 10 .PHN files, 10 .TXT files, 10 .WRD files and 10 .wav files ) into ./TRAIN folder

**Comment by ppwwyyxx** [comment]
Cannot reproduce the problem.
This is usually related to environment and setup.

**Comment by zhyiwei** [comment]
@ppwwyyxx 

when i ran "./create-lmdb.py stat --db train.mdb", it printed:

Traceback (most recent call last):
  File "./create-lmdb.py", line 136, in <module>
    compute_mean_std(args.db, args.output)
  File "./create-lmdb.py", line 105, in compute_mean_std
    ds = LMDBDataPoint(db, shuffle=False)
TypeError: __init__() got an unexpected keyword argument 'shuffle'





so i changed "ds = LMDBDataPoint(db, shuffle=False)" --> "ds = LMDBDataPoint(db)" (create-lmdb.py), then run "./create-lmdb.py stat --db train.mdb" again, but now it print:

Traceback (most recent call last):
  File "./create-lmdb.py", line 137, in <module>
    compute_mean_std(args.db, args.output)
  File "./create-lmdb.py", line 108, in compute_mean_std
    with get_tqdm(total=ds.size()) as bar:
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/dataflow/base.py", line 73, in size
    return self.ds.size()
AttributeError: 'str' object has no attribute 'size'



=========================================

i dont know what's wrong with it

**Comment by ppwwyyxx** [comment]
I'll fix it soon.

**Comment by zhyiwei** [comment]
@ppwwyyxx thank you

and I also changed "loss = tf.nn.ctc_loss(logits, label, seqlen, time_major=False)" to "loss = tf.nn.ctc_loss( label, logits, seqlen, time_major=False)" in train_timit.py  ----  I found  that "label" should be the first arg ,because in ctc_ops.py, the function is defined as : 

def ctc_loss(labels, inputs, sequence_length,
             preprocess_collapse_repeated=False,
             ctc_merge_repeated=True, time_major=True):

-----------------------------------------------------------------------------------------

and now I ran "./train-timit.py --train train.mdb --test test.mdb --stat stats.data", it printed :

[0402 13:01:56 @logger.py:69] Argv: ./train-timit.py --train train.mdb --test test.mdb --stat stats.data
[0402 13:01:56 @format.py:82] Found 111 entries in train.mdb
[0402 13:01:57 @format.py:82] Found 11 entries in test.mdb
[0402 13:01:57 @param.py:190] Use train_log/train-timit/hyper.txt to control hyperparam learning_rate.
[0402 13:01:57 @common.py:94] fc input: [None, 128]
[0402 13:01:57 @common.py:102] fc output: [None, 62]

----------------------------------------------
is that right? where should i find the "edit distance"?

**Comment by ppwwyyxx** [comment]
Thanks for finding it out. It looks like tensorflow changed their API at some moment.

What do you mean "find the edit distance"

**Comment by zhyiwei** [comment]
@ppwwyyxx 

https://github.com/ppwwyyxx/tensorpack/tree/4a30d18dd9512319ddbe2e7f1503abe45e1e80cb/examples/CTC-TIMIT
"
Results:

Get 0.28 LER (normalized edit distance) after about 40 epochs.
"
but i didn't find this "normalized edit distance"

**Comment by ppwwyyxx** [comment]
It is named "error" https://github.com/ppwwyyxx/tensorpack/blob/6ba19a977509e911daaea2367cd0aaa62936b37e/examples/CTC-TIMIT/train-timit.py#L75

and get printed every epoch.

**Comment by zhyiwei** [comment]
@ppwwyyxx 
so it looks like my print contents were not correct, i think there may be somgthing wrong in my train.mdb and test.mdb files

would you mind uploading your .mdb files? i'll be very thankful for this

**Comment by ppwwyyxx** [comment]
```
Found 111 entries in train.mdb
Found 11 entries in test.mdb
```
They shouldn't be only contain 111 and 11 elements, if that's what you're really using.
The files are very large I cannot upload them.

**Comment by zhyiwei** [comment]
@ppwwyyxx 
oh, the dataset I used is just a small one
[TIMIT_speech_database.zip](https://github.com/ppwwyyxx/tensorpack/files/888214/TIMIT_speech_database.zip)
