### ISSUE TITLE
os.rename fails on windows when destination files exists

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#216]
File "C:\Anaconda3\lib\site-packages\tensorpack\train\monitor.py", line 206, in _write_stat
    os.rename(tmp_filename, self._fname)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'train_log\\pix2pix\\stat.json.tmp' -> 'train_log\\pix2pix\\stat.json'

**Comment by ppwwyyxx** [comment]
Does `shutil.move` work on windows in this case?

**Comment by eyaler** [comment]
yes
