### ISSUE TITLE
JoinData should work for arbitrary sizes

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#217]
For the new CycleGAN paper the straightfoward way to read data is
```python
ds = []
ds.append(ImageFromFile(glob.glob(os.path.join(datadir, 'trainA', '*.jpg')), channel=3, shuffle=True))
ds.append(ImageFromFile(glob.glob(os.path.join(datadir, 'trainB', '*.jpg')), channel=3, shuffle=True))
ds = JoinData(ds)
```
However, `JoinData` requires all incoming `ds` to have the same size. Why not using:
```python
new_len = min([k.size() for k in self.df_lists])
```
and just run the generator until the first incoming ds is empty. I would edit that, if you have no concerns.

**Comment by ppwwyyxx** [comment]
JoinData is already like that.
And this is also how data is read in the DiscoGAN example.

**Comment by PatWie** [comment]
https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/dataflow/common.py#L417

**Comment by ppwwyyxx** [comment]
The exception is catched and warned.

**Comment by PatWie** [comment]
Ah, I should update my local copy. Sorry.
