### ISSUE TITLE
ResNet example (imagenet-resnet.py) doesn't use minibatch size when --fake flag is set

### ISSUE THREAD

**Issue by FabiEder** [ppwwyyxx/tensorpack#218]
I'm using the example to benchmark with fake data. Changing the TOTAL_BATCH_SIZE defined in imagenet-resnet.py does not change the result/ training time. The call to FakeData(..) in get_data is fixed to a minibatch size of 64 if I am not mistaken. Shouldn't it be something like:

`if fake:
        return FakeData([[BATCH_SIZE, 224, 224, 3], [BATCH_SIZE]], 1000, random=False, dtype='uint8')`

instead of
`if fake:
        return FakeData([[64, 224, 224, 3], [64]], 1000, random=False, dtype='uint8')`?

I might just do something wrong when using --fake, any feedback appreciated! 
Thanks

**Comment by ppwwyyxx** [comment]
You're right. But it's fake anyway.. so it doesn't really matter to me. I can make a change.

**Comment by FabiEder** [comment]
Yes, I just wanted to let you know. 
It worked fine with larger batch sizes! Thanks.
