### ISSUE TITLE
Build ZMQ-operator

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#221]
I tried to compile your custom-operator on my machine and get
```
Compiling user ops ...
make: Entering directory '/home/patwie/git/tensorpack/tensorpack/user_ops'
[dep] zmq_recv_op.cc ...
In file included from zmq_conn.h:8:0,
                 from zmq_recv_op.cc:10:
zmq.hpp:84:36: error: missing binary operator before token "("
 #if ZMQ_VERSION >= ZMQ_MAKE_VERSION(3, 3, 0)
```

Can you shortly comment, which zmq version do you use. I had to change 
```cpp
//#include <zmq.hpp> into
#include "zmq.hpp"
```
and use 
https://github.com/zeromq/cppzmq

But still getting the error.

**Comment by ppwwyyxx** [comment]
I'm using 4.2.1-1.  cppzmq only contains the cpp header but maybe the c header is incompatible.

**Comment by ppwwyyxx** [comment]
It looks like my package manager automatically includes zmq.hpp for me. (https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/zeromq)
And none of the other packaging system seems to do this. Yay archlinux..

**Comment by PatWie** [comment]
After the following commands

```
git clone https://github.com/zeromq/libzmq
cd libzmq
./configure --prefix=$HOME/zeromq
make
make install

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/zeromq/include/zmq.hpp
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/zeromq/lib/pkgconfig/
wget -O $HOME/zeromq/include/zmq.hpp https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp

```

and explicitly adding
```
CXXFLAGS += -I/home/patwie/zeromq/include/ -L/home/patwie/zeromq/lib/ -lzmq
```

I get at least linking errors from tensorflow.

**Comment by ppwwyyxx** [comment]
As long as you did `export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/zeromq/lib/pkgconfig/`, I suppose you don't need `CXXFLAGS += -I/home/patwie/zeromq/include/ -L/home/patwie/zeromq/lib/ -lzmq`.

**Comment by PatWie** [comment]
I have tested it and I have to add it. I currently try to use `bazel`. [Here](https://github.com/PatWie/CppNumericalSolvers) I managed to let bazel download all dependencies automatically.

**Comment by ppwwyyxx** [comment]
Could you confirm `pkg-config --cflags --libs libzmq` produce your CXXFLAGS after setting PKG_CONFIG_PATH?

Also, the Makefile at first doesn't include libzmq in `LIBS`. If that's the case you may need to pull.

**Comment by PatWie** [comment]
You definitely need Gitter or Slack. I will try that.

**Comment by ppwwyyxx** [comment]
https://gitter.im/tensorpack/dev try this

**Comment by PatWie** [comment]
Just a reminder:

As already discussed this only works with the correct protobuf version. When installing TF from source it is easy to find the correct protobuf version in
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L309

Then
```bash
wget https://github.com/google/protobuf/archive/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz
cd protobuf-2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a

replace_by_sed() {   local regex="${1}";   shift;   if echo "${OSTYPE}" | grep -q darwin; then     sed -i '' -e "${regex}" "$@";   else     sed -i -e "${regex}" "$@";   fi; }
replace_by_sed 's#https://googlemock.googlecode.com/files/gmock-1.7.0.zip#http://download.tensorflow.org/deps/gmock-1.7.0.zip#'   "autogen.sh"

./autogen.sh
./configure --prefix=$HOME/protobuf

make -j 4
make install

export LD_LIBRARY_PATH=$HOME/protobuf/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/protobuf/lib/pkgconfig
```

**Comment by PatWie** [comment]
I strongly argue against sending Tensor-Protos over ZeroMQ. I tried to create a C++ example, but the documentation of TensorFlow clearly says, that they want you to put custom C++ code in the TF directory. I vote for using msgpack directly with a custom dataformat to further reduce the overall requirements when sending from C++. This would remove the TensorFlow-dependency.

**Comment by ppwwyyxx** [comment]
Which document is it? I thought the dynamic-loader design was just aimed to allow people to put ops anywhere.

There is still a small protobuf dependency (only used for data type and shape), and I don't like it either.
* It has protobuf dependency. I'll see if TF is willing to export the symbols otherwise it'll be very hard to build.
* Only dozens of bytes of protobuf is used, but it consumes about 1/4 of the runtime.

Since it's only data type and shape, I will definitely try a new format (probably a custom one to avoid more dependencies).

**Comment by PatWie** [comment]
https://github.com/tensorflow/tensorflow/pull/8728
might be related

**Comment by ppwwyyxx** [comment]
Seems a good reference!
It requires known shape of tensor? That's a big limitation

**Comment by PatWie** [comment]
But I like the `tf.decode` part, such that you just need to send raw data. So it can directly send msg packed data.

**Comment by ppwwyyxx** [comment]
But there is no existing serialization protocol for "list of tensors"

**Comment by PatWie** [comment]
Maybe a better design would be to implement two ops:
- zmq_receive
- msg_decode

**Comment by ppwwyyxx** [comment]
It looks better from the interface. But it'll introduce two copies. One from zmq to a string tensor, and one from the whole string tensor to decoded list of tensors.

If another queue is added after the decode, the latency of copy can be hidden.

**Comment by tillahoffmann** [comment]
We do most of our decoding in python (for now) but intend to migrate to using `[tf.train.Example](https://www.tensorflow.org/api_docs/python/tf/train/Example)` which support variable size tensors and are natively supported by tensorflow. 

Let me know if you want to collaborate on this issue. Would be great to hear your requirements and use cases.

**Comment by ppwwyyxx** [comment]
Thanks for the note. I've checked the Example proto, it supports variable size, but it doesn't contain the meta data inside (the size and dtype). So it's still not an ideal way to transfer "list of tensors".

Also we tend to move away from protobuf because they are slow, and causing build issues.

**Comment by PatWie** [comment]
As TF does not export these symbols, I wrote a small `tensor_msg` class which can be serialized by msgpack: 
https://github.com/PatWie/tf_zmq

**Comment by ppwwyyxx** [comment]
Nice work! Looks like it's using msgpack to replace protobuf. I guess the next question is how to do the equivalent encode method in Python (so that we can send a DataFlow to TF through zmq).

**Comment by PatWie** [comment]
I have though about that. But if you are working in python, then it is easier to directly generate tf.Tensors and just send them. Anyway, my latest attempt to create a `write.py` is here:
https://github.com/PatWie/tf_zmq/blob/bin/python/example.py#L9

**Comment by ppwwyyxx** [comment]
Generate tf.Tensors and with what protocol to send them?

**Comment by PatWie** [comment]
Ah, I see your point.
I was experimenting with pybind (seems easier than swig) and msgpack. 
Then,one just needs the `sbuffer` from msgpack.

**Comment by PatWie** [comment]
Alright, it seems to be quite easy to send and [receive](https://github.com/PatWie/tf_zmq/blob/master/read_py.py) the `tensor_msg` format with native python.

**Comment by PatWie** [comment]
As you already implemented the ZMQ operator --> close.

**Comment by ppwwyyxx** [comment]
But it doesn't build smoothly..
I won't have time for this one in the near future.

**Comment by PatWie** [comment]
Should I create an example with that zmq and polish the implementation to add it to TensorPack?

**Comment by ppwwyyxx** [comment]
It would be nice to have this op! But recently I don't have to time to look at your implementation in details. I guess there are at least these points to clarify:
1. Make it support more tensor types? (including string)
2. How does Python side and C++ side agree on the serialization format they use? Maybe that's some msgpack internals (`packb`) but I'm not very familiar.
3. The performance? If it's still slower than queues, it would be necessary to at least understand what amount of time copy and deserialization contribute.

**Comment by PatWie** [comment]
So the usual business: make it compile, make it link, make it work, make it correct, make it fast, make it flexible. 
I will ping this thread, when I prepared something. But it will take sometime as it has low priority.

**Comment by ppwwyyxx** [comment]
The only problem with the current zmq op seems to be protobuf, and it's easy to solve: just need to serialize shape + dtype somehow. Maybe it is easier to do this way.

**Comment by ppwwyyxx** [comment]
I just removed protobuf dependency. The op should be at least runnable now but there is still work to do.
