### ISSUE TITLE
Issue running training for HED

### ISSUE THREAD

**Issue by agupta74** [ppwwyyxx/tensorpack#224]
I am getting the following error when I run training for the HED module by running the following command. Any ideas on how this can be fixed?

 ./hed.py --load vgg16.npy 

[0408 17:57:57 @sessinit.py:189] Restoring from dict ...
[0408 17:57:58 @concurrency.py:36] Starting EnqueueThread ...
[0408 17:57:58 @base.py:158] Start Epoch 1 ...
  0%|                                                                                                                                           |0/1000[00:00<?,?it/s][0408 17:58:02 @input_data.py:119] ERR Exception in EnqueueThread:
Traceback (most recent call last):
  File "/home/agupta/TensorPack/tensorpack/tensorpack/train/input_data.py", line 115, in run
    self.op.run(feed_dict=feed)
  File "/root/anaconda3/envs/TF_1.0_Master/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1550, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/root/anaconda3/envs/TF_1.0_Master/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3774, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/root/anaconda3/envs/TF_1.0_Master/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 769, in run
    run_metadata_ptr)
  File "/root/anaconda3/envs/TF_1.0_Master/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 940, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/root/anaconda3/envs/TF_1.0_Master/lib/python3.5/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'dict'
[0408 17:58:02 @base.py:173] Training was stopped.
[0408 17:58:02 @input_data.py:125] EnqueueThread Exited.

![image](https://cloud.githubusercontent.com/assets/21690396/24833666/51eb231a-1c85-11e7-8eb0-11718ab8c251.png)

**Comment by ppwwyyxx** [comment]
Cannot reproduce the problem.

**Comment by agupta74** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Will it be possible to share your Vgg16.npy file? I am just wondering if there are issues with converting the caffe model.
Thanks !

Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2017, 7:46 PM, Yuxin Wu <notifications@github.com> wrote:


Cannot reproduce the problem.

**Comment by ppwwyyxx** [comment]
The model is unrelated here. I'd guess it's better to try a different version of numpy or tensorflow?

Others have seen this as well: http://stackoverflow.com/questions/43071987/tensorflow-typeerror-float-argument-must-be-a-string-or-a-number-not-dict

**Comment by ppwwyyxx** [comment]
Or if you're curious you can print the feed_dict at `"/home/agupta/TensorPack/tensorpack/tensorpack/train/input_data.py",`. It should be a dict of numpy array.

**Comment by agupta74** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thanks Yuxin ! I did print it but the value dp[0] was a dict object with raw bytes as keys and values but should instead be a numpy array. Is it possible that the decoding of the input data has some issues ?
Can you please let me know the versions of the following packages you are using ? I installed all these packages using conda install .- numpy- msgpack-Python - msgpack-numpy

Thanks,Ajay
Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2017, 8:04 PM, Yuxin Wu <notifications@github.com> wrote:


Or if you're curious you can print the feed_dict at "/home/agupta/TensorPack/tensorpack/tensorpack/train/input_data.py",. It should be a dict of numpy array.

**Comment by agupta74** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Also can you please let me know the dimensions and data type of input data fed into feed_dict ?


Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2017, 8:28 PM, Ajay Gupta <agupta_74@yahoo.com> wrote:

#yiv0669968416 blockquote, #yiv0669968416 div.yiv0669968416yahoo_quoted {margin-left:0 !important;border-left:1px #715FFA solid !important;padding-left:1ex !important;background-color:white;}Thanks Yuxin ! I did print it but the value dp[0] was a dict object with raw bytes as keys and values but should instead be a numpy array. Is it possible that the decoding of the input data has some issues ?
Can you please let me know the versions of the following packages you are using ? I installed all these packages using conda install .- numpy- msgpack-Python - msgpack-numpy

Thanks,Ajay
Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2017, 8:04 PM, Yuxin Wu <notifications@github.com> wrote:


Or if you're curious you can print the feed_dict at "/home/agupta/TensorPack/tensorpack/tensorpack/train/input_data.py",. It should be a dict of numpy array.

**Comment by ppwwyyxx** [comment]
Then it's probably msgpack or zmq related issue.
I'm using numpy 1.12.1, msgpack-python 0.4.8, msgpack-numpy 0.3.9, pyzmq 16.0.2.

**Comment by ppwwyyxx** [comment]
The shape and type are
```python
        return [InputDesc(tf.float32, [None, None, None, 3], 'image'),
                InputDesc(tf.int32, [None, None, None], 'edgemap')]
```
Where the first dimension (batch size) is set to 8 in the data pre-processing stage.

If an upgrade works for you, could you identify which package is causing the problem? so I can update the requirements.

**Comment by agupta74** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thanks ! Sure I will let you know which package helps.


Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2017, 8:54 PM, Yuxin Wu <notifications@github.com> wrote:


The shape and type are
        return [InputDesc(tf.float32, [None, None, None, 3], 'image'),
                InputDesc(tf.int32, [None, None, None], 'edgemap')]
Where the first dimension (batch size) is set to 8 in the data pre-processing stage.

If an upgrade works for you, could you identify which package is causing the problem? so I can update the requirements.

**Comment by agupta74** [comment]
It looks like after I updated my numpy, opencv and msg-pack numpy packages, it worked. I used the versions you listed and for opencv I used version 3.1.0
Thanks for your help !  
I will let you know if I run into any other issues.
On Saturday, April 8, 2017, 8:56:44 PM PDT, Ajay Gupta <agupta_74@yahoo.com> wrote:#yiv5068476196 blockquote, #yiv5068476196 div.yiv5068476196yahoo_quoted {margin-left:0 !important;border-left:1px #715FFA solid !important;padding-left:1ex !important;background-color:white;}Thanks ! Sure I will let you know which package helps.


Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2017, 8:54 PM, Yuxin Wu <notifications@github.com> wrote:


The shape and type are
        return [InputDesc(tf.float32, [None, None, None, 3], 'image'),
                InputDesc(tf.int32, [None, None, None], 'edgemap')]
Where the first dimension (batch size) is set to 8 in the data pre-processing stage.

If an upgrade works for you, could you identify which package is causing the problem? so I can update the requirements.

**Comment by agupta74** [comment]
I was able to complete the training. In order to make sure that my training process went OK, can you please verify if the following graphs look reasonable (graphs below were generated using tensorboard)?

![cost_summary](https://cloud.githubusercontent.com/assets/21690396/25056859/69dd787a-2120-11e7-9cef-f5c8d7f4e4d4.PNG)

![val_precision_recall](https://cloud.githubusercontent.com/assets/21690396/25056885/987cdb76-2120-11e7-8e64-e7e6adcc5192.PNG)

![trainerror](https://cloud.githubusercontent.com/assets/21690396/25056939/f2410baa-2120-11e7-84b9-44597818ba2c.PNG)

**Comment by ppwwyyxx** [comment]
I don't remember what number you should get in the end, but the shape looks good.
