### ISSUE TITLE
Resnet training with RGB/BGR problem

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#225]
There are two comments in resnet-imagenet about RGB/BGR conversion (since cv2.image_read gives the BGR format but the means are reverse):

-- Should actually add a RGB-BGR conversion here. in _build_graph
-- rgb-bgr conversion in get_data

Where should the conversion go if one wants to train from scratch -- in _build_graph() or augmentors in get_data() or both places?

Is this what one should add: `image = image[:,:,::-1]`

**Comment by ppwwyyxx** [comment]
The conversion was done in get_data already.
Should add it in build_graph if train from scratch.
