### ISSUE TITLE
Procedure for training HED model using custom dataSet

### ISSUE THREAD

**Issue by agupta74** [ppwwyyxx/tensorpack#231]
Can you please provide the procedure on how I can train "HED" model using my own training dataSet? The default dataSet used is BSDS but I need to use my own dataSet. I would like to know the data/file format that should be used and any assumptions of folder hierarchy. It would also be great if I can know the source files used for reading the dataSet for training.

**Comment by ppwwyyxx** [comment]
No file format restrictions. But you'll need to write such function in python to yield your images and labels and change the existing `get_data` function to use your data and your own preprocessing.
See the [documentation](http://tensorpack.readthedocs.io/en/latest/tutorial/extend/dataflow.html)

**Comment by ppwwyyxx** [comment]
The existing BSDS dataset yields data of specific shape and size and value range (see its [documentation](http://tensorpack.readthedocs.io/en/latest/modules/dataflow.dataset.html#tensorpack.dataflow.dataset.BSDS500)). So if your dataflow is different, the preprocessing may have to be different.

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you still have questions.
