### ISSUE TITLE
BEGAN: Boundary Equilibrium Generative Adversarial Networks

### ISSUE THREAD

**Issue by tmquan** [ppwwyyxx/tensorpack#234]
Dear tensorpack, 

Is it feasible to incorporate BEGAN to the current example list? 
https://arxiv.org/abs/1703.10717 
I tried many ways of your example on Image2Image translation. Although the resulting image seems to be fine, there is no way to push the accuracy of the generator higher than 50%. 
Probably, BEGAN is the way to go. 

Bests,

**Comment by ppwwyyxx** [comment]
Usually we don't take "example request", but I'm interested in this one as well.

**Comment by PatWie** [comment]
Isn't this simply adding another update_op:
https://gist.github.com/PatWie/47ca4a676698952536d4e9bc07a4f49d#file-began-py-L43

**Comment by PatWie** [comment]
I have updated the [gist](https://gist.github.com/PatWie/47ca4a676698952536d4e9bc07a4f49d) and downloaded the celebA dataset. There is still a bug somewhere and I will have a look at it tomorrow. So it is actually "running" but producing nonsense.

**Comment by ppwwyyxx** [comment]
I already have my code ready and producing faces.

**Comment by PatWie** [comment]
Nice! Currently, I cannot see where I wired my layers in the wrong way. Would be cool to check it against your implementation.

**Comment by ppwwyyxx** [comment]
Uploaded a pretrained model and some samples. They do look much nicer.
https://github.com/ppwwyyxx/tensorpack/tree/master/examples/GAN

**Comment by PatWie** [comment]
So much luck! I also ran the models, but they also generated creepy faces. So BEGAN basically shows that that others just generate much more creepy faces. Their paper also states that they used their own dataset.
