### ISSUE TITLE
use tf.Supervisor

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#235]
It seems that `tf.Supervisor` is already a wrapper for saving, restoring sessions and [threaded session management](https://www.tensorflow.org/api_docs/python/tf/train/Supervisor). This is essential for #223.

**Comment by ppwwyyxx** [comment]
But we don't have to use the saving/restoring routines of it right?
I haven't tried running with supervisor so I'm not sure what part of it is necessary.

**Comment by PatWie** [comment]
In the distributed settings, the init_op is passed to the Supervisor-class. I did not find a way to separate the creation of the Session and the call of the init_op (for global variables). I updated the pull-request.
