### ISSUE TITLE
TowerContext.get_variable_on_tower can not work with tensorflow v1.1.0

### ISSUE THREAD

**Issue by ricky1203** [ppwwyyxx/tensorpack#243]
```python
import tensorflow as tf

from tensorpack.tfutils.tower import TowerContext, get_current_tower_context

with tf.Session() as sess:
    vs = tf.get_variable_scope()
    with tf.device("/gpu:0"), tf.variable_scope(vs, reuse=False), TowerContext('tower0'):
        tf.get_variable('var0', shape=[], dtype=tf.float32)
        tc = get_current_tower_context()
        tc.get_variable_on_tower('tvar0', shape=[], dtype=tf.float32)
    print(tf.global_variables())
    with tf.device("/gpu:1"), tf.variable_scope(vs, reuse=True), TowerContext('towerp0'):
        tf.get_variable('var0', shape=[], dtype=tf.float32)
        tc = get_current_tower_context()
        tc.get_variable_on_tower('tvar1', shape=[], dtype=tf.float32)
    print(tf.global_variables())
```
will raise exception:
Traceback (most recent call last):
  File "tensorpack/tests/test_tower.py", line 19, in <module>
    tc.get_variable_on_tower('tvar1', shape=[], dtype=tf.float32)
  File "tensorpack/tensorpack/tfutils/tower.py", line 60, in get_variable_on_tower
    assert not scope.reuse
AssertionError

**Comment by ppwwyyxx** [comment]
Do you have a use case for this function?

**Comment by ppwwyyxx** [comment]
The function was just a hack to go against TF scope rules. 
I'm not aware any current use of this function. If you don't have a good use of the function I'll just remove it.

If you want to open a non-reuse scope inside a reuse scope, it may be better to just open an issue in TF and question their design.
