### ISSUE TITLE
Is it possible to load multiple models  with predictor in tensorpack?

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#245]
An end-to-end task needs to run inference with more than one models. The models are executed one by one. Is is possible to load multiple models with tensorpack?

**Comment by ppwwyyxx** [comment]
What do you mean by "load"?
You can easily use multiple models. Just create multiple PredictConfig and then predictors.

**Comment by JesseYang** [comment]
Thanks! That works fine! Is it possible to assign different GPU to different predictors?

**Comment by ppwwyyxx** [comment]
You can just write 
'with tf.device'
in your two models.

**Comment by JesseYang** [comment]
Thanks!
