### ISSUE TITLE
Can you get same score using original DQN?

### ISSUE THREAD

**Issue by Seraphli** [ppwwyyxx/tensorpack#247]
I notice you are using maxpool in DQN model. So the score and video demo is generated using your model , right? I am confused by the performance. I can't reproduce the scores reported in paper. And I also notice that your dueling network structure is different from the description in the paper.

**Comment by ppwwyyxx** [comment]
Yes.
Do you mean you cannot reproduce with my code or others?
I'm using double DQN and that's what I'm trying to reproduce. A cmdline flag can change it to DQN and I believe it can be reproduced as well.

**Comment by ppwwyyxx** [comment]
Yes. But I tried the original architecture in the paper and it works similarly well.

**Comment by ppwwyyxx** [comment]
Yes.
In the code there is some lines implementing the original arch. I just uncomment it and run.
1. I don't remember how long it takes. It iterates 2x faster but may take more iterations to train. The gpu is TitanX. Framerate has different definitions.
2. About 400 on breakout.

**Comment by Seraphli** [comment]
Thank you for your replies. I find a [result](https://github.com/tambetm/simple_dqn/blob/master/results/breakout.csv) generated by simple_dqn. I don't know if you have checked out this repository. Although the max score is >400, the average score is ~200. I am not quite understand why there is a different.

**Comment by ppwwyyxx** [comment]
I didn't know about that project.

**Comment by Seraphli** [comment]
Alright, thank you anyway.
