### ISSUE TITLE
Some dependencies are not compatible with python 3

### ISSUE THREAD

**Issue by Seraphli** [ppwwyyxx/tensorpack#248]
When I run `pip install .` in the repo using python 3 environment. 
``` 
Ignoring subprocess32: markers 'python_version < "3.0"' don't match your environment
Ignoring functools32: markers 'python_version < "3.0"' don't match your environment
```

**Comment by ppwwyyxx** [comment]
It doesn't matter. These libraries are only used in python2.

**Comment by Seraphli** [comment]
I mean you should fix README

**Comment by ppwwyyxx** [comment]
Why?
Python3 is supported. Those libraries (subprocess32, functools32) doesn't matter.
The warning you saw is intended.

**Comment by Seraphli** [comment]
ok
