### ISSUE TITLE
Validation on the CPU

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#249]
Is there a way such that the training happens on the GPUs and the validation happens on the CPUs.
For large batch sizes, I find that I get OOM during the validation stage (after the training is done for an epoch).

**Comment by ppwwyyxx** [comment]
hmm I've hard-coded to use the first GPU. I can make some changes.
But using a smaller batch size in validation will be faster than CPU anyway.

**Comment by ppwwyyxx** [comment]
Now you can use `config.predict_tower = [-1]` to let it use CPU. Or `config.predict_tower = [1]` to let it use GPU1 instead of GPU0 (default).

But note that TF doesn't support convolution with NCHW on CPU. So it won't work out of the box for convnet anyway (if you use NCHW for speed).

**Comment by a-maci** [comment]
I see. Thanks.
