### ISSUE TITLE
How to distinguish the training and testing phases in TrainConfig function?

### ISSUE THREAD

**Issue by yhlleo** [ppwwyyxx/tensorpack#252]
I want to introduce some operations which are different in training phase and testing phase.

 ```
def get_config():
    logger.auto_set_dir()
    dataset_train = get_data('train')
    dataset_test = get_data('test')

    return TrainConfig(
        dataflow=dataset_train,
        callbacks=[
            ModelSaver(),
            InferenceRunner(dataset_test,
                            [ScalarStats('cost'), ClassificationError()]),
            ScheduledHyperParamSetter('learning_rate',
                                      [(1, 0.1), (82, 0.01), (123, 0.001), (300, 0.0002)])
        ],
        model=Model(n=NUM_UNITS, isTrain=True),
        max_epoch=400,
    )
```

However, the current `TrainConfig` can't do this. Both the training and testing phases use the same model (here is `model=Model(n=NUM_UNITS, isTrain=True)`).

Do you have any suggestions?

**Comment by ppwwyyxx** [comment]
This has nothing to do with TrainConfig.
You can tell whether you're in training phase in the model. [mnist example](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/mnist-convnet.py#L47)

**Comment by yhlleo** [comment]
Thank you very much!

**Comment by Sirius083** [comment]
Hello, the mnist example link is not available, can you reput the link?
I cannot find the example of this usage
Thanks in advance

**Comment by ppwwyyxx** [comment]
The links are now updated.
