### ISSUE TITLE
Problem when running pre-trained HED model for edge detection

### ISSUE THREAD

**Issue by kdqzzxxcc** [ppwwyyxx/tensorpack#264]
I have downloaded the pre-trained model from [here](https://drive.google.com/drive/folders/0B5uDfUQ1JTgldzVLaDBERG9zQmc?usp=sharing), and I want to run [HED algorithm](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/HED) in my datasets.

Following the instructions, I input ``./hed.py --load HED_pretrained_bsds.npy --run xxx.bmp`` and it returns error as below shows
``2017-05-10 18:41:27.310526: F tensorflow/core/framework/tensor_shape.cc:169] Check failed: size >= 0 (-2739798016 vs. 0)``

I have tried 2 size of images in my datasets. The size of ``(768*1024*3)`` can get correct results, but ``(1088*1920*3)`` get above mentioned problem.

Because I can't resize my big images, so what can I do to avoid this problem? add extra GPU?

environment:
ubuntu 14.04
tensorflow 1.1.0 (gpu version)
tensorpack 0.1.9
2 * TitanX

If you need any extra information, just let me know. Thank you!

**Comment by PatWie** [comment]
You need to extract patches from the image and process each individually if the memory is not large enough. I barely see deep-learning algorithm which works on fullHD. Just change the line in:
https://github.com/ppwwyyxx/tensorpack/blob/master/examples/HED/hed.py#L198

**Comment by PatWie** [comment]
The line
```
outputs = predictor([[im.astype('float32')]])
```
runs the network on `im` and returns the result. So you have to do something like
```
im = some_image
for patch in im:
  rs = predictor([[patch.astype('float32')]])[5][0]
  put rs at correct position in im
```

**Comment by kdqzzxxcc** [comment]
@PatWie I get it. Thank you very much!

**Comment by kdqzzxxcc** [comment]
@PatWie Sorry to bother you again, I still want to know does the above mentioned error occurred due to the memory limitation of single TitanX (12GB)? so we can't solve it by multiple GPUs?

**Comment by ppwwyyxx** [comment]
Even though you have multiple GPUs you still need to split the task to run on multiple of them.

**Comment by PatWie** [comment]
This is like a kind of MultiGpuPredictor with data-parallel in-graph replication.

**Comment by kdqzzxxcc** [comment]
@PatWie @ppwwyyxx I get it. Thank you again!
