### ISSUE TITLE
allow changing location of train_log itself

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#266]
log files are huge and i would like to change to location the train_log folder, say to a different drive.

**Comment by PatWie** [comment]
You can use `logger.set_logger_dir(/mounts/trainlogs/myproject')` instead of `logger.auto_set_dir()`

**Comment by eyaler** [comment]
thanks. would be nice to have an option in auto_set_dir to change 'train_log' but still use the base_name logic

**Comment by ppwwyyxx** [comment]
`logger.set_logger_dir('/project/logs/' + os.path.basename(__file__))` would work fine.
