### ISSUE TITLE
Equation (3) From DoReFa July v2 Paper - only defining a single fixed-point int, not a sequence?

### ISSUE THREAD

**Issue by the-bobo** [ppwwyyxx/tensorpack#27]
Hello again, thanks for the updated paper - equation 1 now makes sense to me. Could you please help me understand your intent with equation 3?

You say the following: 
![dorefa v2 paper equation 3](https://cloud.githubusercontent.com/assets/4333199/18803921/b493252a-81a9-11e6-8529-bbb9071def8b.PNG)

However, it does not seem like _x_ and _y_ are sequences of integers, it seems like they are single integers. For example, _x_ is some M-bitwidth fixed-point integer, and _y_ is some K-bitwidth fixed point integer. The reason being, if they were sequences of multiple M-bitwidth (and K-bitwidth) integers, say _p_ many M-bitwidth integers and _q_ many K-bitwidth integers, then the bitwise dot product would need to iterate over these sequences. 

Currently, the bitwise dot product as defined only executes MK many summations. There is no Σ for the _p_ many M-bitwidth integers, nor for the _q_ many K-bitwidth integers.

Also, you define _x_ and _y_ as summations of bits to varying powers of 2 (beginning part of the quote above). It seems like they could only represent a single fixed-point integer, not a sequence of fixed-point integers.

Please let me know if I am misunderstanding something, thank you.

EDIT: Two more points:
(1) I think we would also need the constraint that _p_ == _q_, i.e. that the two sequences are of equivalent lengths, if they are to represent the dot product of two vectors.  

(2) The _bitcount_ operation inside the summation seems irrelevant. The bitcount of a bitwise _and_ will be 1 iff the bitwise _and_ evaluates to 1, and 0 otherwise. In other words, it is redundant with the _and_ operation.

I feel I may be misunderstanding what your notation means. Please help me clarify, thank you.

**Comment by ppwwyyxx** [comment]
for any m, c_m(x) is a bit vector, not a bit. similar for c_k(y). The `and` is element-wise and for two bit vectors (of the same length p == q).
if say M=K=2, p=q=2. x = [3, 1] = [11, 01] (in base 2), y = [2, 0] = [10, 00].
Then c_0(x) = [1,1], c_1(x) = [1, 0], c_0(y) = [0, 0], c_1(y) = [1,0]
x \dot y = 3*2 + 1*0 = 6 = 1 * 0 + 2 * 1 + 2 * 0 + 4 * 1

**Comment by the-bobo** [comment]
It took a while for me to understand, but I think I have it. Can you tell me if my understanding matches yours? I found the need to substantially rewrite section 2.1 to make explicit what the sequences are, how they are defined, and how they relate to leveraging reduced bitwidth computation in the context of neural nets. Please let me know if the following is correct.

![dorefa 2 1 part 0](https://cloud.githubusercontent.com/assets/4333199/18889171/90611dc4-84b0-11e6-80cd-9994b6be3cfd.PNG)
![dorefa 2 1 part 1](https://cloud.githubusercontent.com/assets/4333199/18889082/3170695a-84b0-11e6-9747-bc3351ec0df9.PNG)
![dorefa 2 1 part 2](https://cloud.githubusercontent.com/assets/4333199/18889084/3177a86e-84b0-11e6-90c3-b351f347a4fb.PNG)
![dorefa 2 1 part 3](https://cloud.githubusercontent.com/assets/4333199/18889085/317964c4-84b0-11e6-92de-67945234be31.PNG)
![dorefa 2 1 part 4](https://cloud.githubusercontent.com/assets/4333199/18889083/31754da8-84b0-11e6-9481-f4f248916c8a.PNG)

**Comment by zsc** [comment]
Yes, it matches our method. Thanks for the visualization.

**Comment by the-bobo** [comment]
Thanks, are my statements regarding 

> (1) what to do when _M_ != _K_   


and  

> (2) the status of all _x<sub>i</sub>_ and _y<sub>i</sub>_ as unsigned fixed point integers due to the later use of affine transformations

 
 

in agreement with your method?

**Comment by zsc** [comment]
Just noticed these.
When M != K, it's also possible to not pad the shorter-bit-width numbers, if we implement specialized multiplications like 3bit-by-5bit in FPGA.

The sign-vs-unsign problem is more relevant in FPGA. But as we are only doing summation, unsign numbers should be fine.

**Comment by the-bobo** [comment]
Two follow up questions:
1) How do you determine the bit-width for intermediate values? For example, when feeding forward we need to calculate weights * previous activation + biases to get the input to the current layer's activation function. Let's call this value z (the "weighted input"). What bit-width should z take?

2) How do you handle overflow with these fixed-bit-width integers? For example, assume you have weights restricted to 3-bits and activations restricted to 2-bits. Let's say you have a weight of 100 (4) and an activation of 10 (2) Their dot product is 1000 (8), and requires 4 bits to be represented. Do we just run the activation function on this 4-bit number, and then quantize down to the 2-bit activation value? Are there any other cases when overflow might happen?

Thank you very much

**Comment by zsc** [comment]
1) For accumulating intermediate values before the activation, one may optimize the hardware implementation by using lower bit-width addition at the start and use higher bit-width addition towards the higher stages of addition tree.

2) We only do multi-bit multiplication bit-by-bit. There will be no overflow in computing "and(c_m(x), c_k(y))". Now as explained by 1), bitcount[and(c_m(x), c_k(y)] will be kept as high bit-width number. Then we can compute the scaled sum of these high bit-width numbers (there will be only M K such numbers) by sufficient bit-width to ensure no overflow at a trivially small cost.
We already have a DoReFa-net running on FPGA that produces results agreeing with the outputs of GPU, hence we are quite sure there will be no overflows.

**Comment by the-bobo** [comment]
Thanks, i'm struggling to understand your point (2). Let's say we have the numbers:
A: `1 0 0` (4)
and
B: `1 0` (2)

Let's write out the `bitcount` and `and` operations:

1. We `and` the `0` from B's least significant digit with each of the digits in A. This will always produce 0.
2. We `and` the `1` from B's most significant digit with each of the digits in A. This will produce 0 except for the case where we `and` with A's most significant digit, which is also 1. In this case, `bitcount(and(1, 1))` gives `1`, and this value must be bitshifted by `2**(m+k)`, where `m=2` and `k=1`. 
3. Thus, we bitshift by `2**3` to get our final product of A * B. This value is `1000`, which overflows the bitwidth of the two multiplicands.

As you point out, the `and(c_m(x), c_k(y))` will never overflow, and the `bitcount` total may be stored in a high-bitwidth number (say, uint_32) so that we can use the multiply routine over very long sequences of numbers.

My question is what to do about the output of that multiply routine - the returned product can be greater than the bitwidth of the specified parameters (Weights, Activations, Gradients), and it is unclear what bit-width to use for these intermediate values.

**Comment by zsc** [comment]
The output of multiplication will be fed into nonlinear activation functions, which will quantize these values to low bit-width numbers, before these values are passed to the next convolution.

**Comment by the-bobo** [comment]
> The sign-vs-unsign problem is more relevant in FPGA. But as we are only doing summation, unsign numbers should be fine.

How do you implement this bitwise dot product kernel (equation 3 in section 2.1, DoReFa v2 paper) for negative weights? 

The quantize<sub>k</sub> function defined in Section 2.2 as Equation 5 outputs a number _r<sub>o</sub>_ ∈ [0, 1]. The affine transform on F<sub>w</sub><sup>k</sup>(r<sub>i</sub>) in Equation 9 takes the output of a quantize<sub>k</sub> function and multiplies by 2 and subtracts 1: F<sub>w</sub><sup>k</sup>(r<sub>i</sub>) = 2 * quantize<sub>k</sub>(stuff) - 1.

Thus F<sub>w</sub><sup>k</sup>(r<sub>i</sub>) ∈ [-1, 1].

However, the procedure you define in Equation 3 only works for unsigned values. If some values _x<sub>i</sub>_ in the sequence _x_ or _y<sub>i</sub>_ in the sequence _y_ are negative, then their contribution to the dot product is a subtraction, not an addition, so the simple bitcount(and()) operation no longer suffices.

How did you change the bitwise dot product procedure to account for negative weights?

One possibility:
1. Add an additional sign bit to all M-bit fixed point integers _x<sub>i</sub>_ ∈ _x_ and all K-bit fixed point integers _y<sub>i</sub>_ ∈ _y_.
2. This bit is 1 if the number _x<sub>i</sub>_ is negative, and 0 if _x<sub>i</sub>_ is positive (likewise for the _y<sub>i</sub>_), but does not count as a place-value bit for multiplication.
3. Let bitwise_and<sub>(m, k)</sub> = and(c<sub>m</sub>(x), c<sub>k</sub>(y)), ∀(m, k), ignoring the sign bits.
4. Let bitwise_sign = xor(x<sub>i<sub>signed bit</sub></sub>, y<sub>i<sub>signed bit</sub></sub>). This gives us the sign of the product of x<sub>i</sub> and y<sub>i</sub>
5. ∀ bitwise_and<sub>(m, k)</sub> ∀(m, k), note that bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>) is a vector giving the sign for each element in bitwise_and<sub>(m, k).
6. Drop all members of bitwise_and<sub>(m, k) and their corresponding signs in bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>) where bitwise_and<sub>(m, k) == 0. This leaves us with the cases where the bitwise multiplication produced a 1, along with their signs.
7. For each pair of vectors ( bitwise_and<sub>(m, k), bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>) ), compute bitcount[ bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>) ] to get the total number of negatives for the (m*k) place-value. The total number of positives is given by len(bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)) - bitcount[ bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>) ].
8. Use the negative and positive accumulations in 7 to get the signed contribution to the dot product.

**Comment by ppwwyyxx** [comment]
The formulation doesn't necessarily mean how we implement it.
F = 2 quantize(stuff) - 1. Therefore for whatever linear computation F is involved, we can use quantize(stuff) instead to compute the result, and then do a scaling/addition later accordingly.
This is mentioned in Sec 2.6, 
```
By construction, there is always an affine mapping between these low bitwidth
numbers and fixed-point integers. As a result, all the expensive operations can be accelerated signif-
icantly by the fixed-point integer dot product kernel
```

**Comment by timocafe** [comment]
I am reading your paper with interest, but the equation (3) is really not understandable.
You write:

> if say M=K=2, p=q=2. x = [3, 1] = [11, 01] in base 2, , y = [2, 0] = [10, 00].

ok

> Then c_0(x) = [1,1]

ok

> c_1(x) = [1, 0]

What ? should be [0,1] following your logic

> c_0(y) = [0,0]

What ? should be [1,0]

> c_1(y) = [1,0]

again should b [0,0]

There is something I do not understand

**Comment by ppwwyyxx** [comment]
Please read the definition of `c` in Sec 2.1:
`x = c_0(x) 2^0  + c_1(x) 2^1 = c_0(x) + 2 * c_1(x)`
when `x = [3, 1]`. We have `[3, 1] = [1, 1] + 2 * [1, 0]`
So it's correct.
