### ISSUE TITLE
get_global_step changes seems to have broke examples.

### ISSUE THREAD

**Issue by Skylion007** [ppwwyyxx/tensorpack#276]
The new code for get_global_step_var and such seems to have broken certain examples such as DiscoGAN.  Biggest issue seems to be the dtype is an int64_ref instead of an int64 so functions like piecewise constants do not seem to work. Furthermore, despite ending in the word _var it appears to return a tensor instead?

**Comment by Skylion007** [comment]
Ah, figured it out. It's the same bug the was encountered in the rate portion of DiscoGAN. get_global_step_var()'s return value needs to be wrapped in a tf.identity call.

**Comment by ppwwyyxx** [comment]
You can use the `identity` workaround. I'll also prepare a fix.
