### ISSUE TITLE
About ResNet regularization

### ISSUE THREAD

**Issue by freegyp** [ppwwyyxx/tensorpack#280]
In cifar10-resnet, did it apply weight decay to weights in all layers or just fc layer?

**Comment by ppwwyyxx** [comment]
In the [code](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/cifar10-resnet.py#L109).
On all variables named "W" (no bias, no bn scaling factors) of all layers.

**Comment by freegyp** [comment]
In my comprehension, it means all trainable weights in every layer. Is that right?

**Comment by ppwwyyxx** [comment]
It will depend on what you mean by "weights".

As I said, no bias, no bn scaling factors.
