### ISSUE TITLE
Serialising LMDBDatastream breaks without proper errormessage

### ISSUE THREAD

**Issue by msbauer** [ppwwyyxx/tensorpack#281]
Hi,

I use LMDB-files. When de-serialising the values with `LMDBDataPoint` this often does not work properly if msgpack is not installed (or the wrong version is installed). There doesn't seem to be a test/assertion for this. Installing msgpack with conda fixed the issue but it took me some time to track down the cause of the problem.

Best
matthias

**Comment by ppwwyyxx** [comment]
msgpack is in the requirement, but no version is specified now.
What's the behavior when a wrong version is installed?

**Comment by ppwwyyxx** [comment]
Are there more details? 
Otherwise I can only do some guess on what version is needed, based on msgpack changelog.

**Comment by msbauer** [comment]
Unfortunately, I cannot do any testing until Tuesday. I currently use version 0.3.8 which works. A colleague has been using 0.3.9 and had problems; however, I am not certain that was the cause as we haven't checked that 0.3.8 solved the problem for him

The problem was that:
a) no error message when msgpack was not installed (initially I had msgpack-python and msgpack-numpy installed and didn't get an error but it also didn't work). I would expect an error message "module missing" or something similar in that case.
b) The main problem for finding the error was that de-serialization did not return an error but a datastream that could not be interpreted by opencv. Thus, I was looking into issues with opencv for a while before realising that the de-serialization was actually the culprit.

Possible solutions:
a) I will do testing for version specificity next week
b) I think an exception should be raised if a module is missing instead of just returning something that cannot be interpreted (even if msgpack is in the requirement; I used the pip installation recommended in the readme and it did not install msgpack on its own).

**Comment by ppwwyyxx** [comment]
Thanks for trying to figure out the problem! For your information I've never installed msgpack anywhere. I always only install msgpack-python with pip (and I always use latest version).

**Comment by msbauer** [comment]
Ok, now I can reproduce the error. I uninstalled msgpack (in conda) and only installed msgpack-python/msgpack-numpy with pip.

For msgpack-numpy latest version (0.4.0) I get the following error
```
   File "mini_imagenet.py", line 340, in <module>
    df = get_data('test', 'predict', print_datapoints=1, classes=classes, n_split=len(classes), shuffle=False)
  File "mini_imagenet.py", line 267, in get_data
    ds = PrintData(ds, num=print_datapoints)
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 626, in __init__
    self.print_info()
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 696, in print_info
    for i, dummy in enumerate(cutoff(ds.get_data(), self.num)):
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 686, in cutoff
    for el in gen:
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 231, in get_data
    for dp in self.ds.get_data():
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 231, in get_data
    for dp in self.ds.get_data():
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 231, in get_data
    for dp in self.ds.get_data():
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 232, in get_data
    ret = self.func(dp)
  File "~/lib/tensorpack/tensorpack/dataflow/common.py", line 254, in f
    r = func(dp[index])
  File "mini_imagenet.py", line 242, in <lambda>
    ds = MapDataComponent(ds, lambda x: cv2.imdecode(x, cv2.IMREAD_COLOR), 0)   # [[w, h, c], [class]]; c is in BGR
TypeError: buf is not a numpy array, neither a scalar
```

If I use msgpack-numpy==0.3.8 everything works smoothly. Thus, v0.4.0 seems to de-serialise the lmdb-file differently to v0.3.8 (everything else stayed the same).

**Comment by ppwwyyxx** [comment]
Looks like this is mentioned in their [docs](https://github.com/lebedov/msgpack-numpy/blob/master/CHANGES.rst#release-039---february-7-2017), that data serialized with an older version (<0.3.9) cannot be deserialized with a newer version.

**Comment by ppwwyyxx** [comment]
Just updated the dependency to require msgpack-numpy>=0.3.9 1175aade9a482. Thanks for your help!

**Comment by msbauer** [comment]
Thanks. Maybe also mention somewhere in the "efficient data loading" documentation that this incompatibility exists and that old LMDB files don't work anymore when upgrading? The dependence might not be obvious to everyone and it took me a long time to figure out what the problem was (probably also as I am less experienced)
