### ISSUE TITLE
Resuming a crashed run with ResNet on Cifar10

### ISSUE THREAD

**Issue by deeplearningmachine** [ppwwyyxx/tensorpack#282]
Using the --load option is supposed to be exactly the continuation of the last saved checkpoint, but it seems the training error is not.

Before crashed:
100%|###################################################|390/390[00:22<00:00,16.70it/s]
[0601 22:54:47 @base.py:252] Epoch 14 (global_step 5460) finished, time:22.11 sec.
[0601 22:54:47 @saver.py:66] Model saved to train_log_pretrain_10epoch390_/model-1950.
[0601 22:54:47 @monitor.py:294] cond_1/Merge: 0.78492
[0601 22:54:47 @monitor.py:294] input_queue_size: 50
[0601 22:54:47 @monitor.py:294] learning_rate: 0.01
[0601 22:54:47 @monitor.py:294] train_error: 0.27657
[0601 22:54:47 @monitor.py:294] wd_cost: 0.2121
[0601 22:54:47 @base.py:167] Start Epoch 15 ...
100%|###################################################|390/390[00:22<00:00,17.45it/s]
[0601 22:55:10 @base.py:252] Epoch 15 (global_step 5850) finished, time:22.36 sec.
[0601 22:55:10 @saver.py:66] Model saved to train_log_pretrain_10epoch390_/model-2340.
[0601 22:55:10 @monitor.py:294] cond_1/Merge: 0.72082
[0601 22:55:10 @monitor.py:294] input_queue_size: 50
[0601 22:55:10 @monitor.py:294] learning_rate: 0.01
[0601 22:55:10 @monitor.py:294] train_error: 0.26134
[0601 22:55:10 @monitor.py:294] wd_cost: 0.21082
[0601 22:55:10 @base.py:167] Start Epoch 16 ...
 66%|###################################################8                          |259/390[00:14<00:08,16.25it/s]

After resumed:
[0601 22:57:01 @base.py:167] Start Epoch 16 ...
100%|##############################################################################|390/390[00:23<00:00,16.92it/s]
[0601 22:57:24 @base.py:252] Epoch 16 (global_step 6240) finished, time:23.07 sec.
[0601 22:57:36 @saver.py:66] Model saved to train_log_pretrain_10epoch390_/model-390.
[0601 22:57:36 @monitor.py:294] cond_1/Merge: 1.4908
[0601 22:57:36 @monitor.py:294] input_queue_size: 50
[0601 22:57:36 @monitor.py:294] learning_rate: 0.01
[0601 22:57:36 @monitor.py:294] train_error: 0.55708
[0601 22:57:36 @monitor.py:294] wd_cost: 0.2164
[0601 22:57:36 @group.py:43] Callbacks took 11.620 sec in total. ModelSaver: 11.619sec
[0601 22:57:36 @base.py:167] Start Epoch 17 ...
100%|##############################################################################|390/390[00:21<00:00,17.90it/s]
[0601 22:57:58 @base.py:252] Epoch 17 (global_step 6630) finished, time:21.81 sec.
[0601 22:57:58 @saver.py:66] Model saved to train_log_pretrain_10epoch390_/model-780.
[0601 22:57:58 @monitor.py:294] cond_1/Merge: 1.1794
[0601 22:57:58 @monitor.py:294] input_queue_size: 50
[0601 22:57:58 @monitor.py:294] learning_rate: 0.01
[0601 22:57:58 @monitor.py:294] train_error: 0.42562
[0601 22:57:58 @monitor.py:294] wd_cost: 0.21525
[0601 22:57:58 @base.py:167] Start Epoch 18 ...
 27%|#####################2                                                        |106/390[00:05<00:16,17.46it/s]

**Comment by ppwwyyxx** [comment]
Could you provide the command you're using, and the full log of the second run?
It looks like you're not running the examples. Could you explain what changes you've made to the code?

**Comment by deeplearningmachine** [comment]
Thanks!

I executed the following: python nips-cifar10-resnet.py --gpu 0,1,2,3 -n 5

I was not running the examples. I added some k-means costs to the softmax cost function. 

[32m[0601 22:56:14 @logger.py:69][0m Argv: nips-cifar10-resnet.py --gpu 0,1,2,3 -n 5
[32m[0601 22:56:14 @fs.py:99][0m [5m[31mWRN[0m $TENSORPACK_DATASET not set, using /data/tensorpack_data for dataset.
[32m[0601 22:56:14 @cifar.py:33][0m Found cifar10 data in /data/tensorpack_data/cifar10_data.
[32m[0601 22:56:15 @cifar.py:33][0m Found cifar10 data in /data/tensorpack_data/cifar10_data.
[32m[0601 22:56:18 @multigpu.py:38][0m Training a model of 4 tower
[32m[0601 22:56:18 @multigpu.py:46][0m Building graph for training tower 0...
[32m[0601 22:56:18 @common.py:95][0m conv0 input: [None, 3, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m conv0 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.0/conv1 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.0/conv1 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.0/conv2 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.0/conv2 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.1/conv1 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.1/conv1 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.1/conv2 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.1/conv2 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.2/conv1 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.2/conv1 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.2/conv2 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.2/conv2 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.3/conv1 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.3/conv1 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.3/conv2 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.3/conv2 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.4/conv1 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.4/conv1 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res1.4/conv2 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res1.4/conv2 output: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:95][0m res2.0/conv1 input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res2.0/conv1 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.0/conv2 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.0/conv2 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.0/pool input: [None, 16, 32, 32]
[32m[0601 22:56:18 @common.py:103][0m res2.0/pool output: [None, 16, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.1/conv1 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.1/conv1 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.1/conv2 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.1/conv2 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.2/conv1 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.2/conv1 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.2/conv2 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.2/conv2 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.3/conv1 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.3/conv1 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.3/conv2 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.3/conv2 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.4/conv1 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.4/conv1 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res2.4/conv2 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res2.4/conv2 output: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:95][0m res3.0/conv1 input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res3.0/conv1 output: [None, 64, 8, 8]
[32m[0601 22:56:18 @common.py:95][0m res3.0/conv2 input: [None, 64, 8, 8]
[32m[0601 22:56:18 @common.py:103][0m res3.0/conv2 output: [None, 64, 8, 8]
[32m[0601 22:56:18 @common.py:95][0m res3.0/pool input: [None, 32, 16, 16]
[32m[0601 22:56:18 @common.py:103][0m res3.0/pool output: [None, 32, 8, 8]
[32m[0601 22:56:18 @common.py:95][0m res3.1/conv1 input: [None, 64, 8, 8]
[32m[0601 22:56:18 @common.py:103][0m res3.1/conv1 output: [None, 64, 8, 8]
[32m[0601 22:56:18 @common.py:95][0m res3.1/conv2 input: [None, 64, 8, 8]
[32m[0601 22:56:18 @common.py:103][0m res3.1/conv2 output: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:95][0m res3.2/conv1 input: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:103][0m res3.2/conv1 output: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:95][0m res3.2/conv2 input: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:103][0m res3.2/conv2 output: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:95][0m res3.3/conv1 input: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:103][0m res3.3/conv1 output: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:95][0m res3.3/conv2 input: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:103][0m res3.3/conv2 output: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:95][0m res3.4/conv1 input: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:103][0m res3.4/conv1 output: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:95][0m res3.4/conv2 input: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:103][0m res3.4/conv2 output: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:95][0m gap input: [None, 64, 8, 8]
[32m[0601 22:56:19 @common.py:103][0m gap output: [None, 64]
[32m[0601 22:56:19 @common.py:95][0m linear input: [None, 64]
[32m[0601 22:56:19 @common.py:103][0m linear output: [None, 10]
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for conv0/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.0/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.0/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.1/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.1/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.2/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.2/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.3/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.3/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.4/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res1.4/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.0/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.0/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.1/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.1/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.2/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.2/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.3/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.3/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.4/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res2.4/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.0/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.0/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.1/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.1/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.2/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.2/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.3/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.3/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.4/conv1/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for res3.4/conv2/W:0
[32m[0601 22:56:24 @regularize.py:18][0m Apply regularizer for linear/W:0
[32m[0601 22:56:25 @multigpu.py:46][0m Building graph for training tower 1...
[32m[0601 22:56:27 @multigpu.py:46][0m Building graph for training tower 2...
[32m[0601 22:56:28 @multigpu.py:46][0m Building graph for training tower 3...
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t tower0/self.cluster4example.name
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t tower0/Variable
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData-0
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeDataLabel-0
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData-1
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeDataLabel-1
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData-2
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeDataLabel-2
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData-3
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeDataLabel-3
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData-4
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeDataLabel-4
...
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData-388
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeDataLabel-388
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeData-389
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t fakeDataLabel-389
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t tower0/datapoint_of_t
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t tower0/Variable_1
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_0
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_1
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_2
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_3
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_4
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_5
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_6
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_7
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_8
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t datapoint_of_sub_class_9
[32m[0601 22:56:30 @multigpu.py:101][0m [5m[31mWRN[0m No Gradient w.r.t tower0/datapoint_of_entire_dataset
[32m[0601 22:56:31 @model_utils.py:33][0m [36mModel Parameters: 
[0mname                                 shape               dim
-----------------------------------  --------------  -------
conv0/W:0                            [3, 3, 3, 16]       432
conv0/bn/beta:0                      [16]                 16
conv0/bn/gamma:0                     [16]                 16
res1.0/conv1/W:0                     [3, 3, 16, 16]     2304
res1.0/conv1/bn/beta:0               [16]                 16
res1.0/conv1/bn/gamma:0              [16]                 16
res1.0/conv2/W:0                     [3, 3, 16, 16]     2304
...
res3.4/bn/beta:0                     [64]                 64
res3.4/bn/gamma:0                    [64]                 64
res3.4/conv1/W:0                     [3, 3, 64, 64]    36864
res3.4/conv1/bn/beta:0               [64]                 64
res3.4/conv1/bn/gamma:0              [64]                 64
res3.4/conv2/W:0                     [3, 3, 64, 64]    36864
bnlast/bn/beta:0                     [64]                 64
bnlast/bn/gamma:0                    [64]                 64
linear/W:0                           [64, 10]            640
linear/b:0                           [10]                 10
tower0/self.cluster4example.name:0   [128]               128
fakeData:0                           [128, 64]          8192
tower0/Variable:0                    [128]               128
fakeData-0:0                         [128, 64]          8192
fakeDataLabel-0:0                    [128]               128
fakeData-1:0                         [128, 64]          8192
fakeDataLabel-1:0                    [128]               128
fakeData-2:0                         [128, 64]          8192
fakeDataLabel-2:0                    [128]               128
fakeData-3:0                         [128, 64]          8192
fakeDataLabel-3:0                    [128]               128
...
fakeData-388:0                       [128, 64]          8192
fakeDataLabel-388:0                  [128]               128
fakeData-389:0                       [128, 64]          8192
fakeDataLabel-389:0                  [128]               128
tower0/datapoint_of_t:0               [49920, 64]     3194880
tower0/Variable_1:0                  [49920]           49920
datapoint_of_sub_class_0:0            [5, 64]             320
datapoint_of_sub_class_1:0            [5, 64]             320
datapoint_of_sub_class_2:0            [5, 64]             320
datapoint_of_sub_class_3:0            [5, 64]             320
datapoint_of_sub_class_4:0            [5, 64]             320
datapoint_of_sub_class_5:0            [5, 64]             320
datapoint_of_sub_class_6:0            [5, 64]             320
datapoint_of_sub_class_7:0            [5, 64]             320
datapoint_of_sub_class_8:0            [5, 64]             320
datapoint_of_sub_class_9:0            [5, 64]             320
datapoint_of_entire_dataset:0         [50, 64]           3200
tower0/datapoint_of_entire_dataset:0  [128, 64]          8192
tower1/self.cluster4example.name:0   [128]               128
tower1/Variable:0                    [128]               128
tower1/datapoint_of_t:0               [49920, 64]     3194880
tower1/Variable_1:0                  [49920]           49920
tower1/datapoint_of_entire_dataset:0  [128, 64]          8192
tower2/self.cluster4example.name:0   [128]               128
tower2/Variable:0                    [128]               128
tower2/datapoint_of_t:0               [49920, 64]     3194880
tower2/Variable_1:0                  [49920]           49920
tower2/datapoint_of_entire_dataset:0  [128, 64]          8192
tower3/self.cluster4example.name:0   [128]               128
tower3/Variable:0                    [128]               128
tower3/datapoint_of_t:0               [49920, 64]     3194880
tower3/Variable_1:0                  [49920]           49920
tower3/datapoint_of_entire_dataset:0  [128, 64]          8192[36m
Total #param=16736538 (63.84 MB assuming all float32)[0m
[32m[0601 22:56:31 @base.py:118][0m Setup callbacks graph ...
[32m[0601 22:56:55 @monitor.py:203][0m Found existing JSON at train_log_pretrain_10epoch390_/stat.json, will append to it.
[32m[0601 22:56:55 @monitor.py:213][0m Found training history from JSON, now starting from epoch number 16.
[32m[0601 22:56:55 @base.py:123][0m Finalize the graph, create the session ...
[32m[0601 22:57:01 @base.py:132][0m Graph variables initialized.
[32m[0601 22:57:01 @concurrency.py:36][0m Starting EnqueueThread ...
[32m[0601 22:57:01 @base.py:167][0m Start Epoch 16 ...
[32m[0601 22:57:24 @base.py:252][0m Epoch 16 (global_step 6240) finished, time:23.07 sec. 
[32m[0601 22:57:36 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-390.
[32m[0601 22:57:36 @monitor.py:294][0m cond_1/Merge: 1.4908
[32m[0601 22:57:36 @monitor.py:294][0m input_queue_size: 50
[32m[0601 22:57:36 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 22:57:36 @monitor.py:294][0m train_error: 0.55708
[32m[0601 22:57:36 @monitor.py:294][0m wd_cost: 0.2164
[32m[0601 22:57:36 @group.py:43][0m Callbacks took 11.620 sec in total. ModelSaver: 11.619sec
[32m[0601 22:57:36 @base.py:167][0m Start Epoch 17 ...
[32m[0601 22:57:58 @base.py:252][0m Epoch 17 (global_step 6630) finished, time:21.81 sec. 
[32m[0601 22:57:58 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-780.
[32m[0601 22:57:58 @monitor.py:294][0m cond_1/Merge: 1.1794
[32m[0601 22:57:58 @monitor.py:294][0m input_queue_size: 50
[32m[0601 22:57:58 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 22:57:58 @monitor.py:294][0m train_error: 0.42562
[32m[0601 22:57:58 @monitor.py:294][0m wd_cost: 0.21525
[32m[0601 22:57:58 @base.py:167][0m Start Epoch 18 ...
[32m[0601 22:58:20 @base.py:252][0m Epoch 18 (global_step 7020) finished, time:22.09 sec. 
[32m[0601 22:58:20 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-1170.
[32m[0601 22:58:20 @monitor.py:294][0m cond_1/Merge: 1.0012
[32m[0601 22:58:20 @monitor.py:294][0m input_queue_size: 50
[32m[0601 22:58:20 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 22:58:20 @monitor.py:294][0m train_error: 0.3586
[32m[0601 22:58:20 @monitor.py:294][0m wd_cost: 0.21413
[32m[0601 22:58:20 @base.py:167][0m Start Epoch 19 ...
[32m[0601 22:58:43 @base.py:252][0m Epoch 19 (global_step 7410) finished, time:22.29 sec. 
[32m[0601 22:58:43 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-1560.
[32m[0601 22:58:43 @monitor.py:294][0m cond_1/Merge: 0.88364
[32m[0601 22:58:43 @monitor.py:294][0m input_queue_size: 50
[32m[0601 22:58:43 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 22:58:43 @monitor.py:294][0m train_error: 0.31471
[32m[0601 22:58:43 @monitor.py:294][0m wd_cost: 0.21295
[32m[0601 22:58:43 @base.py:167][0m Start Epoch 20 ...
[32m[0601 22:59:05 @base.py:252][0m Epoch 20 (global_step 7800) finished, time:22.02 sec. 
[32m[0601 22:59:05 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-1950.
[32m[0601 22:59:05 @monitor.py:294][0m cond_1/Merge: 0.80321
[32m[0601 22:59:05 @monitor.py:294][0m input_queue_size: 50
[32m[0601 22:59:05 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 22:59:05 @monitor.py:294][0m train_error: 0.28723
[32m[0601 22:59:05 @monitor.py:294][0m wd_cost: 0.21176
[32m[0601 22:59:05 @base.py:167][0m Start Epoch 21 ...
[32m[0601 22:59:27 @base.py:252][0m Epoch 21 (global_step 8190) finished, time:22.30 sec. 
[32m[0601 22:59:28 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-2340.
[32m[0601 22:59:28 @monitor.py:294][0m cond_1/Merge: 0.73514
[32m[0601 22:59:28 @monitor.py:294][0m input_queue_size: 50
[32m[0601 22:59:28 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 22:59:28 @monitor.py:294][0m train_error: 0.25911
[32m[0601 22:59:28 @monitor.py:294][0m wd_cost: 0.2105
[32m[0601 22:59:28 @base.py:167][0m Start Epoch 22 ...
[32m[0601 22:59:50 @base.py:252][0m Epoch 22 (global_step 8580) finished, time:22.13 sec. 
[32m[0601 22:59:50 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-2730.
[32m[0601 22:59:50 @monitor.py:294][0m cond_1/Merge: 0.67178
[32m[0601 22:59:50 @monitor.py:294][0m input_queue_size: 50
[32m[0601 22:59:50 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 22:59:50 @monitor.py:294][0m train_error: 0.23213
[32m[0601 22:59:50 @monitor.py:294][0m wd_cost: 0.20925
[32m[0601 22:59:50 @base.py:167][0m Start Epoch 23 ...
[32m[0601 23:00:12 @base.py:252][0m Epoch 23 (global_step 8970) finished, time:22.39 sec. 
[32m[0601 23:00:12 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-3120.
[32m[0601 23:00:12 @monitor.py:294][0m cond_1/Merge: 0.63242
[32m[0601 23:00:12 @monitor.py:294][0m input_queue_size: 50
[32m[0601 23:00:12 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 23:00:12 @monitor.py:294][0m train_error: 0.21668
[32m[0601 23:00:12 @monitor.py:294][0m wd_cost: 0.20793
[32m[0601 23:00:12 @base.py:167][0m Start Epoch 24 ...
[32m[0601 23:00:35 @base.py:252][0m Epoch 24 (global_step 9360) finished, time:22.61 sec. 
[32m[0601 23:00:35 @saver.py:66][0m Model saved to train_log_pretrain_10epoch390_/model-3510.
[32m[0601 23:00:35 @monitor.py:294][0m cond_1/Merge: 0.58666
[32m[0601 23:00:35 @monitor.py:294][0m input_queue_size: 50
[32m[0601 23:00:35 @monitor.py:294][0m learning_rate: 0.01
[32m[0601 23:00:35 @monitor.py:294][0m train_error: 0.2044
[32m[0601 23:00:35 @monitor.py:294][0m wd_cost: 0.20664
[32m[0601 23:00:35 @base.py:167][0m Start Epoch 25 ...
[32m[0601 23:00:48 @base.py:265][0m Detected Ctrl-C and exiting main loop.
[32m[0601 23:00:48 @input_data.py:125][0m EnqueueThread Exited.

**Comment by ppwwyyxx** [comment]
Have you used `--load` at all?

**Comment by deeplearningmachine** [comment]
Sorry. I thought the k (keep) selection below would perform the "--load" action to restore the latest saved model.

[0602 12:16:41 @logger.py:86] WRN If you're resuming from a previous run you can choose to keep it.
[0602 12:16:41 @logger.py:87] Select Action: k (keep) / b (backup) / d (delete) / n (new):


It works perfectly now when I use this one:  python nips-cifar10-resnet.py --gpu 0,1,2,3 -n 5 --load train_log_pretrain_10epoch390_/model-1170

Thanks a lot for your prompt help!
