### ISSUE TITLE
Support of Conv3D and Deconv3D

### ISSUE THREAD

**Issue by tmquan** [ppwwyyxx/tensorpack#283]
@Hi tensorpack, 

Is there any plan to support wrapper of Conv3D and Deconv3D (Conv3D_Transpose)?
Currently, I have 2 versions: a self-implemented custom code and tflearn wrapper. But I believe having supports from tensorpack library is much more useful. 

3D version has been recently added to r1.2.0 https://github.com/tensorflow/tensorflow/blob/r1.2/RELEASE.md 

It is somehow related to this issue #211 for people who are working on 3D CNN and 3D FCN

Best,

**Comment by ppwwyyxx** [comment]
If you have such code already, you can call your code or tflearn wrapper directly within a tensorpack model.

**Comment by ppwwyyxx** [comment]
Closing this and tracking the issue in #291.
