### ISSUE TITLE
Warning for Variables without any gradients

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#285]
Currently, only the MultiGPU-Trainer gives a warning about Variables which are not updated by backprop if multiple GPUs were used. It would be nice if this sanity check will also be triggered in SingleGPU mode.

This warning is usually a good hint for a mistake in the computation graph (typo etc).

**Comment by ppwwyyxx** [comment]
Oh it's actually still working. I thought I broke it.
