### ISSUE TITLE
Atrous convolution

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#289]
Atrous convolution (also called dilated convolution) is used in quite a few works. Tensorflow has its implementation as tf.nn.atrous_conv2d. It should be nice if tensorpack/models/conv2d.py has a wrapper for tf.nn.atrous_conv2d :-)

**Comment by ppwwyyxx** [comment]
It would be nice of course.
But you can just call `tf.layers.conv2d` in your model, with the `dilation_rate` option.

**Comment by JesseYang** [comment]
I see. Thanks! :-)

**Comment by Skylion007** [comment]
@JesseYang I just officially added it to the Tensorpack Conv2D class with #625 so now we officially support it.

**Comment by JesseYang** [comment]
Thanks!
