### ISSUE TITLE
Manuel device selection

### ISSUE THREAD

**Issue by chuber1986** [ppwwyyxx/tensorpack#295]
Hi *,
it would be nice to have the possibility to manually chose the computation device of a ContextTower in the PredictConfig (similar to the TrainConfig).
E.g.:
pred_config = PredictConfig(..., devices=['/gpu:1'])

BR Christian

**Comment by ppwwyyxx** [comment]
What is your use case? I think you can always just write `tf.device` around your predictor.

**Comment by chuber1986** [comment]
Wrapping the predictor in 'with tf.device(...)' doesn't work because the OfflinePredictor builds the graph within an TowerContex which uses an '\gpu:0' as default.
I build want to use a Resnet to preprocess the input for another  Resnet (OfflinePredictor as target function of an ThreadedMapData). Because of there size of these networks I need to put them in distinct GPUs. (Writing the activations to a file isn't feasible ether)

- Christian

**Comment by ppwwyyxx** [comment]
You can try again now.

**Comment by chuber1986** [comment]
Thanks! Works like a charm!
