### ISSUE TITLE
How to do data preprocessing across entire dataset?

### ISSUE THREAD

**Issue by Skylion007** [ppwwyyxx/tensorpack#297]
So I am trying to implement DistanceGAN in Tensorpack, but am struggling because I am not quite sure how I can read in all the data easily to calculate the standard deviation and expectation of the dataset. Is there an easy way for me to do a first pass across the dataset first to calculate and store that? Something like maybe hacking parameter setter? 

Reference implementation can be found here: https://github.com/sagiebenaim/DistanceGAN

**Comment by ppwwyyxx** [comment]
Could you loop over the dataset and do that yourself?

**Comment by Skylion007** [comment]
Also should mention that it needs to be updated every n epochs. Essentially, it would be like a scheduled hyperparam setter but the values used would be dynamically calculated based on the dataset.

**Comment by ppwwyyxx** [comment]
Why would mean/std of your dataset change?

**Comment by Skylion007** [comment]
Should of been more clear, it would not change. However, if you wanted to experiment about say dividing by the difference between your predictions and the actual dataset, that would be interesting. I just wanted to demonstrate their should be a way to have a different training regime happen every x epochs, possibly one that doesn't involve backprop. I guess the example I used could be hacked using the inferencerunner? Just wanted to see what you would recommend in that case.

**Comment by ppwwyyxx** [comment]
>  However, if you wanted to experiment about say dividing by the difference between your predictions and the actual dataset, that would be interesting.

It's easy if this is what you want to do. Though I don't see it has anything to do with your original question.
You can just write a callback which runs some forward predictions and do whatever with its output, and run it every several epochs. [CycleGAN example](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/GAN/CycleGAN.py#L182) has such a callback.

**Comment by deeplearningmachine** [comment]
Is the Graph finalized in the callback?

**Comment by PatWie** [comment]
The is finalized [after](https://github.com/ppwwyyxx/tensorpack/blob/16145cc862e6131cd9f22c6081c0328bc890c90f/tensorpack/train/base.py#L125-L137) the [_setup_graph()](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/DynamicFilterNetwork/steering-filter.py#L70)

**Comment by Skylion007** [comment]
I'd like to point out that the new paper [TTUR](https://github.com/bioinf-jku/TTUR) also calculates stats across large portions of the dataset. It might be useful to integrate such a system as a feature in Tensorpack, especially if we can allow a user to define a temporary static graph to calculate it.

**Comment by PatWie** [comment]
Why not writing a Callback for this task?

**Comment by deeplearningmachine** [comment]
any example code for outputting the last layer's representation across the entire training and testing datasets of all batches?
