### ISSUE TITLE
Same transformation for inputs and labels

### ISSUE THREAD

**Issue by vqdang** [ppwwyyxx/tensorpack#300]
I'm doing image segmentation and so is there anyway to apply the same augmentation for the inputs and labels? Will just setting the same seed using `random.seed` is enough?

**Comment by ppwwyyxx** [comment]
#214

**Comment by vqdang** [comment]
@ppwwyyxx  Thanks

I also have some more questions to ask.

- Is there anyway to set the buffer size for `PrefetchDataZMQ` ? Setting more nr_proc didn't seem to better utilize my CPUs while the GPUS still starved

- `get_current_tower_context().is_training`, allows `InferenceRunner` to perform validation. I also need to run testing after training like validation (inputs at `_build_graph` only has image, no label). Basically at each epoch it will be training -> validation -> testing. How can I achieve that?

**Comment by ppwwyyxx** [comment]
1. The "high-water-mark" is what people called buffer size. http://tensorpack.readthedocs.io/en/latest/modules/dataflow.html#tensorpack.dataflow.PrefetchDataZMQ
If both cpu and gpu are starved you might want to reduce the communication by e.g. compression.

2. A lot of examples run testing after training, for instance [this one](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/HED/hed.py#L189).

**Comment by vqdang** [comment]
I don't understand how the `run` part can help me achieve that. From what I have seen, the `run` part is not executed at the same session as training. What I need is preferable like this

```
config = TrainConfig(
            dataflow=train_generator,
            callbacks=[
                      InferenceRunner(valid_generator, BinaryClassificationStats('prediction', 'edgemap4d')),
                      InferenceRunner(test_generator, TestInferencer('prediction', 'edgemap4d'))
                      ],
            model=Model(),
            steps_per_epoch=steps_per_epoch,
            max_epoch=100)
```

`test_generator `will also provide different shape from from the `valid_generator`. So far, I have sub-classed `Inferencer` to create the `TestInferencer`. But it seems that I could not even provide input with different shapes to the `Inferencer`. This is the error when `valid_generator` output shape [102, 102, 3] and `test_generator` output shape [478, 478, 3]

`tensorflow/core/framework/tensor_shape.cc:240] Check failed: size >= 0 (-3800563712 vs. 0)`

**Comment by PatWie** [comment]
You can provide different shapes for different phases, if the Model-InputDesc have a shape like `[None, None, None, 3]` for rgb images. This is more about how to use a TensorFlow graph and not TensorPack.

**Comment by vqdang** [comment]
Thanks, I understand.
