### ISSUE TITLE
MultiGPU device logging correct?

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#304]
I get
```
name            shape                dim  device
--------------  ----------------  ------  --------
conv1/W:0       [3, 3, 47, 128]   150400  /gpu:0
conv2/W:0       [3, 3, 128, 128]  147456  /gpu:1
conv3/W:0       [3, 3, 128, 128]  147456  /gpu:2
conv4/W:0       [3, 3, 128, 128]  147456  /gpu:3
conv5/W:0       [3, 3, 128, 128]  147456  /gpu:1
conv_final/W:0  [1, 1, 128, 1]       128  /gpu:1
conv_final/b:0  [1]                    1  /gpu:2
```

testing 4 GPUs. I thought SyncMultiGPUTrainer was data-parallelism (each tower a part of the batch) and not model-parallelism.

**Comment by ppwwyyxx** [comment]
It is data parallel but variables are spread among GPUs.
https://www.tensorflow.org/performance/performance_models#parameter_server_variables

**Comment by PatWie** [comment]
I though each Tower had its own varscope. Is this the new LeastLoadedDeviceSetter ?

**Comment by ppwwyyxx** [comment]
In the other mode https://www.tensorflow.org/performance/performance_models#replicated_variables each tower has its own var scope.

Yes.
