### ISSUE TITLE
allow non-default borderValue

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#306]
There is no way to set borderValue for border/borderType/borderMode = cv2.BORDER_CONSTANT in imgproc.py, geometry.py and image_sample.py. also we can use this opportunity to make the argument naming consistent.

**Comment by ppwwyyxx** [comment]
There are too many things you can do in opencv and I don't expect to cover all of them. Users who need this can write their own augs, and I think people usually don't care much about stuff like border value.
You're welcome to send PRs. But this feature is probably not something I'm going to work on.

**Comment by eyaler** [comment]
the above merge fixes add border_value for shift and rotate image augmentation. please note that for rgb border_value should be a tuple (r,g,b)
