### ISSUE TITLE
Unstable iter/sec and slowly becomes very small

### ISSUE THREAD

**Issue by vqdang** [ppwwyyxx/tensorpack#308]
I need some helps to figure out what wrong with my training or model. I'm training with 3 P100 and I have already set `PrefetchDataZMQ(ds, 20, 1000)`

At first epoch, it started from 0.14 iter/sec to 1.41 iter/sec then maintained like that till the end. However, from the 2nd epochs onward, the highest iter/sec kept going down before stucking at about 0.3 iter/sec. Not just training, the validation also when down from 3.x iter/sec to about 1.x iter/sec

I thought that  I was augmenting too much so I only kept Flipping left but it still happens. Compile Tensorflow from source didn't help me either. The output of `nvidia-smi` is as follow with 3 GPUS rarely utilized at the same time (I can still capture when 3 work at the same time but most of the time it just like this):

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 378.13                 Driver Version: 378.13                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 0000:02:00.0     Off |                    0 |
| N/A   67C    P0    42W / 250W |  11739MiB / 12193MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 0000:03:00.0     Off |                    0 |
| N/A   62C    P0    44W / 250W |  11739MiB / 12193MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-PCIE...  Off  | 0000:83:00.0     Off |                    0 |
| N/A   76C    P0    46W / 250W |  11739MiB / 12193MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Thanks

**Comment by ppwwyyxx** [comment]
Most likely your data is too slow. You can probably see that input queue size is nearly zero in the log.
hwm in `PrefetchDataZMQ` rarely affects speed and it's better to keep it as default. You can use `TestDataSpeed` to benchmark your dataflow pipeline and figure out which part is slow, or in particular which part may become slower overtime. See some info in [tutorial](http://tensorpack.readthedocs.io/en/latest/tutorial/efficient-dataflow.html) as well.

**Comment by vqdang** [comment]
Running `TestDataSpeed` got me at least 90 iter/sec both on server and local machine. I rechecked my operation in the graph and changed cropping using slicing to `tf.image.resize_image_with_crop_or_pad`,  (I need to crop output at some bottom layers and then concatenate them at some upper layers, like Unet)   

Testing on single gpu for both server and local machine (same augmentations)

- local machine (nr_proc = 16):  iter/sec stable around 1.84 iter/sec (it improved alot) (just 16 logical processor)
- the server: reach higher peak but dropping to low at some following epochs. `nr_proc > 16` just made it dropping faster (it has 32 logical processor). I then removed the augmentation but it changed nothing.

I also used resizing in the network, do all tensorflow operations operate on GPU? I honestly don't know how should I go with this. But I highly suspect that something CPU-related are my bottleneck, I just dont know how to pinpoint it.

I plan to try the following but I am not sure how I can apply to my case.
```
ds0 = dataset.ILSVRC12('/path/to/ILSVRC12', 'train', shuffle=True)
augmentor = AugmentorList(lots_of_augmentors)
ds1 = ThreadedMapData(
    ds0, nr_thread=25,
    map_func=lambda x: augmentor.augment(x), buffer_size=1000)
# ds1 = PrefetchDataZMQ(ds1, nr_proc=1)
ds = BatchData(ds1, 256)
```

This is my `get_data()`
```
""" data: numpy array for images
    label: numpy array for images' labels
"""
def get_data_generator(data, data_shape, label, label_shape, 
                                batch_size = 16, is_train = False):
    ds = Dataset(data, label)
    ### augmentation for both the input and label
    if is_train:
        shape_aug = [
            ElasticDeform(size = (4, 8), ampl = (6, 10)),
            RandomRotation(45),
            imgaug.Flip(horiz=True),
            imgaug.Flip(vert=True),
            imgaug.ToUint8()
        ]
    else:
        shape_aug = [
            imgaug.CenterCrop(data_shape),
        ]
    ds = AugmentImageComponents(ds, shape_aug, (0, 1), copy=True)

    ### augmentation for just the output
    augmentors = [
        # finally crop mask size to output shape
        LabelProc(False, True), # to fix label value or shape
        imgaug.CenterCrop(label_shape),
    ]
    ds = AugmentImageComponent(ds, augmentors, index = 1, copy=True)

    ### augmentation for just the input
    if is_train:
        augmentors = [
            imgaug.CenterCrop(data_shape),
        ]
        ds = AugmentImageComponent(ds, augmentors, index = 0, copy=False)
        ds = BatchDataByShape(ds, batch_size, idx=0)
        ds = PrefetchDataZMQ(ds, 16)
    else:
        ds = BatchData(ds, batch_size)

    return ds
```
Thanks

**Comment by ppwwyyxx** [comment]
If your data is 90it/s and training is only 1.8it/s, bottleneck is not on the data but in the graph.
If GPU utilization is low, it's the CPU operations in the graph that's slow.

**Comment by vqdang** [comment]
Do you know anyway too track which tensorflow operation running on GPU/CPU? I'm doing brute force by rerunning the graph to check it for now but this way is a bit too counter-intuitive.

**Comment by PatWie** [comment]
Do not forget that TensorPack is still TensorFlow. Just do profiling!

```python
m = Model()
hdrs = m.get_reused_placehdrs()


with TowerContext('', is_training=False):
    m._build_graph(hdrs)
    with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
        options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
        run_metadata = tf.RunMetadata()
        sess.run(tf.global_variables_initializer())

        prediction = tf.get_default_graph().get_tensor_by_name('........')
        sess.run(prediction, {hdrs[0]: .....}, options=options, run_metadata=run_metadata)

        fetched_timeline = timeline.Timeline(run_metadata.step_stats)
        chrome_trace = fetched_timeline.generate_chrome_trace_format()
        with open('profile.json', 'w') as f:
            f.write(chrome_trace)
```

This will tell you which ops are executed on CPU and which are on GPU (even on which cuda stream). In addition, you get all timings.

**Comment by ppwwyyxx** [comment]
Usually a bisection can quickly point me to the slow area. You can try profiling as well.

**Comment by vqdang** [comment]
@ppwwyyxx 
It's abit troublesome because I need both upsampling and concatenation (via `tf.concat` and `tf.image.resize_nearest_neighbor` or conv2d transpose) but the existence of either resize or conv2d transpose still make iter/sec goes down the same way. I will look it through again today.

@PatWie  Thanks for your nice code! I haven't known such thing exist.

I will close this because this is now out of tensorpack scope. Thanks everyone.
