### ISSUE TITLE
Gradient Update Step - DoReFa v2 Paper

### ISSUE THREAD

**Issue by the-bobo** [ppwwyyxx/tensorpack#31]
Thank you for your help. I have three questions about the update procedure for updating weights.
1. When you initialize the weights on first-run of the neural net, do you initialize to low-bitwidth samples from the normal distribution, or do you initialize to full-precision values?
2. What bit-width does the update step for the weights use? In the algorithm on page 6 it looks like W<sub>k</sub><sup>t+1</sup> = Update(W<sub>k</sub>, gW<sub>k</sub>, _η_) is operating on full precision weights. Why not use the quantized weights instead?
3. How do you calculate ∂W<sub>k</sub><sup>b</sup> / ∂W<sub>k</sub>? This should be the partial derivative of the quantized weights with respect to the full precision weights, but I do not know how you calculate that.

Thank you.

**Comment by ppwwyyxx** [comment]
1. The underlying weights W<sub>k</sub>  are always full-precision, including the initialization stage. It is quantized to W<sub>k</sub><sup>b</sup> to compute Wx+b or conv(W,x)+b.

2. It is full precision. After training the network, we only need to keep the quantized value but a full precision update is needed in training.

3. It is standard chain rule. There is a explicit formula to compute W<sub>k</sub><sup>b</sup> from W<sub>k</sub>, where the derivative of `quantize()` function is already defined.

**Comment by the-bobo** [comment]
Thanks, 1 and 2 make sense to me.

For 3 - where can I find this calculation being done in your DoReFa code?

**Comment by ppwwyyxx** [comment]
You cannot find it, because standard chain rule comes with tensorflow when you compute `tf.gradient`.

(5) and (6) defines the forward and backward (i.e. the derivative) of `quantize()` function. This is also in the code in the definition of `quantize()` function.

**Comment by the-bobo** [comment]
(6) says ∂c/∂r<sub>i</sub> = ∂c/∂r<sub>o</sub>, where r<sub>i</sub> = a single real-valued weight, and r<sub>o</sub> = a single _k_-bit quantized, real-valued weight.

We want to find a component expression for ∂W<sub>k</sub><sup>b</sup>/∂W<sub>k</sub>, where W<sub>k</sub><sup>b</sup> is a matrix containing quantized weights, and W<sub>k</sub> is the full-precision version of that matrix.

In component terms, we are looking for ∂r<sub>o</sub>/∂r<sub>i</sub>, as r<sub>o</sub> are the components of W<sub>k</sub><sup>b</sup>, and r<sub>i</sub> are the components of W<sub>k</sub>.

Given (6), that ∂c/∂ri = ∂c/∂ro, are you saying that ∂ri = ∂ro¬, which means ∂ro/∂ri = 1? 

In that case, line 18 of the algorithm on page six reduces from:
gW<sub>k</sub> = gW<sub>k</sub><sup>b</sup>(∂W<sub>k</sub><sup>b</sup>/∂W<sub>k</sub>)
gW<sub>k</sub> = gW<sub>k</sub><sup>b</sup>(1)
gW<sub>k</sub> = gW<sub>k</sub><sup>b</sup>

Is this what you intended? I think I am mistaken somehow but am not sure…

===

My other strategy is to attempt computing the derivative with respect to r<sub>i</sub> for the following equation:
2 * quantize<sub>k</sub>[ _tanh_(r<sub>i</sub>) / (2*_max_(|_tanh_(r<sub>i</sub>)|)) + 1/2] -1.

Please advise, thank you!

**Comment by ppwwyyxx** [comment]
∂Wkb/∂Wk == 1 is not right, because Wkb != quantize(Wk).
Wkb = f_w(Wk) defined in equation (9) so your second strategy is correct.

**Comment by the-bobo** [comment]
I'm working on this but am getting stuck - how do you derivate the _max()_ function in the divisor?

**Comment by ppwwyyxx** [comment]
The derivative of max function is a zero vector but the position of the maximum is 1.

**Comment by the-bobo** [comment]
> Wkb = f_w(Wk) defined in equation (9) so your second strategy is correct.

Okay, let's do this. Does the following result look correct to you? I am particularly anxious about my understanding of the Straight-Through-Estimator, as I could not find the Hinton video lecture you cite (which the Bengio paper you cite also references).

**dF<sub>w</sub><sup>k</sup>/dr<sub>i</sub> = 2 * ⟦ (1-tanh<sup>2</sup>(r<sub>i</sub>)) * [2 * max(|tanh(r<sub>i</sub>)|)]<sup>-1</sup> ⟧**

===

Let F<sub>w</sub><sup>k</sup> := 2 * quantize<sub>k</sub>[ tanh(r<sub>i</sub>) / ( 2*max(|tanh(r<sub>i</sub>)|) ) + 1/2 ] - 1

Given quantize<sub>k</sub>(r<sub>i</sub>) := (1 / (2<sup>k</sup>-1)) * round((2<sup>k</sup> - 1)r<sub>i</sub>).

Find dF<sub>w</sub><sup>k</sup>/dr<sub>i</sub>.

**First, express F<sub>w</sub><sup>k</sup> as the composition of multiple functions, so that _chain rule_ may be used.**
(1) F<sub>w</sub><sup>k</sup> = 2 * quantize<sub>k</sub>[ tanh(r<sub>i</sub>) * ( 2*max(|tanh(r<sub>i</sub>)|) )<sup>-1</sup> + 1/2 ] - 1

(2) Define component functions as follows:
- a(r<sub>i</sub>) = 2 * [1/(2<sup>k</sup>-1) * round((2<sup>k</sup>-1) * r<sub>i</sub>)] -1
- b(r<sub>i</sub>) = tanh(r<sub>i</sub>) * [2max(|tanh(r<sub>i</sub>)|)\<sup>-1</sup> + 1/2

∴  F<sub>w</sub><sup>k</sup> = a(b(r<sub>i</sub>))

(3) (_via chain rule_) dF<sub>w</sub><sup>k</sup>/dr<sub>i</sub> = a'(b(r<sub>i</sub>)) * b'(r<sub>i</sub>)

**Start by expanding b'(r<sub>i</sub>)**
(4) The _max()_ function in the square brackets is a constant when derivating with respect to r<sub>i</sub>, as the max value is taken over all the weights r<sub>i</sub> in a given layer, and thus does not vary with respect to the particular r<sub>i</sub> with which we are derivating.
(5) ∴ (_via Identity One_) b'(r<sub>i</sub>) = (1-tanh<sup>2</sup>(r<sub>i</sub>)) * [2 * max(|tanh(r<sub>i</sub>)|)]<sup>-1</sup>

**Now expand a'(b(r<sub>i</sub>))**
First consider a'(r<sub>i</sub>)
(6) (_under condition of Expectation of a Straight-Through-Estimator_) a'(r<sub>i</sub>) = 2.
Consider that the quantize<sub>k</sub> function decomposes into two scaling factors and a round operator. The two scaling factors are the multiplicands 1/(2<sup>k</sup>-1) and (2<sup>k</sup>-1), on the outside and inside of the round operator respectively. 

If we evaluated this function in the absence of a round operator, the two scalars would cancel, and the function would change in a manner directly proportional to the input r<sub>i</sub>, leaving a derivative of 1. Since a(r<sub>i</sub>) is 2 * quantize<sub>k</sub>(r<sub>i</sub>) - 1, this derivative would be 2 * 1 = 2.

The round operator is simply an additive shift of [-0.5, 0.5], as it either rounds a number down or up to the nearest integer value. Thus our outer scale factor of 1/(2<sup>k</sup>-1) is technically multiplying the result of (2<sup>k</sup>-1)*(r<sub>i</sub>)+ δ, where δ ∈ [-0.5, 0.5].

In any given evaluation of a(r<sub>i</sub>) it is unlikely that the two scale factors are exact inverses, due to the low probability of δ = 0. However, under assumption that δ is drawn uniformly and at random from [-0.5, 0.5], the expectation is 𝐄(δ) = 0. 
**∴ under expectation 𝐄(δ) = 0, dquantize<sub>k</sub>(r<sub>i</sub>)/dr<sub>i</sub> = 1**
(7) Given (6), a'(b(r<sub>i</sub>)) = 2, as the derivative a' is a constant, and thus does not vary with respect to the function's input.

**Now compute dF<sub>w</sub><sup>k</sup>/dr<sub>i</sub> = a'(b(r<sub>i</sub>)) * b'(r<sub>i</sub>)**
(8)dF<sub>w</sub><sup>k</sup>/dr<sub>i</sub> = 2 * ⟦ (1-tanh<sup>2</sup>(r<sub>i</sub>)) * [2 * max(|tanh(r<sub>i</sub>)|)]<sup>-1</sup> ⟧ ∎


**Identities**
1. Identity One: d/dx tanh(x) = 1-tanh<sup>2</sup>(x)
Source: https://en.wikipedia.org/wiki/Hyperbolic_function#Derivatives

**Comment by ppwwyyxx** [comment]
d quantize<sub>k</sub>(r<sub>i</sub>)/dr<sub>i</sub> = 1. This is correct. That's exactly how we define the function quantize_k in (5) and (6).

max() actually does have a gradient. It varies with respect to the maximum value. You might need to take that into account.
```python
a = tf.placeholder(dtype=tf.float32, name='a', shape=[4])
b = tf.reduce_max(a)
c = tf.gradients([b], [a])[0]
with tf.Session() as sess:
    v = np.asarray([1, 2, 3, 4], dtype='float32')
    print sess.run(c, feed_dict={a:v})  # 0, 0, 0, 1
```

**Comment by the-bobo** [comment]
I'll take a look at that, thank you for the code. Where does that code come
from?

Also, does my interpretation of the STE and it's value under expectation
match yours?

**Comment by ppwwyyxx** [comment]
I wrote the code to show what the gradient is.

STE can be thought of as a function whose derivative is defined differently, so that gradient can propagate better.

I don't understand your argument on expectation. But the function quantize_k, mathematically, has zero gradient almost everywhere: http://www.wolframalpha.com/input/?i=round(x+*+7)+%2F+7
We define the gradient to be 1 so that it can be trained.

**Comment by the-bobo** [comment]
Regarding STE - okay, I think we are doing the same thing, just different justifications. My argument provides a reason for defining the gradient of quantize<sub>k</sub> as 1. (It is a way to convert the step-wise shape of the round() graph into a linear approximation, whose slope is 1.)

Regarding your `tf.gradients()` code - I don't understand. If we are differentiating 2 * quantize<sub>k</sub>[ _tanh_(r<sub>i</sub>) / (2*_max_(|_tanh_(r<sub>i</sub>)|)) + 1/2] -1 with respect to r<sub>i</sub>, then the max(r<sub>i</sub>) for a given layer is just a per-layer constant. I think I am misunderstanding you.

**Comment by ppwwyyxx** [comment]
max(x) is an amount that depends on x, more specifically it depends on the maximum element in x.
That's why the gradients would be 0,0,0,1. At least that's what's implemented in tensorflow.
Since this gradient is just a subgradient, treating max(x) as a constant and use 0,0,0,0 may also work in training. But I cannot guarantee that.

**Comment by the-bobo** [comment]
Okay that's interesting. Let me confirm that I understand what you are saying.

Is this what you mean?
1. Let r⃗<sub>ℓ</sub> := a vector with weights from layer _ℓ_
2. Let r<sub>ℓ<sub>i</sub></sub> := the i<sup>th</sup> component of the weight vector r⃗<sub>ℓ</sub>
3. Let r<sub>ℓ<sub>max</sub></sub> := the maximum component of the weight vector r⃗<sub>ℓ</sub>
4. ∀ r<sub>ℓ<sub>i</sub></sub> where r<sub>ℓ<sub>i</sub></sub> ≠ r<sub>ℓ<sub>max</sub></sub>, dr<sub>ℓ<sub>max</sub></sub>/dr<sub>ℓ<sub>i</sub></sub> = 0.
5. When r<sub>ℓ<sub>i</sub></sub> = r<sub>ℓ<sub>max</sub></sub>, dr<sub>ℓ<sub>max</sub></sub>/dr<sub>ℓ<sub>i</sub></sub> = 1.

**Comment by ppwwyyxx** [comment]
Yes. It works for optimization purpose and this is what is implemented in most frameworks. Technically this is not a derivative anymore, but a subgradient.

**Comment by the-bobo** [comment]
Yes, this is definitely a subgradient. However, it seems unstable. What do you recommend in the case where r<sub>ℓ<sub>i</sub></sub> and r<sub>ℓ<sub>j</sub></sub> both =  r<sub>ℓ<sub>max</sub></sub>?

**Comment by ppwwyyxx** [comment]
With subgradient, the result can actually be any number in [0,1]. 
If you modify my code example above to try you'll see if input is [1,2,2,2], output will be [0,0.33,0.33,0.33]. But that's just a choice by tensorflow. Other library may have different choices. It's just people usually don't use zero because it's always better to have some gradient..

**Comment by the-bobo** [comment]
Ohhhhhh I get it, so if there are multiple r<sub>ℓ<sub>i</sub></sub> that satisfy r<sub>ℓ<sub>max</sub>, you just split the unit gradient of 1 evenly among them. 

So if r<sub>ℓ<sub>i</sub></sub> = r<sub>ℓ<sub>j</sub></sub> = r<sub>ℓ<sub>k</sub></sub> = r<sub>ℓ<sub>max</sub>, then dr<sub>ℓ<sub>max</sub></sub>/dr<sub>ℓ<sub>i</sub></sub> = dr<sub>ℓ<sub>max</sub></sub>/dr<sub>ℓ<sub>j</sub></sub> = dr<sub>ℓ<sub>max</sub></sub>/dr<sub>ℓ<sub>k</sub></sub> = (1/3).

Okay wow, that's subtle. Please confirm that this is what you mean! 

Second question - if I can no longer treat d[2max(|tanh(r<sub>i</sub>)|)]<sup>-1</sup>/dr<sub>i</sub> as a constant, then I must use chain rule with it and expand my differentiation of 2 * quantize<sub>k</sub>[ _tanh_(r<sub>i</sub>) / (2*_max_(|_tanh_(r<sub>i</sub>)|)) + 1/2] -1 further. Is this correct?

**Comment by ppwwyyxx** [comment]
Yes.

**Comment by the-bobo** [comment]
Thanks ppwwyyxx, two more questions:

1) When I'm differentiating 2 * quantize<sub>k</sub>[ tanh(r<sub>ℓ<sub>i </sub></sub>) / (2*max(|tanh(r<sub>ℓ<sub>i </sub></sub>)|)) + 1/2] -1 with respect to dr<sub>ℓ<sub>i </sub></sub>, for that _max()_ function in the denominator, you write "where the maximum is taken over all weights in that layer" (page 4, DoReFa v2 paper).

Are you talking about finding the maxima of the full-precision, _non-quantized_ weights?

2) Does "full-precision" for DoReFa v2 paper mean "float32" ?

**Comment by ppwwyyxx** [comment]
1. the input to the max function is full precision, so yes.
2. yes.

**Comment by the-bobo** [comment]
When you say that you quantize weights to k-bits using quantize<sub>k</sub>, how do you handle the overflow case when defining F<sub>w</sub><sup>k</sup>(r<sub>ℓ<sub>i</sub></sub>)? 

If F<sub>w</sub><sup>k</sup>(r<sub>i</sub>) = 2 * quantize<sub>k</sub>[ tanh(r<sub>ℓ<sub>i</sub></sub>) / (2*max(|tanh(r<sub>ℓ<sub>i</sub></sub>)|)) + 1/2] -1

then in cases where quantize<sub>k</sub>(r<sub>ℓ<sub>i</sub></sub>) returned a k-bit value of [1, 1, 1...., 1] where all k-bits are set to 1, 2 * quantize<sub>k</sub>(r<sub>ℓ<sub>i</sub></sub>) will overflow.

Am I misunderstanding something?

**Comment by the-bobo** [comment]
Okay, here is an attempt at an explicit proof for the derivative of the weight quantization function used in DoReFa v2 paper. It is remarkable that we trust TensorFlow to auto-differentiate this correctly. Please let me know if this proof looks correct, thank you!

When implementing DoReFa outside of TensorFlow, it is necessary to have an explicit derivative for computing Step 18 of Algorithm 1 from DoReFa v2 paper: gW<sub>k</sub> = g<sub>W<sub>k</sub><sup>b</sup></sub> * ∂W<sub>k</sub><sup>b</sup> / ∂W<sub>k</sub>.

- Note that dr<sub>i<sub>ℓ</sub></sub> refers to the _derivative_ of some function with respect to r<sub>i<sub>ℓ</sub></sub>, while d(r<sub>i<sub>ℓ</sub></sub>) is itself a function.
- r<sub>i<sub>ℓ</sub></sub> refers to some real-valued weight _i_ in layer _ℓ_. 

Let F<sub>w</sub><sup>k</sup> := 2 * quantize<sub>k</sub>[ tanh(r<sub>i<sub>ℓ</sub></sub>) / ( 2*max(|tanh(r<sub>i</sub>)|) ) + 1/2 ] - 1

Given quantize<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) := (1 / (2<sup>k</sup>-1)) * round((2<sup>k</sup> - 1)r<sub>i<sub>ℓ</sub></sub>).

Find dF<sub>w</sub><sup>k</sup>/dr<sub>i<sub>ℓ</sub></sub>.

**First, express F<sub>w</sub><sup>k</sup> as the composition of multiple functions, so that _chain rule_ may be used.**
(1) F<sub>w</sub><sup>k</sup> = 2 * quantize<sub>k</sub>[ tanh(r<sub>i<sub>ℓ</sub></sub>) * ( 2*argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|) )<sup>-1</sup> + 1/2 ] - 1

(2) Define component functions as follows:

- h(r<sub>i<sub>ℓ</sub></sub>) = 2 * argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|)
- e(r<sub>i<sub>ℓ</sub></sub>) = (r<sub>i<sub>ℓ</sub></sub>)<sup>-1</sup>
- d(r<sub>i<sub>ℓ</sub></sub>) = tanh(r<sub>i<sub>ℓ</sub></sub>) * e(h(r<sub>i<sub>ℓ</sub></sub>)) + 1/2
- c(r<sub>i<sub>ℓ</sub></sub>) = quantize<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) = (1 / (2<sup>k</sup>-1)) * round((2<sup>k</sup>-1)r<sub>i<sub>ℓ</sub></sub>)
- b(r<sub>i<sub>ℓ</sub></sub>) = 2 * r<sub>i<sub>ℓ</sub></sub> - 1

Note – to avoid confusion with F<sub>w</sub><sup>k</sup>(r<sub>i<sub>ℓ</sub></sub>), there is **no** f(r<sub>i<sub>ℓ</sub></sub>). There is also **no** g(r<sub>i<sub>ℓ</sub></sub>).

(3) ∴ F<sub>w</sub><sup>k</sup> = b(c(d(r<sub>i<sub>ℓ</sub></sub>)))
(4) (_via chain rule_) F’<sub>w</sub><sup>k</sup> = b’(c(d(r<sub>i<sub>ℓ</sub></sub>))) * c’(d(r<sub>i<sub>ℓ</sub></sub>)) * d’(r<sub>i<sub>ℓ</sub></sub>)
**Second, begin finding the three derivatives in (4), so that F' may be calculated.**
**Start with d’(r<sub>i<sub>ℓ</sub></sub>)**
(5) d(r<sub>i<sub>ℓ</sub></sub>) = tanh(r<sub>i<sub>ℓ</sub></sub>) * e(h(r<sub>i<sub>ℓ</sub></sub>)) + 1/2
(6) Let a(r<sub>i<sub>ℓ</sub></sub>) = e(h(r<sub>i<sub>ℓ</sub></sub>))
(7) (_via product rule_) d’(r<sub>i<sub>ℓ</sub></sub>) = dtanh(r<sub>i<sub>ℓ</sub></sub>)/dr<sub>i<sub>ℓ</sub></sub> * a(r<sub>i<sub>ℓ</sub></sub>) + tanh(r<sub>i<sub>ℓ</sub></sub>) * a’(r<sub>i<sub>ℓ</sub></sub>)
(8) (_via Identity One_) d’(r<sub>i<sub>ℓ</sub></sub>) = (1-tanh<sup>2</sup>(r<sub>i<sub>ℓ</sub></sub>)) * a(r<sub>i<sub>ℓ</sub></sub>) + tanh(r<sub>i<sub>ℓ</sub></sub>) * a’(r<sub>i<sub>ℓ</sub></sub>)
**Now find a’(r<sub>i<sub>ℓ</sub></sub>)**
(9) (_via chain rule_) a’(r<sub>i<sub>ℓ</sub></sub>) = e’(h(r<sub>i<sub>ℓ</sub></sub>)) * h’(r<sub>i<sub>ℓ</sub></sub>)
**Begin with differentiating h(r<sub>i<sub>ℓ</sub></sub>) = 2 * argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|)**
(10) (_via Lemma One_) h’(r<sub>i<sub>ℓ</sub></sub>) = 0 if r<sub>i<sub>ℓ</sub></sub> ∉ ℓ<sub>max</sub>, and 2 * (1/|ℓ<sub>max</sub>|) if if r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>, where |ℓ<sub>max</sub>| denotes the cardinality of the set ℓ<sub>max</sub>, where ℓ<sub>max</sub> is the set of all r<sub>i<sub>ℓ</sub></sub> that satisfy argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|).
(11) (_via (9)_) ∴ a’(r<sub>i<sub>ℓ</sub></sub>) = 0 if r<sub>i<sub>ℓ</sub></sub> ∉ ℓ<sub>max</sub>
**Now find e’(h(r<sub>i<sub>ℓ</sub></sub>))**
(12) (_via power rule_) e’(h(r<sub>i<sub>ℓ</sub></sub>)) = -1 * [2 * argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|)]<sup>-2</sup>
(13) ∴ a’(r<sub>i<sub>ℓ</sub></sub>) = [ -1 * (2 * argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|))<sup>-2</sup> ] * h’(r<sub>i<sub>ℓ</sub></sub>) = 
Case 1: 0 if r<sub>i<sub>ℓ</sub></sub> ∉ ℓ<sub>max</sub>
Case 2: [ -1 * (2 * argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|))<sup>-2</sup> ] * [ 2 * (1/|ℓ<sub>max</sub>|) ] if r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>.
(14) ∴ d’(r<sub>i<sub>ℓ</sub></sub>) = (1-tanh<sup>2</sup>(r<sub>i<sub>ℓ</sub></sub>)) * a(r<sub>i<sub>ℓ</sub></sub>) + tanh(r<sub>i<sub>ℓ</sub></sub>) * a’(r<sub>i<sub>ℓ</sub></sub>) = 
Case 1: (1-tanh<sup>2</sup>(r<sub>i<sub>ℓ</sub></sub>)) * a(r<sub>i<sub>ℓ</sub></sub>) if r<sub>i<sub>ℓ</sub></sub> ∉ ℓ<sub>max</sub>
Case 2: (1-tanh<sup>2</sup>(r<sub>i<sub>ℓ</sub></sub>)) * a(r<sub>i<sub>ℓ</sub></sub>) + tanh(r<sub>i<sub>ℓ</sub></sub>) * a’(r<sub>i<sub>ℓ</sub></sub>) if r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>.
**Now find c’(d(r<sub>i<sub>ℓ</sub></sub>))**
(15) (_via Lemma Two_) c’(d(r<sub>i<sub>ℓ</sub></sub>)) = 1
**Now find b’(c(d(r<sub>i<sub>ℓ</sub></sub>))**
(16) b’(c(d(r<sub>i<sub>ℓ</sub></sub>)) = 2 
**Now find F’<sub>w</sub><sup>k</sup>**
(17) F’<sub>w</sub><sup>k</sup> = b’(c(d(r<sub>i<sub>ℓ</sub></sub>))) * c’(d(r<sub>i<sub>ℓ</sub></sub>)) * d’(r<sub>i<sub>ℓ</sub></sub>) 
= 2 * 1 * d’(r<sub>i<sub>ℓ</sub></sub>)
Case 1: 2 * [ (1-tanh<sup>2</sup>(r<sub>i<sub>ℓ</sub></sub>)) * a(r<sub>i<sub>ℓ</sub></sub>) ] >) if r<sub>i<sub>ℓ</sub></sub> ∉ ℓ<sub>max</sub>
Case 2: 2 * [ (1-tanh<sup>2</sup>(r<sub>i<sub>ℓ</sub></sub>)) * a(r<sub>i<sub>ℓ</sub></sub>) + tanh(r<sub>i<sub>ℓ</sub></sub>) * a’(r<sub>i<sub>ℓ</sub></sub>) ] if r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>.
Expanding Case 2: 
= 2 * [ 1-tanh<sup>2</sup>(r<sub>i<sub>ℓ</sub></sub>)) * (2 * argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|))<sup>-1</sup> + tanh(r<sub>i<sub>ℓ</sub></sub>) * (-1 * (2 * argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|))<sup>-2</sup> ] * [ 2 * (1/|ℓ<sub>max</sub>|) ) ] if r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>.

We now have an explicit formula for differentiating F<sub>w</sub><sup>k</sup> with respect to r<sub>i<sub>ℓ</sub></sub> over two cases, Case 1 in which r<sub>i<sub>ℓ</sub></sub> ∉ ℓ<sub>max</sub> and Case 2 in which r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>.



**Identities**
1. Identity One: d/dx tanh(x) = 1-tanh<sup>2</sup>(x)

**Lemmas**
**[1] Lemma One: subderivative of the argmax function.**
Quoting Wikipedia, “the subderivative, subgradient, and subdifferential generalize the derivative to functions which are not differentiable. The subdifferential of a function is set-valued.” (https://en.wikipedia.org/wiki/Subderivative).

Intuitively, the subderivative is a way to differentiate continuous functions at non-differentiable points. 

Without proof we hold that the subderivative of a function f(x) with domain ∈ ℝ and range ∈ ℝ at a non-differentiable point x0 is the closed set [_a_, _b_] where _a_ = lim<sub>x→x<sub>0-</sub> (f(x)-f(x<sub>0</sub>)_ / (x-x<sub>0</sub>) and _b_ = lim<sub>x→x<sub>0+</sub> (f(x)-f(x<sub>0</sub>)_ / (x-x<sub>0</sub>).

That is, the subderivative at point x<sub>0</sub> is a set whose elements are the closed interval [_a_, _b_] where _a_ and _b_ are the left-hand and right-hand derivatives of f(x) as x approaches x<sub>0</sub>, respectively.

(N.B.: You can think of the traditional derivative as a special case where the set comprising the solutions to the subderivative has only one element.)

**Accordingly, we define the subderivative of the argmax function by cases.**
(1) Let y(r<sub>i<sub>ℓ</sub></sub>) = argmax(|tanh(r<sub>i<sub>ℓ</sub></sub>)|), where y(r<sub>i<sub>ℓ</sub></sub>) evaluates to _true_ when r<sub>i<sub>ℓ</sub></sub> produces the maximum value of |tanh(r<sub>i<sub>ℓ</sub></sub>)| ∀ r<sub>i<sub>ℓ</sub></sub> ∈ ℓ, and _false_ otherwise.

That is, y(r<sub>i<sub>ℓ</sub></sub>) is evaluated ∀ r<sub>i<sub>ℓ</sub></sub> ∈ ℓ, and is true when its input is the weight in layer ℓ that produces the maximum value for the |tanh(r<sub>i<sub>ℓ</sub></sub>)| function.

(2) Let ℓ<sub>max</sub> := { r<sub>i<sub>ℓ</sub></sub> | y(r<sub>i<sub>ℓ</sub></sub>) } denote the set of all weights in layer ℓ that produces a maximum value as defined in (1).
**(3) Case one: argmax’(|tanh(r<sub>i<sub>ℓ</sub></sub>)|) = 0 if r<sub>i<sub>ℓ</sub></sub> ∉ ℓ<sub>max</sub>.**
**(4) Case two: argmax’(|tanh(r<sub>i<sub>ℓ</sub></sub>)|) = 1 / |ℓ<sub>max</sub>| if r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>** where |ℓ<sub>max</sub>| denotes the cardinality (number of elements) of the set ℓ<sub>max</sub>. 

Note that if r<sub>i<sub>ℓ</sub></sub> is the only element in ℓ<sub>max</sub> then its subderivative is 1.

Note that if r<sub>i<sub>ℓ</sub></sub> is _not_ the only element in ℓ<sub>max</sub> then it splits the subderivative of 1 equally with all other r<sub>i<sub>ℓ</sub></sub> ∈ ℓ<sub>max</sub>.    

**[2] Lemma Two: differentiating quantize<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) yields 1 under condition of Expectation of a Straight-Through Estimator.**  
(1) Given quantize<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) = (1 / (2<sup>k</sup>-1)) * round((2<sup>k</sup> - 1)r<sub>i<sub>ℓ</sub></sub>).
(2) Consider ~quantize<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) ≔ (1 / (2<sup>k</sup>-1)) * ((2<sup>k</sup> - 1)r<sub>i<sub>ℓ</sub></sub>) = r<sub>i<sub>ℓ</sub></sub>.
(3) ~quantize’<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) = 1.
(4) Observation: in the absence of a _round()_ function the two scale factors cancel and the derivative is 1. Can we make the _round()_ function “disappear” in some justified fashion?
(5) Note that the _round(r<sub>i<sub>ℓ</sub></sub>)_ function adds some number _n_ ∈ [-0.5, 0.5] to r<sub>i<sub>ℓ</sub></sub> to round r<sub>i<sub>ℓ</sub></sub> to the nearest integer. 
(6) If _n_ = 0, then quantize’<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) = ~quantize’<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) = 1.
(7) if _n_ ≠ 0, then our outer scale factor of 1/(2<sup>k</sup>-1) is technically multiplying the result of (2<sup>k</sup>-1)*(r<sub>i<sub>ℓ</sub></sub> + _n_), and thus the scale factors do not cancel.
(8) Note that the probability of _n_ == 0 is low, and so any individual call to quantize<sub>k</sub>() is unlikely to result in a case where we can ignore the _round()_ function.
(8) However, under assumption that _n_ is drawn uniformly and at random from [-0.5, 0.5], the expectation 𝐄(_n_) = 0.
(9) **∴ under expectation 𝐄(_n_) = 0, quantize’<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) = ~quantize’<sub>k</sub>(r<sub>i<sub>ℓ</sub></sub>) = 1.**

Consider that the quantize<sub>k</sub> function decomposes into two scaling factors and a round operator. The two scaling factors are the multiplicands 1/(2<sup>k</sup>-1) and (2<sup>k</sup>-1), on the outside and inside of the round operator respectively. 

If we evaluated this function in the absence of a round operator, the two scalars would cancel, and the function would change in a manner directly proportional to the input r<sub>i</sub>, leaving a derivative of 1. Since a(r<sub>i</sub>) is 2 * quantize<sub>k</sub>(r<sub>i</sub>) - 1, this derivative would be 2 * 1 = 2.

The round operator is simply an additive shift of [-0.5, 0.5], as it either rounds a number down or up to the nearest integer value. Thus our outer scale factor of 1/(2<sup>k</sup>-1) is technically multiplying the result of (2<sup>k</sup>-1)*(r<sub>i</sub>)+ δ, where δ ∈ [-0.5, 0.5].

In any given evaluation of a(r<sub>i</sub>) it is unlikely that the two scale factors are exact inverses, due to the low probability of δ = 0. However, under assumption that δ is drawn uniformly and at random from [-0.5, 0.5], the expectation is 𝐄(δ) = 0. 
**∴ under expectation 𝐄(δ) = 0, dquantize<sub>k</sub>(r<sub>i</sub>)/dr<sub>i</sub> = 1**

**Comment by ppwwyyxx** [comment]
This looks OK to me. Nevertheless you can easily compute some numerical gradients to check if the final formula is correct.
