### ISSUE TITLE
Multi-GPU training when #GPU>10

### ISSUE THREAD

**Issue by xingyul** [ppwwyyxx/tensorpack#310]
When using multi-GPU training and the number of GPU > 10, I encounter problems of variable sharing. When building 11th tower, I have the following error:
`[0623 02:20:52 @multigpu.py:89] Building graph for training tower 10...
...
ValueError: Variable XXX/W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:
`

This error won't happen when #GPU <= 10.
I was using `SyncMultiGPUTrainer(config).train()`

**Comment by ppwwyyxx** [comment]
Oh I don't know such machine exists. I'll try to fix.
