### ISSUE TITLE
tf.metrics and tensorpack evaluation callbacks

### ISSUE THREAD

**Issue by EchoWho** [ppwwyyxx/tensorpack#312]
Right now if I need some custom evaluation metric, I need to to implement/use a evaluation callback, similar to classificationerror, scalarstats and etc. 

While this is fine for most of the classification cases, it feels a wasted effort for more complex evaluation metrics, like mean_iou and mean_iou_per_class, which are implemented in tf.metrics already. Sadly, tf.metric versions are all for streaming data only, and do not have reset functionality. (so basically they wrote the triggers but not the resets, and the tensorflow authors were reluctant to add the resets until recently ( https://github.com/tensorflow/tensorflow/issues/4814) . 

What's you opinion on implementing these metrics in callbacks? Basically, either we reimplement tf.metrics for now in callbacks, or we have to add hacks to find tf.metric local variables and write reset_op ourselves.

**Comment by ppwwyyxx** [comment]
`ClassificationError` is only (slightly) not equivalent to `ScalarStats('some_error_tensor_in_the_graph')`, when the size of validation dataset is not a multiple of validation batch size. Most of the time, as long as you can compute the per-batch error in the graph, `ScalarStats('tensor')` (which gives you mean error for all batches) should be enough and you don't need to add new metrics to callbacks.

In terms of the interface, I think it's a TensorFlow design flaw that they provide only streaming interface without a non-streaming interface. And do not have reset is an even bigger issue..

Maybe you can wrap streaming interface into non-streaming interface like this:
```python
error, update_op = tf.metrics.error(..., update_collections=[])
with tf.control_dependencies([update_op]):
  error = tf.identity(error)
```

**Comment by ppwwyyxx** [comment]
But as mentioned https://github.com/tensorflow/tensorflow/issues/9498#issuecomment-307884950 a non-streaming version is usually very simple to implemented from scratch. So in tensorpack using a non-streaming version + `ScalarStats` should be enough for most situations.
