### ISSUE TITLE
More complicated operation on DataFlow

### ISSUE THREAD

**Issue by xiaodiu2010** [ppwwyyxx/tensorpack#313]
Thank for your great job!
I'm working on an object detection case and run into processing bottleneck.  So I want to try your project. 
But, I can't do augmentation on images and boxes at the same time like the operation tf.image.crop_to_bounding_box.  I need change all elements in ds(dataflow).
How could I do that? Any suggestions?
Thanks a lot.

**Comment by ppwwyyxx** [comment]
#334

**Comment by haamoon** [comment]
What is your status on this project? I spent some time on this while ago. The accuracy I got was ~10% less than the original [tf-faster-rcnn](https://github.com/endernewton/tf-faster-rcnn) implementation I used. I never found some time to review the code and find the problem. I can share the code with you if you are willing to work on that.

**Comment by ppwwyyxx** [comment]
Btw I have a faster-rcnn code in tensorpack which gets reasonable performance on coco. But I'm busy with other stuffs and don't have time to clean it up and open source it recently.

**Comment by haamoon** [comment]
I can work on it. I wouldn’t be able to finish until CVPR submission deadline though.

**Comment by ppwwyyxx** [comment]
https://github.com/ppwwyyxx/tensorpack/tree/master/examples/FasterRCNN
Still WIP but should work now.
