### ISSUE TITLE
checkpoint-prof.py fails when using QueueInputTrainer

### ISSUE THREAD

**Issue by zsc** [ppwwyyxx/tensorpack#317]
Full example at https://github.com/zsc/tensorpack-exp/blob/master/mnist/base.queue/main.py

For comparison, https://github.com/zsc/tensorpack-exp/blob/master/mnist/base/main.py works like a charm.

The command line used:

python3 ~/zsc-tensorpack/scripts/checkpoint-prof.py --model train_log/main/checkpoint --meta train_log/main/graph-0625-115015.meta --input input:0=1,28,28 label:0=1 --output cross_entropy_loss --print-flops

**Comment by ppwwyyxx** [comment]
In training, the input tensor is called `input_dequeued:0`, the output tensor is `loss:0`
It also builds the graph for validation, where input tensor is named e.g. `input:0`, and output tensor is `towerp0/loss:0`.
You can `print(tensor.name)` to see the name. This is currently very unintuitive, I'll fix it in the future.

**Comment by zsc** [comment]
For that specific instance, the name seems to be input_deque, and a working command line is as follows:

checkpoint-prof.py --model train_log/main/checkpoint --meta train_log/main/graph-0625-115015.meta --input input_deque:0=1,28,28 input_deque:1=1 --output cross_entropy_loss:0 --print-flops
