### ISSUE TITLE
A3C-gym Pre-trained Model 

### ISSUE THREAD

**Issue by sxjzwq** [ppwwyyxx/tensorpack#319]
Hi,

Thanks for the code and your pre-trained model on the open AI gym.

I follow your instruction to install everything and I can train my own model by using your provided training script. However, when I run this

./train-atari.py --task gen_submit --load Breakout-v0.tfmodel --env Breakout-v0 --output output_dir

I got following errors:

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [4] rhs shape= [6]
	 [[Node: 139922605668464/Assign_9 = Assign[T=DT_FLOAT, _class=["loc:@fc-pi/b"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fc-pi/b, 139922605668464/RestoreV2_9/_5)]]

It seems that the model config is not same as the train-atari.py config. How should I modify the training script so that I can use your pre-trained model in the model ZOO?

Thanks!

**Comment by sxjzwq** [comment]
UPDATE: It works on other model and env, such as WizardOfWor-v0

**Comment by ppwwyyxx** [comment]
This is because gym change their environment in recent versions.

**Comment by ppwwyyxx** [comment]
This is https://github.com/openai/atari-py/issues/16. Closing now. I might upload a new model if I have time.

**Comment by sxjzwq** [comment]
Thanks! 
Downgrade the gym to 0.8.2, it works now.

**Comment by ppwwyyxx** [comment]
The model was updated for latest atari-py.
