### ISSUE TITLE
YellowFin Optimizer?

### ISSUE THREAD

**Issue by deeplearningmachine** [ppwwyyxx/tensorpack#320]
Any plan to integrate the YellowFin Optimizer?

paper: https://arxiv.org/abs/1706.03471
code: https://github.com/JianGoForIt/YellowFin/blob/master/tuner_utils/yellowfin.py

**Comment by ppwwyyxx** [comment]
You've given an implementation already, therefore no plan.

The implementation claims to be a "drop-in" replacement of other tf optimizers. If that's true you can just use it.
