### ISSUE TITLE
GPU utilization sometimes 0% when training on multi-gpu

### ISSUE THREAD

**Issue by kdplus** [ppwwyyxx/tensorpack#321]
For one epoch it only need 20 hours on single-gpu,
but when I try to use 4 gpu it need 40-50 hours.

And then I checked the nvidia-smi, I found that in the 4 gpu case, sometimes all of 4 gpu are idle (almost half the time they are not working). But for the single gpu case, it's GPU-Util is always 100%.

I use ZMQ in the my code with nr_proc=10
`ds = PrefetchDataZMQ(ds, nr_proc=nr_proc)`
And test ds using TestDataSpeed, it get 0.56it/s, but in the 4-gpu training case it's not very stable it's about 0.1it/s . 
I also checked the tensorboard :
(4gpu case)
![screenshot from 2017-06-30 14 53 54](https://user-images.githubusercontent.com/3047375/27724339-15f83356-5da4-11e7-9df7-4c557e149e15.png)
(1gpu case)
![screenshot from 2017-06-30 14 55 36](https://user-images.githubusercontent.com/3047375/27724361-316a8ce2-5da4-11e7-85d6-ef3cdd91bc11.png)

**Comment by ppwwyyxx** [comment]
Number of GPUs shouldn't affect the speed of your ds, because ds doesn't use GPU at all. You might have done something wrong somewhere.

**Comment by kdplus** [comment]
GPU util seems good after we fixed a disk mounting problem (by moving data from network-mounted to local). Thanks :p

**Comment by kdplus** [comment]
Well, there are still some problems with the ds in multi-GPUs. It do work on the first several hours of training, but it will slow down after a few hours(GPU waiting for the data)
![screenshot from 2017-07-01 11 18 10](https://user-images.githubusercontent.com/3047375/27758728-ff7954ec-5e4e-11e7-9a72-5af9b712a6f4.png)
finally it will look like this
![screenshot from 2017-07-01 11 19 10](https://user-images.githubusercontent.com/3047375/27758739-296d913c-5e4f-11e7-8335-da3704c16b24.png)
and for the single gpu case it looks like this
![screenshot from 2017-07-01 11 20 26](https://user-images.githubusercontent.com/3047375/27758750-5b4141ae-5e4f-11e7-9ab2-45e9b3a52bc8.png)

And today morning I even found it got stuck in the get_data() here， when executing InferenceRunner. But it works well in the previous epoch.
```
 def run(self):
        with self.default_sess():
            try:
                self.dataflow.reset_state()
                while True:
                    for dp in self.dataflow.get_data():
                        feed = dict(zip(self.placehdrs, dp))
                        # print 'qsize:', self.sess.run([self.op, self.size_op], feed_dict=feed)[1]
                        self.op.run(feed_dict=feed)
            except (tf.errors.CancelledError, tf.errors.OutOfRangeError):
                pass
            except Exception:
                logger.exception("Exception in EnqueueThread:")
            finally:
                try:
                    self.close_op.run()
                except Exception:
                    pass
                logger.info("EnqueueThread Exited.")
```

**Comment by ppwwyyxx** [comment]
You need to check your dataflow again then. Make sure it could run that many of datapoints without slowing down or throwing exception. I don't think anything in tensorpack will slow it down over time.
Some users have reported that their dataflow code doesn't throw exception (but silently died) due to bad opencv installed (#68). This may also lead to your situation.

**Comment by kdplus** [comment]
I think it might be a special problem on my machine or data, when I use the batch size = 1, it won't slow down anymore. Thx
