### ISSUE TITLE
Char-RNN sample 

### ISSUE THREAD

**Issue by luiscarm9** [ppwwyyxx/tensorpack#323]
When you try to generate a new sample based on a model it fails.

But if you change line 146 
`x = np.array([[ds.lut.get_idx(c)]], dtype='int32')`
to
`x = np.array([[ds.chars.index(c)]], dtype='int32')`
And line 158 
`x = np.array([[ds.lut.get_idx(c)]], dtype='int32')`
to
`c = ds.chars[pick(prob[0])]`

It is the same as you wanted in yout initial version?

**Comment by ppwwyyxx** [comment]
Thanks for reporting!
