### ISSUE TITLE
Feature Request: Ability to specify enqueue timeout

### ISSUE THREAD

**Issue by Skylion007** [ppwwyyxx/tensorpack#324]
Since upgrading, I have multiple examples of CycleGAN fail due to enqueue timeout (I think mainly on the test set). There should be  a way to specify the timeout without editing the source code or at the very least the timeout should be increased significantly.

**Comment by ppwwyyxx** [comment]
It's too bad if it takes >10s for a datapoint. Anyway I'll increase it and provide an option.

**Comment by Skylion007** [comment]
I think I narrowed down the issue. Model saver + visualizing test set can easily take more than ten seconds. (Since they use different dataflows it thinks the training one has timed out since it hasn't received anything in 10+ seconds). Model saving alone can easily take 10 seconds if you are saving over the network. Maybe you need to add an exception to the timeout for callbacks?
