### ISSUE TITLE
Conv2D With No Bias in ResNet Example

### ISSUE THREAD

**Issue by haamoon** [ppwwyyxx/tensorpack#327]
Just wondering why convolution layers have no bias in the resent example?
https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L102

It does not seem to be the case in the fb.resnet.torch setup. Am I missing something?

**Comment by ppwwyyxx** [comment]
https://arxiv.org/pdf/1502.03167.pdf Section 3.2.
