### ISSUE TITLE
Optimize a Subset of Variables

### ISSUE THREAD

**Issue by haamoon** [ppwwyyxx/tensorpack#328]
What is the cleanest way to fix some tensorpack layers' variables during training? Obviously, implementing a new Trainer would be an option...

**Comment by ppwwyyxx** [comment]
https://github.com/ppwwyyxx/tensorpack/issues/87#issuecomment-270545291

**Comment by haamoon** [comment]
Thanks! I am trying to port faster-rcnn implementation (https://github.com/endernewton/tf-faster-rcnn) to tensorpack. It seems they have fixed BatchNorm layers during training. Any suggestion for freezing their params?

**Comment by ppwwyyxx** [comment]
https://github.com/ppwwyyxx/tensorpack/issues/296

**Comment by haamoon** [comment]
Reading the documents for freezing several layers in [FAQ](http://tensorpack.readthedocs.io/en/latest/tutorial/faq.html#how-to-freeze-some-variables-in-training). It seems that in cases we are also doing l2_regularization, just using stop_gradient may not be sufficient to freeze some layers. Is that right?

**Comment by ppwwyyxx** [comment]
Method 2 and 3 works for regularization, because regularization is a loss.
Also you can choose what variables to regularize.
