### ISSUE TITLE
Using bitwise convolutions with negative weights?

### ISSUE THREAD

**Issue by the-bobo** [ppwwyyxx/tensorpack#33]
Could not reopen the issue, please see here for more context: https://github.com/ppwwyyxx/tensorpack/issues/27#issuecomment-249977898

> The sign-vs-unsign problem is more relevant in FPGA. But as we are only doing summation, unsign numbers should be fine.

How do you implement this bitwise dot product kernel (equation 3 in section 2.1, DoReFa v2 paper) for negative weights? 

The quantize<sub>k</sub> function defined in Section 2.2 as Equation 5 outputs a number _r<sub>o</sub>_ ∈ [0, 1]. The affine transform on F<sub>w</sub><sup>k</sup>(r<sub>i</sub>) in Equation 9 takes the output of a quantize<sub>k</sub> function and multiplies by 2 and subtracts 1: F<sub>w</sub><sup>k</sup>(r<sub>i</sub>) = 2 * quantize<sub>k</sub>(stuff) - 1.

Thus F<sub>w</sub><sup>k</sup>(r<sub>i</sub>) ∈ [-1, 1].

However, the procedure you define in Equation 3 only works for unsigned values. If some values _x<sub>i</sub>_ in the sequence _x_ or _y<sub>i</sub>_ in the sequence _y_ are negative, then their contribution to the dot product is a subtraction, not an addition, so the simple bitcount(and()) operation no longer suffices.

How did you change the bitwise dot product procedure to account for negative weights?

One possibility:
1. Add an additional sign bit to all M-bit fixed point integers _x<sub>i</sub>_ ∈ _x_ and all K-bit fixed point integers _y<sub>i</sub>_ ∈ _y_.
2. This bit is 1 if the number _x<sub>i</sub>_ is negative, and 0 if _x<sub>i</sub>_ is positive (likewise for the _y<sub>i</sub>_), but does not count as a place-value bit for multiplication.
3. Let bitwise_and<sub>(m, k)</sub> = and(c<sub>m</sub>(x), c<sub>k</sub>(y)), ∀(m, k), ignoring the sign bits.
4. Let bitwise_sign = xor(x<sub>i<sub>signed bit</sub></sub>, y<sub>i<sub>signed bit</sub></sub>). This gives us the sign of the product of x<sub>i</sub> and y<sub>i</sub>
5. ∀ bitwise_and<sub>(m, k)</sub> ∀(m, k), note that bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)</sub> is a vector giving the sign for each element in bitwise_and<sub>(m, k)</sub>.
6. For each pair of vectors ( bitwise_and<sub>(m, k)</sub>, bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)</sub> ) ∀(m,k), drop all members of bitwise_and<sub>(m, k)</sub> and their corresponding signs in bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)</sub> where bitwise_and<sub>(m, k)</sub> == 0. This leaves us with the cases where the bitwise multiplication produced a 1, along with their signs.
7. For each pair of vectors ( bitwise_and<sub>(m, k)</sub>, bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)</sub> ) ∀(m,k), compute bitcount[ bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)</sub> ] to get the total number of negatives for the (m*k) place-value. The total number of positives is given by _len_(bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)</sub>) - bitcount[ bitwise_sign<sub>(x<sub>i</sub>, y<sub>i</sub>)</sub> ].
8. Use the negative and positive accumulations in 7 to get the signed contribution to the dot product.

**Comment by ppwwyyxx** [comment]
Reopen #27 .Closing this.
