### ISSUE TITLE
Use a Tensorpack Layer Inside a Tensorpack Layer

### ISSUE THREAD

**Issue by haamoon** [ppwwyyxx/tensorpack#330]
When implementing a new tensorpack layer, we need to pass the scope of that layer down to the other layers. However, we don't have access to it since it is not an explicit input of the layer.

**Comment by haamoon** [comment]
My bad. I think we don't need to pass the parent scope down to other layers. We just need to pass down different names for each layer. Correct me if it is wrong.

**Comment by ppwwyyxx** [comment]
I think you can always use whatever names as long as the variables created inside the layer don't conflict with others.

**Comment by ppwwyyxx** [comment]
I think you can use whatever names as long as the variables created inside the layer don't conflict with others.
