### ISSUE TITLE
cyclegan differences from paper

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#331]
would be beneficial to mention differences and reasons for the differences:
1. lsgan here uses 0.9 instead of 1 for positive label
2. paper uses 50 image replay buffer for discriminators
3. missing flip augmentations
4. anything else?

**Comment by ppwwyyxx** [comment]
1. https://github.com/junyanz/CycleGAN/blob/master/models/cycle_gan_model.lua#L88
2. I'm lazy

**Comment by eyaler** [comment]
interesting... in the pytotch implementation its 1
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/ee0a8292e2b87449c325bdb9439f90f911a0c0a1/models/networks.py#L94

**Comment by ppwwyyxx** [comment]
It doesn't matter I think

**Comment by Skylion007** [comment]
Is there any easy way to add a replay buffer in Tensorpack? That seems like a useful feature that could be a nice dataflow augmentation.

**Comment by ppwwyyxx** [comment]
https://gist.github.com/ppwwyyxx/e1900b0e49bfb6771af22cc882b57bb5
Doesn't make much difference in my experience.

**Comment by eyaler** [comment]
they changed 0.9 to 1 in the original code, so for educational purposes would be a good idea to change as well

**Comment by ppwwyyxx** [comment]
Sure. done
