### ISSUE TITLE
hue and saturation imgaug assume BGR

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#332]
hue and saturation imgaug assume BGR but ImageFromFile already fixes BGR -> RGB

**Comment by eyaler** [comment]
btw, when i played with saturation augmentation it seemed like it was changing the colors (even when taking into account to BGR/RGB issue)

**Comment by ppwwyyxx** [comment]
Maybe it's OK to move to RGB default to be consistent within dataflow/.
