### ISSUE TITLE
Add image dataflows (feature request)

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#333]
I would suggest adding some image dataflows or would be happy to get advice on preferred way to implement:
1. ImageFromIterable
2. ImageFromWebcam

currently i am saving to file and using ImageFromFile

**Comment by ppwwyyxx** [comment]
1. There is a more general DataFromGenerator
2. Why do you want this? I don't think this'll be useful for training. For testing you can call whatever webcam libraries anyway.

In general just write whatever code in get_data().http://tensorpack.readthedocs.io/en/latest/tutorial/extend/dataflow.html

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you have more to discuss.
