### ISSUE TITLE
split filter weights dimension

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#336]
When we split a filter (e.g. in AlexNet), why are there fewer parameters:

e.g. Alexnet
conv2/W:0      [5, 5, **48**, 256]

However, I had specified 96 output filters for the first layer (conv1/W:0      [11, 11, 3, **96**]). 
**So, shouldn't the third dimension be 96?**

Am I missing something? Or is the same filter re-used across 48 channels each of the previous layer's channels?

Thanks.

**Comment by ppwwyyxx** [comment]
This is what "split" means. Each output only connects to half channels in the input.
https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf

**Comment by a-maci** [comment]
Got it.
