### ISSUE TITLE
Is it possible to build the ModelDesc from the saved checkpoint files?

### ISSUE THREAD

**Issue by NoobFang** [ppwwyyxx/tensorpack#338]
According the examples, such as "CAM-resnet.py", before using the pretrained resnet, I have to build the model from scratch. However, could I build the ModelDesc by load the checkpiont files? I only know how to build the graph by importing the meta graph...

Besides, could anyone tell me how to redirect the input placeholders to the loaded pretrained model?

**Comment by ppwwyyxx** [comment]
TF checkpoint only stores variables. 

What do you mean by "redirect the input placeholders to the loaded pretrained model"?

**Comment by NoobFang** [comment]
Specifically, I have trained the resnet50 by your example "imagenet-resnet.py", then I want to build a new model upon this pretrained resnet, say, add some layers after the output of some conv layer of resnet50. However, when I import the meta graph which saved by the exmaple "imagenet-resnet.py" and I print the imported model by "decscribe_model" function but did not find the input placeholder for feeding new data. 
Do I need to create new placeholders for new data? If so, how to connect (which I said redirect) these new placeholder to the pretrained resnet? Or is there some elegant api to do this without build the whole model from scratch(like input placeholders -> every blocks of resnet-> my new layers -> ...)?

**Comment by ppwwyyxx** [comment]
In a serialized graph, there is nothing called "inputs", "layers". These are just human-made abstractions that will get lost once you dump the graph.
The best way would be to copy the model code from the old script and modify upon it.

**Comment by NoobFang** [comment]
OK, I got it. 
Thanks for your prompt reply!
