### ISSUE TITLE
Rookie Here, Could Someone Please Explain How to Run This? I'm Easy. All Modules are loaded

### ISSUE THREAD

**Issue by MotorCityCobra** [ppwwyyxx/tensorpack#34]
It's not you, tensorpack. It's me.
I'm 100% ready to go with everything installed I just don't know how to code what needs to be coded here.
I've installed gym. The full version.
I have every program and every module set to go in my virtualenv but I'm not sure what to write in run-atari.py, train-atari.py, I'd like to see this play Breakout so I have the Breakout-v0.tfmodel file, all in my folder with the modules. There's also different algorithms for the games, like this one...
https://gym.openai.com/evaluations/eval_L55gczPrQJamMGihq9tzA
I'd appreciate if someone could tell me where this code goes as well.

I've run SpaceInvadors-v0 from a tutorial, the repo of which is here...
https://github.com/llSourcell/Game-AI
If there's an easy way to swap SpaceInvaders with another game and algorithm in this setup, that works for me too.

I've installed additional modules so just to make it clear, if someone could spell out, in specific code what needs to happen to deploy...
run-atari.py and train-atari.py, and have them play this file... Breakout-v0.tfmodel
and where this algorithm goes... https://gym.openai.com/evaluations/eval_L55gczPrQJamMGihq9tzA

Thank You!

**Comment by ppwwyyxx** [comment]
I don't understand what you're asking. What exactly do you want to do?

If you just want to see it play Breakout, use `run-atari.py` as the instructions in the readme and it'll produce a directory with videos.
```
./run-atari.py --load Breakout-v0.tfmodel --env Breakout-v0
```

**Comment by MotorCityCobra** [comment]
That is all I want to do. I'm just beyond my depth. When I type...
$ python run-atari.py --load Breakout-v0.tfmodel --env Breakout-v0
Traceback (most recent call last):
  File "run-atari.py", line 24, in <module>
    from common import play_one_episode
ImportError: cannot import name play_one_episode

I think the...
 Enable import tensorpack:
export PYTHONPATH=$PYTHONPATH:`readlink -f path/to/tensorpack`
... part from your instructions is my problem. I don't know.
It's to make Python able to find the tensorpack file?
I enter this and get an error...
$ export PYTHONPATH=$PYTHONPATH: readlink -f /Users/me/PE11/gym/tensorpack
-bash: export: `-f': not a valid identifier
-bash: export: `/Users/me/PE11/gym/tensorpack': not a valid identifier

**Comment by ppwwyyxx** [comment]
1. There is a symbolic-link `common.py` in the [OpenAIGym directory](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/OpenAIGym), it looks like you lost that file somehow.

2. the command `readlink -f` may not work on MacOSX. You just need to use
`export PYTHONPATH=$PYTHONPATH:/absolute/path/to/PE11/gym/tensorpack`

**Comment by MotorCityCobra** [comment]
Thank for all the responses
The export PYTHONPATH=$PYTHONPATH thing seems to have worked
I think I'm down to one last thing...
That common.py file is pointing to another common.py file in the /Atari2600 folder if I'm not mistaken.
I know I should know how to do this before bothering a software wizard but I don't know how to get it to point to the Atari2600 common file
The original way it's written I get
    ../Atari2600/common.py
    ^
SyntaxError: invalid syntax

I dug online and couldn't figure out how to do it for python (OSX)
I tried saving the path as this instead (in the common.py file)...
~/Users/AnthonyCelio/PE11/gym/tensorpack/examples/Atari2600/common.py
     ^
SyntaxError: invalid syntax

and tried

    ~/Atari2600/common.py
     ^
SyntaxError: invalid syntax

**Comment by ppwwyyxx** [comment]
If you had the file but it's not pointing correctly, then either your filesystem doesn't support such link, or you have copied the project to other filesystem (which doesn't support link) before.
In this case you can just copy the file from Atari2600/ to here.
This has nothing to do with python.

**Comment by MotorCityCobra** [comment]
I got past the parts discussed earlier, and thank you again.
I though I was set up to go but I don't know what I'm doing with this. I'm taking a break from this for a while

$ python run-atari.py --load Breakout-v0.tfmodel --env Breakout-v0
[1020 12:37:33 @run-atari.py:87] Environment Name: Breakout-v0
[2016-10-20 12:37:33,622] Making new env: Breakout-v0
[2016-10-20 12:37:33,672] Making new env: Breakout-v0
Traceback (most recent call last):
  File "run-atari.py", line 98, in <module>
    run_submission(cfg)
  File "run-atari.py", line 66, in run_submission
    player = get_player(dumpdir=dirname)
  File "run-atari.py", line 27, in get_player
    pl = GymEnv(ENV_NAME, dumpdir=dumpdir, auto_restart=False)
  File "/Users/me/PE11/gym/tensorpack/RL/gymenv.py", line 33, in __init__
    self.gymenv.monitor.start(dumpdir)
  File "/Users/me/PE11/gym/gym/monitoring/monitor.py", line 138, in start
    You should use a unique directory for each training run, or use 'force=True' to automatically clear previous monitor files.'''.format(directory, ', '.join(training_manifests[:5])))
gym.error.Error: Trying to write to monitor directory gym-submit with existing monitor files: gym-submit/openaigym.manifest.0.67134.manifest.json.

 You should use a unique directory for each training run, or use 'force=True' to automatically clear previous monitor files.

**Comment by ppwwyyxx** [comment]
The error is saying that the output file `gym-submit/*` already exists. If you delete the directory then it will run.

**Comment by MotorCityCobra** [comment]
It's running. Thank you so much for your help.
Do need to add
'--display true'
to the end of... 
$'python run-atari.py --load Breakout-v0.tfmodel --env Breakout-v0'
to see it play?

**Comment by MotorCityCobra** [comment]
Nevermind. I see know. It saves as an mp4.
Thank you again!!!!!!!!
