### ISSUE TITLE
Better Graph Visualization in Tensorboard (hide boilerplate)

### ISSUE THREAD

**Issue by Skylion007** [ppwwyyxx/tensorpack#340]
Hiya, I absolutely love this library, however, it does produce quite messy visualizations in Tensorflow at time. I was wondering if there were any efforts to help re-mediate this. While this project makes great strides in using good naming scopes some operations (like the l2regularizer) make the graph very difficult to read. In particular, many of the GAN architectures can be difficult to visualize.

**Comment by ppwwyyxx** [comment]
The graph is just so complex, and I don't know how tensorboard organizes a graph and how to make it looks better. Maybe I'll try adding some name scope here and there but I'm not sure.

**Comment by Skylion007** [comment]
Yeah, I wish there was a feature in Tensorflow for hidden namescopes or such. Regardless, I've figured out how to look at Generator and Discriminator based Tensorboards, but it can definitely be confusing at times. My biggest pete peave is the l2regularizers and conditionals which creates a long lines of disconnected ops and require zooming in a lot. Also a lot of the dataflow code could probably be a little better organized. All in all, the namescopes at last make it readable which is more than I can say for other libraries.

**Comment by ppwwyyxx** [comment]
Until now tensorflow still doesn't have a nice way to reuse a name_scope (https://github.com/tensorflow/tensorflow/issues/6007). Without this feature it's hard to group relevant ops together in tensorboard.
