### ISSUE TITLE
Modify the weight of certain layer after every step

### ISSUE THREAD

**Issue by flydance0217** [ppwwyyxx/tensorpack#342]
Hello,

I am using the cifar100-resnet.py as an example, and I am wondering what will be the best way to change the weight of one or more layers after each step (after each gradient update) during the training?

I tried doing after self._callbacks.trigger_step(). I can access the weights and change to a numpy format for post-processing by calling tf.trainable_variables(). However, I can not update the weight back to the graph. self.sess.run(tf.trainable_variables()[counter].assign(new_weights)) will generate the following error:
RuntimeError: Graph is finalized and cannot be modified

Which makes sense to me but this approach would work in the tensorflow mnist examples, I guess because everything is running within a session.

**Comment by ppwwyyxx** [comment]
You can do it through a callback. You have to create the op in `_setup_graph`, and run them in `_trigger_step`. This design is exactly to prevent you from doing `self.sess.run(tf.trainable_variables()[counter].assign(new_weights)` which will add thousands of ops to the graph and blow everything.

**Comment by ppwwyyxx** [comment]
You may wish to make your assignment an explicit dependency of the training iteration, to save the extra "sess.run" overhead. `PostProcessOptimizer`, `VariableAssignmentOptimizer` may help do some easy per-variable assignment, for example, the [Wasserstein GAN](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/GAN/WGAN.py#L36) example clips the weights every iteration.

**Comment by flydance0217** [comment]
Thanks ppwwyyxx for the prompt response. I have been looking at the 2 solutions you mentioned over the weekend, but still unable to develop a working solution.

I hope I can make this clear, just to briefly describe what I want to achieve

In every step, I want to look at the entire or subset (i.e., in the case of the weights for fully connected layer, say the first 10 rows) weights of one or more layers. I want to do some post-processing (i.e., by computing std, mean, median, etc). Depending on the post-processed info, I would then want to have the ability to change the weight value on the same/different layer at the specific location to specific values (i.e., last row of the fully-connected layer). 

First suggestion (create ops in _setup_graph):
I don't seen to be able to access the weight value in this case(i.e., by calling tf.trainable_variables()[index].eval()). Can you please elaborate more on what you meant by "create ops in _setup_graph"? Does this mean that all the operations need to be in tf world?

Second suggestion:
I looked at the Wasserstein GAN example you provided. It uses the tf.clip_by_value function provided by tensorflow, and works on the entire weight only. I traced through the code to gen_math_ops.py and op_def_library.py but its not straight-forward at this point, and is limited to tf world only. It would be nice if I can work using numpy (which I don't seen to be able to do it in this case)

The post-processing in numpy is key in this case I guess, as there are some complicated algorithms that have been developed in numpy world.

Thanks so much for the help!

**Comment by ppwwyyxx** [comment]
It'll be slow if you do the operations in numpy. But there are ways to do it.
You should be able to just call `var.eval()` and `var.load(value)` to read and write to a variable in `trigger_step`. If you meet errors please post them.

**Comment by flydance0217** [comment]
Thanks. I didn't realize that you can do var.load(value) to update the value. This works but now it is extremely slow (as expected). I really need to consider rewriting everything in ops in the graph now...

Thanks again!

**Comment by flydance0217** [comment]
Sorry to bother you again. I was able to follow your Wasserstein GAN example and made the per-variable operation with VariableAssignmentOptimizer. However, is there a way to optionally perform this operation say after epoch 20? In the case of the Wasserstein GAN example, this means only perform clipping after epcoh 20.

**Comment by ppwwyyxx** [comment]
If you have complicated control logic it's easier to do it in callbacks. As long as you don't call `var.eval()` and `var.load()` it's not going to hurt much in performance.
Just create the assignment ops you need to run in `_setup_graph()` and run them in `_trigger_step()`. You can access the epoch number by `self.epoch_num`.

In the graph there is no notion of "epoch". You can use `global_step` (with `tf.train.get_or_create_global_step()`) and `tf.cond` for the condition.

**Comment by ppwwyyxx** [comment]
the WGAN example was just updated to include two ways to clip the weights.

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you have more questions.
