### ISSUE TITLE
Error with OpenCV in RandomResize

### ISSUE THREAD

**Issue by Skylion007** [ppwwyyxx/tensorpack#343]
I tried to modify the CycleGAN code to include additional augmentations and got a peculiar error:
   
     resize_range = (int(SHAPE * 1.07), int(SHAPE * 1.17))
     augs = [
            imgaug.Flip(horiz=True),
            #imgaug.Resize(int(SHAPE * 1.12)),
            imgaug.RandomResize(resize_range, resize_range,
                aspect_ratio_thres=0),
            imgaug.RandomCrop(SHAPE),
        ]

Error: 

OpenCV Error: Unspecified error (The numpy array of typenum=2, ndims=3 can not be created) in allocate, file /build/opencv-FWWjHr/opencv-2.4.9.1+dfsg/modules/python/src2/cv2.cpp, line 201

any idea what the problem could be?

**Comment by ppwwyyxx** [comment]
The two arguments are scaling ratio (e.g. 0.8-1.2), not pixels.

**Comment by Skylion007** [comment]
It would be really nice to have a version random resize that took in a range of pixels. Otherwise, you have to calculate the maximum size of the image, resize it to that and then calculate a downsize range to preserve as much information as possible and remove downsampling artifacts.

**Comment by ppwwyyxx** [comment]
Sounds like a reasonable feature to add.
