### ISSUE TITLE
Tensorflow checkpoint dir and log dir can be a HDFS path

### ISSUE THREAD

**Issue by tonyw** [ppwwyyxx/tensorpack#345]
the checkpoint dir maybe a hdfs path, so should not assert os.path.isdir(checkpoint_dir)

**Comment by ppwwyyxx** [comment]
Switched to `tf.gfile.IsDirectory`. Please reopen if the problem still exists.

**Comment by tonyw** [comment]
yes，tensorflow can support hdfs,but tensorpack     not.by specific，there is an assert in the "callback.saver" class,in tensorpack souce  code. So I think the  source  keeper shuold remove the assert statement or use gfile interface

**Comment by tonyw** [comment]
I checked it. Its runs smoothly. Thank you respected job
