### ISSUE TITLE
About SyncMultiGPUTrainerReplicated

### ISSUE THREAD

**Issue by tonyw** [ppwwyyxx/tensorpack#346]
I find SyncMultiGPUTrainerReplicated class in the source code ,but I do not find example. I use it in the mnist-keras example, but it's failed. So I want to know 'SyncMultiGPUTrainerReplicated' is ready for product or not

**Comment by tonyw** [comment]
Or Is there any sample for SyncMultiGPUTrainerReplicated?

**Comment by ppwwyyxx** [comment]
With keras you simply cannot do replicated training. That's by design of keras.
Apart from that, you should be able to replace SyncMultiGPUTrainerParameterServer with SyncMultiGPUTrainerReplicated anywhere.

**Comment by tonyw** [comment]
But it's alway failed,and throw exception like:
ValueError: Variable conv0/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
you can test with mnist-slim or anyone other's

**Comment by ppwwyyxx** [comment]
I tested with mnist-convnet.py. Just replace the trainer and it works.

**Comment by tonyw** [comment]
after I use newest code,it works too.
Thank you
