### ISSUE TITLE
Error using use BatchRenorm

### ISSUE THREAD

**Issue by JahodaPavel** [ppwwyyxx/tensorpack#347]
X1 = BatchRenorm(X1, rmax, dmax, data_format='NHWC')
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/models/common.py", line 106, in wrapped_func
    assert isinstance(name, six.string_types), name
AssertionError: Tensor("Reshape:0", shape=(?, 108, 192, 1), dtype=float32)

Some of my code:
    rmax = tf.Variable(1)
    dmax = tf.Variable(0)
    X1 = tf.reshape(data, [-1, height, width, 1])
    X1 = BatchRenorm(X1, rmax, dmax, data_format='NHWC')

Maybe its a beginner mistake, but to be honest, i did not find any examples how to use BatchRenorm function

**Comment by ppwwyyxx** [comment]
There are examples using other layers. You need a scope name as the first argument. 

X1 = BatchRenorm('bn', X1, rmax, dmax, data_format='NHWC')

**Comment by ppwwyyxx** [comment]
After dc448bdab391a6eac87de47efd5f8a64caebaf99, [API documentation] was now updated to include the name argument.
