### ISSUE TITLE
InferenceRunner on a different model?

### ISSUE THREAD

**Issue by haamoon** [ppwwyyxx/tensorpack#352]
My training and validation graph have some differences and it would much easier if I could create them as two different graphs that share the same set of trainable variable names. In this case, I can not use InferenceRunner callback since it does the inference on the training graph only.  I am wondering if  there is any other callback for this case?

**Comment by ppwwyyxx** [comment]
No. Everything happens in one graph, and it's not trivial to share variables between two graphs.
The existing tools are for the most common cases only, for your situation you can setup the validation ops in `_setup_graph` and write the inference yourself.

**Comment by ppwwyyxx** [comment]
Also if the difference is small you can just check `if ctx.is_training` in `_build_graph`.

**Comment by haamoon** [comment]
Does InferenceRunner call _build_graph with ctx.is_training == False? I though _build_graph is called only once when the training starts...

**Comment by ppwwyyxx** [comment]
InferenceRunner will call _build_graph with ctx.is_training == False.

`_build_graph` was also called multiple times if you use multi-gpu training.

**Comment by haamoon** [comment]
Thanks! That is exactly what I needed.
