### ISSUE TITLE
2 GPU performance same as 1 GPU

### ISSUE THREAD

**Issue by tonyw** [ppwwyyxx/tensorpack#353]
I run with 2 GPU ,but the performance asme as 1 GPU.
There is the chrome tracing file,and I use the vgg16 model.
Is there anything wrong with me?
[chrome-trace-100.json.zip](https://github.com/ppwwyyxx/tensorpack/files/1187315/chrome-trace-100.json.zip)

**Comment by ppwwyyxx** [comment]
What do you mean " the performance is the same as 1 GPU"?
Please describe what you saw, not only the interpretation of what you saw.

**Comment by tonyw** [comment]
when I run with 1 GPU,the progress bar print the throughput like this "99/590[00:50<03:23,2.41it/s". when I use 2 GPU's by changing the 'CUDA_VISIBLE_DEVICES',the progress bar print the same value.
At the begin, there are some log like this:
[0731 19:01:07 @model_utils.py:47] Model Parameters: 
name         shape                   dim  device
-----------  ----------------  ---------  -------------
conv1_1/W:0  [3, 3, 3, 64]          1728  /device:GPU:0
conv1_1/b:0  [64]                     64  /device:GPU:1
conv1_2/W:0  [3, 3, 64, 64]        36864  /device:GPU:1
conv1_2/b:0  [64]                     64  /device:GPU:0
conv2_1/W:0  [3, 3, 64, 128]       73728  /device:GPU:0
conv2_1/b:0  [128]                   128  /device:GPU:1
conv2_2/W:0  [3, 3, 128, 128]     147456  /device:GPU:1
conv2_2/b:0  [128]                   128  /device:GPU:0
conv3_1/W:0  [3, 3, 128, 256]     294912  /device:GPU:0
conv3_1/b:0  [256]                   256  /device:GPU:1
conv3_2/W:0  [3, 3, 256, 256]     589824  /device:GPU:1
conv3_2/b:0  [256]                   256  /device:GPU:0
conv3_3/W:0  [3, 3, 256, 256]     589824  /device:GPU:0
conv3_3/b:0  [256]                   256  /device:GPU:1
conv4_1/W:0  [3, 3, 256, 512]    1179648  /device:GPU:1
conv4_1/b:0  [512]                   512  /device:GPU:0
conv4_2/W:0  [3, 3, 512, 512]    2359296  /device:GPU:0
conv4_2/b:0  [512]                   512  /device:GPU:1
conv4_3/W:0  [3, 3, 512, 512]    2359296  /device:GPU:1
conv4_3/b:0  [512]                   512  /device:GPU:0
conv5_1/W:0  [3, 3, 512, 512]    2359296  /device:GPU:0
conv5_1/b:0  [512]                   512  /device:GPU:1
conv5_2/W:0  [3, 3, 512, 512]    2359296  /device:GPU:1
conv5_2/b:0  [512]                   512  /device:GPU:0
conv5_3/W:0  [3, 3, 512, 512]    2359296  /device:GPU:0
conv5_3/b:0  [512]                   512  /device:GPU:1
fc6/W:0      [25088, 4096]     102760448  /device:GPU:1
fc6/b:0      [4096]                 4096  /device:GPU:0
fc7/W:0      [4096, 4096]       16777216  /device:GPU:0
fc7/b:0      [4096]                 4096  /device:GPU:0
fc8/W:0      [4096, 2]              8192  /device:GPU:0
fc8/b:0      [2]                       2  /device:GPU:0
Total #vars=32, #param=134268738 (512.19 MB assuming all float32)


I think there are must be someting wrong

**Comment by ppwwyyxx** [comment]
This would depend on how you write `get_data()`.
If you use the same batch size in `get_data()`, the total batch size would be doubled when you use a multigpu trainer.

**Comment by tonyw** [comment]
[log.log.zip](https://github.com/ppwwyyxx/tensorpack/files/1187338/log.log.zip)
there is the raw log.
I want to see a clearly performance raise by the progress bar.for example: if I use 1 GPU,the progress bar print 1it/s,when I use 2 GPU, the pregress bar print 2it/s. like this.
In that case, I did not change the batch size.

**Comment by ppwwyyxx** [comment]
Then you should set batch size to be `batch_size / num_gpu`.

**Comment by tonyw** [comment]
Oh, you mean the tensorpack would fetch double data , If I use two tower? 
In that case , if I set the max_epoch = 1, each tower run half epoch or each tower will run all epoch?

**Comment by ppwwyyxx** [comment]
In each iteration each tower takes one datapoint from your dataflow and train on it.

**Comment by tonyw** [comment]
Thank you.
Is there anyway to evaluate the total throughput around all Gpu cards?

**Comment by ppwwyyxx** [comment]
what's the definition of total throughput around all Gpu cards?

**Comment by ppwwyyxx** [comment]
If you're talking about images per second, that's just iteration/s * total_batch_size

**Comment by tonyw** [comment]
I red the ProgressBar class. I think you're right.The throughput is not a common definition for sync and async training. But In sync Multi-GPU Trainer,the throughput is just mean in a sync iterator,all gpu process data counter.

**Comment by tonyw** [comment]
So I think if tensorpack supply a specific progressbar for sync Multi-GPU Trainer, it's will be a better job.And will avoid make other users conflict like me.

**Comment by ppwwyyxx** [comment]
I don't think there will be confusion if you know what happen in an iteration. Progress bar has nothing to do with this -- it doesn't know what is a batch anyway.

**Comment by tonyw** [comment]
thanks for your feedback

**Comment by ppwwyyxx** [comment]
Thanks and I'll find a place in tutorial to mention what is an iteration.
