### ISSUE TITLE
Difference between PrefetchDataZMQ and PrefetchOnGPUs

### ISSUE THREAD

**Issue by tonyw** [ppwwyyxx/tensorpack#354]
If I train data by multiGpuTrainer, what's difference between PrefetchDataZMQ and PrefetchOnGPUs?

**Comment by PatWie** [comment]
Sometimes the pre-processing can benefit from running on a GPU, e.g. you can use GPU 1&2 for training and 3&4 for preprocessingdata on-the-fly (OpenCV supports GPUs or custom code)
see: https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/dataflow/prefetch.py#L207

**Comment by tonyw** [comment]
Thank you for your comment
