### ISSUE TITLE
Problems with execution of examples/HED with pretrained model

### ISSUE THREAD

**Issue by VladMiryaha** [ppwwyyxx/tensorpack#355]
Hi,

I want to run HED example with pretrained model - HED_pretrained_bsds.npy, but faced with a couple of problems:

1.
> Traceback (most recent call last):
>   File "hed.py", line 225, in <module>
>     run(args.load, args.run, args.output)
>   File "hed.py", line 196, in run
>     predictor = OfflinePredictor(pred_config)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorpack-0.3.0-py3.5.egg\tensorpack\predict\base.py", line 134, in __init__
>     config.model.build_graph(input)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorpack-0.3.0-py3.5.egg\tensorpack\graph_builder\model_desc.py", line 124, in build_graph
>     self._build_graph(inputs)
>   File "hed.py", line 49, in _build_graph
>     b2 = branch('branch2', l, 2)
>   File "hed.py", line 37, in branch
>     l = BilinearUpSample('upsample{}'.format(up), l, 2)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorpack-0.3.0-py3.5.egg\tensorpack\models\common.py", line 133, in wrapped_func
>     outputs = func(*args, **actual_args)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorpack-0.3.0-py3.5.egg\tensorpack\models\pool.py", line 164, in BilinearUpSample
>     inp_shape = x.shape.as_list()
> **AttributeError: 'Tensor' object has no attribute 'shape'**

I fixed it by changing line 164 of [models/pool.py:](https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/models/pool.py)
`inp_shape = x.shape.as_list()` -> `inp_shape = x.get_shape().as_list()`

2. After this fix I got this one:

> Traceback (most recent call last):
>   File "hed.py", line 225, in <module>
>     run(args.load, args.run, args.output)
>   File "hed.py", line 196, in run
>     predictor = OfflinePredictor(pred_config)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorpack-0.3.0-py3.5.egg\tensorpack\predict\base.py", line 134, in __init__
>     config.model.build_graph(input)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorpack-0.3.0-py3.5.egg\tensorpack\graph_builder\model_desc.py", line 124, in build_graph
>     self._build_graph(inputs)
>   File "hed.py", line 70, in _build_graph
>     tf.concat([b1, b2, b3, b4, b5], 3), 1, 1,
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1075, in concat
>     dtype=dtypes.int32).get_shape(
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 669, in convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 165, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 367, in make_tensor_proto
>     _AssertCompatible(values, dtype)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertCompatible
>     (dtype.name, repr(mismatch), type(mismatch).__name__))
> TypeError: Expected int32, got list containing Tensors of type '_Message' instead

So as I understood we have problems with `tf.concat([b1, b2, b3, b4, b5], 3)`, but
I don't know how to fix it.

Could somebody help me with this problem?

P.S. Tensor flow version - 0.12.1, python 3.5, CUDA 8.0 & CUDNN 5.1
TensorPack - current repo (data of installation - 31.07.2017)

**Comment by VladMiryaha** [comment]
Problems disappeared after updating to Tensorflow ver. 1.0

**Comment by ppwwyyxx** [comment]
tensorpack requires tensorflow>=1.0.
