### ISSUE TITLE
When GraphProfiler is triggered I get SIGABRT

### ISSUE THREAD

**Issue by maciejjaskowski** [ppwwyyxx/tensorpack#356]
When I add GraphProfiler in v0.3.0 to callbacks list I get 

```
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

during or right after `_before_run()` (not sure when). 

Is this specific to my code or a known bug?

**Comment by ppwwyyxx** [comment]
before_run only adds 
```python
opt = tf.RunOptions()
opt.trace_level = tf.RunOptions.FULL_TRACE
```
to sess.run. I have no clue why it crashes, but it's probably not a tensorpack issue.

**Comment by maciejjaskowski** [comment]
Ok, I just tested adding GraphProfiler to imagenet-resnet.py from examples and it crashed the same way. 

```
python imagenet-res.py --fake --gpu=0
```

Any clues where to look for the cause?

**Comment by ppwwyyxx** [comment]
It's weird, but likely a TF or cuda issue. And since it works on newer version probably no one in TF team would look at it.
