### ISSUE TITLE
Inconsistent setting on learning rate of cifar10-resnet

### ISSUE THREAD

**Issue by chunfuchen** [ppwwyyxx/tensorpack#357]
In example/ResNet/cifar10-resnet.py,
the default learning rate is 0.01; however the learning rate schedule changes the learning rate to 0.1 after the first epoch. May I know the purpose to increase the learning rate after 1 epoch? Or just a typo in setting default learning rate. 
Thanks.

**Comment by ppwwyyxx** [comment]
this follows the original paper.

**Comment by chunfuchen** [comment]
Thanks. I do not notice this detail.
