### ISSUE TITLE
examples/ResNet/imagenet-resnet.py do not speed up with more gpus 

### ISSUE THREAD

**Issue by maciejjaskowski** [ppwwyyxx/tensorpack#359]
I tried running `imagenet-resnet.py` on my 4x Titan X instance like this

`python imagenet-resnet.py --fake --gpu=0`

and 

`python imagenet-resnet.py --fake --gpu=0,1,2,3`

The performance as given by progress bar is ~ 9.5 it/s in the first case and 5000 iterations to go in the first case and 7.5 it/s in the latter case and 5000 iterations to go as well.

What am I missing?

**Comment by ppwwyyxx** [comment]
#218

**Comment by maciejjaskowski** [comment]
Ok, let me then ask these questions:
What does an iteration mean in the case of multi-gpu training? Is it
batch_size*nr_tower or batch_size ?

Are there any requirements when it comes to shuffling data in dataflow when
using multigpu trainer?

Best,
Maciej

**Comment by PatWie** [comment]
One iteration means one [update-step
](https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/train/base.py#L102). It is then `batchsize*towers` unless you [change it](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L89) explictly.

The shuffle should be the same as in single-gpu.

**Comment by ppwwyyxx** [comment]
@maciejjaskowski also see #353
