### ISSUE TITLE
Improve ZMQ operator

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#362]
Following #221 which has two many outdated discussions.

Status:
ZMQ Op now can run. Can receive list of tensors from an endpoint.

TODO list:
Build:
- [ ] Now it still requires libzmq & zmq.hpp header. Anyway to make it easier? Maybe zmq.hpp can be downloaded automatically. A header doesn't hurt.
- [x] Anyway to detect whether TF is built with CXX11ABI?
- [x] Compile to .dylib on mac?

Functionalities:
- [x] Support more types of tensors.
- [x] Support more socket options.
  - [x] hwm
  - [x] bind/connect

Correctness:
- [x] Check if it works under multi-threading. May need a lock per Op?
- [ ] Some "real" unittests are needed.

Performance:
- [x] My expectation is that zmq op alone will be slightly slower than queues (due to copy), but with GPU prefetch they should be the same. Need some benchmark.
- [ ] Python-side serialization is quite slow actually. Needs improvements.

This issue is still not my priority, btw

**Comment by cyrsis** [comment]
ZMQ is good for  message, Do you want to do reactive version of tensorpack?

**Comment by ppwwyyxx** [comment]
No. It's expected to be used to send data for training.

**Comment by ppwwyyxx** [comment]
Moved to a separate project at https://github.com/tensorpack/zmq_ops.

**Comment by ppwwyyxx** [comment]
Btw, after the recent updates, I found that zmq reader is slightly faster than using queues or `dataset.from_generator`.
