### ISSUE TITLE
import tensorpack on python 3.6 too slow

### ISSUE THREAD

**Issue by ricky1203** [ppwwyyxx/tensorpack#363]
```
time python -c 'import tensorpack'
real	0m9.369s
user	0m9.136s
sys	0m0.224s
```
tensorpack will import all modules in tensorpack/__init__.py, why not let user choose import only needed modules ?

**Comment by ppwwyyxx** [comment]
The above commits should improve it a little bit, but the majority of time is spent in tensorflow.
```python
# a.py:
import tensorflow.contrib.framework             
import cv2              
import time             
s = time.time()         
import tensorpack       
print(time.time() - s) 
```
`time python a.py` takes 8s to finish, but prints 0.25s

**Comment by ppwwyyxx** [comment]
Better to ask why `tensorflow.contrib` import all modules in [`__init__.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/__init__.py)
