### ISSUE TITLE
error in DataParallelInferenceRunner

### ISSUE THREAD

**Issue by chunfuchen** [ppwwyyxx/tensorpack#365]
I was using `DataParallelInferenceRunner` without any issue but after I pull your recent changes, it throws an error about undefined attribute.  Do I need to revise the usage of this class? 

Thanks for your kindly support.

Here is my code to use `DataParallelInferenceRunner` (refer to cifar10-resnet.py)
```python
DataParallelInferenceRunner(dataset_test,
  [ScalarStats('cost'), ClassificationError()], [ x for x in range(get_nr_gpu()) ]),
```

and the log is
 
```
raceback (most recent call last):
  File "examples/ResNet/cifar10-resnet.py", line 178, in <module>
    SyncMultiGPUTrainerParameterServer(config).train()
  File "/u/chenrich/Developer/tensorpack/tensorpack/train/base.py", line 100, in train
    self.setup()
  File "/u/chenrich/Developer/tensorpack/tensorpack/train/base.py", line 140, in setup
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/u/chenrich/Developer/tensorpack/tensorpack/callbacks/base.py", line 54, in setup_graph
    self._setup_graph()
  File "/u/chenrich/Developer/tensorpack/tensorpack/callbacks/group.py", line 64, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/u/chenrich/Developer/tensorpack/tensorpack/callbacks/base.py", line 54, in setup_graph
    self._setup_graph()
  File "/u/chenrich/Developer/tensorpack/tensorpack/callbacks/inference_runner.py", line 170, in _setup_graph
    cbs = self._input_source.setup(self.trainer.model.get_inputs_desc())
  File "/u/chenrich/Developer/tensorpack/tensorpack/graph_builder/input_source_base.py", line 43, in setup
    self._setup(inputs_desc)
  File "/u/chenrich/Developer/tensorpack/tensorpack/graph_builder/input_source.py", line 136, in _setup
    self._cb = self._DataParallelFeedCallback(self._repeat_ds, self._placehdrs_per_tower)
AttributeError: 'DataParallelFeedInput' object has no attribute '_repeat_ds'
```

**Comment by ppwwyyxx** [comment]
Probably a bug I introduced while working on #139. I will take a look.

btw are you able to see any speed improvements over the non-parallel InferenceRunner? It's quite slow in my cases so I reopen #139.

**Comment by chunfuchen** [comment]
Here are my logs on resnet-18 over the ImageNet dataset. (I am testing on P100)
w/o `DataParallelInfereneRunner`: ~50 seconds
w/  `DataParallelInfereneRunner` (4 gpus): ~26 seconds

Even if it is not linear speedup, it still help a lot.

Btw, to achieve the above results, I need to enable data prefetch for inference as well (in your example codes, the prefetch is disable.)

[examples/ResNet/imagenet-resnet.py line 79](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L79)
```
if isTrain:
    ds = PrefetchDataZMQ(ds, min(20, multiprocessing.cpu_count()))
```

**Comment by chunfuchen** [comment]
One more results, resneXt-50 over the ImageNet dataset. (ResNeXt is implemented by using *split* in Conv2d.)

w/o `DataParallelInfereneRunner `: ~180 seconds
w/ `DataParallelInfereneRunner `: ~60 seconds

**Comment by ppwwyyxx** [comment]
You shouldn't enable multi-process prefetch for inference (and that's why inference is slow and that's what I'm fixing).
You can use at most one process for inference, otherwise you have many processes reading validation data at the same time -- processes don't talk to each other, you may end up getting one data point multiple times.

**Comment by chunfuchen** [comment]
Thanks. I see. Nonetheless, in this case, for training data, after completing one epoch, it also does not guarantee all images are processed once, right? (It might be okay for training.)

**Comment by ppwwyyxx** [comment]
Yes. For stochastic training it doesn't matter.

**Comment by PatWie** [comment]
What about introducing ranges for RngDataFlow? So each process handles a disjoin subset.

**Comment by ppwwyyxx** [comment]
I guess there are two types of solutions: either fork ImageNet reader or not.
My current plan was to use a single reader (to just produce file names, for example) but multiple workers to process it (`ThreadedMapData` is already doing something similar). This way the imagenet reader doesn't need to be aware of potential forks. 
It might be also a solution to fork but let each reader have its own range.

**Comment by ppwwyyxx** [comment]
```python
    ds = ILSVRCNames()

    aug = imgaug.AugmentorList(augs)
    def mapf(dp):
        fname, cls = dp
        im = cv2.imread(fname, cv2.IMREAD_COLOR)
        if im.ndim == 2:
            im = np.expand_dims(im, 2).repeat(3, 2)
        im = aug.augment(im)
        return im, cls
    ds = ThreadedMapData(ds, 30, mapf, buffer_size=1000, strict=True)
    ds = BatchData(ds, batch)
    ds = PrefetchDataZMQ(ds, 1)
    TestDataSpeed(ds).start_test()
```
With this code, and `ILSVRCNames` producing simply (filename, label) pairs, I am able to get about 20x speed up (about 1.8k images/s) over the non-prefetched dataflow, while still keeping it equal to the whole validation set. This speed is often enough to keep at least a couple of GPUs busy. 

GPUs are becoming so fast that it's already pretty hard to keep them busy at training -- for inference it's harder, especially with Python. I'll go with this solution for now and update examples/docs these days unless some day I found it's becoming a bottleneck again.

Closing this now and track #139 on inference performance.

**Comment by chunfuchen** [comment]
thanks, btw, will I get any benefit if I create lmdb database for validation dataset?

Furthermore, for multi-thread prefetch, does each thread open indenpendent read transaction or they share the same transaction? 

Thanks.

**Comment by chunfuchen** [comment]
Thanks for rapid reply. Then, I think the above codes can be used for `DataParallelInfereneRunner `, right? 

With this improvement, I can ~2x by using `DataParallelInfereneRunner ` ( 4 gpus are used.)

**Comment by ppwwyyxx** [comment]
Yes. #139 has a todo list about improving the performance.
