### ISSUE TITLE
BatchData _aggregate_batch do not support list

### ISSUE THREAD

**Issue by tonyw** [ppwwyyxx/tensorpack#371]
When I use list in my get_data function.there throw exception like this:
--------------------
/tensorpack/dataflow/common.py", line 132, in _aggregate_batch
    raise TypeError("Unsupported type to batch: {}".format(type(dt)))
TypeError: Unsupported type to batch: <type 'list'>

--------------------
Is there any way to support it?

**Comment by ppwwyyxx** [comment]
Your previous dataflow produces a list of list, which is not supported by BatchData. BatchData only works for a list of [ndarray or scalar].
I don't know any good way to support it, because a list can contain anything...

**Comment by ppwwyyxx** [comment]
In any case you can use `BatchData(use_list=True)` which does no type check. Otherwise it only makes sense to batch ndarray from ndarray.
