### ISSUE TITLE
DataFlow and Prefetch support Big File

### ISSUE THREAD

**Issue by tonyw** [ppwwyyxx/tensorpack#372]
Suppose there some Big data file,which saved feature line by line, how to make sure each prefetcher focus on an independent file?

**Comment by ppwwyyxx** [comment]
Prefetch has different mechanism, please see the [tutorial](http://tensorpack.readthedocs.io/en/latest/tutorial/efficient-dataflow.html) for more details. And in practice it depend on what interface you have to your data file, and what kind of dataflow you need, e.g. can you afford random access in the file? Do you want dataflow to be shuffled? If each datapoint is a random sample, do you want each pass of the dataflow to be exactly the whole data file? All these questions affect how you write your dataflow.
If you have any specific question after reading the tutorial, feel free to ask with your specific scenario.

**Comment by huangzehao** [comment]
@ppwwyyxx Hi, yuxin. Would you explain why DataFlow with prefetchDataZMQ will forks the ImageNet reader? Can we avoid this problem while keep it fast? Thanks!

**Comment by ppwwyyxx** [comment]
That's how [PrefetchDataZMQ](http://tensorpack.readthedocs.io/en/latest/modules/dataflow.html#tensorpack.dataflow.PrefetchDataZMQ) is implemented.

Some possible combinations of dataflow are shown in the [tutorial](http://tensorpack.readthedocs.io/en/latest/tutorial/efficient-dataflow.html). As mentioned above, `ThreadedMapData` may help, but it all depends on the actual problem.
