### ISSUE TITLE
How can we introduce a new .py file for a new dataset (e.g., Cars196 or Oxford102flowers) in dataflow/dataset ?

### ISSUE THREAD

**Issue by Openning07** [ppwwyyxx/tensorpack#374]
I attempted to introduce a new .py file in dataflow/dataset folder to make it convenient to load another new dataset (e.g., Cars196). But after that, my tensorpack.dataflow.dataset cannot find the Cars196.py I just wrote ...

**Comment by ppwwyyxx** [comment]
You can import your file directly... not import from tensorpack.

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you still have questions.
