### ISSUE TITLE
Distributed training examples or documentation?

### ISSUE THREAD

**Issue by tarvaina** [ppwwyyxx/tensorpack#375]
The front-page [README.md](https://github.com/ppwwyyxx/tensorpack/blob/master/README.md) says:

> Data-parallel distributed training is off-the-shelf to use.

I guess [tensorpack.train.distributed](https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/train/distributed.py) has something to do with it but I have not seen any examples or documentation about how to use it. Any tips?

**Comment by ppwwyyxx** [comment]
Last time I tried tensorflow still didn't have good distributed performance. So I never wrote an example about it..

**Comment by tarvaina** [comment]
Thanks.

The EC2 distributed benchmark at the bottom of https://www.tensorflow.org/performance/benchmarks indicates good scalability. Am I reading it wrong or is that an unrealistic setting? I would like to understand the current situation better before choosing a solution.

**Comment by PatWie** [comment]
They use the "slow" K80 for benchmarking. I can confirm that this is an unrealistic setting (try that with the new TitanX). So far I can only use 2 GPU for real-world task and 4 GPUs for image classification on a single machine.
