### ISSUE TITLE
DoReFa for image2image

### ISSUE THREAD

**Issue by yg320** [ppwwyyxx/tensorpack#376]
Hi!

I'm trying to use DoReFa on image2image model in order to reduce inference run-time.
For some reason though, no matter what values I use for BITW, BITG and BITA, I get the same inference run-time (Actually best run-time is given when I use BITW=BITG=BITA=32).
Am I missing something?
Is DoReFa implementation in tensorpack only there to show feasibility of low bitwidth operations?
I suspect this is the case because I couldn't find where in dorefa.py a casting from tf.float32 to tf.uint8 happens.

Thanks!

**Comment by ppwwyyxx** [comment]
[dorefa.net](dorefa.net) says:
```
We're not planning to release our C++ runtime for bit-operations. 
In this repo, bit operations are performed through tf.float32.
```

**Comment by yg320** [comment]
Thanks
