### ISSUE TITLE
Inferencer Warning After Updated To Latest

### ISSUE THREAD

**Issue by vqdang** [ppwwyyxx/tensorpack#377]
I got this warning in the inferencer during validation phase at each step. Is it serious? Can I turn it off?

`[0811 17:09:52 @inference.py:82] WRN Inferencer._datapoint was renamed to _on_fetches`

**Comment by ppwwyyxx** [comment]
What inferencer do you use?

**Comment by vqdang** [comment]
I'm using the default `InferenceRunner`. Some more details:

`
def get_valid_data_generator(data, data_shape, label, label_shape, batch_size = 16):
    ds = Dataset(data, label)
    shape_aug = [
        imgaug.CenterCrop(data_shape),
    ]
    ds = AugmentImageComponents(ds, shape_aug, (0, 1), copy=True)
    augmentors = [
        imgaug.CenterCrop(label_shape),
    ]        
    ds = AugmentImageComponent(ds, augmentors, index = 1, copy=True)
    ds = BatchData(ds, batch_size)
    return ds
`

And the setup in `TrainConfig`:

`
InferenceRunner(get_valid_data_generator(x_valid, base_shape, 
                                                                      y_valid, mask_shape, 
                                                                      batch_size = 32),
                            ClassificationStats('predmap', 'segmapx')),
`

**Comment by ppwwyyxx** [comment]
Thanks. So you wrote a inferencer, and the methods were recently renamed, so it prints a warning.
