### ISSUE TITLE
Better documentation for ResNet

### ISSUE THREAD

**Issue by chrisyeh96** [ppwwyyxx/tensorpack#378]
It seems like the ResNet examples are following the architecture from the newer 2016 paper [Identity Mappings in Deep Residual Networks](https://arxiv.org/abs/1603.05027) featuring "pre-activation" rather than the original ResNets proposed in the 2015 paper [Deep Residual Learning for Image Recognition](https://arxiv.org/abs/1512.03385).

I hope that the README for the ResNet examples can be updated to make it clear which ResNet architecture the TensorPack implementation is based on. This is particularly helpful for others who want to use the pre-trained weights.

In addition, I hope that there could be better example code for how to load the pre-trained weights provided in the linked Google Drive folder. First, it should be made clear that the `.npz` files, when loaded, are dictionaries mapping variable names to weights. Also, the `load_resnet.py` file expects a `.npy` file with variable names from a Caffe model, even though the pre-trained weights in the Google Drive folder are `.npz` with variable names that already match the TensorPack ResNet model. Hopefully this can be corrected (unless I'm missing something?).

Thank you so much for all of the work that you've put into TensorPack!

**Comment by ppwwyyxx** [comment]
The readme already made it clear:
```
Training code of ResNet on ImageNet, with pre-activation and squeeze-and-excitation. The pre-act ResNet follows the setup in fb.resnet.torch (except for the weight decay) and gets similar performance (with much fewer lines of code).
```
`load-resnet.py` has its own usage (and its only usage) and it's also mentioned in the readme.

**Comment by chrisyeh96** [comment]
Thanks for the clarification!
