### ISSUE TITLE
ResNet Implementation does not match Paper

### ISSUE THREAD

**Issue by chrisyeh96** [ppwwyyxx/tensorpack#379]
Comparing the ResNet bottleneck implementation between TensorPack and Kaiming He's own GitHub, I noticed several discrepancies. Specifically, I'm looking at Kaiming He's code here: https://github.com/KaimingHe/resnet-1k-layers/blob/master/resnet-pre-act.lua

1. When using bottleneck blocks, the stride-2 convolutions for downsampling are performed at different locations:
- in Kaiming's code: the first 1x1 convolution in each block performs the downsampling with stride-2 ([here](https://github.com/KaimingHe/resnet-1k-layers/blob/master/resnet-pre-act.lua#L70))
- in TensorPack: the middle 3x3 convolution in each block performs the downsampling with stride-2 ([here](
https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet_resnet_utils.py#L149))

2. When using "basic blocks," the treatment of the first block in a group is different
- in Kaiming's code: BN+ReLU are applied prior to all blocks.
- in TensorPack: BN+ReLU is applied to all blocks except the first block of the first group.

Also, there seems to be a typo in TensorPack's `imagenet_resnet_utils.py` file. On lines 130 and 134, `BNReLU` is called with `BNReLU(preact_type, input)` even though the definition of the `BNReLU` function takes arguments in the opposite order `BNReLU(input, preact_type)`.

**Comment by ppwwyyxx** [comment]
As said in the readme, this implementation follows the architecture in fb.resnet.torch.
And this is the file I referred to: https://github.com/facebook/fb.resnet.torch/blob/master/models/preresnet.lua

The arguments of BNReLU is `BNReLU(layer_name, input)`.
