### ISSUE TITLE
ResNet image transformation

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#383]
Why is this transformation on images is done in ResNets?

```
if self.data_format == 'NCHW':
            image = tf.transpose(image, [0, 3, 1, 2])
```

From NCHW to NWCH?

**Comment by ppwwyyxx** [comment]
Because the input image is originall NHWC.

**Comment by a-maci** [comment]
I see. 
Why is this transformation not done for other networks in the examples - alexnet, VGG, inception?

**Comment by ppwwyyxx** [comment]
Those examples only support one data format.

**Comment by a-maci** [comment]
Got it.
