### ISSUE TITLE
freeze_graph gives truncated error after export

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#386]
i am trying to run tensorflow freeze_graph after doing export.

```
        from tensorflow.python.tools import freeze_graph

        tf.reset_default_graph()
        e = ModelExport(Model(), input_names, output_names)
        e.export(model_file, export_dir)

        freeze_graph.freeze_graph(
            input_graph=os.path.join(export_dir, 'saved_model.pb'), input_saver="", input_binary=True,
            input_checkpoint=os.path.join(export_dir, 'variables', 'variables.data-00000-of-00001'),
            output_node_names="output_node", restore_op_name = "save/restore_all", filename_tensor_name = "save/Const:0",
            output_graph=os.path.join(export_dir, 'saved_model_frozen.pb'), clear_devices=True, initializer_nodes="")

```

i get 
```

  File "C:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 170, in freeze_graph
    input_graph_def = _parse_input_graph_proto(input_graph, input_binary)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 137, in _parse_input_graph_proto
    input_graph_def.ParseFromString(f.read())
  File "C:\Anaconda3\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1069, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1105, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 633, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1105, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1105, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 743, in DecodeMap
    if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1095, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 799, in _SkipGroup
    new_pos = SkipField(buffer, pos, end, tag_bytes)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 814, in _SkipFixed32
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

**Comment by ppwwyyxx** [comment]
The protobuf saved by `tf.saved_model.builder.SavedModelBuilder` is not the format expected by freeze_graph.
This issue is not related to tensorpack, closing.

**Comment by eyaler** [comment]
Thanks. Could you provide some clues on how to apply freeze graph after using tensorpack?

**Comment by ppwwyyxx** [comment]
That part of code in tensorflow is not documented well and is not even a public API. After a glance I think it's probably easier to just call `tf.graph_util.convert_variables_to_constants` directly. You can get the graphdef from the metagraphdef file saved by tensorpack.

**Comment by eyaler** [comment]
i could not figure out how do i get the graphdef from the file? and how should i initialize the session?

**Comment by ppwwyyxx** [comment]
#106 had something similar. 
You can probably also just use `tf.get_default_graph().as_graph_def()`.

According to tensorflow documents you seem to need those variables restored in the session. If you are starting from scratch you might need to load the metagraph first, than use `SaverRestore(checkpoint).init(sess)` to initialize the session (http://tensorpack.readthedocs.io/en/latest/modules/tfutils.html#tensorpack.tfutils.SessionInit).

Btw I never use these TF features so I'm not sure what is correct.

**Comment by eyaler** [comment]
i was stuck on this for too many days so i want to share my solution.
running freeze_graph directly on the tensorpack save files yielded different results than before the freeze_graph. i ended up doing the following which worked for me:

`       from tensorpack.tfutils.export import ModelExport
        from tensorflow.python.saved_model import tag_constants
        from tensorflow.python.framework.graph_util import convert_variables_to_constants
        
        tf.reset_default_graph()
        e = ModelExport(Model(), input_node_list, output_node_list)
        e.export(checkpoint_file, export_folder)

        with tf.Session() as sess:
            tf.saved_model.loader.load(sess, [tag_constants.SERVING], export_folder)
            G = tf.get_default_graph().as_graph_def()
            for node in G.node:
                node.device = ''
            G = convert_variables_to_constants(sess, G, output_node_list)
            with tf.gfile.GFile(frozen_filename, 'wb') as f:
                f.write(G.SerializeToString())
`

to infer:
`
        with tf.gfile.GFile(os.path.join(frozen_filename), 'rb') as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())

        with tf.Graph().as_default() as graph:
            tf.import_graph_def(graph_def)
            input_tensor = graph.get_tensor_by_name('import/input_nodename:0')
            output_tensor = graph.get_tensor_by_name('import/output_node_name:0')
            with tf.Session(graph=graph) as sess:
                output = sess.run(output_tensor, {input_tensor: input_image[None]})[0]
            
`
hopes this helps. if @ppwwyyxx is interested i can wrap this in some helper functions and make a PR

**Comment by ppwwyyxx** [comment]
Thanks! The code looks reasonable. However it's not relying on anything in tensorpack and not used by anything in tensorpack -- it's only demonstrating a usage of tensorflow. So it may not be a good idea to include them here.

**Comment by Skylion007** [comment]
I think it would be a good idea to include it as it's useful documentation that would otherwise be hard to find.

**Comment by PatWie** [comment]
Why not using `examples/scripts` to put an example (maybe for the mnist-classification) for freezing a graph.

**Comment by ppwwyyxx** [comment]
Oh putting it in scripts sounds OK.

**Comment by ppwwyyxx** [comment]
But I guess that's what the `freeze_graph` scripts in tensorflow is for? (although it's unclear how to use it..
