### ISSUE TITLE
Storing activation after every minibatch

### ISSUE THREAD

**Issue by flydance0217** [ppwwyyxx/tensorpack#389]
Hello,

Sorry to bother you again. Now I now how to manipulate the weight, I am wondering if there is a way to store the activation (i.e., output of a convolution layer) to a text file after a mini-batch?
I can use the tensorbard summary function, but only provides histogram, rms, etc but I would prefer to have access to all the values for post-processing. 

My initial thinking is to modify the Conv2D code so create an additional tf.Variable to store the output of the tf.nn.conv2d, then I can access it after every minibatch through tf.global_variables().  However this doesn't seen to work because tf.Variable requires all dimension to be known. 

Thanks for the help.

**Comment by ppwwyyxx** [comment]
```python
class MyCallback(Callback):
    def _setup_graph(self):
		t = self.graph.get_tensor_by_name('conv0/output:0')
        self._fetches = tf.train.SessionRunArgs(fetches=[t])

    def _before_run(self, _):
        return self._fetches

    def _after_run(self, _, rv):
        t = rv.results
        np.save('output-{}.txt'.format(self.global_step), t)
```

**Comment by ppwwyyxx** [comment]
This is probably a common need (I'm using it recently as well), just added a callback `DumpTensor`: http://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.DumpTensor

**Comment by a-maci** [comment]
Is there a way to dump the gradient tensors for a batch of inputs?

**Comment by ppwwyyxx** [comment]
Create that tensor in the graph with `tf.gradients` and use the above callback.

**Comment by a-maci** [comment]
Could you give an example? That would be helpful.
Say, in the tensorpack imagenet-resnet.py example, what should I do to dump the two gradients (wrt input and wrt weights) for CONV2 layer?

**Comment by a-maci** [comment]
Also, I was using DumpTensor in my callbacks. 
I put DumpTensor('conv0/output:0'), in callbacks but I get error:
`KeyError: "The name 'c:0' refers to a Tensor which does not exist. The operation, 'c', does not exist in the graph."`

What should I put for the name of a tensor? I was trying this on mnist-convnet.py example.
Thanks

**Comment by ppwwyyxx** [comment]
DumpTensor expects a list of names:
```
Parameters:	names (list[str]) – names of tensors
```

**Comment by ppwwyyxx** [comment]
This diff can make `mnist-visualizations.py` dump the gradients:
```diff
diff --git i/examples/mnist-visualizations.py w/examples/mnist-visualizations.py                 
index b9fc60c..1ff6803 100755                   
--- i/examples/mnist-visualizations.py          
+++ w/examples/mnist-visualizations.py          
@@ -112,6 +112,12 @@ class Model(ModelDesc):    
                               regularize_cost('fc.*/W', tf.nn.l2_loss),                         
                               name='regularize_loss')                                           
         self.cost = tf.add_n([wd_cost, cost], name='total_cost')                                
+                       
+        c1_input = p0  
+        c1_W = c1.variables.W                  
+        grads = tf.gradients(self.cost, [c1_input, c1_W])                                       
+        print(grads)   
+                       
         summary.add_moving_summary(cost, wd_cost, self.cost, accuracy)                          
                        
         summary.add_param_summary(('.*/W', ['histogram', 'rms']))                               
@@ -144,6 +150,8 @@ def get_config():           
             ModelSaver(),                      
             InferenceRunner(                   
                 dataset_test, [ScalarStats('cross_entropy_loss'), ClassificationError('incorrect')]),
+            DumpTensor(['gradients/conv1/Conv2D_grad/Conv2DBackpropInput:0',                    
+                'gradients/conv1/Conv2D_grad/Conv2DBackpropFilter:0'])                          
         ],             
         steps_per_epoch=dataset_train.size(),  
         max_epoch=100, 
```

**Comment by a-maci** [comment]
Thanks. I had somehow missed the mnist-vis example. Its a nice example to access the internal variables. I also saw you updated the docs to mention these. Thanks again.

**Comment by a-maci** [comment]
One (stupid) question:
How did you figure out the string for the gradient tensor? For example this string -- **gradients**/conv1/**Conv2D_grad/Conv2DBackpropInput**

I see such string in the events file in the log directory but for multi-gpu training they have "towerXX" in front of them. Is there a way to print the aggregate gradients?

Here is what I have in the callbacks and I am getting errors:
```
DumpTensor(['gradients/group2/block2/conv2/Conv2D_grad/Conv2DBackpropInput:0', 'gradients/group2/block2/conv2/Conv2D_grad/Conv2DBackpropFilter:0']),
DumpTensor(['group2/block2/conv2/output:0']),
```
`KeyError: "The name 'gradients/group2/block2/conv2/Conv2D_grad/Conv2DBackpropInput:0' refers to a Tensor which does not exist. The operation, 'gradients/group2/block2/conv2/Conv2D_grad/Conv2DBackpropInput', does not exist in the graph."`

The error is produced even when I run with a very small batch size on 1 gpu.

**Comment by ppwwyyxx** [comment]
I used `print(grads)` in the above snippet to see the name. I agree this is annoying. 
For multigpu training it'll be hard to access the aggregate gradients, because gradients are internal to the trainers. One feasible way is to write a `GradientProcessor` that does nothing but print the tensor.
