### ISSUE TITLE
Question about usage of AccumGradOptimizer

### ISSUE THREAD

**Issue by chunfuchen** [ppwwyyxx/tensorpack#391]
Hi I find there is `AccumGradOptimizer` class defined in `optimizer.py` but it is not exposed in the `__all__` list. Do it have bugs? Or it works correctly? 

Furthermore, since I need to setup `steps_per_epoch` in `TrainConfig`, when using `AccumGradOptimizer`, does the step number count `k` times or the step number will be increased by one after every gradient update?
That is, should I change the `steps_per_epoch` to `k` times as the original value or keep the original value?

Thanks.

**Comment by ppwwyyxx** [comment]
It should work. But I don't use it for my work so I can't be sure.
Gradient update happens every k steps.
