### ISSUE TITLE
ResNet-152

### ISSUE THREAD

**Issue by thadpasce16** [ppwwyyxx/tensorpack#392]
Do you have ResNet-152 pretrained model?
If not, any intuition/idea if I train with the following cfg (based on imagenent-resnet.py) and the learning rates and batch size in that file, if things will be OK? I have a 8 GPU box.

`152: ([3, 8, 36, 3], resnet_bottleneck)`

**Comment by ppwwyyxx** [comment]
I don't. You can train it.

**Comment by ppwwyyxx** [comment]
now there is a resnet152 pretrained model.
