### ISSUE TITLE
about get_config() in tensorpack/examples/A3C-Gym/train-atari.py

### ISSUE THREAD

**Issue by lezhang-thu** [ppwwyyxx/tensorpack#395]
The following code is the focus.
```
    return TrainConfig(
        model=M,
        dataflow=dataflow,
        callbacks=[
            ModelSaver(),
            ScheduledHyperParamSetter('learning_rate', [(20, 0.0003), (120, 0.0001)]),
            ScheduledHyperParamSetter('entropy_beta', [(80, 0.005)]),
            HumanHyperParamSetter('learning_rate'),
            HumanHyperParamSetter('entropy_beta'),
            master,
            StartProcOrThread(master),
            PeriodicTrigger(Evaluator(
                EVAL_EPISODE, ['state'], ['policy'], get_player),
                every_k_epochs=3),
        ],
        session_creator=sesscreate.NewSessionCreator(
            config=get_default_sess_config(0.5)),
        steps_per_epoch=STEPS_PER_EPOCH,
        max_epoch=1000,
        tower=train_tower
    )
```

I noticed that `master` is a `threading.Thread`. However, I also noticed that both `master` and `StartProcOrThread(master)` are passed in as callbacks.

Right now, I want to do something in `_trigger_step(self)` of `master` (as `master` is a `Callback`, so I know I can do that.). What confuses me is that whether thread_A `master` being a `Callback` and thread_B `StartProcOrThread(master)` are two threads, or they are just the same, being the same thread?

Why do I ask the question? The reason is that I want to do some `threading.Lock.acquire()` in `_trigger_step(self)` of master, and I want to do some `threading.Lock.release()` in the `run()` method of `StartProcOrThread(master)` (as to the latter, more precisely, I just want to do `release()` in the `run()` method of `master`.). If both masters are the same master, i.e. the master passed in callbacks, and the master passed in `StartProcOrThread`, then acquire and release would be meaningless, as they are the same thread.

Sorry for not understanding threading mechanism well, but this point confused me. I really don't know whether it's legal or effective to bring the release and acquire stuff here. If it worked, that would be helpful for me, as I want to synchronize something in `_trigger_step(self)`, and meanwhile I must wait for the `run()` method of the master to finish.
Thanks!

**Comment by lezhang-thu** [comment]
I found a new API of Python 3 `threading.Barrier`, with the parameter `parties` of 2.
So now my question is straightforward, if in `_trigger_step(self)` and `run()`, the `threading.Barrier` are called,  would these two functions wait for each other? Thanks.

**Comment by ppwwyyxx** [comment]
When something inherits `threading.Thread`, it's `run()` method will be called under a different thread.

Callback methods are always called by the trainer, so they are called under main thread.

**Comment by lezhang-thu** [comment]
So you mean they are in different threads?
Hence your answer to the `threading.Barrier` question is yes?
I think if `run()` (by `threading.Thread`) and `_trigger_step()` (by callbacks) are called in different threads, the answer should be yes. So these two threads can be synchronized.
Thanks!
