### ISSUE TITLE
Better support on tf.data.Dataset

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#397]
Looks like dataset API became more and more stable and will become a standard, so it's good to add explicit support for it as an `InputSource`.

Dataset API as of today doesn't contradict with the benefits of tensorpack:
1. There is `Dataset.from_generator`, which wraps a generator (therefore a DataFlow) into a dataset.
2. There is `dataset.prefetch()`, which is a TF-side prefetch.
3. A dataset iterator can be terminated and be restarted.

But some things are unclear:
1. Whether it's faster or not?
2. In what scenarios will `tf.data` creates multiple python generators? And how does this affect or possibly break dataflow?

**Comment by ppwwyyxx** [comment]
The simplest way to try it now is to just replace `dataflow=mydataflow` in TrainConfig by:
```python
mydataflow.reset_state()
TrainConfig(
data=Dataset.from_generator(mydataflow.get_data, (tf.float32, tf.int64)).repeat().prefetch(50)
)
```

**Comment by ppwwyyxx** [comment]
`get_data` will only be called when `Dataset.Iterator.initializer` is called, which is when `InputSource.reset_state()` is called, which happens once before training.

About speed, when python-side iterator is fast enough, dataset is as fast as queues.

**Comment by tworuler** [comment]
how to use tf dataset in InferenceRunner and Predictor? 
TFDatasetInput didn't implement size(), it cannot be used in InferenceRunner.
Predictors like SimpleDatasetPredictor only accept DataFlow, is there any way to use tf dataset?

**Comment by ppwwyyxx** [comment]
Now `InferenceRunner` only takes something that has a size, so it can know when to stop inference.
The whole `predictors` are designed to use Python data for quick demo.

Tensorpack doesn't support inference with tf dataset now. You'll need to do them by yourself, i.e. call `build_graph` on tf.dataset tensors and evaluate the output in your own loop.

**Comment by ppwwyyxx** [comment]
The latest commit may support InferenceRunner without size (but DataParallelInferenceRunner still requires size), as long as the tf dataset will stop (e.g. no `repeat()`). I don't have a use case to test whether it works.

**Comment by TomorrowIsAnOtherDay** [comment]
@ppwwyyxx 
![image](https://user-images.githubusercontent.com/25046619/34258412-d202a252-e698-11e7-86f2-f8bd31ba0b84.png)
It doesn't work,  error information like this:
![Uploading image.png…]()
