### ISSUE TITLE
Issue with k-folds training (cross-validation)

### ISSUE THREAD

**Issue by vfdev-5** [ppwwyyxx/tensorpack#398]
Hi,

I try to train k models on k-folded data. Code is [here](https://gist.github.com/vfdev-5/05648eaf8ffb71a6f2dd0ee932e22dea). Training on the 1st fold runs correctly and on the next fold I have the following error:
```
ValueError: Tensor("input:0", shape=(?, 30, 30, 3), dtype=float32) must be from the same graph as Tensor("QueueInput/input_queue:0", shape=(), dtype=resource).
```
Could you suggest how to do such k-folds training within your frame work (probably, I would have a similar graph problem with pure TF).

Thank you

**Comment by ppwwyyxx** [comment]
I think you need to clear the graph with `tf.reset_default_graph()` before starting a new training.

**Comment by vfdev-5** [comment]
Yes, I do this [here](https://gist.github.com/vfdev-5/05648eaf8ffb71a6f2dd0ee932e22dea#file-cifar-convnet-cross-validation-py-L186). However, it is not sufficient

**Comment by ppwwyyxx** [comment]
Should be fixed now. BTW, because you created a new graph each time, you probably don't need a reset.

**Comment by vfdev-5** [comment]
Okay, I see. Thank you !

**Comment by vfdev-5** [comment]
I rerun my code with the latest `tensorpack` and the bug disappeared 👍  
However, at the end there is an `IndexError` that is thrown after the messge `Train is finished!`. Here is the traceback:
```
[0830 21:45:55 @base.py:242] Training has finished!
Traceback (most recent call last):
  File "cifar-convnet-cross-validation.py", line 190, in <module>
    trainer.train()
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3815, in get_controller
    if self.stack[-1] is not default:
IndexError: list index out of range
[0830 21:45:55 @prefetch.py:174] [Prefetch Master] Context terminated.
Prefetch process exited.
[0830 21:45:55 @input_source.py:203] EnqueueThread QueueInput/input_queue Exited.
Prefetch process exited.
Prefetch process exited.
Prefetch process exited.
Prefetch process exited.
```
@ppwwyyxx  could you hint how to fix this? Thanks

**Comment by ppwwyyxx** [comment]
Using `reset_default_graph` under `tf.Graph()` is already forbidden in latest TensorFlow (I'm using nightly).

Using this and it will be fine:
```python
for val_fold_index in range(n_folds):
    with tf.Graph().as_default():
```

**Comment by zxpeter** [comment]
Hi yx,

My question is similar and I'm using examples/FasterRCNN with my own dataset (600 images).
The model easily overfitting at around 50 epoch (100 steps per epoch).
![image](https://user-images.githubusercontent.com/12379916/56081626-fce10000-5e41-11e9-9cb7-1ab7e7ee7e00.png)

And frcnn loss keep going down.
![image](https://user-images.githubusercontent.com/12379916/56081712-f30bcc80-5e42-11e9-9aec-8d4778628c47.png)

I'm wondering if we got any solutions like cross validation/drop out/early stop in tensorpack for FRCNN? 
Can I assume that we don't need those methods for large dataset like COCO?

**Comment by ppwwyyxx** [comment]
You can implement early stop with tensorpack callbacks.
