### ISSUE TITLE
Any advice on multigpu processing with embedding layer?

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [ppwwyyxx/tensorpack#403]
I found the performance of multi-gpu version with embedding layer is really slow, because the embedding layers have a lot of parameters which are larger than that of FC layer.Any advice to solve this problem?

**Comment by ppwwyyxx** [comment]
There are currently two multigpu methods in tensorpack (parameter server and replicated), which are both data-parallel but different in the communication pattern. They may have different performance on your task.

To get better performance for scenarios like this, you might need to design specific multi-gpu strategy for your task (e.g. sharding of variables, mix of data parallel and model parallel, etc). Tensorpack doesn't implement these cases.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your reply.I am trying to do something for current model. Could you please give me some advice?
Is there a faster way to communicate among different GPUs? I supposed the current communication like this:GPU0->cpu->GPU1(e.g. cifar10_multi_gpu_train.py)
Can I communicate among different GPUs directly?

**Comment by ppwwyyxx** [comment]
Different GPUs always communicate directly when they can.

The strategy would depend on the actual model and will need a number of trials, provided that you understand what and when communication is happening. TF documentation has something about sharding and it may help.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your advice, I will have a try ~

**Comment by tranorrepository** [comment]
Any progress for this question?
