### ISSUE TITLE
resnet cifar10 example not working

### ISSUE THREAD

**Issue by msbauer** [ppwwyyxx/tensorpack#404]
The example cifar10-resnet.py doesn't seem to work. I get the following error when running it with default arguments:

```
InvalidArgumentError (see above for traceback): Nan in summary histogram for: param-summary/res2.2/conv1/W
	 [[Node: param-summary/res2.2/conv1/W = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](param-summary/res2.2/conv1/W/tag, res2.2/conv1/W/read/_145)]]
```

When I comment out the histogram training runs but the wd_cost is NaN. I haven't done much testing of what the error could be, but thought the examples should all run out of the box.

I use tensorflow 1.2 and tensorpack0.4.

**Comment by ppwwyyxx** [comment]
I cannot reproduce your problem.
If you're using cudnn 5.1.5 you should upgrade it. I cannot think of any other reasons.

**Comment by msbauer** [comment]
Ok, I have switched to tensorflow 1.3 and cudnn/6.0. Now it seems to work perfectly. It is a bit strange that cudnn 5.1 does not work at all, whereas cudnn/6 works fine.

**Comment by ppwwyyxx** [comment]
cudnn5.1.10 should work
