### ISSUE TITLE
allow ConstantBackgroundFiller background_shape to accept list 

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#407]
currently ConstantBackgroundFiller._fill() will raise TypeError if background_shape is list instead of tuple. we should change: 
`return_shape = background_shape + (img.shape[2],)`
to
`return_shape = tuple(background_shape) + (img.shape[2],)`

**Comment by ppwwyyxx** [comment]
The document actually said you need to use tuple. 
Anyway, now list is allowed.
