### ISSUE TITLE
Imagenet-ResNet low it/s and low GPU utils with high system load

### ISSUE THREAD

**Issue by jongchoi** [ppwwyyxx/tensorpack#409]
On a system with 4x Titan X, 1x Xeon (12core), 64GB memory and SSD / HDD,

I've got decent performance for cifar10-resnet.py: \~10 it/s for training, \~22 it/s for validation; GPU utilization > 90%, loadavg: 1\~2

```
|390/390[00:40<00:00, 9.71it/s]
|79/79[00:03<00:00,22.46it/s]
```

For imagenet-resnet.py, however, I could not get similar numbers. The speed is around 0.1~0.2 it/s, with close to zero GPU utilization, but with very high level of system load (loadavg > 300)

![xosview-snapshot](https://user-images.githubusercontent.com/212674/30009460-8770b6e6-9163-11e7-9e81-dd9f42fa2fc7.png)

Following the suggestions in the previous issue threads like #5 #65, I reinstalled Tensorflow from the source, but no avail (I suspect this might be a little different because it is not reproduced with cifar10 and there seems to be excessive threading on the system).

Will be great if you can give me suggestions where to look into further.

**Comment by ppwwyyxx** [comment]
What's the queue size shown in the training log? If the queue is near empty you're bounded by data.

**Comment by jongchoi** [comment]
The average queue size during the first training epoch appears to be very low indeed: 2.32e-37. Also, because I was able to draw ~7.8 it/s with the --fake option on, so tensorflow seems good.

In the experiment, there seems to be some difference in performance (it/s) between train and predict phases: 0.19 it/s during training vs. 1.68 it/s during prediction.

I first thought that this could be explained by the difference in the amount of computation needed for the two phases, but I'm a little confused now because the input queue seems to be full (average queue size is 50?) during prediction.

```
[0905 03:44:38 @monitor.py:355] DataParallelInferenceRunner/QueueInput/queue_size: 50
[0905 03:44:38 @monitor.py:355] QueueInput/queue_size: 2.3199e-37
```

I'll look into further what may cause slow data in my system. Do you have any suggestion on how to best profile the system with the imagenet example?

**Comment by ppwwyyxx** [comment]
You can check out the tutorial about efficient data loading: http://tensorpack.readthedocs.io/en/latest/tutorial/efficient-dataflow.html

**Comment by ppwwyyxx** [comment]
Added a page about performance tuning: http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you still have questions.
