### ISSUE TITLE
Question on resnet blocks

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#410]
In resnet-v2 (Identity mappings in Deep Residual Nets) there is no ReLU after the last conv. 
I see that you have added a ReLU (line 195 in imagenet_resnet_utils.py) here. 

Is this intended?

**Comment by ppwwyyxx** [comment]
That's the code for resnet-v1 now. v2 is named `preresnet_group`.

**Comment by a-maci** [comment]
Yes, got it.
