### ISSUE TITLE
Question about Quantization Fn in DoReFa

### ISSUE THREAD

**Issue by skoppula** [ppwwyyxx/tensorpack#413]
Hi there -- question about the the quantization function to k-bit in DoReFa-Net:

1/(2^k - 1) * round((2^k - 1) * r_i)

where r_i is the input.

Why do the (2^k - 1) scaling? Why would bit shifting (just scaling by 2^k) do the same job?

Thanks!

**Comment by ppwwyyxx** [comment]
k bits can represent 0...2^k - 1, not 0...2^k

**Comment by skoppula** [comment]
Ah, yup, of course.
