### ISSUE TITLE
LinearWrap is not a tensor instance.

### ISSUE THREAD

**Issue by mikeun** [ppwwyyxx/tensorpack#415]
There is a problem when I try to concatenate several tensors, but tensors are result of LinearWrap.
> /opt/anaconda3/lib/python3.6/site-packages/tensorpack/models/common.py(135)wrapped_func()
    132            if not (isinstance(inputs, (tf.Tensor, tf.Variable)) or
    133                     (isinstance(inputs, (list, tuple)) and
    134                         isinstance(inputs[0], (tf.Tensor, tf.Variable)))):
--> 135                 raise ValueError("Invalid inputs to layer: " + str(inputs))
you check here input types but without case <tensorpack.models.linearwrap.LinearWrap object
if I test (isinstance(inputs(), (tf.Tensor, tf.Variable)) => True because inputs() is tf.Tensor.
inputs()
<tf.Tensor 'tower0/Reshape:0' shape=(?, 31) dtype=float32>

**Comment by ppwwyyxx** [comment]
It is not a tensor. Otherwise you wouldn't have all the features of it.
There is a pair of braces in the end: https://github.com/ppwwyyxx/tensorpack/blob/master/examples/mnist-convnet.py#L58
