### ISSUE TITLE
ModelSaver is hard to use with GCS

### ISSUE THREAD

**Issue by maciejjaskowski** [ppwwyyxx/tensorpack#416]
`ModelSaver` verifies if a directory exists during init and it's counter intuitive when working with Google Cloud Storage as GCS has no concept of directories.

So, if I want to save models under `gs://mybucket/some_directory/` I have to create a dummy file e.g. `gs://mybucket/some_directory/dummy`

I admint, this feature is very useful in the case of local directories, though. 

What do you think about changing [the assertion](https://github.com/ppwwyyxx/tensorpack/blob/c5e05d7adcd337f8386f7dea381e03b79a9ce1d4/tensorpack/callbacks/saver.py#L50) so that it's ignored if the path starts with "gs://" ?

**Comment by ppwwyyxx** [comment]
I'm not familiar with gcs, but from the [code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/cloud/gcs_file_system.cc#L1220), it looks like `IsDirectory()` can return true for gcs path.

**Comment by maciejjaskowski** [comment]
You can't create a directory in GCS. 

In GCS, just like in S3 there is no real tree structure, it's all flat. A file "gs://mybucket/a/b/c/d/myfile" is just a file and "gs://mybucket/a/b is NOT a directory. You can do with this address many things you'd do with a directory, e.g. you can "list a directory". However, you can't create a directory unless you place a file in it The closest analogy that should be familiar to github user is... git :) You can't `git add` an (empty) directory, can you?

On the other hand, if you have an _empty_ bucket gs://mybucket, unlike on typical filesystems, nothing stops you from writing a file into "gs://mybucket/a/b/c/d/myfile". It's 100% legal.

**Comment by ppwwyyxx** [comment]
Thanks for the explanations. After reading more on the code, I think it'll work to call `tf.gfile.CreateDir` when `IsDirectory` returns false -- it will create a so-called "directory marker". I can make this the default behavior in ModelSaver.

**Comment by maciejjaskowski** [comment]
How about [recursive_create_dir](https://github.com/tensorflow/tensorflow/blob/5f92a68a0f37bedd69a380915b546262d5a93992/tensorflow/python/lib/io/file_io.py#L356)? Seems to me like a more suitable :)

**Comment by maciejjaskowski** [comment]
`MaxSaver` and `MinSaver` are for now useless on GCS as well, as `shutil.copy` and `glob.glob` are used instead of respectively `tf.gfile.Copy` and `tf.gfile.Glob`

**Comment by ppwwyyxx** [comment]
Ah you're right. A lot of code need to be moved to gfile.

**Comment by ppwwyyxx** [comment]
Github fails to track references.. the commit is 1a19939ea3ea02fb977f08975c2b344ed0c333c1

**Comment by maciejjaskowski** [comment]
Awesome, thanks for tackling it so quickly! What is the best way to install tensorpack from a commit like that?

**Comment by ppwwyyxx** [comment]
`pip install -U git+https://github.com/ppwwyyxx/tensorpack.git` will install from github
