### ISSUE TITLE
Accuracy of ResNet-152 with preactivation

### ISSUE THREAD

**Issue by chunfuchen** [ppwwyyxx/tensorpack#417]
Hi,

Have you tried to train a ResNet-152? I added a configuration in your `imagenet-resnet.py`  to create ResNet-152 architecture. `152: ([3, 8, 36, 3], preresnet_bottleneck)`, based on original paper. 
Then, I trained it on 4 gpus, after 110 epochs, the top-1 validation error only achieved ~24.3%, which is worse than ResNet-101 or even ResNet-50. 

My version is `342cdc70c9a1f41d51b4482d0d64a519266ea828` (date: Aug 31st)

Do you know what is the possible issue? or just because random seed of initialization? 
Thanks.

**Comment by Skylion007** [comment]
I imagine posting your modified code in a GIST would help debug.

**Comment by chunfuchen** [comment]
Here is my code gist:
https://gist.github.com/chunfuchen/1df7224432cd53fbd88bdd9ce143f589

The modification I did are commented with "modified" keyword, only three lines.

Thanks.

**Comment by ppwwyyxx** [comment]
The code looks fine and I don't know why this happened. Random initialization should not make such a big difference.

**Comment by chunfuchen** [comment]
I can not find out the issue... I just re-train it and now it looks well... I will close this issue. Thanks.
