### ISSUE TITLE
how to set limit of gpu memory usage

### ISSUE THREAD

**Issue by chunfuchen** [ppwwyyxx/tensorpack#418]
I would like to run multiple small jobs on my P100 gpu; however, tensorflow by default will allocate as more as memory. There is a configuration at tensorflow can hardly limit the upper bound of gpu memory. 

`tf.GPUOptions` as part of the optional config argument:
You can use it like: (copied from stackoverflow: https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory)

Assume that you have 12GB of GPU memory and want to allocate ~4GB:
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)

sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)
```
How do I achieve it in tenorpack? Thanks.

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/en/latest/modules/train.html#tensorpack.train.TrainConfig

Use the session_config option,

**Comment by simongraham** [comment]
How can I limit the GPU memory during inference? Currently, I am using `PredictConfig()` , but am struggling to find a way to do this.

Would appreciate any help :D
