### ISSUE TITLE
Why initialize BN parameter gamma with zeros

### ISSUE THREAD

**Issue by chunfuchen** [ppwwyyxx/tensorpack#420]
In `imagenet_resnet_utils.py`, the conv layer in non-preact resnet block use zero init for gamma.

Since if gamma is initialized with zeros, the output of BN layer will be zeros as well, right? 
`out = gamma * in + beta`

May I know why? Or gamma will be updated eventually? 
Thanks.

Here are codes:
```python
def get_bn(zero_init=False):
    if zero_init:
        return lambda x, name: BatchNorm('bn', x, gamma_init=tf.zeros_initializer())
    else:
        return lambda x, name: BatchNorm('bn', x)

def resnet_bottleneck(l, ch_out, stride, preact):
    l, shortcut = apply_preactivation(l, preact)
    l = Conv2D('conv1', l, ch_out, 1, nl=BNReLU)
    l = Conv2D('conv2', l, ch_out, 3, stride=stride, nl=BNReLU)
    l = Conv2D('conv3', l, ch_out * 4, 1, nl=get_bn(zero_init=True))
    return l + resnet_shortcut(shortcut, ch_out * 4, stride, nl=get_bn(zero_init=False))
```

**Comment by ppwwyyxx** [comment]
They will be trained. It's a common technique to improve resnet.

**Comment by ppwwyyxx** [comment]
https://arxiv.org/pdf/1706.02677.pdf mentioned this.

**Comment by chunfuchen** [comment]
got it and thanks.

**Comment by chunfuchen** [comment]
got it and thanks.

**Comment by sbalk** [comment]
From the paper:
> For BN layers, the learnable scaling coefficient γ is initialized to be 1, except for each residual block’s last BNwhereγis initialized to be 0. Setting γ = 0 in the last BN of each residual block causes the forward/backward signal initially to propagate through the identity shortcut of ResNets, which we found to ease optimization at the start of training. This initialization improves all models but is particularlyhelpful for large minibatch training as we will show.
