### ISSUE TITLE
Horovod

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#422]
This solution might an interesting approach for distributed training (although I haven't test it yet on my own):
https://github.com/uber/horovod

**Comment by ppwwyyxx** [comment]
https://eng.uber.com/horovod/

**Comment by PatWie** [comment]
74ca05d, 1a262e8 Awesome! Any benchmarks :wink: ?

**Comment by ppwwyyxx** [comment]
95%~97% speed of existing trainers on single machine.
Don't have the resource to try distributed now. Not sure it works..

**Comment by ppwwyyxx** [comment]
Distributed training was supported. Didn't test speed but according to horovod benchmarks I assume it will be fast..
