### ISSUE TITLE
DoReFa-net weight histograms apparently not quantized

### ISSUE THREAD

**Issue by ipalit1981** [ppwwyyxx/tensorpack#425]
Hi, I am running svhn-digit-dorefa.py for w,a,g=2,2,32. I just ran it for 5 epochs to see the effect on weights via tensorboard. I would expect 4 distinct bins for weights at any epoch. However, in tensorboard I see a normal distribution. My question is what the code is saving for histogram? The actual weight that is being learned or the quantized version? If it is not saving the quantized version, how to do so? Thanks.

**Comment by ppwwyyxx** [comment]
It's not saving the quantized version.
You can call `tf.summary.histogram` on the quantized tensor.
```diff
--- i/examples/DoReFa-Net/svhn-digit-dorefa.py  
+++ w/examples/DoReFa-Net/svhn-digit-dorefa.py  
@@ -65,7 +65,9 @@ class Model(ModelDesc):       
                 return v                       
             else:      
                 logger.info("Binarizing weight {}".format(v.op.name))                           
-                return fw(v)                   
+                ret = fw(v)                    
+                tf.summary.histogram(ret.name, ret)                                             
+                return ret                     
                        
         def cabs(x):   
             return tf.minimum(1.0, tf.abs(x), name='cabs')  
```

**Comment by ipalit1981** [comment]
Thanks. The saved models reflect the actual weights, not the quantized one. As such, when using such pretrained models for inference, one should pass the weights through the quantization function and then use it. Please correct me if I am wrong.

**Comment by ppwwyyxx** [comment]
You are right. You can pass them through quantization function __before__ inference as well.

**Comment by ipalit1981** [comment]
Thanks. I am closing this issue.

**Comment by ipalit1981** [comment]
Hi, coming back with another question that just crossed my mind. The reported accuracy numbers (from the code) after each epoch -- generated via inference runner -- are based-on the quantized weights. Right?

**Comment by ppwwyyxx** [comment]
yes.

**Comment by ipalit1981** [comment]
Thanks.

**Comment by erdollar** [comment]
Hi，I meet the same problem in runing alxnet-dorefa.py ,and weights are 1 bit. In tensorboard I see a normal distribution weights too. When I follow your advice above, I also get  a normal distribution weights. 
![image](https://user-images.githubusercontent.com/20589365/32923680-cf0564f8-cb73-11e7-9ac8-48e889338359.png)

Should not the weights be just 0 or 1? Thanks a lot.

**Comment by ppwwyyxx** [comment]
@erdollar It's already answered above.

**Comment by ppwwyyxx** [comment]
You use `tf.summary.histogram(ret.name, ret) `. So you should look for "ret.name" in tensorboard, whatever it is. The name is definitely not "param-summary/conv2/W-histogram".
