### ISSUE TITLE
Interface for aggregation methods

### ISSUE THREAD

**Issue by Skylion007** [ppwwyyxx/tensorpack#427]
Is there an easy interface to change the [aggregation method](https://www.tensorflow.org/api_docs/python/tf/AggregationMethod) without having to extend the trainer? Might be worth looking into if there is not and could be relevant to #318

**Comment by ppwwyyxx** [comment]
You can override `_get_cost_and_grad` method of `ModelDesc`.

**Comment by ppwwyyxx** [comment]
What's the reason you want to change the aggregation method? I don't expect this to be changed as the default should be good.
After some recent refactoring there is no `_get_cost_and_grad` any more (it wasn't a public method so I didn't take too much care on it) and the relevant code to compute gradients is buried deeper.

**Comment by Skylion007** [comment]
The experimental aggregation methods can be significantly more memory
efficient. I also wrote a custom multiGPUGANTrainer that averages the
gradient instead of the loss and found that rather difficult to do even
with _get_cost_and_grad.

**Comment by ppwwyyxx** [comment]
I'll try the aggregation methods. Writing a GAN trainer should have nothing to do with this method because you're supposed to build the graph by yourself anyway.

**Comment by Skylion007** [comment]
Not, it doesn't have to do with building the graph, but  it does have two
separate costs that both have to be optimized with custom variable lists.
That can be hard to access through the current interface.

**Comment by ppwwyyxx** [comment]
You can access `model.g_loss`, `model.g_vars`. What is hard to access?

**Comment by Skylion007** [comment]
Hmm, I haven't taken a look at the new interface. Last time I tried this was in July.

**Comment by ppwwyyxx** [comment]
What do you mean by new interface? `GAN.py` hasn't been changed much since MultiGPUGANTrainer was added.

**Comment by Skylion007** [comment]
No but ModelDesc has and I really hacked it alot to get it do what I want.
I ended up not pursuing it because the performance was really bad over
multiple GPUs and I just stuck with default multiGPU GAN trainer since then.

**Comment by ppwwyyxx** [comment]
`ModelDesc` is for single-cost models only, so whatever changes should not affect GANs.
a GAN model should build the forward/backward graph by itself, not using anything in `ModelDesc` other than `build_graph`, `get_inputs`.

`GANModelDesc` mistakenly subclasses `ModelDesc` at the beginning but not anymore. So they are totally unrelated now.
