### ISSUE TITLE
protoc error

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#43]
Which version of protoc is required by tensorpack/tensorpack/utils/loadcaffe.py line 119?
I have 2.6.1 and I get an error saying
    "caffe proto compilation failed! Did you install protoc?"
AssertionError: caffe proto compilation failed! Did you install protoc?

I am on Ubuntu 16.04, running CUDA 8 and CUDNN 5.

**Comment by ppwwyyxx** [comment]
2.6.1 is OK.
The function is straightforward:
```python
def get_caffe_pb():
    dir = get_dataset_path('caffe')
    caffe_pb_file = os.path.join(dir, 'caffe_pb2.py')
    if not os.path.isfile(caffe_pb_file):
        proto_path = download(CAFFE_PROTO_URL, dir)
        ret = os.system('cd {} && protoc caffe.proto --python_out .'.format(dir))
        assert ret == 0, \
                "caffe proto compilation failed! Did you install protoc?"
```
Maybe it failed to download the file successfully. Or maybe protoc isn't in your path. You can also run `protoc caffe.proto --python_out .` yourself to fix this.

**Comment by a-maci** [comment]
protoc is in my path. The error is in compiling the caffe.proto file which I hadnt noticed before.

I get this error message upon compiling:
protoc caffe.proto --python_out=.
**caffe.proto:1:1: Expected top-level statement (e.g. "message").**

Any chance they updated the caffe.proto file (the file was last updated 4 months ago). Any chance you could upload your caffe.proto file in this repo?

Need help.

**Comment by ppwwyyxx** [comment]
https://github.com/google/protobuf/issues/592

**Comment by a-maci** [comment]
No, the link ends with "Will update our parser to ignore BOM". I dont know if protoc 2.6.1 incorporates this. I downloaded protoc 3.1.0 and I still get the above error. I wonder how it works for other people using protoc 2.6.1.

**Comment by ppwwyyxx** [comment]
It works for others because caffe.proto doesn't have BOM.
Will you check your caffe.proto is downloaded correctly? I also tried 16.04.

**Comment by ppwwyyxx** [comment]
Broken proto file. Closed.
