### ISSUE TITLE
Memory exhaustion happen, When using RemoteDataZMQ

### ISSUE THREAD

**Issue by ildoonet** [ppwwyyxx/tensorpack#432]
If too many multiple node process to send data through zmq to the master,

master node memory can be easily exhausted since it receives too many packets in receive queue.

Any suggestion?

**Comment by ppwwyyxx** [comment]
Added an option which can control the queue size of zmq on the receiver side.

**Comment by ildoonet** [comment]
@ppwwyyxx Thanks, I already did the same way you do for this problem, It works properly.

I will pull your code to use it. Thanks!
