### ISSUE TITLE
Is there any simple way to convert to tensorflow queue?

### ISSUE THREAD

**Issue by ildoonet** [ppwwyyxx/tensorpack#436]
I have implemented a general queue for tensorpack to use tensorpack's dataflow for tensorflow.

Is there any simple way to convert to tensorflow queue?

If not, I will PR or open a new repo for that feature.

**Comment by ppwwyyxx** [comment]
tensorpack is already using tensorflow queue. What have you done in addition to that?

**Comment by ildoonet** [comment]
I only use tensorpack's dataflow.

I don't use tensorpack's wrapper for tensorflow.

If I create a model by pure tensorflow, can dataflow like below be converted to tensorflow queue easily?

```
def get_mnist_data(is_train, image_size, batchsize):
    ds = MNISTCh('train' if is_train else 'test', shuffle=True)

    if is_train:
        augs = [
            imgaug.RandomApplyAug(imgaug.RandomResize((0.8, 1.2), (0.8, 1.2)), 0.3),
            imgaug.RandomApplyAug(imgaug.RotationAndCropValid(15), 0.5),
            imgaug.RandomApplyAug(imgaug.SaltPepperNoise(white_prob=0.01, black_prob=0.01), 0.25),
            imgaug.Resize((224, 224), cv2.INTER_AREA)
        ]
        ds = AugmentImageComponent(ds, augs)
        ds = PrefetchData(ds, 128*10, multiprocessing.cpu_count())
        ds = BatchData(ds, batchsize)
        ds = PrefetchData(ds, 256, 4)
    else:
        # no augmentation, only resizing
        augs = [
            imgaug.Resize((image_size, image_size), cv2.INTER_CUBIC),
        ]
        ds = AugmentImageComponent(ds, augs)
        ds = BatchData(ds, batchsize)
        ds = PrefetchData(ds, 20, 2)
    return ds
```

I have created a simple class to convert, and used it for me...

**Comment by ppwwyyxx** [comment]
```python
from tensorpack.graph_builder.input_source import EnqueueThread

placeholder = [tf.placeholder(...), tf.placeholder(...)]
queue = tf.FIFOQueue(50, [x.dtype for x in placeholder])
thread = EnqueueThread(queue, ds, placeholder)
tensors = queue.dequeue()

with sess.as_default():
    thread.start()
```
something like this?

**Comment by ildoonet** [comment]
Very nice. Thanks.

**Comment by haamoon** [comment]
I am still not sure how to use the dataflow with 'slim.learning.train' where we don’t have direct access to the session object. Maybe we need to write an operation which reads from ds and enqueue into the queue and make a QueueRunner for that?

**Comment by haamoon** [comment]
Does it make sense if we start the thread in a function and pass the function to slim.learning.train as the init_fn argument?

```
def init_fn(sess):
  with sess.as_default():
    thread.start()

slim.learning.train(...., init_fn=init_fn)
```

**Comment by ppwwyyxx** [comment]
It seems OK, but I'm not familiar with that interface.
