### ISSUE TITLE
Bug Report: no TFEventWriter warning when logger set after constructing TrainConfig

### ISSUE THREAD

**Issue by swiatkowski** [ppwwyyxx/tensorpack#438]
Bug Report

When logger is set after the TrainConfig is constructed then events.out.tfevents files are not written, but also there is no warning when constructing TFEventWriter monitor (as in [1]). I would expect that in this scenario either the TFEventWriter should be able to write to the events.out.tfevents or the warning as in the linked line should be produced.

[1] https://github.com/ppwwyyxx/tensorpack/blame/5fc3a2b1afaa1a6967fac964f77bedb4208cfd37/tensorpack/callbacks/monitor.py#L198

Thanks,
Jakub

**Comment by ppwwyyxx** [comment]
```
╰─$python3 -c 'from tensorpack import *; x = TrainConfig(dataflow=FakeData([1]))'
Failed to load OpenCL runtime (expected version 1.1+)
[1010 09:18:31 @monitor.py:198] WRN logger directory was not set. Ignore TFEventWriter.
[1010 09:18:31 @monitor.py:238] WRN logger directory was not set. Ignore JSONWriter.
```
Could you double check?

**Comment by swiatkowski** [comment]
Thanks for your quick replay. Yes, you are right that this warning is printed to the console. However, it is not stored in the log file (e.g. log.log). I used the log file for debugging the problem with no tfevents file being generated and couldn't find the warnings there. I believe that having the warnings in the log would make debugging easier.

The first line of the log is stored only after the log file handler is set in [2]. The TFEventWriter warnings are generated before this file handler is set. Additionally, the InferenceRunner log in [3] is similarly printed only to the console and not to the log file.
 
Best,
Jakub

[2] https://github.com/ppwwyyxx/tensorpack/blob/a36ad1807632060824a0cb156e644315216085ad/tensorpack/utils/logger.py#L74

[3] https://github.com/ppwwyyxx/tensorpack/blob/d5f3350de60974424feb08057af84fbb82dff21c/tensorpack/callbacks/inference_runner.py#L81

**Comment by ppwwyyxx** [comment]
It says `logger directory was not set`. So there is **no log file** at that time.

**Comment by swiatkowski** [comment]
Ok, I might have misunderstood the concept of the log file that is automatically generated during training. I thought it would contain any logs generated by the TensorPack code. However, if understand correctly now, this log is meant to only store the logs generated during the training process (and not during setting up the TrainConfig etc). This makes sense to me and as far as I am concern this issue be closed. Thanks for addressing this concern and keep up the good work :)

**Comment by ppwwyyxx** [comment]
Technically, the log file stores any logs generated after you've set the log directory.
