### ISSUE TITLE
[Usage Q or Bug (?)] batch_norm (or moving average) messes up dataflow input

### ISSUE THREAD

**Issue by skoppula** [ppwwyyxx/tensorpack#439]
Hi there!

I was extending the CIFAR [ ResNet example](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/cifar10-resnet.py); I added a few tf.nn.batch_normalization to the graph, and a few other moving average variables. When I do this, I get an error I can't decipher, from TF

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,32,32,3]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,32,32,3], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: tower0/linear/output/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1544_tower0/linear/output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

This was a bit mysterious, because as for as I understand it, the CIFAR dataflow handles the feeding in data, and I shouldn't need to worry about placeholder if I'm using InputDesc/__build_graph(input, ...) like in the Resnet example.

Would you have any idea what might be causing this? I suspect it's something to do with using Tensorflow's moving_average (as tf.nn.batchnorm does), because things seemed to break when I added moving averages and a few other things to the ResNet graph, but I'm not sure.

I can paste a minimum working example if you'd like. Full error log can be found [here](https://pastebin.com/duJTyfiS)

Thanks, by the way -- TP's a great framework. I use it in my work everyday.

**Comment by ppwwyyxx** [comment]
I don't know what's the reason. It's best if there is a minimum failure example.
Are you using anything like `self.xxx = xxx` inside `build_graph` (except for the cost). This might cause problems like this.

**Comment by ppwwyyxx** [comment]
Or could you provide what exactly did you add to make it fail?
Please note that `build_graph` will be called multiple times (#gpu times for training and 1 time for inference). Adding things that have side effect may cause problems like this.

**Comment by skoppula** [comment]
Hi there! I've created a self-contained working example of the issue:

https://gist.github.com/skoppula/93320039610b0d2d4332bb18ce70ff19

**Comment by ppwwyyxx** [comment]
You should only call `update_ema` when `ctx.is_main_training_tower` is True. Or at least when `ctx.is_training` is True.

**Comment by skoppula** [comment]
Thanks! Fixed the problem.
