### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by fferreres** [ppwwyyxx/tensorpack#44]
@ppwwyyxx awesome work and thanks for sharing it. Do you know which parts really require python 2 or how non trivial it may be to adapt it to python 3?

**Comment by ppwwyyxx** [comment]
It should support python 3 already, except for some of the examples maybe.
 Please report if you find it incompatible with python 3.

**Comment by fferreres** [comment]
Awesome, thanks for the quick reply and the good news!
