### ISSUE TITLE
[Usage Q] How to print out values of intermediate layers for specific example?

### ISSUE THREAD

**Issue by skoppula** [ppwwyyxx/tensorpack#440]
Hi there,

I'm using the in-built CIFAR dataflow, and my network is unable to print weight statistics because there are NaNs in the weight matrix after an epoch of training (erroring out). 

Is there a simple way to take one example in the from the dataflow in Tensorpack and examine the intermediate activations/weights?

Thanks.

**Comment by ppwwyyxx** [comment]
`tf.Print` may work for you. https://github.com/ppwwyyxx/tensorpack/issues/389 is also related. But I'm not sure are those exactly what you need.

To access the weight tensor of a layer,also see https://github.com/ppwwyyxx/tensorpack/issues/389#issuecomment-327971447 .

**Comment by skoppula** [comment]
Great, thanks. Should be workable.
