### ISSUE TITLE
Is there any way to use"split" parameter in function "Conv2D" in parallel?

### ISSUE THREAD

**Issue by Szy-Young** [ppwwyyxx/tensorpack#441]
Usage Questions:

I wanna use the "split" parameter in function "Conv2D" to split channels and make a multi-branch process. In my view processing it in parallel should be viable and time-efficient. However I found that source code of this part in fact use a "for" circulation, i.e. a serial way. Is there any way to process it in parallel ?

**Comment by ppwwyyxx** [comment]
It won't necessarily run in serial. It's allowed to run in parallel and tensorflow runtime engine will decide what to do.
You can write whatever model implementation with tensorflow. `Conv2D` is just a simple wrapper over a common layer, you can and should write your own layer if you need more than what's commonly used.

**Comment by Szy-Young** [comment]
Thanks for your reply. I think I really need further looking into the framework of tensorflow and make better use of it to meet my requests.
