### ISSUE TITLE
Multi GPU's  Efficiency

### ISSUE THREAD

**Issue by adeagle** [ppwwyyxx/tensorpack#445]
///////////////////////////////////////Problem ///////////////////////////////////////////
I write a benchmark for tensorpack use densenet and synthetic data
the report show 2 GPUs is no more efficiency than 1 GPU
I wonder to know is any problem with my code,and how to speed up my training with more gpus use tensorpack

///////////////////////////////////////CMD LINE ///////////////////////////////////////////
time python densenet_benchmark.py --max_epoch 3  #Only One Gpu
time python densenet_benchmark.py --max_epoch 3 --gpu 0,1 --trainer SyncMultiGPUTrainer
time python densenet_benchmark.py --max_epoch 3 --gpu 0,1 --trainer SyncMultiGPUTrainerReplicated
time python densenet_benchmark.py --max_epoch 3 --gpu 0,1 --trainer AsyncMultiGPUTrainer

///////////////////////////////////////Summary ///////////////////////////////////////////
time python densenet_benchmark.py --max_epoch 3
[1016 17:12:02 @base.py:241] Epoch 3 (global_step 300) finished, time:12.60 sec.
real	0m54.396s
user	0m42.144s
sys		0m7.508s

time python densenet_benchmark.py --max_epoch 3 --gpu 0,1 --trainer SyncMultiGPUTrainer
[1016 17:13:05 @base.py:241] Epoch 3 (global_step 300) finished, time:13.60 sec.
real	1m3.314s
user	1m21.096s
sys		0m11.640s

time python densenet_benchmark.py --max_epoch 3 --gpu 0,1 --trainer SyncMultiGPUTrainerReplicated
[1016 17:14:16 @base.py:241] Epoch 3 (global_step 300) finished, time:13.27 sec.
real	1m10.512s
user	1m44.348s
sys		0m12.760s

time python densenet_benchmark.py --max_epoch 3 --gpu 0,1 --trainer AsyncMultiGPUTrainer
[1016 17:15:24 @base.py:241] Epoch 3 (global_step 300) finished, time:14.28 sec.
real	1m8.172s
user	1m44.760s
sys		0m15.996s

source code:
[densenet_benchmark.txt](https://github.com/ppwwyyxx/tensorpack/files/1386866/densenet_benchmark.txt)
test output log:
[tensorpack_benchmark_detail.log](https://github.com/ppwwyyxx/tensorpack/files/1386868/tensorpack_benchmark_detail.log)

**Comment by ppwwyyxx** [comment]
It means it has over 90%  efficiency. See #359.

**Comment by adeagle** [comment]
ok,Oh, I see,thanks a lot
