### ISSUE TITLE
How to enable multithreading for prediction in HED?

### ISSUE THREAD

**Issue by bor2093** [ppwwyyxx/tensorpack#446]
Hello,

I use the hed example for contours detection. I can train it on machine with GPU, but I need to do predictions on machine without GPU. As I noticed OfflinePredictor in CPU mode use only one thread. What is the simplest way to enable multithreading?

**Comment by ppwwyyxx** [comment]
tensorpack doesn't care about inference or deployment so we won't add this feature. It gives you a tensorflow checkpoint and you can use whatever inference features tensorflow supports. The simplest thing is to just open many Python threads to run `sess.run`, but I don't know does tensorflow support anything more than that. You'd better ask this question in the tensorflow community.

**Comment by bor2093** [comment]
The problem solves by changing intra_op_parallelism_threads from 1 to 0 in tfutils/common.py

**Comment by ppwwyyxx** [comment]
OK. I thought you want to run multiple predictors.
Setting the thread to 0 make single predictor multi-threaded. This setting is usually not good for training.

You don't need to modify any code. You can pass this to PredictConfig:
```python
config = tf.ConfigProto()
# change config
PredictConfig(session_creator=NewSessionCreator(config=config)) 
```
