### ISSUE TITLE
DoReFa accuracy

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#45]
Question on accuracy of DoReFa Alexnet on Imagenet dataset.

With "--dorefa 1,2,6" I am getting **train-error-top1: 0.51935**, **val-error-top1: 0.30192** and **train-error-top5: 0.26953**

This is better than the top-1 single-crop **validation error of 51%** mentioned in the comments in the alexnet-dorefa.py. Are the numbers I am seeing expected or I am getting garbage? The above numbers are at 48 epochs on a 2 GPU Titan X Pascal machine.

Thanks.

**Comment by ppwwyyxx** [comment]
Probably that's top-5 instead of top-1.  I just found a typo in the code which only prints the top-5 error rather than the top-1 error. Will fix soon.
Top-5 error of 30% at epoch 48 is normal.

**Comment by a-maci** [comment]
Cool, thanks.

One other item:
When I want to print the training error curves I get val error.

cat ../examples/DoReFa-Net/train_log/alexnet-dorefa/stat.json | jq '.[] | .train_error, .validation_error' | past
e - - | python plot-point.py --legend 'train,val' --xlabel 'epoch' --ylabel 'error'
Traceback (most recent call last):
  File "plot-point.py", line 313, in <module>
    main()
  File "plot-point.py", line 284, in main
    val = float(val)
ValueError: could not convert string to float: null

**Comment by ppwwyyxx** [comment]
the statistics has a different name for this config.
you might need to use something like `jq '.[] | .train_error_top1,."val-top1-error"'` instead
