### ISSUE TITLE
RunUpdateOps every N Batches

### ISSUE THREAD

**Issue by adeagle** [ppwwyyxx/tensorpack#450]
due to small gpu memorys,i want to update params for n batches
how to do ?

**Comment by ppwwyyxx** [comment]
Override the "extra_callbacks" list and replace the callback with [PeriodicRunHooks](http://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.PeriodicRunHooks)

**Comment by adeagle** [comment]
ok,works,it‘s very thoughtful.
