### ISSUE TITLE
Low GPU utilization

### ISSUE THREAD

**Issue by llyyqq** [ppwwyyxx/tensorpack#452]
Hi,
When I'm using Tensorpack, it seems to me that the Memory-Usage is extremely high, while the GPU-Util is very low. The speed is ~0.3 - ~1it/s. Do you have any idea on this?

For the log below. I'm using GPU 1 and 3, where Memory-Usage is approaching 100%, but the GPU-Util is usually 0.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 0000:02:00.0     Off |                  N/A |
| 53%   83C    P2   184W / 250W |  12121MiB / 12189MiB |    100%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    On   | 0000:03:00.0     Off |                  N/A |
| 32%   55C    P2    57W / 250W |  11757MiB / 12189MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    On   | 0000:82:00.0     Off |                  N/A |
| 47%   77C    P2    88W / 250W |   5467MiB / 12189MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  TITAN X (Pascal)    On   | 0000:83:00.0     Off |                  N/A |
| 31%   53C    P2    57W / 250W |  11757MiB / 12189MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      9584    C   python                                       12119MiB |
|    1      8723    C   python                                       11755MiB |
|    2     13289    C   ...ch/gcc/4.8.5/src/torch/install/bin/luajit  5473MiB |
|    3      8723    C   python                                       11755MiB |
+-----------------------------------------------------------------------------+

Thanks!

**Comment by ppwwyyxx** [comment]
You should read the tutorial on performance tuning first.
