### ISSUE TITLE
Retrieve tensor values

### ISSUE THREAD

**Issue by chenchen718** [ppwwyyxx/tensorpack#454]
I have a pre-trained model which I want to use to calculate the value of a middle layer. The question is how I can get the value of the tensors (middle features). What function should I look into? How can I pass the value back outside the wrapped functions?

Thanks very much!

**Comment by ppwwyyxx** [comment]
See this http://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.ProcessTensors
