### ISSUE TITLE
batch A3C?

### ISSUE THREAD

**Issue by weiHelloWorld** [ppwwyyxx/tensorpack#46]
Hi Yuxin,

In your A3C implementation for Atari game you mentioned that you "used a modified version where each batch contains transitions from different simulators, which I called "Batch-A3C"" (https://github.com/ppwwyyxx/tensorpack/tree/master/examples/Atari2600), could you give me more detailed information on this?  And does it improve the performance of original A3C?  Thanks!

**Comment by ppwwyyxx** [comment]
The code is here: https://github.com/ppwwyyxx/tensorpack/blob/master/examples/OpenAIGym/train-atari.py

And someone just wrote a paper to explain this design: http://openreview.net/pdf?id=r1VGvBcxl

**Comment by weiHelloWorld** [comment]
Great, thank you!
