### ISSUE TITLE
A minor issue with A3C

### ISSUE THREAD

**Issue by henrykmichalewski** [ppwwyyxx/tensorpack#461]
1. What you did. `python ./train-atari.py --env Seaquest-v0`
2. What you observed. 
```
Traceback (most recent call last):
  File "./train-atari.py", line 33, in <module>
    from common import (Evaluator, eval_model_multithread,
  File "/home/henryk.michalewski/stefan/tensorpack/examples/A3C-Gym/common.py", line 12, in <module>
    from tensorpack.callbacks import Triggerable
ImportError: cannot import name 'Triggerable'
```

**Comment by ppwwyyxx** [comment]
Thanks a lot!

**Comment by henrykmichalewski** [comment]
But wait, what is the fix? I tried to import other callbacks from base.py and trigger.py instead of Triggerable, but so far the learning seems to be stuck at  `Pre-filling staging area ...`

**Comment by ppwwyyxx** [comment]
It's a long-standing issue when data depends on the model and may get dead-locked during initialization. Now you can run it with single GPU (`--gpu 0`) but not more. I'll try to fix it.

**Comment by ppwwyyxx** [comment]
Btw, as mentioned in the README, running with many GPUs doesn't give you much benefits.
