### ISSUE TITLE
How can i use different models for training and testing

### ISSUE THREAD

**Issue by anthony123** [ppwwyyxx/tensorpack#468]
in the get_config function, I can create model using Model function, How can i Create two different models for training and testing since the two models are slightly different in my experiment?

**Comment by ppwwyyxx** [comment]
I'm not sure I understand what do you mean by "testing".
I assume you want to use the model in testing mode __during training__, with the `get_predictor` or `InferenceRunner` API. If that is the case you can just write the model differently for testing, like this:
 https://github.com/ppwwyyxx/tensorpack/blob/9f6b58d547c74e61422bf0a3f99565009b2dc500/examples/FasterRCNN/train.py#L93-L94

**Comment by anthony123** [comment]
@ppwwyyxx   That's exactly what i want, I need  to know whether I am in training mode or testing mode ,  and when I am in testing mode, I need change the network a little bit, Just like what dropout does!
