### ISSUE TITLE
imagenet preprocessing on GPU

### ISSUE THREAD

**Issue by flydance0217** [ppwwyyxx/tensorpack#469]
Hello,

This is a feature request. As more powerful GPUs are available (i.e., V100), it seems that CPU can become the bottleneck so I am wondering if it is possible to move some of the imagenet data preprocessing task to GPU?

**Comment by ppwwyyxx** [comment]
You can write them as part of your model.
https://github.com/ppwwyyxx/tensorpack/blob/9f6b58d547c74e61422bf0a3f99565009b2dc500/examples/ResNet/imagenet_utils.py#L181-L195
