### ISSUE TITLE
Train error unusual

### ISSUE THREAD

**Issue by chenchen718** [ppwwyyxx/tensorpack#472]
I am using the provided code to train resnet50 on the dataset "places". But the training error is very weird. It is very low at even the first epoch shown as following. As it is training, the errors just fluctuate around these values. 

```
[1102 16:24:03 @monitor.py:359] train-error-top1: 0.30722
[1102 16:24:03 @monitor.py:359] train-error-top5: 0.04876
[1102 16:24:03 @monitor.py:359] val-error-top1: 0.98652
[1102 16:24:03 @monitor.py:359] val-error-top5: 0.9654
```

I tried running the 'evaluation' process on the training and validation datasets, and they are over 0.9, which is normal. I guess there should be some problem in the training procedure, but find it hard to debug inside tensorpack. What might be the problem? How can I inspect the code?

Thank you very much!

**Comment by ppwwyyxx** [comment]
My best guess is that you use some inappropriate data preprocessing in training. But I can't help more since there is no code I can run and it's unlikely a tensorpack issue.

**Comment by chenchen718** [comment]
Thanks for your suggestion. I have resolved the problem. I didn't shuffle the training data when generating the LMDB file and only used the local shuffling strategy when reading the LDMB file. Consequently, only a couple of categories are trained in each epoch, which results in bad generalization results.

**Comment by chenchen718** [comment]
One more question is if I set 'steps_per_epoch' smaller than the actual epoch size of the training dataset (e.g. actual epoch size for imagenet with batch size 100 is about 13000), then at the second epoch, will 'Dataflow' continue fetching the data from where it stops at the first epoch or start all over again? I'm afraid that if it is the latter case, some data will never be trained if I use a pre-shuffling strategy.

**Comment by ppwwyyxx** [comment]
It will call `dataflow.get_data()` again, and it depends on the `get_data` implementation whether it will start over. For most dataflow it will start over.
You can use [FixedSizeData](http://tensorpack.readthedocs.io/en/latest/modules/dataflow.html#tensorpack.dataflow.FixedSizeData) to keep the iteration state.

**Comment by ppwwyyxx** [comment]
I guess this is a bit counter-intuitive and may cause subtle error. I'll see if I can change this somehow.

**Comment by ppwwyyxx** [comment]
Ah my bad. `dataflow.get_data()` actually won't be called at epoch beginning -- the different input source already takes care of the iterator state. So the iterator state will be preserved and dataflow won't start over at each training epoch.

**Comment by chenchen718** [comment]
Good! How do I check input images in each iteration while training so that I can make sure it is going correctly? I know that in evaluation I can do so by passing the variable name to "PredictConfig", but I couldn't find such a interface in training.

**Comment by ppwwyyxx** [comment]
Isn't this #454?

**Comment by chenchen718** [comment]
'DumpTensors' and 'ProcessTensors' cannot be recognized by Tensorpack somewhat. I have the following error when trying using them.
```
ImportError: cannot import name DumpTensors
```

**Comment by ppwwyyxx** [comment]
`DumpTensors` was added Oct 15. If your tensorpack is newer than that you should be able to import.
