### ISSUE TITLE
Issues with loading a model from checkpoint

### ISSUE THREAD

**Issue by yg320** [ppwwyyxx/tensorpack#473]
Hi, 

I'm training an image2image model. 
Whenever I load a model from checkpoint, it uses the learning_rate taken epoch 0 and not the one it should use based on ScheduledHyperParamSetter callback.

After some code digging  I found the reason:
Trainer.epoch_num is initialized to config.starting_epoch - 1 (in Trainer constructor). 
This is the value that is read by ScheduledHyperParamSetter when the method _get_value_to_set is first called to set params before_train.
(self._callbacks.before_train()   at Trainer:main_loop)

When Trainer self.epoch_num is set to self.config.starting_epoch in the main_loop, it's already too late and the learning_rate will be the one from TrainConfig (either the one the user specified or just the default value)

The value config.starting_epoch is being overridden by JSONWriter based on the last epoch from stat.json 
I think the user might expect the learning_rate to be taken from the last epoch. 
The user can specify the starting_epoch with TrainConfig (But he'll probably just read it from stat.json, and I don't think he should do that).

Currently, I locally changed
self.trainer.config.starting_epoch = epoch      (JSONWriter:_setup_graph)
To: 
self.trainer.config.starting_epoch = self.trainer.epoch_num = epoch

**Comment by ppwwyyxx** [comment]
Thanks very much for finding this subtle bug. I think your solution makes sense.
