### ISSUE TITLE
[Bug] Specify on which GPUs to train GAN

### ISSUE THREAD

**Issue by tschnz** [ppwwyyxx/tensorpack#474]
I used the old GAN trainer and always were able to set the GPU/Tower used to learn by writing:

```python
config.nr_tower = nr_gpu
config.tower = gpu_list
```

Easy as that. Now with TrainerV2, most examples only have

```python
if args.gpu:
    os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu
```

which is not working for me. Specifying a GPU doesn't work, device 0 is always chosen.  This is pretty problematic if there are couple of GPU clusters where GPU 0 is always busy. Looking in the source code didn't help me. 
What I found was, that in the MultiGPUGANTrainer, only the first x GPUs are used. Again, no possibility to specifically choose which GPUs to use.

Maybe stop using the range generator:

```python
raw_devices = ['/gpu:{}'.format(k) for k in range(nr_gpu)]
...
cost_list = DataParallelBuilder.build_on_towers(
            list(range(nr_gpu)),
            lambda: tower_func(*input.get_input_tensors()), devices)
```

and do something like:

```python
gpu_list = [2,3] # Let user somehow choose GPU number 2 and 3
...
raw_devices = ['/gpu:{}'.format(k) for k in gpu_list]
...
cost_list = DataParallelBuilder.build_on_towers(
            gpu_list,
            lambda: tower_func(*input.get_input_tensors()), devices)
```

Greetings

**Comment by ppwwyyxx** [comment]
Use MultiGPUGANTrainer with `CUDA_VISIBLE_DEVICES` should work.

**Comment by ppwwyyxx** [comment]
`raw_devices = ['/gpu:{}'.format(k) for k in range(nr_gpu)]` This is using the first x GPUs in `CUDA_VISIBLE_DEVICES`.

**Comment by tschnz** [comment]
Setting GPU 2,3 on a cluster with 4 GPUs starts training and building /gpu:0 and /gpu:1. I'm not admin for these machines. Would be also nice to have a choice on which device to train when using only one GPU on a multi-GPU cluster.

**Comment by ppwwyyxx** [comment]
In tensorfllow, '/gpu:0' and '/gpu:1' means the first and second GPU in `CUDA_VISIBLE_DEVICES`, as long as you set the environment variable.

**Comment by tschnz** [comment]
My bad. Can be closed. Works.
