### ISSUE TITLE
how to get aumentation params? 

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#475]
I am using AugmentImageComponents to do image augmentations and then loop over ds.get_data() to do some work on the augmented images. I need to get the params from some of the augmentations, for which i have implemented _get_augment_params().

so for example say that in the mnist-addition example i would like for each image to get the random rotation degree used by RotationAndCropValid augmentation.

how would you recommend to do it?

**Comment by ppwwyyxx** [comment]
Write your own dataflow for it. In that dataflow you can call `_get_augment_params(image)` and then `_augment(image, params)`.

**Comment by eyaler** [comment]
thanks. i ended up using AugmentImageCoordinates
