### ISSUE TITLE
Error with only 1 gpu

### ISSUE THREAD

**Issue by bigcat77** [ppwwyyxx/tensorpack#48]
I got an error when I tried to train a model with only 1 gpu, not sure if the error goes away with 2 or not.

Here is the command line 
python2.7 train-atari.py --env Breakout-v0 --gpu 0
Here is the error message. 
Traceback (most recent call last):
  File "train-atari.py", line 258, in <module>
    AsyncMultiGPUTrainer(config, predict_tower=predict_tower).train()
TypeError: Can't instantiate abstract class AsyncMultiGPUTrainer with abstract methods get_predict_func

Thanks for any help with this. It looks like a great package. I was able to get run_atari.py to run and got good output movies.

**Comment by ppwwyyxx** [comment]
Sorry I was doing some significant changes in the design and it looks like some part was broken.
I'm preparing a fix and meanwhile you can switch to some earlier commit e.g. efbf256e85eb9 to play with it.

**Comment by ppwwyyxx** [comment]
It looks like the latest 775f5c9ad96846e20 is working. Please let me know if you encounter further error.

**Comment by bigcat77** [comment]
Yes, it now runs thanks. By the way efbf256 didn't work either but efc74f2 did.

Thanks again.
