### ISSUE TITLE
Tensorpack virtual memory consumption is high

### ISSUE THREAD

**Issue by yg320** [ppwwyyxx/tensorpack#480]
Hi,

I'm training an image2image model. 
Since my (8) CPUs load is pretty low and my (4) GPUs utilization is ~70% I'm trying to find where the bottleneck is.

The main Python process uses 3 different DataFlows (1 for training and 2 for validations) decorated with PrefetchData (with 1 process).
So all in all I have 4 different Python processes.

Running top I found this line (This is the main Python process):
![image](https://user-images.githubusercontent.com/30895002/32549625-db7884f0-c492-11e7-99a2-ca8b23dcc402.png)

Any idea why this processed consumes 0.1TB of virtual memory? 
I should mention that the dataset is only ~20GB

**Comment by ppwwyyxx** [comment]
The [tutorial](http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html) has more information about how to find the bottleneck.

`PrefetchData` is not efficient especially for large data and you'd better use `PrefetchDataZMQ` whenever possible. [docs](http://tensorpack.readthedocs.io/en/latest/modules/dataflow.html#tensorpack.dataflow.PrefetchData)

I don't know why it uses large VM but in my experience tensorflow always uses large VM. I don't think that's a big problem. Just using 4 TitanX alone would've accounted for 48G VM space already.

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you still have questions.

**Comment by AngusG** [comment]
I'm using the `alexnet-dorefa.py` training script with data in LMDB format and seeing up to 4.099TB of virtual memory usage causing things to crash approx 30% of the way into Epoch 1 on a 4 GPU cluster with 24 cores and 125GB CPU memory. I adapted `get_imagenet_dataflow.py` from `imagenet_utils.py` according to http://tensorpack.readthedocs.io/en/latest/tutorial/efficient-dataflow.html#sequential-read like so:
```
def get_imagenet_dataflow(
        datadir, name, batch_size,
        augmentors):
    """
    See explanations in the tutorial:
    http://tensorpack.readthedocs.io/en/latest/tutorial/efficient-dataflow.html
    """
    assert name in ['train', 'val', 'test']
    assert datadir is not None
    assert isinstance(augmentors, list)
    isTrain = name == 'train'
    cpu = min(30, multiprocessing.cpu_count())
    if isTrain:
        ds = LMDBData(os.path.join(datadir, 'ILSVRC12-train.lmdb'), shuffle=False)
        ds = LocallyShuffleData(ds, 50000)
        ds = PrefetchData(ds, 5000, 1)
        ds = LMDBDataPoint(ds)
        ds = MapDataComponent(ds, lambda x: cv2.imdecode(x, cv2.IMREAD_COLOR), 0)
        ds = AugmentImageComponent(ds, augmentors, copy=False)
        ds = PrefetchDataZMQ(ds, cpu)
        ds = BatchData(ds, batch_size, remainder=False)
    else:
        ds = LMDBData(os.path.join(datadir, 'ILSVRC12-val.lmdb'), shuffle=False)
        aug = imgaug.AugmentorList(augmentors)
        ds = LMDBDataPoint(ds)
        ds = MapDataComponent(ds, lambda x: cv2.imdecode(x, cv2.IMREAD_COLOR), 0)
        ds = AugmentImageComponent(ds, augmentors, copy=False)
        ds = BatchData(ds, batch_size, remainder=True)
        ds = PrefetchDataZMQ(ds, 1)
    return ds
```
I have tried reducing `buffer_size` in LocallyShuffleData() but that doesn't seem to have an effect on the virtual memory allocation. Full output is attached if you have any suggestions as to how I can address this issue.
[cdr344-3799739.txt](https://github.com/ppwwyyxx/tensorpack/files/1589965/cdr344-3799739.txt)

**Comment by ppwwyyxx** [comment]
It's best to first figure out what makes your script crash. Virtual memory, as the name suggests, is virtual. There is no reason for slurm to limit your virtual memory usage. And using TB of virtual memory is exactly how lmdb works.

Slurm probably limits your resident memory use and it may overestimate it by adding resident memory of each process although they are actually shared. Using a smaller number of processes can probably make it happy.
