### ISSUE TITLE
Shufflenet is slow than squeezenet

### ISSUE THREAD

**Issue by pribadihcr** [ppwwyyxx/tensorpack#485]
Hi @ppwwyyxx,

I tried benchmark shufflenet and squeezenet. Shufflenet is slower than squeezenet.
Is this because the depthwise conv ?.

Thanks

**Comment by ppwwyyxx** [comment]
This is not a tensorpack issue.

ShuffleNet is designed to have low-flops with good accuracy. Low-flops doesn't mean faster. To be fast you'll need good kernels which tensorflow doesn't have.

**Comment by liuheng92** [comment]
I think DepthConv may be the truely problem. issue from tensorflow https://github.com/tensorflow/tensorflow/issues/12940
https://github.com/tensorflow/tensorflow/issues/12132

**Comment by byronyi** [comment]
This seems to be fixed by latest TF nightly and should be available on 2.2. It requires fp16, NCHW, stride==1, and cuDNN version >= 7.6.3 though.

See https://github.com/tensorflow/tensorflow/pull/33836 for details.
