### ISSUE TITLE
How to reset the existing graph then reload the checkpoint?

### ISSUE THREAD

**Issue by vqdang** [ppwwyyxx/tensorpack#486]
I need some help to do the following
 
1. train the network for some epochs with a dataflow  
2. stop the training 
3. do some evaluation on the training set 
4. calculate a new probability for each sample being use for training process 
5. update the dataflow 
6. resume the training 
7. repeat. 

For now,  did as follow:
```
for period in range(0, N):
    train_dataflow = Dataset(dir_path)
    config = TrainConfig(
        dataflow=train_dataflow,
        callbacks=[ModelSaver],
        model=Model(),
        steps_per_epoch=steps_per_epoch,
        max_epoch=nr_epoch
    )

    if period != 0:
        config.session_init = SaverRestore(model_path)

    SyncMultiGPUTrainer(config).train()

    model_path = '...' # path to the most recent checkpoint
    new_dist = '...' # some calculation to change probability of sampled being used
    train_dataflow.dist = new_dist

    tf.reset_default_graph()
```

However, I got error when reloading the checkpoint at the next period. I'm sure this is not right way to do, any idea how can I achieve that? This is the error. Thanks.

```
Traceback (most recent call last):
  File "trainer_miccai.py", line 296, in <module>
    train(args, n_gpus)
  File "trainer_miccai.py", line 255, in train
    SyncMultiGPUTrainer(config).train()
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/trainv1/base.py", line 175, in train
    self.setup()
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/trainv1/base.py", line 210, in setup
    self._config.session_init._setup_graph()
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 112, in _setup_graph
    dic = self._get_restore_dict()
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 161, in _get_restore_dict
    self._match_vars(f)
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 128, in _match_vars
    reader, chkpt_vars = SaverRestore._read_checkpoint_vars(self.path)
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 122, in _read_checkpoint_vars
    reader = tf.train.NewCheckpointReader(model_path)
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /media/vqdang/Data_2/dang/output/miccai/v1.3.0_b//model-8

```

**Comment by ppwwyyxx** [comment]
The way you're using should work. The error is saying the model path is wrong. Any chance you may have removed the checkpoint by mistake?

Everything other than the training can be done in callbacks. You can write a callback which, when triggered, run the evaluation (or get previous evaluation results) and change `train_dataflow.dist`. You can have the DataFlow be a subclass of Callback as well. In RL the data always depend on the training, so this has been used in both RL examples, e.g. in DQN [dataflow is a callback]((https://github.com/ppwwyyxx/tensorpack/blob/2c129dede46b8eb76e3f8a137d80d6accd4b48ff/examples/DeepQNetwork/expreplay.py#L109) ).

**Comment by vqdang** [comment]
I solved the problem. Using '//' in the path broke the tensorflow loader, I don't know why and it seems silly. Here the examples:

Above: /media/vqdang/Data_2/dang/output/miccai/v1.3.0_b//model-8.index
Fixed : /media/vqdang/Data_2/dang/output/miccai/v1.3.0_b/model-8.index

About the dataflow, is the queue reset every epoch? I haven't thought too much about that but the dataflow-callback way as in https://github.com/ppwwyyxx/tensorpack/blob/2c129dede46b8eb76e3f8a137d80d6accd4b48ff/examples/DeepQNetwork/expreplay.py#L109
looks more elegant and I want to try that. However, I need to make sure that from the next period, every samples used for training must be generated from the new distribution.

**Comment by ppwwyyxx** [comment]
Ah that's a problem. If you use queues, there will definitely be several datapoints from the old distribution after you made any changes to the dataflow. 
To really avoid this you will need to 1. pause your dataflow (make it block) and 2. Eval the inputs with `sess.run` + timeout option, until it timeout so the queue is empty. Perhaps this can be made a builtin method of `QueueInput`.

**Comment by vqdang** [comment]
@ppwwyyxx I forgot to ask, after finishing SyncMultiGPUTrainer(config).train(), the existing dataflow will stop and existing queue will be removed right? Sorry to bring this up after closing the issue.

**Comment by ppwwyyxx** [comment]
The dataflow will be stopped. The queue will be closed but not removed until you reset the graph.
