### ISSUE TITLE
Reset QueueInput

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#487]
`QueueInput.reset_state()` currently does nothing. It might make more sense to:

1. pause the underlying enqueue thread
2. eval dequeue() until timeout, to clear the queue
3. reset the underlying dataflow
4. resume the enqueue

**Comment by ppwwyyxx** [comment]
btw, by default training data won't be reset between epochs.

**Comment by vqdang** [comment]
@ppwwyyxx  Could you provide an example on how to use this features? Thanks.

**Comment by ppwwyyxx** [comment]
data=QueueInput(dataflow)
callbacks=[..., CallbackFactory(trigger=lambda _: data.reset_state())]

to reset it every epoch.

**Comment by ppwwyyxx** [comment]
This function creates more problems than it solves, mainly because dataflow doesn't guarantee anything about being reset-able. Calling `reset_state` or `get_data` for more than one times is not guaranteed to do useful things, and for a lot of parallel dataflows it's usually hard to do anything. As a result this function actually will lose some data.

Before there's a clearer semantics on what it means to reset the state, this function was renamed to `refill_queue` to avoid being called by inferencerunnner.
