### ISSUE TITLE
Why the channels of shuffleNet are [224, 416, 832]?

### ISSUE THREAD

**Issue by xmfbit** [ppwwyyxx/tensorpack#488]
The code confused me is here: https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ShuffleNet/shufflenet.py#L91
I see that you used `group = 8`. From the [ShuffleNet paper](https://arxiv.org/pdf/1707.01083.pdf), the channels are: [384, 768, 1536]. I also tried to build ShuffleNet on my own, but I found that the number of channels cannot be divided by group, (384-24) / 4 = 90 % 8 != 0.
Do you just build the network using your own configuration?

**Comment by ppwwyyxx** [comment]
```diff
diff --git i/examples/ShuffleNet/shufflenet.py w/examples/ShuffleNet/shufflenet.py
index fa27ad1..42a890b 100755
--- i/examples/ShuffleNet/shufflenet.py
+++ w/examples/ShuffleNet/shufflenet.py
@@ -88,9 +88,9 @@ class Model(ImageNetModel):
         with argscope([Conv2D, MaxPooling, AvgPooling, GlobalAvgPooling, BatchNorm], data_format=self.data_format), \
                 argscope(Conv2D, use_bias=False):
             group = 8
-            channels = [224, 416, 832]
+            channels = [384, 768, 1536]
 
-            l = Conv2D('conv1', image, 16, 3, stride=2, nl=BNReLU)
+            l = Conv2D('conv1', image, 24, 3, stride=2, nl=BNReLU)
             l = MaxPooling('pool1', l, 3, 2, padding='SAME')
 
             with tf.variable_scope('group1'):
```
The above code runs without problems.

`(384-24) / 4 = 90 % 8 != 0.` this formula comes from nowhere. 
`384 % 16 == 0` is enough. `-24` only happens in the last conv of each unit.

**Comment by xmfbit** [comment]
Thanks! I misunderstood it.

**Comment by sharpstill** [comment]
@ppwwyyxx Really Sorry to bother you again,Why you say 384 % 16 == 0 is enough.  I notice that `
l = Conv2D('conv2', l,
               out_channel if stride == 1 else out_channel - in_channel,
               1, split=group, nl=BN)` , but in the caller `l = shufflenet_unit(l, channels[0], group, 2 if i == 0 else 1)`, thus the channel=16 must satisfy formular: `(out_channel - in_channel)%group == 0`? `(384-24)%8 == 45.0`

Am I understand correct?

**Comment by ppwwyyxx** [comment]
I don't understand what you're saying but since the code can run and you can print the channels of every tensor I assume you can figure these out by your own.

**Comment by sharpstill** [comment]
@ppwwyyxx oh really sorry, I think the tensorflow cannot print anything in the running process because the `sess.run` magic call hides everything. Maybe I am wrong, I am not familar with tf, I use chainer before.

**Comment by ppwwyyxx** [comment]
You can print the static shape of tensors by something like `print(l)`.

**Comment by xmfbit** [comment]
@sharpstill  
> `-24` only happens in the last conv of each unit.

The channels of previous units are 384
