### ISSUE TITLE
HED initial model download

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#491]
I think it may be more useful to provide an initial vgg16 model to download. rather than let the user transfer it themselves.  it will be more convenient for beginners.

**Comment by ppwwyyxx** [comment]
All models are hosted on google drive with limited space. VGG is much larger than any other models and I'm afraid I can't share that before we use a better place to host models.

**Comment by ppwwyyxx** [comment]
https://help.github.com/articles/distributing-large-binaries/
Maybe we can try this, probably on a separate repo, (e.g. tensorpack/models).
Not sure if github is OK with us putting GBs of models in an empty project.

**Comment by dongzhuoyao** [comment]
may be you can try that. I think it will be ok for github.

**Comment by dongzhuoyao** [comment]
how about this [https://mega.nz/#!YU1FWJrA!O1ywiCS2IiOlUCtCpI6HTJOMrneN-Qdv3ywQP5poecM](https://mega.nz/#!YU1FWJrA!O1ywiCS2IiOlUCtCpI6HTJOMrneN-Qdv3ywQP5poecM)  ?

**Comment by dongzhuoyao** [comment]
also luckily, the vgg16.npy can be used for HED initialization.

**Comment by ppwwyyxx** [comment]
But now the model converted from caffe can be downloaded at http://models.tensorpack.com/caffe/.

Thanks @PatWie for hosting the models! When I have good network I'll move more models there.

**Comment by charliememory** [comment]
This link seems not work now. Could you help to address this issue? Thanks.

**Comment by charliememory** [comment]
@PatWie  This link still does not work for me  http://models.tensorpack.com/caffe/ 
Anyway, I find the one cached by google search engine working for me. http://webcache.googleusercontent.com/search?q=cache:ox2CCzCHrPkJ:models.tensorpack.com/+&cd=1&hl=en&ct=clnk&gl=be

**Comment by PatWie** [comment]
Did you try Ctrl+F5. I double checked it. I can see the page.

**Comment by charliememory** [comment]
Well, now it works. Thanks for your help.
