### ISSUE TITLE
How to use NCHW to accelerate my alexnet_dorefa?

### ISSUE THREAD

**Issue by erdollar** [ppwwyyxx/tensorpack#492]
How to use NCHW to accelerate my alexnet ?
I add data_format=NCHW in alexnet-dorefa.py to accelerate training ,but i got error:

ValueError: Negative dimension size caused by subtracting 12 from 3 for 'tower0/conv0/Conv2D' (op: 'Conv2D') with input shapes: [?,224,224,3], [12,12,224,96].

![image](https://user-images.githubusercontent.com/20589365/32881380-0ba02c50-caec-11e7-8db3-65d1b202200f.png)

what's the right ways to use NCHW? thanks a lot.

**Comment by ppwwyyxx** [comment]
You change your layers to NCHW. But your input is not in NCHW.
Also you may need to modify the quantization function since it may assume NHWC.

**Comment by erdollar** [comment]
thanks a lot.  I am a newer ,so I may be not change it by myself. Are you have changed any example such as restnet ,VGG ,and I will follow example to change alexnet?

**Comment by ppwwyyxx** [comment]
The [resnet example](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/ResNet) supports both data format. But you do need to learn some tensorflow before you can change the quantization function.

**Comment by erdollar** [comment]
ok ,thanks very much.
