### ISSUE TITLE
logging images to tensorboard during validation

### ISSUE THREAD

**Issue by bradyz** [ppwwyyxx/tensorpack#496]
It's easy to find scalar statistics for validation using ScalarStats. Is there anything similar for running various image summaries during the validation callback?

**Comment by ppwwyyxx** [comment]
You can easily add images to tensorboard in a callback, with `self.trainer.monitors.put_image`:
https://github.com/ppwwyyxx/tensorpack/blob/7f55d502aa181073f6ca0b9f2d4131c2c87369c7/examples/GAN/CycleGAN.py#L196-L202

**Comment by bradyz** [comment]
perfect! exactly what i was looking for
