### ISSUE TITLE
gpu_options.allow_growth = True invalid

### ISSUE THREAD

**Issue by Forwil** [ppwwyyxx/tensorpack#497]
1. What you did. (command you run if using examples; post or describe your code if not)
  I want to test GPU memory utilization ratio of tensorpack. I add three line code on "tensorpack/trainv1/config.py"
`108                 gpu_options=tf.GPUOptions()`
`109                 gpu_options.allow_growth = True`
`110                 config = tf.ConfigProto(gpu_options = gpu_options,allow_soft_placement = True)`
`111                 self.session_creator = NewSessionCreator(config=config)`
  rebuild tensorpack by
` python setup.py install`
  and then run
`python imagenet-resnet.py --fake --gpu 0,1 --depth 18 --mode resnet`
  use nvidia-smi to to monitor GPU memory utilization

2. What you observed. (training logs)

|===============================+======================+======================|
|   0  TITAN Xp            On   | 0000:04:00.0     Off |                  N/A |
| 35%   61C    P2   161W / 250W |  11763MiB / 12189MiB |     58%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            On   | 0000:06:00.0     Off |                  N/A |
| 35%   61C    P2   153W / 250W |  11763MiB / 12189MiB |     60%      Default |
+-------------------------------+----------------------+----------------------+

3. What you expected, if not obvious
   show the real gpu memory utilization
4. Your environment (TF version, GPUs), if it matters.
tensorpack: tensorpack-0.7.1-docs
tensorflow: 1.4.0
GPU: 2 * titan XP
CUDA CUDNN: cuda 8.0, cudnn 6.0

**Comment by ppwwyyxx** [comment]
This is unrelated to tensorpack and is a tensorflow bug. See https://github.com/tensorflow/tensorflow/issues/9374  https://github.com/tensorflow/tensorflow/issues/9831

**Comment by ppwwyyxx** [comment]
Possible workaround:
1. Remove all use of `get_nr_gpu` in imagenet, so that cuda context is not initialized before session creation. This may let TensorFlow repsect your session config.
2. Setting `per_process_memory_fraction` in session config will probably limit the maximum memory to use (at least on my laptop). `allow_growth` seems broken and I don't know the workaround.

**Comment by Forwil** [comment]
thanks ppwwyyxx! the reference is very useful.
I found a workaround method by add two line below __name__ == '__main__':
`    gpu_options = tf.GPUOptions(allow_growth=True)`
`    sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))`
just create a useless session with gpu_options in the begging of sample.
It seems like gpu_options is a global setting and not a session setting.

**Comment by ppwwyyxx** [comment]
Thanks for the workarounds! Closing this now.
