### ISSUE TITLE
Error when enabling the float64 in train and inference

### ISSUE THREAD

**Issue by Junsong-Wang** [ppwwyyxx/tensorpack#50]
I want to enable float64 in the train and inference, I only change the input type from float32 to float64, but I got the following error...what is wrong? I checked the tf document, it should support float64.
```
Input 'filter' of 'Conv2D' Op has type float32 that does not match type float64 of argument 'input'
```

**Comment by ppwwyyxx** [comment]
tensorpack assumes you're only using flloat32, because higher precision doesn't improve models.

If you really want to do so you can monkey-patch `tf.get_variable` and add `dtype=tf.float64` whenever dtype is None.
