### ISSUE TITLE
Problem with continue training

### ISSUE THREAD

**Issue by erdollar** [ppwwyyxx/tensorpack#500]
When the training interrupted ,I choose keep to countinue to previous training . The training will be start at Epoch 67 ,but the error of training down from 1.0 rather than previous training . 

log.log
--------------------------------------------------------------------------
[32m[1119 20:35:29 @concurrency.py:36][0m Starting EnqueueThread QueueInput/input_queue ...
[32m[1119 20:35:30 @monitor.py:251][0m Found existing JSON at train_log/alexnet-dorefa/stat.json, will append to it.
[32m[1119 20:35:30 @monitor.py:262][0m Found training history from JSON, now starting from epoch number 67.
[32m[1119 20:35:30 @base.py:209][0m Start Epoch 67 ...
[32m[1119 21:10:27 @base.py:219][0m Epoch 67 (global_step 10000) finished, time:2097.31 sec.
[32m[1119 21:10:33 @saver.py:82][0m Model saved to train_log/alexnet-dorefa/model-10000.
[32m[1119 21:11:28 @monitor.py:363][0m QueueInput/queue_size: 50
[32m[1119 21:11:29 @monitor.py:363][0m cost: 5.9455
[32m[1119 21:11:29 @monitor.py:363][0m cross_entropy_loss: 5.8991
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/conv0/W-rms: 0.067988
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/conv1/W-rms: 0.040989
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/conv2/W-rms: 0.02956
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/conv3/W-rms: 0.034119
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/conv4/W-rms: 0.034149
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/fc0/W-rms: 0.014811
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/fc1/W-rms: 0.022189
[32m[1119 21:11:29 @monitor.py:363][0m param-summary/fct/W-rms: 0.022158
[32m[1119 21:11:29 @monitor.py:363][0m regularize_cost: 0.046381
[32m[1119 21:11:29 @monitor.py:363][0m train-error-top1: 0.95903
[32m[1119 21:11:29 @monitor.py:363][0m train-error-top5: 0.88012
[32m[1119 21:11:29 @monitor.py:363][0m val-error-top1: 0.93398
[32m[1119 21:11:29 @monitor.py:363][0m val-error-top5: 0.82844
[32m[1119 21:11:29 @monitor.py:363][0m validation_cost: 5.5529
[32m[1119 21:11:29 @group.py:42][0m Callbacks took 61.329 sec in total. InferenceRunner: 55.482sec
[32m[1119 21:11:29 @base.py:209][0m Start Epoch 68 ...
[32m[1119 21:46:23 @base.py:219][0m Epoch 68 (global_step 20000) finished, time:2093.86 sec.
[32m[1119 21:46:30 @saver.py:82][0m Model saved to train_log/alexnet-dorefa/model-20000.
[32m[1119 21:47:24 @monitor.py:363][0m QueueInput/queue_size: 50
--------------------------------------------------------------------------------------------------
thanks a lot.

**Comment by ppwwyyxx** [comment]
You start with the epoch number but didn't load the previous model. The example has a `--load` option.

**Comment by erdollar** [comment]
I try load model-xxx.data-xx   or model-xx.index but failed. Should i tranform them into .npy and load it?

**Comment by dongzhuoyao** [comment]
"--load model-xxx"    is ok, don't need postfix.

**Comment by erdollar** [comment]
Thanks . It's does't work .
information is as following  @dongzhuoyao

Traceback (most recent call last):
  File "alexnet-dorefa.py", line 306, in <module>
    config.session_init = SaverRestore(args.load)
  File "/home/wa/.local/lib/python2.7/site-packages/tensorpack/tfutils/sessinit.py", line 106, in __init__
    model_path = get_checkpoint_path(model_path)
  File "/home/wa/.local/lib/python2.7/site-packages/tensorpack/tfutils/varmanip.py", line 167, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: /train_log/alexnet-dorefa/model-660000
(tensorflow) wangchao@haoyu-Precision-Tower-7910:~/tensorflow/BNN/DoReFa-Net$ python alexnet-dorefa.py --dorefa 1,32,32 --load /train_log/alexnet-dorefa/model-660000 --data /resources/data/ILSVRC2012/images/ --gpu 1

**Comment by dongzhuoyao** [comment]
check whether or not this file "/train_log/alexnet-dorefa/model-660000.index"  exists.

**Comment by erdollar** [comment]
yes .  File "/train_log/alexnet-dorefa/model-660000.index" exists.

**Comment by ppwwyyxx** [comment]
@erdollar 
Are you aware that "/train_log/alexnet-dorefa/model-660000.index" and "./train_log/alexnet-dorefa/model-660000.index" are two different paths?

**Comment by erdollar** [comment]
wuuwu,I realized where I was wrong. I realize that is the absolute path and the relative path difference.Thanks a lot.
