### ISSUE TITLE
how to realize the InferenceRunner in the image segmentation

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#506]
Hi, I want to implement a Deeplab-LargeFOV,

 morever I want to  realize an InferenceRunner like:

`InferenceRunner(dataset_test,
                            [ScalarStats('cost'), ClassificationError('wrong_vector')]),`

 in the classification task.

I want to calculate the MIoU in pascalVOC validation dataset after every epoch.  the image segmentation task differs from the image classification task in:

- the image size is various, so I need run many fixed overlapped window(such as 512*512, most time also need some paddings.) and match them together(and average the probability in the overlapped area) to the original image size. 

so how should I implement an InferenceRunner for segmentation? **Obviously I need to run sess.run several times.** 

however, the InferenceRunner, InferencerToHook are all about single image one-time feed into the session.

I am not so much familiar with tensorflow and the tensorpack framework, Could you give some suggestions about how to implement it elegantly?

-  how to run several times sess.run in every patch?

- how to get every validation image in numpy format

- how to pass the every predicted result to Statistics to calculate MIoU

**Comment by ppwwyyxx** [comment]
You'll create a predict function inside the callback, and call it however you want when the callback is triggered.
See http://tensorpack.readthedocs.io/en/latest/tutorial/extend/callback.html#explain-the-callback-methods
> self.trainer.get_predictor() is a helper function to create a callable under inference mode.

Examples:
https://github.com/ppwwyyxx/tensorpack/blob/aaf62f2db9ae4fcf40772a35df8b41d4f5c5ddf1/examples/GAN/CycleGAN.py#L188-L199
