### ISSUE TITLE
using TFDatasetInput to wrap tf dataset that read tfrecord is slow?

### ISSUE THREAD

**Issue by tworuler** [ppwwyyxx/tensorpack#507]
I use tf dataset api to read tfrecord files and then pass it to TFDatasetInput for training. IO is slow and become the bottleneck. Below is a part of my code
```
def record_parser(record):
    image_height = 227
    image_width = 454
    image_channels = 3
    keys_to_features = {
        'image_path': tf.FixedLenFeature((), tf.string, default_value=''),
        'image': tf.FixedLenFeature((), tf.string, default_value=''),
        'label': tf.FixedLenFeature([], tf.int64, default_value=-1)
    }
    parsed = tf.parse_single_example(record, keys_to_features)
    image = tf.image.decode_jpeg(
        parsed['image'],
        image_channels
    )
    image = tf.image.resize_images(image, [image_height, image_width])
    label = tf.cast(parsed['label'], dtype=tf.int32)
    return image, label

tfrecord_list = <a list of tfrecord file names>
batch_size=160
tfrecord_dataset = (
    tf.data.Dataset.from_tensor_slices(tfrecord_list)
      .shuffle(buffer_size=1024)
      .flat_map(tf.data.TFRecordDataset)
      .map(record_parser, num_parallel_calls=10)
      .prefetch(batch_size * 5)
      .shuffle(buffer_size=5000)
      .repeat()
      .batch(batch_size)
)
train_config = TrainConfig(
    data = TFDatasetInput(tfrecord_dataset),
    ...
)
SimpleTrainer(train_config).train()
```
When I use tf dataset to read image directly, IO is fast enough and is not the bottleneck. Below is the code
```
def _parse_function(filename, label):
    image_string = tf.read_file(filename)
    image_decoded = tf.image.decode_jpeg(image_string, 3)
    image_resized = tf.image.resize_images(image_decoded, [227, 454])
    return image_resized, label

image_dataset = (
    tf.data.Dataset.from_tensor_slices((filenames, labels))
      .shuffle(buffer_size=5000)
      .repeat()
      .map(_parse_function, num_parallel_calls=10)
      .batch(batch_size)
      .prefetch(5)
)
train_config = TrainConfig(
    data = TFDatasetInput(image_dataset),
    ...
)
SimpleTrainer(train_config).train()
```
However, I use below code to test the performance of dataset api. The `tfrecord_dataset` is even faster than the `image_dataset`.
```
def test_perf(dataset):
    iterator = dataset.make_one_shot_iterator()
    next_element = iterator.get_next()
    with tf.Session() as sess:
        t1 = time.time()
        for i in range(100):
            sess.run(next_element)
        t2 = time.time()
    return t2 - t1
```
Do I use the tf dataset api in tensorpack correctly?

**Comment by ppwwyyxx** [comment]
You bring two issues if I understand correctly:
1. Reading tfrecord is slower than reading images directly, both with tf.data APIs.

This is only about "how to write more efficient tf.data pipeline" and is nothing about tensorpack. We won't  discuss it here.

2. You used a snippet to test raw speed of tfrecord and found it faster than reading images.

-- How do you know the speed of `image_dataset`? Have you written a similar script to test it? If not, you're probably not comparing things apple-to-apple.

**Comment by tworuler** [comment]
The returned value of `test_perf(tfrecord_dataset)` is smaller than `test_perf(image_dataset)`, but using `tfrecord_dataset`, IO is the bottleneck, `image_dataset` not. How is `TFDatasetInput._iterator` used in training progress?

**Comment by ppwwyyxx** [comment]
It's just a simple `iterator.get_next()` as you can see. No magic is happening: 
https://github.com/ppwwyyxx/tensorpack/blob/ef9fb4b8b7b1c2c4b1b8b19bd92650665a48f822/tensorpack/input_source/input_source.py#L433-L445

I don't have a good explanation for that tfrecord become slower than image_dataset during training. Some points you might want to investigate:
1. How do you know IO is the bottleneck? Is that a correct conclusion?
2. Use only one GPU to make the problem simple
3. Have you tested more than one times to make sure the observation is stable?
4. During training a different session config is used (`tensorpack.tfutils.get_default_sess_config`). Maybe it affects the speed and you can try to benchmark with this config instead.

**Comment by tworuler** [comment]
it's caused by `prefetch` and should be nothing about tensorpack. I changed the code as below and the issue was gone.
```
tfrecord_dataset = (
    tf.data.Dataset.from_tensor_slices(tfrecord_list)
      .shuffle(buffer_size=1024)
      .flat_map(tf.data.TFRecordDataset)
      .map(record_parser, num_parallel_calls=10)
      .shuffle(buffer_size=5000)
      .repeat()
      .batch(batch_size)
      .prefetch(5)
)
```
