### ISSUE TITLE
function dicussion[list the augmentations when you start training]

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#511]
is it necessary to list the augmentations you applied to the dataset when you start to run the training?

I find it necessary, especially when you use "RandomResize" augmentations.

because you cannot easily validate it via  "--view" flag in semantic segmentation tasks.

**Comment by ppwwyyxx** [comment]
You can always write print in your code if you like. I don't see why this would become a problem
