### ISSUE TITLE
Just Clone and Try to run some Sample

### ISSUE THREAD

**Issue by cyrsis** [ppwwyyxx/tensorpack#512]
```bash
> python ./train-atari.py --env Breakout-v0 --gpu 0  
TF<1.2 support will be removed in the future!
Traceback (most recent call last):
  File "./train-atari.py", line 27, in <module>
    from common import Evaluator, eval_model_multithread, play_n_episodes
  File "/Users/victor/Documents/Dev/TensorflowPY36CPU/_12_Tensorpack/A3C-Gym/common.py", line 1
    ../DeepQNetwork/common.py
    ^
SyntaxError: invalid syntax
```

Try to move files around, seems do not fix anything rather than mess up things again

Please help

**Comment by ppwwyyxx** [comment]
A3C-Gym/common.py is a symbolic link. You did something during clone that broke symbolic links.

**Comment by cyrsis** [comment]
Thanks man
git clone again , everything seems working but I dont even have GPU in my Mac need a new machine for training, from your benchmark, you done really well
