### ISSUE TITLE
Can the model trained by tensorpack be converted into tensorflow lite file?

### ISSUE THREAD

**Issue by magentay** [ppwwyyxx/tensorpack#513]
I used the code in ResNet ImageNet example, converted the checkpoints results into graphdef (.pb) file , applied the bazel-bin toco tool to generate the tftile file. It doesn't work.

What I have tried:
1. By tensorboard, I found the graph was separated into several parts by the MultiGPUTrainer.  It is hard to tell the right input and output nodes. I tried some of the combinations, it doesn't work out.

2. I switched to SimpleTrainer to get a simple graph. But it still failed to convert into tftile file.  The result only show "Segmentation fault (core dumped)" without further information.

My Questions:
1. Can the model trained by tensorpack be converted into tensorflow lite file? If so, how?
2. If I use slim symbolic libraries. will it work?

**Comment by ppwwyyxx** [comment]
tensorpack saves models in standard format so theoretically there is nothing you cannot do as long as tensorflow supports it, regardless of what symbolic libraries you use.

I don't know what you mean by "doesn't work". Segfault always sounds like a tensorflow bug. Without you providing information about what you did I cannot help more.

**Comment by magentay** [comment]
1. covert the  imagenet resnet18 checkpoints file to graphdef file resnet.pb using 
      output_node = ['InferenceTower/linear/output']

 ```python
   with tf.Session() as sess:
        new_saver = tf.train.import_meta_graph(
            metafile, clear_devices=True)
        new_saver.restore(sess, ckpt.model_checkpoint_path)

        output_graph_def = tf.graph_util.convert_variables_to_constants(
            sess,  # The session is used to retrieve the weights
            tf.get_default_graph().as_graph_def(),  # The graph_def is used to retrieve the nodes
            output_node  # The output node names are used to select the usefull nodes
        )

        # Finally we serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))
```

2  try to use summarize_graph 
 ```
    bazel-bin/tensorflow/tools/graph_transforms/summarize_graph \
    >   --in_graph= resnet.pb
    No inputs spotted.
    No variables spotted.
    Found 1 possible outputs: (name=InferenceTower/linear/output, op=Identity)
    Found 11699467 (11.70M) const parameters, 0 (0) variable parameters, and 0 control_edges
    Op types used: 208 Const, 124 Identity, 81 Reshape, 61 Mul, 48 Add, 21 Sub, 20 Conv2D, 20 Rsqrt, 17 
    Relu, 1 Mean, 1 Transpose, 1 RealDiv, 1 QueueDequeueV2, 1 MaxPool, 1 MatMul, 1 FIFOQueueV2, 1 Cast, 1 BiasAdd
```
I also tried output_node = ['tower0/linear/output'] and had the same result.

Thanks!

**Comment by ppwwyyxx** [comment]
What result do you expect?

**Comment by magentay** [comment]
I am expecting the summarize_graph can find both "input" and "output". 

If I convert this graphdef file to tflite file
```

bazel-bin/tensorflow/contrib/lite/toco/toco -- \
  --input_file=resnet.pb \
  --input_format=TENSORFLOW_GRAPHDEF  --output_format=TFLITE \
  --output_file=resnet.lite --inference_type=FLOAT \
  --input_type=FLOAT --input_arrays=input \
  --output_arrays=InferenceTower/linear/output  --input_shapes=1,224,224,3

2017-11-29 18:45:39.848975: I tensorflow/contrib/lite/toco/import_tensorflow.cc:937] Converting unsupported operation: FIFOQueueV2
2017-11-29 18:45:39.849072: I tensorflow/contrib/lite/toco/import_tensorflow.cc:937] Converting unsupported operation: QueueDequeueV2
2017-11-29 18:45:39.849104: I tensorflow/contrib/lite/toco/import_tensorflow.cc:937] Converting unsupported operation: Transpose
2017-11-29 18:45:39.849122: F tensorflow/contrib/lite/toco/import_tensorflow.cc:286] Check failed: GetStringAttr(node, "data_format") == "NHWC" (NCHW vs. NHWC)
Aborted (core dumped)
```

**Comment by ppwwyyxx** [comment]
For `summarize_graph`: by "inputs" it means "placeholders". But indeed there are no placeholders in the graph, because placeholders are slow. So it works as expected.

For `toco`: tensorflow seems to only support NHWC for tflite, but the graph you used is for GPU and therefore is NCHW. So the graph cannot be converted to tflite. 

To work around both of the above issues you'll need to build the graph again, with placeholders & NHWC, rather that import the metagraph.

**Comment by magentay** [comment]
```python
 def _get_inputs(self):
        return [InputDesc(self.image_dtype, [None, self.image_shape, self.image_shape, 3], 'input'),
                InputDesc(tf.int32, [None], 'label')]
```

The "input" in the resnet model is very similar as other example models,  How to modify it with "placeholders"?

**Comment by ppwwyyxx** [comment]
To build the graph for inference you do not need to use tensorpack. Just build like normal tensorflow. All you need to do is create placeholders and call your symbolic functions on them.

To avoid writing all the symbolic functions again you can use `model.build_graph(placeholder1, placeholder2)` but honestly it's equivalent to writing them with pure tensorflow.
You can leave `_get_inputs` the way it was. It has nothing to do with whether the graph uses placeholders or not.

**Comment by magentay** [comment]
So the solution is: 
1. generate simple inference graph by pure tensorflow ( or tensorpack symbolic)
2. attach the checkpoint file to freeze the graph
3. convert the freeze graph to tflite.

I will try it.
Thanks for your help!

**Comment by magentay** [comment]
```
2017-11-30 00:22:17.240715: F tensorflow/contrib/lite/toco/tflite/export.cc:192] Unsupported operator: ReorderAxes
Aborted (core dumped)
```

I used the tensorpack's LinearWrap to generate the graph and combined the checkpoint, but I got this error by  toco tool. I did not find this operator "ReorderAxes" in the graphdef ops. What is this  "ReorderAxes" operator? Is it related with LinearWrap?

Thanks!

**Comment by ppwwyyxx** [comment]
Still, it has nothing to do with tensorpack.
From tensorflow source code contrib/lite/toco/import_tensorflow.cc it seems like it has something to with convolution data_format.

**Comment by magentay** [comment]
If I write a graph with data_format " NHWC", but freeze with the checkpoint trained by "NCHW". Is it still right? or I have to retrain the checkpoint with data_format "NHWC"?

**Comment by ppwwyyxx** [comment]
It depends on your model and I cannot answer that.
