### ISSUE TITLE
ValueError: Cannot feed value of shape (128, 1) for Tensor u'label:0', which has shape '(?,)'

### ISSUE THREAD

**Issue by zuokai** [ppwwyyxx/tensorpack#524]
1）following is the way i set the placehold
class Model(ModelDesc):
    def _get_inputs(self):
        return [InputDesc(tf.float32, [None, IMAGE_SIZE, IMAGE_SIZE, 3], 'input'),
                InputDesc(tf.int32, [None, ], 'label')]
2）following is the way i load the data
class YelpDateFlow(RNGDataFlow):
    def __init__(self, dir_path, lable_path):
        self.file_list = []
        for line in open(lable_path):
            temp_str = line.split('\t', 1)
            self.file_list.append((os.path.join(dir_path, temp_str[0]), np.array([int(temp_str[1])])))

    def size(self):
        return len(self.file_list)

    def get_data(self):
        idxs = np.arange(len(self.file_list))
        self.rng.shuffle(idxs)
        for k in idxs:
            fname, label = self.file_list[k]
            im = cv2.imread(fname, cv2.IMREAD_COLOR)
            assert im is not None, fname
            yield [im, label]

def get_data():
    ds = YelpDateFlow(FLAGS.path, FLAGS.path_label)
    ds = AugmentImageComponent(ds, [imgaug.Resize(IMAGE_SIZE)])
    ds = PrefetchDataZMQ(ds, nr_proc=4)
    ds = BatchData(ds, FLAGS.batch_size)
    return ds

And i got the error as title shows，actually the batch size is 128, the version of tensorflow is 1.4. do you know what's wrong with it and how can i fix it?

**Comment by ppwwyyxx** [comment]
The error is telling you already. Your label shape is (128, 1) not (128,).
Because before batching, your label is a vector of length 1, not a scalar.
` np.array([int(temp_str[1])])` apparently this line of code creates a vector of length 1.

**Comment by zuokai** [comment]
I want to change the label shape to (128,), when i load data by tensorpack, how can I change the data shape manually？

**Comment by ppwwyyxx** [comment]
`self.file_list.append((os.path.join(dir_path, temp_str[0]), np.array(int(temp_str[1]))))`

**Comment by zuokai** [comment]
thanks
