### ISSUE TITLE
It is possible to implement multi-losses GAN network?

### ISSUE THREAD

**Issue by gildorgood** [ppwwyyxx/tensorpack#525]
Hi,

I want to implement CVAE-GAN in Tensorpack, but I cannot find appropriate Trainer class in Tensorpack.
It seems that GANTrainer instance gets only two loss functions for generator and discriminator. 

Is it possible to implement GAN which have multiple loss functions more than two, using Tensorpack?
For example, the CVAE-GAN has four loss functions for training.

I have one more question.
I cannot find documents about GAN training. Where can I find it?

Any advice are appreciated.
Thanks.

**Comment by ppwwyyxx** [comment]
Sure you can. As long as you can build the graph and define what to do in an iteration, you can train it with tensorpack.

There are no documents about GAN training. GAN is just an example of how to define a trainer for non-standard tasks. GAN is not part of the library. The documents about defining a trainer are http://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html and http://tensorpack.readthedocs.io/en/latest/tutorial/extend/trainer.html.
