### ISSUE TITLE
Got Nan on Val_set loss

### ISSUE THREAD

**Issue by YC-YunyingChen** [ppwwyyxx/tensorpack#526]
I tried to build my own network with my own dataset. I used the same data on dataset and valset.  The definition is as follow:
def get_data(data_dir,train_or_test):
  isTrain = train_or_test == 'train'
  train_set=data_set.get_dataset(data_dir)
  image_list, label = data_set.get_image_paths_and_labels(train_set)
  desSize=map(int,(args.image_size,args.image_size))
  df= image_data.MyDataFlow(image_list,label,channel=3,resize=tuple(desSize),shuffle=False)
  
  if isTrain:
     augmentors = [
        imgaug.Resize((224, 224)),
        imgaug.Brightness(30),
	imgaug.RandomApplyAug(imgaug.GaussianBlur(3), 0.5),
  	imgaug.Flip(horiz=True),
	
        ]
  else:
     augmentors = [
	imgaug.Resize((224, 224))
        ]
  df=AugmentImageComponent(df,augmentors,copy=False)
  df=BatchData(df,64,remainder=not isTrain)
  if isTrain:
    df = PrefetchDataZMQ(df, min(12, multiprocessing.cpu_count()))

I got the value of loss, but the validation_loss is Nan.

How should I fix this? Thank you!

**Comment by ppwwyyxx** [comment]
There is no way I would know why your model does not work for your data. There is no indication that this is a tensorpack-related problem. Closing now.
