### ISSUE TITLE
Quantize the weights to ternary (-1, 0 1)?

### ISSUE THREAD

**Issue by Junsong-Wang** [ppwwyyxx/tensorpack#53]
I would like to quantize the weights to ternary (-1, 0 +1) , which could increase the diversity of the conv. kernel while won't afford much more logic resource in FPGA, I wrote it like:
```
E = tf.stop_gradient(tf.reduce_mean(tf.abs(x)))
clip_x = tf.clip_by_value(x/E, -2.0, 2.0) / 2.0
with G.gradient_override_map({"Floor": "Identity"}):
    return tf.round(clip_x) * E
``` 
However, it seems not work fine? Is there any good approach to implement this?

**Comment by ppwwyyxx** [comment]
What do you mean by not working fine, and why do you choose such quantization equation? The equation looks rather arbitrary and seems like a lot of the entries would end up being zero.

**Comment by Junsong-Wang** [comment]
It seems not converged...I tested this equation dependently, the output is what I expected...But I don't know if the gradient is also correct for training. I can't find a good tensorflow fucntion to implement this. The only thing I want to do is if x > E, return 1, elif x < -E return -1, else, return 0, do you have any ideal, thanks.

**Comment by Junsong-Wang** [comment]
The reference paper is https://arxiv.org/abs/1605.04711

**Comment by ppwwyyxx** [comment]
The E used here is derived for binary quantization and it seems like there are different equations for ternary cases in the paper.

You can write a small snippet to compute the output/gradient and see if it is expected. The gradient looks wrong to me. You probably need to override the gradient of clip_by_value and the division to identity.

**Comment by Junsong-Wang** [comment]
The paper said that the 0.7E is the approximate optimal threshold. yes, I also think the clip_by_value has no correct gradient. By the way, how I can get the gradient name of the tf function, so I can overwrite, such as tf.round is gradient name is Floor.

**Comment by ppwwyyxx** [comment]
clip_by_gradient is implemented by a `Minimum` and a `Maximum`.

**Comment by Junsong-Wang** [comment]
If I try to override the clip_by _value to identity, 
```
with G.gradient_override_map({"Maximum":"Identity", "Minimum":"Identity"}):
            clip_x = tf.clip_by_value(x/E, -2.0, 2.0) / 2.0
```
it occurs...
```
ValueError: Num gradients 1 generated for op name: "tower0/conv4/clip_by_value"
op: "Maximum"
input: "tower0/conv4/clip_by_value/Minimum"
input: "tower0/conv4/clip_by_value/y"
device: "/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_gradient_op_type"
  value {
    s: "Identity"
  }
}
```
what is the problem...

**Comment by Junsong-Wang** [comment]
I found if I didn't override the clip_by_value, the covergence speed is very slow, I think the cause is clip_by_value make most place zero gradient, only has gradient 1 in [-E, E]. So I think override the clip_by_value with identity could make the covergence speed much faster...

**Comment by Junsong-Wang** [comment]
I found if I didn't override the clip_by_value, the covergence speed is very slow, I think the cause is clip_by_value make most place zero gradient, only has gradient 1 in [-E, E]. So I think override the clip_by_value with identity could make the covergence speed much faster... so could you help to see the above problem.

**Comment by ppwwyyxx** [comment]
Identity takes one input and min/max takes two, so they are not consistent and you cannot use the gradient of Identity directly. You'll need to write another function which implements the gradient of identity and register it.

**Comment by thadpasce16** [comment]
@Junsong-Wang Were you able to get this working?
Here is how I am implementing the TWN ternarization but I am not getting results.


            shape             = x.get_shape()
            weightAbs         = tf.stop_gradient(tf.abs(x))
    
            threshold         = tf.stop_gradient(tf.reduce_mean(weightAbs) * 0.7)

            absW_gt_threshold = tf.select( weightAbs > threshold, weightAbs, tf.zeros(shape))
            nnz                           = tf.cast(tf.count_nonzero(absW_gt_threshold), dtype=tf.float32)
            weightScale             = tf.stop_gradient(tf.reduce_sum(absW_gt_threshold)/(nnz))

            weights_p         = tf.select( x >  threshold, tf.ones(shape) *  weightScale, tf.zeros(shape))
            weights_n         = tf.select( x < -threshold, tf.ones(shape) * -weightScale, weights_p)

            mask_z            = tf.select( (x < threshold) & (x > -threshold), tf.zeros(shape), tf.ones(shape))
            with G.gradient_override_map({"Sign":"Identity", "Mul": "Add"}):
                w = tf.sign(x) * tf.stop_gradient(mask_z)
            w = w * weights_n

            return w

**Comment by Junsong-Wang** [comment]
I didn't following exactly follow the paper in scale factor.
```
E = tf.stop_gradient(tf.reduce_mean(tf.abs(x))) 
with G.gradient_override_map({"Sign": "Identity"}): 
    return 0.5 * E * (tf.sign(x / E - 0.7) + tf.sign(x / E + 0.7)) 
```

**Comment by ppwwyyxx** [comment]
Thanks @Junsong-Wang! Although not the same as the paper, this looks very smart.
I implemented the quantization following TWN paper today. 

```python
delta = 0.7 * tf.reduce_mean(tf.abs(x))
mask = tf.logical_or(x < -delta, x > delta)
maskf = tf.cast(mask, tf.float32)

x_side = x * maskf
Wl = tf.reduce_sum(tf.abs(x_side)) / tf.cast(tf.count_nonzero(x_side), tf.float32)

maskf = tf.stop_gradient(Wl * maskf)
with G.gradient_override_map({"Sign":"Identity", "Mul": "Add"}):
    output = tf.sign(x) * maskf
return output

```

**Comment by thadpasce16** [comment]
(Newbie) question for clarification: why dont you have stop_gradient in the first line when calculating delta? As in 
`delta =  tf.stop_gradient(0.7 * tf.reduce_mean(tf.abs(x)))`

Thanks to both of you for sharing your code. Its quite helpful.

**Comment by ppwwyyxx** [comment]
The gradient is already cut by the other `stop_gradient` call. Adding `stop_gradient` to the beginning changes nothing.

**Comment by Junsong-Wang** [comment]
In ternary weights, using different scale weight for positive and negative could improve the accuracy, the paper is here https://arxiv.org/abs/1612.01064, does anybody have ideals of how to implement it in this tensorpack framework?

**Comment by ppwwyyxx** [comment]
@thadpasce16 has an implementation. I haven't got time to test it but I was told it had good results.

**Comment by thadpasce16** [comment]
The authors recently open sourced their implementation here: https://github.com/czhu95/ternarynet

It is based on tensorpack!

I have a version but if you want to replicate the numbers in the paper it's better to go with their official version.
