### ISSUE TITLE
FasterRCNN: visualize error

### ISSUE THREAD

**Issue by petwill** [ppwwyyxx/tensorpack#530]
when I run train.py with the flag --visualize, the following error occurs.
`KeyError: "The name 'generate_rpn_proposals/probs:0' refers to a Tensor which does not exist. The operation, 'generate_rpn_proposals/probs', do es not exist in the graph."`

**Comment by ppwwyyxx** [comment]
Ah. I'll correct the name. These visualization code wasn't maintained for a while.

**Comment by petwill** [comment]
Just to inform you that there are still many unfixed errors in the function visualize in `train.py`.

**Comment by ppwwyyxx** [comment]
OK.. I'll run it when I get a time

**Comment by ppwwyyxx** [comment]
Now `--visualize` should be runnable.
