### ISSUE TITLE
Does ZMQ support communication between multi-machines ?

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [ppwwyyxx/tensorpack#531]
Thanks for your amazing A3C examples~
I want to expand this algorithm between machines, which means I want to launch many simulators in different machines and collect their data and run batch version A3C.So I have to solve the data communication between machines.
Does ZMQ support communication between multi-machines ?

**Comment by cyrsis** [comment]
Yes, ZMQ can works well with windows and mac.

but the latency between machine is the biggest issues as far as I can tell

**Comment by ppwwyyxx** [comment]
Yes.

This is not a tensorpack question. I'll close it if there is no more questions.
