### ISSUE TITLE
AssertionError: Breakout-v0.npy"

### ISSUE THREAD

**Issue by cyrsis** [ppwwyyxx/tensorpack#532]
```bash
[1201 10:47:55 @monitor.py:363] max_score: 863
[1201 10:47:55 @monitor.py:363] mean_score: 590.14
```
This is my first work out with GYM
Ran for 2 days with and stable , pretty good with single 1070 w8G Ram

it still running, 

when I do 

```bash
./train-atari.py --task gen_submit --load Breakout-v0.npy --env Breakout-v0 --output output_dir
```
It said 

```bash
AssertionError: Breakout-v0.npy"
```

Do I need to wait for the training finish to get Breakout-v0.npy ????

**Comment by ppwwyyxx** [comment]
Look at your log directory. That's where your models are. Breakout-v0.npy is my released pretrained model.
