### ISSUE TITLE
custom Progressbar

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#538]
https://github.com/ppwwyyxx/tensorpack/blob/fe0591806883d1975e607d1f2e4a8c6be48df9f6/examples/SimilarityLearning/mnist-embeddings.py#L355-L360

seems to be deprecated without any way to add customs values for ProgressBar.

**Comment by ppwwyyxx** [comment]
works for me.

**Comment by PatWie** [comment]
Pull the latest version of TensorPack and the error seems to be gone.
