### ISSUE TITLE
tf.GraphKeys.UPDATE_OPS

### ISSUE THREAD

**Issue by zuokai** [ppwwyyxx/tensorpack#540]
do I need to add following code：

  update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
  with tf.control_dependencies(update_ops):
    train_op = optimizer.minimize(loss)

 if I want to save the mean and var of BatchNorm in tensorpack？

**Comment by ppwwyyxx** [comment]
it's enabled by default in tensorpack

**Comment by zuokai** [comment]
thanks
