### ISSUE TITLE
How many epochs should be set for resnet on ImageNet?

### ISSUE THREAD

**Issue by yuxwind** [ppwwyyxx/tensorpack#544]
I'm confused by the epochs in resnet example and what is reported on [resnet](https://arxiv.org/pdf/1512.03385.pdf) paper: 

1.  imagenet-resnet.py

- In the [README](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/ResNet) of imagenet-resnet.py, you report the command line to run resnet is as below: 
./imagenet-resnet.py --data /path/to/original/ILSVRC --gpu 0,1,2,3 -d 50 [--mode resnet/preact/se]
Also, you provide your performance figure. From the figure, we can see the total epoch is 120.

- As you explained in #353 , one iteration update weights with the data size of TOTAL_BATCH_SIZE. As explained in the [document](https://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html):
_In each iteration all GPUs (all replicates of the model) will take tensors from the InputSource, instead of taking one for all and split._ 
 
It means one epoch the trainer will go through the whole dataset four times as there are 4 gpus. When it runs for 120 epochs, I think it means it will go through the dataset for 480 times. 

2. Resnet paper

- As reported in [resnet](https://arxiv.org/pdf/1512.03385.pdf) paper, the training runs for 600000 iterations. As the total training dataset size of imagenet is 1281167 and batch size is 256, the trainer needs to run 1281167/256=5004 iteration to go through the dataset once. So it means the training go through the dataset 600000/5004=120 times. 

If my understanding doesn't go wrong, it seems the multiple gpu training will go through the dataset 4 times greater than what is reported in [resnet](https://arxiv.org/pdf/1512.03385.pdf) paper. 

- Do I miss something when I get 480 times by calculation? 

- Do you know what the iteration means in [resnet](https://arxiv.org/pdf/1512.03385.pdf) paper? Should I also count #gpu into one iteration?

**Comment by ppwwyyxx** [comment]
TOTAL_BATCH_SIZE is always 256 no matter how many GPUs you use. So one epoch is always one epoch. The number of GPUs only affects how many samples per GPU.

The original resnet paper means the same thing. It may differ a little bit (i.e. 5004 vs 5000) but that's negligible.

**Comment by yuxwind** [comment]
Do you mean in one epoch, 4 GPUs will go through the dataset one time instead of 4 times?

**Comment by ppwwyyxx** [comment]
Yes.

**Comment by yuxwind** [comment]
When I set the TOTAL_BATCH_SIZE = 192, the progress bar will show something like 4908/26690. What does that mean? Is this the progress of iteration?

It seems to make sense that 26690 = 1281167/48 (the size of training is 1281167).

**Comment by ppwwyyxx** [comment]
Please always __paste__ your observation instead of describing it. I do not understand what you observed.

As far as I know you will not see anything like `4908/26690` if changing TOTAL_BATCH_SIZE is the only thing you did.

**Comment by ppwwyyxx** [comment]
You will NOT see anything like this if you're using the ResNet example in this repo and only changed the batch size. Please confirm what you did, including the changes you made and command you run.

**Comment by ppwwyyxx** [comment]
Closing because information about the problem was not provided. Reopen if you still have questions.

**Comment by yuxwind** [comment]
I checked my code and found the problem is caused by deleting 'steps_per_epoch=5000' in TrainConfig in imagenet-resnet.py. When this config is added, it shows the correct running progress now. Thanks a lot!
