### ISSUE TITLE
Pre-filling staging area

### ISSUE THREAD

**Issue by jiang1st** [ppwwyyxx/tensorpack#546]
When I was training Mask RCNN with more than one gpus, the training process got stuck at "Pre-filling staging area...". When trained with one gpu, there is no such problem.  What could be the reason? Thank you.

**Comment by ppwwyyxx** [comment]
How did you install tensorpack? There was an old version which may have this problem.
If it's installed with pip, try: `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`.

**Comment by ppwwyyxx** [comment]
Oh looks like latest master is actually broken. It's probably related to a recent commit a couple days ago.. I'll check that.

**Comment by jiang1st** [comment]
Can I check out an old tensorpack to get the training started?

**Comment by ppwwyyxx** [comment]
Should be fixed now. It's always very hard to run tensorflow on multiple processes. The code worked before but is broken now probably because I'm using a newer tensorflow. 

I'll just disable multiprocessing for now, since it shouldn't affect speed very much for fasterrcnn.

**Comment by snownus** [comment]
@ppwwyyxx , I have installed the latest tensorpack, with Tensorflow 1.9.0. I want to run the DoReFaNet on ImageNet using Tensorpack provided. has same issue. I have tried to change Tensorflow version, but still stuck at Prefilling staging... Can you provide some suggestions?
