### ISSUE TITLE
QueueInput/input_queue: Skipping cancelled dequeue attempt with queue not closed

### ISSUE THREAD

**Issue by mikeun** [ppwwyyxx/tensorpack#548]
Hi,

I'm not sure - what does it mean?

[1212 13:42:36 @base.py:218] Initializing the session ...
[1212 13:42:36 @base.py:225] Graph Finalized.
[1212 13:42:38 @concurrency.py:36] Starting EnqueueThread QueueInput/input_queue ...
**2017-12-12 13:42:38.576804: W tensorflow/core/kernels/queue_base.cc:285] _0_QueueInput/input_queue: Skipping cancelled dequeue attempt with queue not closed**

After this it goes well. But can you explain please?
I used: 
launch_train_with_config(config, QueueInputTrainer()) with one GPU (1 tower)

def get_data():
    train = TFRecordData(train_tfrecords_file, size=hm_train_tfrecords, compress=True)
    train = BatchData(train, batch_size, remainder=False)

**Comment by ppwwyyxx** [comment]
It tries to clear the queue. It does not hurt but I'll see if I can get rid of this annoying message.

**Comment by mikeun** [comment]
Thank you.
