### ISSUE TITLE
Error on custom gym-env with train-atari.py

### ISSUE THREAD

**Issue by bigcat77** [ppwwyyxx/tensorpack#55]
I'm created my own gym environment, and am trying to use your code on it. The state is an 84x84x3 image and has discrete actions. Everything runs fine up until it starts the graph, and I get the following error.

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 894, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (2, 84, 84, 16) for Tensor u'state:0', which has shape '(?, 84, 84, 12)'

Have you seen anything like this in your development, or do you have any clue as to what is going wrong?

Thanks so much. This is a really fantastic package.

**Comment by ppwwyyxx** [comment]
If your image has 3 channels then the input `state` should have 3x4 channels (4 history).
But somehow you're feeding a `state` of 16 channels.

**Comment by bigcat77** [comment]
I had a screwup in converting from gray-scale to RGB. 

Thanks for the help.
