### ISSUE TITLE
TFGAN

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#550]
Should we consider TFGAN to replace some of the code in GAN examples?

https://research.googleblog.com/2017/12/tfgan-lightweight-library-for.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+blogspot/gJZg+(Official+Google+Research+Blog)

**Comment by ppwwyyxx** [comment]
I don't see much value in bringing in TFGAN. From what I can see the training utilities will only make the current code more complicated. The symbolic functions aren't very interesting either, and if you need them for a new type of GAN you can just import and call them.
