### ISSUE TITLE
Get a pure graph for inference

### ISSUE THREAD

**Issue by hhxjzyr** [ppwwyyxx/tensorpack#551]
[scripts/dump-model-params.py](https://github.com/ppwwyyxx/tensorpack/blob/master/scripts/dump-model-params.py)
can be used to remove unnecessary variables in a checkpoint and save it as a new checkpoint, but how to I get a pure graph without unnecessary variables and restore the new checkpoint to the pure graph exactly.

For example, the training graph for a specific model contains many unnecessary variables and its model part has been constructed correctly and I don't want to construct the model part by myself step by step again

**Comment by ppwwyyxx** [comment]
There is no way to automatically "guess" which part of graph is useful for inference.
You can just write pure symbolic code to construct the graph again.
Also see https://github.com/ppwwyyxx/tensorpack/issues/513#issuecomment-348093710

**Comment by hhxjzyr** [comment]
Thank you very much, I will just try to use `model._build_graph`

**Comment by hhxjzyr** [comment]
I found some solution by using
 [tensorflow/tensorflow/python/tools/freeze_graph.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) to get a pure inference graph after training a model from tenorpack (or any other trainining method)

Here is my usage 

```python
with tf.Session() as sess:
    model_path = tf.train.latest_checkpoint(CHECKPOINT_DIR)
    # get metagraphDef which contains graphDef, clear devices placement in training stage
    tf.train.import_meta_graph(os.path.join(CHECKPOINT_DIR,'graph-1214-001754.meta'),clear_devices=True)
    # write GraphDef to a GraphDef protocol buffer file which suitable for freeze_graph.py input 
    tf.train.write_graph(graph_or_graph_def=tf.get_default_graph().as_graph_def(),logdir='train_log',name='original.pbtxt',as_text=True)

```

```shell
python tensorflow/tensorflow/python/tools/freeze_graph.py \
--input_graph /home/yaren/densenet-tensorflow/train_log/original.pbtxt 
--input_checkpoint /home/yaren/densenet-tensorflow/train_log/cifar10-single-fisrt150-second225-max3001214-001743/model-234300 \
--output_node_names "InferenceTower/in_top_k/InTopKV2" \
--output_graph /home/yaren/densenet-tensorflow/train_log/frozen.pb 

```

**Comment by ppwwyyxx** [comment]
That script is perhaps not very reliable. IIRC it assumes input tensors for inference are placeholders, but that's not always true in a graph saved by tensorpack because placeholders are slow. It works for `InferenceRunner(some_dataflow)`, though.
