### ISSUE TITLE
Cannot get the correct inference during the training or testing time

### ISSUE THREAD

**Issue by tmquan** [ppwwyyxx/tensorpack#552]
Hi 

I tried to implement the image denoising problem by using U-net network to learn the noise pattern in the image. It gradually reaches the expectation as shown in this image. 
![image](https://user-images.githubusercontent.com/4506781/33989665-9bce5588-e10b-11e7-9a9a-8afe16fb0b8c.png)

However, the VisualizeRunner callback (to tensorboard) and the Deployment of the saved model at a specific checkpoint didn't work as they always give black results. 
![image](https://user-images.githubusercontent.com/4506781/33989674-a4c75158-e10b-11e7-84b9-6327ea474482.png)

I am pretty sure that the losses are decreasing during the training set. But the thing is the deployment wasn't right.  I would like to ask whether my custom VisualizeRunner was implemented correctly or the model doesn't use the trained weights and always output the black images?

Here are my implementation of VisualzeRunner callback and TrainingConfig
```python
class VisualizeRunner(Callback):
	def _setup_graph(self):
		self.pred = self.trainer.get_predictor(
			input_names=['A', 'B']
		output_names=['viz_A_recon'])

	def _before_train(self):
		global args
		self.ds_train, self.ds_valid = get_data(args.imageDir, args.labelDir, size=1)
		self.ds_train.reset_state()
		self.ds_valid.reset_state() 

	def _trigger(self):
		for lst in self.ds_train.get_data():
			viz_train = self.pred(lst)
			self.trainer.monitors.put_image('viz_train', viz_train)
		for lst in self.ds_valid.get_data():
			viz_valid = self.pred(lst)
			self.trainer.monitors.put_image('viz_valid', viz_valid)
```
```python
if nr_tower == 1:
	trainer = SeparateGANTrainer(ds_train, model, g_period=2, d_period=1)
else:
	trainer = MultiGPUGANTrainer(nr_tower, ds_train, model)

trainer.train_with_defaults(
	callbacks=[
		PeriodicTrigger(ModelSaver(), every_k_epochs=50),
		VisualizeRunner(),
		InferenceRunner(ds_valid, [ScalarStats('losses/Img/Recon/recon_img_AA'),]),
		ScheduledHyperParamSetter('learning_rate', 
			[(0, 2e-4), (100, 1e-4), (200, 2e-5), (300, 1e-5), (400, 2e-6), (500, 1e-6)], interp='linear')
		],
	session_init=SaverRestore(args.load) if args.load else None, 
	steps_per_epoch=ds_train.size(),
	max_epoch=500
        )
```

**Comment by tmquan** [comment]
Resolved due to scale issue in tf.summary.image 
https://www.tensorflow.org/api_docs/python/tf/summary/image

**Comment by ppwwyyxx** [comment]
Unrelated to `tf.summary.image`. But you do need to read the [doc](http://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.Monitors.put_image) before calling an API.
