### ISSUE TITLE
Something strange in DataFlow, am I making wrong use of it?

### ISSUE THREAD

**Issue by nameless-Chatoyant** [ppwwyyxx/tensorpack#553]
```python
from tensorpack import *
import numpy as np

shape = (5, 8, 8, 1)

class Data(RNGDataFlow):
    def size(self):
        return 10
    def get_data(self):
        return np.ones(shape)


if __name__ == '__main__':
    ds = Data()
    ds.reset_state()
    output = [i for i in ds.get_data()]
    print(len(output))
```
As `size()` return `10`, `len(output)` is supposed to be 10.

1. When `shape = (1, ...)`(starts with 1), output is 1.
2. When `shape = (5, 8, 8, 1)`(has more than 4 dimensions), output is shape[0], equals 5.

The second situation is frequent for temporal tasks. And combined with `BatchData` it will produce bugs like this:
I write a customed `RNGDataFlow` to yield `(t, h, w, c)` tensors, and thought `BatchData` would yield `(b, t, h, w, c)` tensors. However it yields `[(b, h, w, c)] * t` list, as I have set `use_list = False`
```python
>>> tensorpack.__version__
'0.8.0'
```
may be a conflict in designing a simple wise dataflow?

**Comment by ppwwyyxx** [comment]
You were not writing a dataflow. You need to yield your datapoints one by one.
See docs: http://tensorpack.readthedocs.io/en/latest/tutorial/extend/dataflow.html

**Comment by nameless-Chatoyant** [comment]
I have changed `get_data` to yield one by one, it seems `BatchData()` still reproduce above 2nd mistake

```python
from tensorpack import *
import numpy as np

shape = (5,8,8,1)

class Data(RNGDataFlow):
    def size(self):
        return 10
    def get_data(self):
        for i in range(10):
            yield np.ones(shape)
```
```python
ds = Data()
ds.reset_state()
for i in ds.get_data():
    print(i.shape)
```
it will output `(5,8,8,1)` 10 times.

```python
ds = Data()
ds = BatchData(ds, 8, use_list = False)
ds.reset_state()
for i in ds.get_data():
    print(type(i))
    print(len(i))
    print(*[j.shape for j in i])
```

output
```python
<class 'list'>
5
(8, 8, 8, 1) (8, 8, 8, 1) (8, 8, 8, 1) (8, 8, 8, 1) (8, 8, 8, 1)
```

**Comment by ppwwyyxx** [comment]
You were not writing a correct dataflow. A datapoint has to be a __list__ of python objects. It can be a list of 1 element.
See http://tensorpack.readthedocs.io/en/latest/tutorial/dataflow.html#what-is-dataflow
and http://tensorpack.readthedocs.io/en/latest/tutorial/extend/dataflow.html

**Comment by nameless-Chatoyant** [comment]
It works.Thank you so much for correct my mistakes, and apologize for such a issue
