### ISSUE TITLE
When i train resnet,steps_per_epoch can be changed ?

### ISSUE THREAD

**Issue by erdollar** [ppwwyyxx/tensorpack#557]
When i train resnet, i change TOTAL_BATCH_SIZE  from 256 to 64 and should i change  steps_per_epoch = 5000*4=20000 ?
I think that TOTAL_BATCH_SIZE  *steps_per_epoch  should be equal to 1280000, am i right ? thanks for you correct my thoughts if I am wrong .

**Comment by ppwwyyxx** [comment]
If you keep `TOTAL_BATCH_SIZE *steps_per_epoch` a constant, this means one epoch go through the same amount of data.

**Comment by erdollar** [comment]
Resnet needs to run 1281167 picture ( picture numbers of imagenet train set ) in one epoch ,right? If  TOTAL_BATCH_SIZE *steps_per_epoch != 1281167 , this will be contradiction with definition of epoch? 
 
> epoch: one forward pass and one backward pass of all the training examples

**Comment by ppwwyyxx** [comment]
That's not how I define an epoch but different people have different definitions. Please note that 1281167 is a prime.

**Comment by erdollar** [comment]
Emm. I got it. Thanks .:smile:
