### ISSUE TITLE
Is it possible to use GlobalNormClip to only part of the network?

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#559]
Our network has two parts: the CNN part and the RNN part. We want to apply a gradient clip by global norm to only the RNN part. I have checked the usages of GlobalNormClip in the examples, and have not found that the clipping can be applied to only part of the network.

**Comment by ppwwyyxx** [comment]
It doesn't support this feature. The code is only 5 lines so you can easily extend it or write a new one: http://tensorpack.readthedocs.io/en/latest/_modules/tensorpack/tfutils/gradproc.html#GlobalNormClip
