### ISSUE TITLE
ImportError: No module named tensorpack

### ISSUE THREAD

**Issue by FedorovIgor** [ppwwyyxx/tensorpack#56]
Hello,

I am trying to reproduce your results, but I have the following problem:

(tensorflow) xxxxxxx# ./train-atari.py --env Breakout-v0 --gpu 0
Traceback (most recent call last):
  File "./train-atari.py", line 17, in <module>
    from tensorpack import *
ImportError: No module named tensorpack

I would appreciate your help. Thank you!

**Comment by ppwwyyxx** [comment]
You should add the path to this repo to PYTHONPATH, as said at the end of `README.md`.

**Comment by FedorovIgor** [comment]
Thank you for helping!
I first did :  # git clone https://github.com/ppwwyyxx/tensorpack.git
then, export PYTHONPATH=$PYTHONPATH:`readlink -f path/to/tensorpack` , where I substituted path/to/tensorpack with/my/path/tensorpack

Is it right?

**Comment by ppwwyyxx** [comment]
Roughly yes.... it sounds like you're not very familiar with command line and variables.
Basically you did `export PYTHONPATH=$PYTHONPATH:/ABC/DEF/G` where "/ABC/DEF/G" is the absolute path to the whole directory you cloned.

**Comment by FedorovIgor** [comment]
Yes, you are absolutely right. I am learning how to do it right. I see what are you saying. Could you show me how to do it, please?

**Comment by ppwwyyxx** [comment]
`export PYTHONPATH=$PYTHONPATH:/ABC/DEF/G` where "/ABC/DEF/G" is the absolute path to the whole directory you cloned, before running the program.

**Comment by FedorovIgor** [comment]
it looks like i am on the right way, if I do echo $PYTHONPATH it gives me :/ABC/DEF/tensorpack . But something is still wrong.

**Comment by FedorovIgor** [comment]
thank you, I think I went over it:)

**Comment by FedorovIgor** [comment]
Hi again,

I made new version of Ubuntu14.04 on VB and I still not able to run the code. Here, i would like to show my path to tensorpack and PYTHONPATH :

osboxes@osboxes:/opt/tensorpack/tensorpack$ ls -l
total 40
drwxr-xr-x 2 root root 4096 Nov 26 03:14 callbacks
drwxr-xr-x 4 root root 4096 Nov 26 03:14 dataflow
-rw-r--r-- 1 root root  578 Nov 26 03:14 __init__.py
drwxr-xr-x 2 root root 4096 Nov 26 03:14 models
drwxr-xr-x 2 root root 4096 Nov 26 03:14 predict
-rw-r--r-- 1 root root  453 Nov 26 03:14 README.md
drwxr-xr-x 2 root root 4096 Nov 26 03:14 RL
drwxr-xr-x 2 root root 4096 Nov 26 03:14 tfutils
drwxr-xr-x 2 root root 4096 Nov 26 03:14 train
drwxr-xr-x 2 root root 4096 Nov 26 03:14 utils
osboxes@osboxes:/opt/tensorpack/tensorpack$ echo $PYTHONPATH
:/opt/tensorpack/tensorpack
osboxes@osboxes:/opt/tensorpack/tensorpack$

**Comment by ppwwyyxx** [comment]
`echo $PYTHONPATH` should contain `/opt/tensorpack`, not `/opt/tensorpack/tensorpack`.

**Comment by FedorovIgor** [comment]
Thank you so much it helped. Then, I tried to reproduce the atari game on openAIGym it complained that gym is not installed. I installed but know I can not activate tensorflow environment wiht source ~/tensorflow/bin/activate . I tried to run without it and got the following : 

osboxes@osboxes:/opt/tensorpack/openAIgames-fedorov$ ./train-atari.py --env Breakout-v0 --gpu 0
[1126 06:06:17 @bsds500.py:18] WRN Cannot import scipy. BSDS500 dataset won't be available!
[1126 06:06:17 @svhn.py:18] WRN Cannot import scipy. SVHNDigit dataset won't be available!
[1126 06:06:17 @format.py:16] WRN Error in 'import h5py'. HDF5Data won't be available.
[1126 06:06:17 @format.py:24] WRN Error in 'import lmdb'. LMDBData won't be available.
[1126 06:06:17 @format.py:31] WRN Error in 'import sklearn'. SVMLightData won't be available.
[1126 06:06:18 @concurrency.py:24] WRN Cannot import Future in tornado.concurrent. MultiThreadAsyncPredictor won't be available.
Traceback (most recent call last):
  File "./train-atari.py", line 25, in <module>
    import common
  File "/opt/tensorpack/openAIgames-fedorov/common.py", line 1
    ../Atari2600/common.py
    ^
SyntaxError: invalid syntax
osboxes@osboxes:/opt/tensor

**Comment by ppwwyyxx** [comment]
The project contains symbolic link. It looks like you're using Windows, or using a filesystem which doesn't support symbolic link.
In that case you need to copy the file `examples/Atari2600/common.py` to `examples/OpenAIGym`.

**Comment by FedorovIgor** [comment]
I am using Ubuntu14.04 on VB which is installed on Windows10. But I use usb to transfer files from windows to ubuntu. May it affect it? Could you recommend something to resolve it?

**Comment by ppwwyyxx** [comment]
It will affect. You need to copy the file like I said.

**Comment by FedorovIgor** [comment]
It moved further but now it is OSError: [Errno 13] Permission denied: 'train_log'

osboxes@osboxes:/opt/tensorpack/examples/Atari2600$ ls -l
total 148
-rw-r--r-- 1 root root   7255 Nov 26 07:41 atari.py
-rw-r--r-- 1 root root   5972 Nov 26 07:41 breakout.jpg
-rw-r--r-- 1 root root   3456 Nov 26 07:41 common.py
-rw-r--r-- 1 root root 111444 Nov 26 07:41 curve-breakout.png
-rwxr-xr-x 1 root root   8202 Nov 26 07:41 DQN.py
-rw-r--r-- 1 root root   1714 Nov 26 07:41 README.md

osboxes@osboxes:/opt/tensorpack/examples/OpenAIGym$ ls -l
total 26500
-rw-rw-r-- 1 osboxes osboxes 13561375 Nov 26 07:56 Asteroids-v0.tfmodel
-rw-rw-r-- 1 osboxes osboxes 13544955 Nov 26 07:56 Breakout-v0.tfmodel
-rw-r--r-- 1 root    root        3457 Nov 26 08:14 common.py
-rw-r--r-- 1 root    root        4659 Nov 26 07:41 README.md
-rwxr-xr-x 1 root    root        3278 Nov 26 07:41 run-atari.py
-rwxr-xr-x 1 root    root        9580 Nov 26 07:41 train-atari.py
osboxes@osboxes:/opt/tensorpack/examples/OpenAIGym$ ./train-atari.py --env Breakout-v0 --gpu 0
[1126 08:20:41 @bsds500.py:18] WRN Cannot import scipy. BSDS500 dataset won't be available!
[1126 08:20:41 @svhn.py:18] WRN Cannot import scipy. SVHNDigit dataset won't be available!
[1126 08:20:41 @format.py:16] WRN Error in 'import h5py'. HDF5Data won't be available.
[1126 08:20:41 @format.py:24] WRN Error in 'import lmdb'. LMDBData won't be available.
[1126 08:20:41 @format.py:31] WRN Error in 'import sklearn'. SVMLightData won't be available.
[1126 08:20:44 @concurrency.py:24] WRN Cannot import Future in tornado.concurrent. MultiThreadAsyncPredictor won't be available.
[2016-11-26 08:20:44,722] Making new env: Breakout-v0
[1126 08:20:45 @train-atari.py:249] [BA3C] Train on gpu 0 and infer on gpu 0
Traceback (most recent call last):
  File "./train-atari.py", line 255, in <module>
    config = get_config()
  File "./train-atari.py", line 177, in get_config
    logger.auto_set_dir()
  File "/opt/tensorpack/tensorpack/utils/logger.py", line 117, in auto_set_dir
    action=action)
  File "/opt/tensorpack/tensorpack/utils/logger.py", line 91, in set_logger_dir
    mkdir_p(dirname)
  File "/opt/tensorpack/tensorpack/utils/fs.py", line 22, in mkdir_p
    raise e
OSError: [Errno 13] Permission denied: 'train_log'

**Comment by ppwwyyxx** [comment]
You don't have permission to write in the `examples` directory.
That's likely because you're using virtualbox and put things under `/opt`.
You can use a different directory such as the user's home directory.

**Comment by FedorovIgor** [comment]
Thank you so much. It completed training with some warnings. Started evaluation also with some warnings.

**Comment by ppwwyyxx** [comment]
It shouldn't complete training without running for days.

**Comment by FedorovIgor** [comment]
May I sent you an email with an output, then?

**Comment by ppwwyyxx** [comment]
yes.

**Comment by FedorovIgor** [comment]
Hello,

this is me again. Could you look at the screen shot please? Am not sure if
it is a live or not?

Igor
