### ISSUE TITLE
Error: error in tensorpack setup command: 'extras_require' requirements cannot include environment markers, in 'all': 'tornado; python_version < "3.0"'

### ISSUE THREAD

**Issue by xx4966946** [ppwwyyxx/tensorpack#560]
I got the error message when tried to install tensorpack:

Collecting git+https://github.com/ppwwyyxx/tensorpack.git
  Cloning https://github.com/ppwwyyxx/tensorpack.git to /tmp/pip-IxEFVq-build
    Complete output from command python setup.py egg_info:
    error in tensorpack setup command: 'extras_require' requirements cannot include environment markers, in 'all': 'tornado; python_version < "3.0"'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-IxEFVq-build/

please help!

PS: python: 2.7 with anaconda. 
      tensorflow: 1.2

**Comment by ppwwyyxx** [comment]
You probably need to upgrade setuptools and pip.

**Comment by ppwwyyxx** [comment]
Switched to another syntax following https://github.com/pypa/setuptools/issues/1087, so it works with older version of setuptools.

**Comment by xx4966946** [comment]
Solved by upgrading setuptools

Thank you!
