### ISSUE TITLE
How to specify output node name?

### ISSUE THREAD

**Issue by wanghuok** [ppwwyyxx/tensorpack#563]
When i build model use tensorpack. I specify output node name such as "output". Then i load trained model, i output all node name, that output node name become "tower-pred-0/output". How can i fix it?

**Comment by ppwwyyxx** [comment]
When you "specify output node name" that is not for only one node. You model will be used more than one time and multiple nodes will be created. One may be named "tower-pred-0/output", one may be named "tower1/output", etc, depending on the name scope under which the tensor is created. This is how tensorflow works.

**Comment by wanghuok** [comment]
So, such as 'tower-pred-0' is tensorpack add, and there is no control to it?

**Comment by ppwwyyxx** [comment]
Yes. Why do you need to control it?
