### ISSUE TITLE
Using tf.data.Dataset as InferenceRunner inputsource 

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [ppwwyyxx/tensorpack#565]
https://github.com/ppwwyyxx/tensorpack/blob/7a5b861ab5ff9d018f4700e95bf0985d55c1841c/tensorpack/callbacks/inference_runner.py#L80
Should this line be self._size = np.inf ? 
When self._size is set as 0, there will be no output in self.stats in ScarStates,
and if it is set as inf, tf.errors.OutOfRange will be raised before the end of dataflow.

**Comment by ppwwyyxx** [comment]
Thanks for pointing out! Could you try again?

**Comment by TomorrowIsAnOtherDay** [comment]
It worked as expected after pulling the newest code  ：）
