### ISSUE TITLE
Penn Treebank throws tuple out of range error when NUM_LAYER=1

### ISSUE THREAD

**Issue by RadZaeem** [ppwwyyxx/tensorpack#567]
Bug Reports/Feature Requests/Usage Questions Only:

Bug reports or other problems with code: PLEASE always include
1. What you did. (command you run and changes you made if using examples; post or describe your code if not)
When I edit so that NUM_LAYER=1 in
examples/PennTreebank/PTB-LSTM.py
2. What you observed, e.g. as much as logs possible.
  File "PTB-LSTM.py", line 87, in _build_graph
    tf.assign(state_var[1].c, last_state[1].c),
IndexError: tuple index out of range

3. What you expected, if not obvious.
4. Your environment (TF version, cudnn version, number & type of GPUs), if it matters.
TF 1.4.1
5. About efficiency, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

Feature Requests:
1. Improve an existing feature.
2. Add a new feature. Please note that, you can implement a lot of features by extending tensorpack
	(See http://tensorpack.readthedocs.io/en/latest/tutorial/index.html#extend-tensorpack).
	It may not have to be added to tensorpack unless you have a good reason.
3. Note that we don't implement papers at others' requests.

You can also use gitter (https://gitter.im/tensorpack/users) for more casual discussions.

Could it be due to the update ops assume there exist next layer holding next state?
Thanks.

**Comment by ppwwyyxx** [comment]
The code was only written for two layers. Now it should work for one layer as well.

**Comment by RadZaeem** [comment]
That was fast.
Thank you!

By the way, any recommendation or guide on how to use tfdbg to 'trace' value of gradients flow.
Currently I am porting code from[ bit-rnn ](https://github.com/hqythu/bit-rnn)(quantized RNN, He et al)to tensorpack

**Comment by ppwwyyxx** [comment]
```
callbacks=[
            HookToCallback(tf_debug.LocalCLIDebugHook()), ...
```

**Comment by RadZaeem** [comment]
Thanks again
