### ISSUE TITLE
Poor performance for embedding layer with GPU ?

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [ppwwyyxx/tensorpack#568]
Recently I tried to rewrite my TF model under tensorpack framework.But when I transfered a NLP model(with a shape of 400000 * 256 embedding layer), GPU utility is only 30%~40%.Before I rewrite the code, it could be 90%+.
I found the problem: some operation of embedding layer has been placed on CPU while it was placed on GPU before.
I tried to specific the device using tf.device API, like this
`        with tf.device('/gpu:0'):
            user_embed = embedding(uid, 100001, hid_size, name='user_embedding')
            title_embed = embedding(title, 400001, hid_size, name='unigram_embedding')`
but 
![image](https://user-images.githubusercontent.com/25046619/34295627-54038748-e749-11e7-84ac-6b790c968183.png)
how can I solve the performance problem with large embedding layer?

**Comment by TomorrowIsAnOtherDay** [comment]
additional infomation:
![image](https://user-images.githubusercontent.com/25046619/34295722-c831ba72-e749-11e7-9d28-a5b4264c6a37.png)

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/ppwwyyxx/tensorpack/blob/a3cc3a18c492ac16e6d678e1f26c076c3ae5f70f/tensorpack/train/tower.py#L185
When I set colocate_gradients_with_ops = False, It become faster as it was.
I think this config make embedding layer poor performance.
Any advice on this problem?

**Comment by ppwwyyxx** [comment]
Maybe `colocate_gradients_with_ops` is not a good option. I saw that `tensorflow/benchmarks` didn't set this option either, so I was considering removing it.

**Comment by ppwwyyxx** [comment]
The option was kept unchanged because I found it still helps my vision models. But now you should be able to set it by `trainer.COLOCATE_GRADIENTS_WITH_OPS=False`, before building the graph.

**Comment by TomorrowIsAnOtherDay** [comment]
It worked as expected, now I can used SingleCostTrainer. COLOCATE_GRADIENTS_WITH_OPS=False to set it:)
