### ISSUE TITLE
AttributeError: 'PrefetchDataZMQ' object has no attribute 'socket'

### ISSUE THREAD

**Issue by youkaichao** [ppwwyyxx/tensorpack#569]
when i'm using dataflow.dataloader, i got this exception. 

By scanning the source code in prefetch.py, i find that **reset_state** method is **not called** in the construction function of PrefetchDataZMQ, but the 'socket' property is set in the _reset_once function which is not called.

I think reset_state can be called when initializing PrefetchDataZMQ, that will be more convenient.

**Comment by ppwwyyxx** [comment]
It's supposed to be called by you. The first tutorial has more details about it.

**Comment by youkaichao** [comment]
thanks! problem solved!

But i still think that since reset_state can be called only once, it's better if it's called automatically when constructed ^_^
