### ISSUE TITLE
Bug:(maybe) can't install by 'pip install -U git+https://github.com/ppwwyyxx/tensorpack.git'

### ISSUE THREAD

**Issue by erdollar** [ppwwyyxx/tensorpack#570]
I can not install tensorpack using 
`pip install -U git+https://github.com/ppwwyyxx/tensorpack.git` 
and 
`pip install -U git+https://github.com/ppwwyyxx/tensorpack.git --user`
does't work.

![image](https://user-images.githubusercontent.com/20589365/34346310-4a53e7d4-ea31-11e7-8c38-7189c8777ad7.png)
Finally, I download zip format , and install it by 
`pip install /home/xxx/download/tensorpack-master.zip`
It works.
So, it's a bug or I use this incorrectly?

**Comment by ppwwyyxx** [comment]
It said cannot find git

**Comment by erdollar** [comment]
Would you please update the link? Thanks
I follow the guide [Tensorpack install page](https://github.com/ppwwyyxx/tensorpack).
