### ISSUE TITLE
how to duplicate some layers with pretrained weight?

### ISSUE THREAD

**Issue by bilipa** [ppwwyyxx/tensorpack#572]
Hi, I want to duplicate some layers with pretrained weight. For example, duplicating **L** 2 times(note as L_1, L_2).
In training, I only fine-tuning L_1,  when fine-tuning L_1 done,  copy the L_1 wight to L_2, then only fine-tuning L_2. 
Does there have any method to do it ?
Thanks.

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/en/latest/tutorial/save-load.html
and http://tensorpack.readthedocs.io/en/latest/tutorial/faq.html#how-to-freeze-some-variables-in-training
have everything you need to know to do this.

**Comment by bilipa** [comment]
thanks
