### ISSUE TITLE
How to save binary or quantized weights?

### ISSUE THREAD

**Issue by erdollar** [ppwwyyxx/tensorpack#573]
When I use DoReFa-net, the weights saved reflect the actual weights, not the quantized one. What should I do if I want to save  binary or quantized weights? Thanks a lot.

**Comment by ppwwyyxx** [comment]
Run `fw` manually on the saved actual weights.

**Comment by erdollar** [comment]
haven't any ways or idea to directly save binary weights? Thanks

**Comment by ppwwyyxx** [comment]
Tensorflow can only save variables. It cannot save a tensor which is computed from another variable. 

To save binary weights you'll need to create a variable to each of the weights, and assign them the value of `fw(actual weights)` every epoch before saving the actual weights. Since it is not useful at all to save binary weights during training, I recommend you just do the post-processing after training.

**Comment by erdollar** [comment]
Thanks a lot. I will have a try.

**Comment by erdollar** [comment]
Sir, I failed to do the post-processing after training. I can't make weights in .npy going through Binary Function. Could you help me?

**Comment by ppwwyyxx** [comment]
```python
import numpy as np
import tensorflow as tf
import tensorflow.contrib.eager as eager
eager.enable_eager_execution()

bitW = 1

def fw(x):
    if bitW == 32:
        return x
    if bitW == 1:   # BWN
        E = tf.stop_gradient(tf.reduce_mean(tf.abs(x)))
        return tf.sign(x / E) * E
    x = tf.tanh(x)
    x = x / tf.reduce_max(tf.abs(x)) * 0.5 + 0.5
    return 2 * quantize(x, bitW) - 1


arr = np.random.rand(10, 10) - 0.5
print(arr, fw(arr))
```

**Comment by erdollar** [comment]
Thanks. I know how to use fw(x). What confuse me is how to get the weights from the npy format ? (Because the weights are saved in a .npy file) I try to use np.load('xx.npy'), and just get :
![image](https://user-images.githubusercontent.com/20589365/34857092-f53ea396-f783-11e7-81a1-243123fc3608.png)
![image](https://user-images.githubusercontent.com/20589365/34857147-2b43ffa4-f784-11e7-964a-3da3024b6025.png)

**Comment by ppwwyyxx** [comment]
`a.item()` is a dict.

**Comment by erdollar** [comment]
Thank you for your patience. I get it. 
I use this code to get the weights:
`a = np.load('1.npy')
print a.item()['which weights you want']
`
