### ISSUE TITLE
Faster R-CNN example bug report

### ISSUE THREAD

**Issue by sharpstill** [ppwwyyxx/tensorpack#574]
On https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/train.py#L105 
`decoded_boxes = decode_bbox_target(rpn_box_logits, fm_anchors) # fHxfWxNAx4, floatbox`
the `decoded_boxes` is defined on the feature_map which is 1/16.0 scale smaller than original image, because `fm_anchors `is defined on feature_map but not the original image size.

But in https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/train.py#L115
The `rcnn_sampled_boxes `is also come from  `decoded_boxes  `and not resize, so it should define already on  1/16.0 scale smaller feature map, you should not multiply 1/16.0

**Comment by ppwwyyxx** [comment]
> the decoded_boxes is defined on the feature_map which is 1/16.0 scale smaller than original image, 

No. It's defined on the original image.

**Comment by sharpstill** [comment]
@ppwwyyxx two proof:
1.  because fm_anchors is define on 1/16 feature map,
2. and in
https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/model.py#L43
 ,your comment also says the box_logits is defined on 1/16 feature map.
I think the `decoded_boxes `  is defined on 1/16 feature map

**Comment by ppwwyyxx** [comment]
1. `fm_anchors` is defined on original image
2. The comment is talking about the shape of `box_logits`, and has nothing to do with its scale.

**Comment by sharpstill** [comment]
@ppwwyyxx 
about 1: https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/train.py#L86  and https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/data.py#L50 prove that the fm_anchor is defined on 1/16.0 smaller scale feature map.
Am I correct or I am missing something?

**Comment by ppwwyyxx** [comment]
You can print the return value of `get_all_anchors` to confirm what it is.

**Comment by ppwwyyxx** [comment]
And https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/train.py#L86 is still only about shape, not the scale.

**Comment by sharpstill** [comment]
@ppwwyyxx  I am confused, in get_all_anchors, yes, I found it return anchor defined on the original size of image, but in https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/train.py#L86 , You only use tf.shape(image)[0] // config.ANCHOR_STRIDE to slice the anchor ,why ?
and what is difference between shape and scale, for example, shape=[H/16, W/16] means the image size is 1/16 of original image(H,W)??

**Comment by sharpstill** [comment]
I have wechat, and email:sharpstill@163.com, If you can speak chinese , we can contact with each other more convenient , I am using your tensorpack to finish my PhD thesis, So it is very important for me

**Comment by ppwwyyxx** [comment]
The input image can be small and may not use all the anchors. So I slice the anchors.

Shape is the number of elements in a tensor. Scale is about the value of elements in a tensor. Changing the shape doesn't change the values. Slicing changes the shape. `boxes = boxes / 16.0` changes the value.

**Comment by sharpstill** [comment]
@ppwwyyxx 
one point: 
in `fm_anchors = self._get_anchors(image)` the returned anchor box coordinates is height/16.0 and width/16.0 of original image height & width? Am I right? so decoded_boxes box coordinates is height/16.0 and width/16.0 of original image height & width??? why you say it is defined on original image?

**Comment by ppwwyyxx** [comment]
> Slicing changes the shape. boxes = boxes / 16.0 changes the value.

The number of boxes on the image is (height/16 * width/16 * 15). This is SHAPE.
It has nothing to do with whether the coordinates (i.e. VALUES) are divided by 16 or not.

**Comment by Superlee506** [comment]
@ppwwyyxx @sharpstill Hi, I know about the "generate_anchors" function, but I have a little confused about [Line 68](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/data.py#L68) in "get_all_anchors". Why do we need to add 1 as below:
![image](https://user-images.githubusercontent.com/13114675/39399701-90a345ac-4af0-11e8-9b23-41b24f1937d7.png)

Is it related with the float box you mentioned？ But I'm still confused.  Any suggestion would be appreciated.

**Comment by ppwwyyxx** [comment]
Yes. The anchor code is copied elsewhere which used a different definition of box.
