### ISSUE TITLE
How to debug(break point debug) tensorpack efficiently

### ISSUE THREAD

**Issue by sharpstill** [ppwwyyxx/tensorpack#575]
I use tensorpack and tensorflow to finish my PhD thesis, I am modifying the Faster  R-CNN code in example, One question: How do you debug tensorpack and add break point to effieciently find bugs?
What do you suggest the best practice

**Comment by ppwwyyxx** [comment]
tensorpack is written in python and you debug in the same way you debug python. I personally use `import IPython as IP; IP.embed() `.

Not a tensorpack issue. Closing.

**Comment by sharpstill** [comment]
but in my knowledge, tensorflow cannot add break point and op cannot break point to debug, because sess.run magic hide the background actual flow

**Comment by ppwwyyxx** [comment]
yes. you can only break in python.

**Comment by sharpstill** [comment]
for  complex code such as Faster R-CNN, You use IPython as IP; IP.embed(). to debug? or log? I am using pycharm before, and using chainer which can debug like usual python code. But this time I use your tensorpack , how to best practice of debug ?

**Comment by Remember2018** [comment]
Hi @ppwwyyxx , could you please give some advice on how to use the `tf.Print` to debug the Tensorpack? In my case, I use the FasterRCNN in Tensorpack and is there any way to print the value of `decoded_boxes`  tensor in the terminal log? Thanks.

**Comment by ppwwyyxx** [comment]
See examples at https://tensorpack.readthedocs.io/tutorial/faq.html#how-to-print-dump-intermediate-results-during-training

**Comment by Remember2018** [comment]
@ppwwyyxx Thanks a lot for your kind reply! I added the `tf.Print` in the graph of `ResNetC4Model`, but there are no the desired outputs when training. I used the `tf.py_func` to show the image tensor. Maybe I can also save the image values into the disk for checking. Thanks.
