### ISSUE TITLE
Training Mask RCNN encounter KeyError: 'file_name'

### ISSUE THREAD

**Issue by tranorrepository** [ppwwyyxx/tensorpack#577]
Training Mask RCNN encounter error below:
File "./tensorpack/examples/FasterRCNN/data.py", line 208, in preprocess
    fname, boxes, klass, is_crowd = img['file_name'], img['boxes'], img['class'], img['is_crowd']
KeyError: 'file_name'

and then the training process get stuck at "Pre-filling staging area...“

My environment: python 3.4, tf 1.4, cuda 8.0.

**Comment by ppwwyyxx** [comment]
Please follow the [issue template](https://github.com/ppwwyyxx/tensorpack/blob/master/.github/ISSUE_TEMPLATE.md) to report problems.

I think you didn't use a valid COCO annotation file.

**Comment by tranorrepository** [comment]
@ppwwyyxx 

COCO annotations are download from http://cocodataset.org/#home

print the img,
{..., b'license': 4, b'file_name': b'../data/COCO/train2014/COCO_train2014_000000158420.jpg'} 

when I modified the img['file_name'] to img[b'file_name'], the error disappear.

**Comment by ppwwyyxx** [comment]
There is no `b` if I print it. It may be due to some difference in python version or its json implementation.

**Comment by ppwwyyxx** [comment]
After a though I think it's due to how msgpack serializes/deserializes the data. What's you msgpack version and could you perhaps upgrade it?

**Comment by tranorrepository** [comment]
My msgpack is 0.4.8, it seems to be the latest.

**Comment by ppwwyyxx** [comment]
Turned out that msgpack always transforms strings to bytes. Should be fixed now.
