### ISSUE TITLE
load-resnet.py does not load ResNet weights available on Google Drive

### ISSUE THREAD

**Issue by ghostFaceKillah** [ppwwyyxx/tensorpack#58]
First of all, thank you for making tensorpack open. It is hands down my favourite DNN framework / TF wrapper, and amazing piece of work. It removes so much boilterplate i had to write from scartch every time. Congratulations!

I had some trouble using the ResNet example and would like to let you know about them. I will be trying to fix them and will let you know about progress.

I have some trouble loading models from the [link](https://drive.google.com/drive/folders/0B9IPQTvr2BBkTXBlZmh1cmlnQ0k) you have mentioned in [readme for ResNet example](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/ResNet).
[load-resnet.py](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/load-resnet.py) does not load the models from your Google Drive.

More specifically, running 
```
./load-resnet.py --gpu 0 --load gdrive-models/ImageNet-ResNet50.npy -d 50 --input imgs/jet_499x330.jpg 
```

results in 
```
[1130 22:00:44 @load-resnet.py:211] ERR Exception when processing caffe layer group2/block4/preact/bn/variance/EMA:0
Traceback (most recent call last):
  File "./load-resnet.py", line 209, in <module>
    newname = name_conversion(k)
  File "./load-resnet.py", line 166, in name_conversion
    layer_block_part1 = s.group(3)
AttributeError: 'NoneType' object has no attribute 'group'
```

It seems that both regex in line 163 and 165 does not match layer name "group2/block4/preact/bn/variance/EMA:0".

**Comment by ppwwyyxx** [comment]
The model is not for `load-resnet.py`. It is the trained model by `imagenet-resnet.py`. They are different variants of ResNet.
`load-resnet.py` is "A script to convert and run ImageNet-ResNet{50,101,152} Caffe models released by Kaiming." You'll need to download the caffe model and use the converter to build a npy model, as mentioned in the readme.

**Comment by ghostFaceKillah** [comment]
Aha, I see. 

Thank you for your help!
