### ISSUE TITLE
ShuffleNet 's unit output channels configuration is not consistence with original paper

### ISSUE THREAD

**Issue by sharpstill** [ppwwyyxx/tensorpack#580]
in https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ShuffleNet/shufflenet.py#L90
the `channels = [224, 416, 832]`, I notice that your `group=8`, in original paper the channel in Table 1 written as `[384,768,1536]` (Table 1's rightmost column), why you config different?

**Comment by dongzhuoyao** [comment]
maybe this can help you: #488

**Comment by sharpstill** [comment]
Another question, If I want to use ShuffleNet as Faster R-CNN backbone base net, How to use it? Which layers can I used as RPN and RoI Pooling? Which layers can I use after RoI pooling?

**Comment by ppwwyyxx** [comment]
It's your choice to make your models and I do not give guidance on that.

**Comment by sharpstill** [comment]
@ppwwyyxx Thank you anyway. Your tensorpack give me a lot of help already

**Comment by sharpstill** [comment]
@ppwwyyxx In your tutorial document , You write the conception of **tower**, What is **tower** concept, you didn't give any information in earlier section of your document? Can you give some information about it?

**Comment by ppwwyyxx** [comment]
The document says " a tower function is a callable that takes input tensors and adds one replicate of the model to the graph". This is the definition.

**Comment by sharpstill** [comment]
@dongzhuoyao Really Sorry to bother you again,Why @ppwwyyxx say 384 % 16 == 0 is enough. I notice that l = Conv2D('conv2', l, out_channel if stride == 1 else out_channel - in_channel, 1, split=group, nl=BN) , but in the caller l = shufflenet_unit(l, channels[0], group, 2 if i == 0 else 1), thus the channel=24must satisfy formular: (out_channel - in_channel)%group == 0? (384-24)%8 == 0

Am I understand correct?
