### ISSUE TITLE
How to Get Data from different File in a file list with PrefetchDataZMQ And A RNGDataFlow

### ISSUE THREAD

**Issue by kelvict** [ppwwyyxx/tensorpack#582]
How to Get Data from different File in a file list with PrefetchDataZMQ And A RNGDataFlow

**Comment by kelvict** [comment]
I define my get data as below.
 
```
   def get_data(self):
        self.rng.shuffle(self.filenames)
        for idx, fname in enumerate(self.filenames):
            with open(fname) as f:
                for l_idx, l in enumerate(f):
                    yield [os.getpid(), fname.split('.')[-1], l_idx] + self.extract_features_from_a_line(l)
```

And use prefetch as below 

```
    df = MDPRankDataFlow()
    #df = BatchData(df, 3)
    #cpu_cnt = cpu_count()
    cpu_cnt = 4
    df = PrefetchDataZMQ(df, cpu_cnt, 50)
    df.reset_state()
```

But I still get the same example from different process. I just want to get a example one time.

**Comment by ppwwyyxx** [comment]
It's the expected behavior that all process will give you randomly-sampled files from your list. Therefore they could be the same.

**Comment by ppwwyyxx** [comment]
The document says: 
```
When nr_proc>1, the dataflow produces the same distribution of data as ds if each sample from ds is i.i.d. (e.g. fully shuffled). You probably only want to use it for training.
```
"Having the same distribution" implies that there may be duplications.

I don't know what behavior you want, but you may be interested in `MultiProcessMapData` or `MultiThreadMapData`.
