### ISSUE TITLE
What is the FASTRCNN_BBOX_REG_WEIGHTS in Faster R-CNN used for?

### ISSUE THREAD

**Issue by sharpstill** [ppwwyyxx/tensorpack#583]
in example Faster R-CNN https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/config.py#L50 
I really cann't understand this config argument purpose?

**Comment by ppwwyyxx** [comment]
https://github.com/rbgirshick/py-faster-rcnn/blob/96dc9f1dea3087474d6da5a98879072901ee9bf9/lib/fast_rcnn/config.py#L89

**Comment by sharpstill** [comment]
Maybe stackoverflow is better place for these questions? Chainer group move these type of question to stackoverflow  which can answer by other developer who are willing to do as well.

**Comment by sharpstill** [comment]
Maybe I put a tag = "tensorpack" on stackoverflow . You may watch it, You can answer it or not based on your mood.

**Comment by sharpstill** [comment]
Really sorry to bother you , I am not for fun to do it, My job is modify your faster r-cnn code.
 I have deep learning experience and have a vision paper in CVPR, but I used chainer framework before.
I am new to tensorpack . So sometimes I am stuck for your code and really need your help.
