### ISSUE TITLE
Question about ShuffleNet Implementation

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#585]
Two questions about the shuffle-net implementation:
1. Table 1 in the paper shows that stage 3 has 8 convolution layers. But in this implementation, stage 3 has only 6 convolution layers. (https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ShuffleNet/shufflenet.py#L101)
2. According to the paper, ShuffleNet 0.5x means scaling the number of filters in ShuffleNet 1x by 0.5 times. But in this implementation, the number of channels are [224, 416, 832] (https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ShuffleNet/shufflenet.py#L90), which is not as 0.5 times as the number of channels for ShuffleNet 1x [384, 768, 1536]

**Comment by ppwwyyxx** [comment]
This is `ShuffleNet 0.5x (arch2) g=8 in the paper`. Not table 1.

**Comment by JesseYang** [comment]
Thanks!
