### ISSUE TITLE
QueueInput is missing

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#586]
```
python imagenet-resnet.py --fake --gpu 3
```

gives

```
Traceback (most recent call last):
  File "imagenet-resnet.py", line 9, in <module>
    from tensorpack import logger, QueueInput
ImportError: cannot import name QueueInput
```

at commit efa492d6e5aea55d39af192087982bc9deb057ac
  
However, 
```
from tensorpack.input_source import QueueInput
```

seems to work. 
Adding imagenet-resnet.py this to the travis-test cases would probably slown down ci even more.

**Comment by ppwwyyxx** [comment]
` imagenet-resnet.py` is on travis and it works.

**Comment by PatWie** [comment]
really strange, I cannot even reproduce it today on my machine.
