### ISSUE TITLE
Shape mismatch for Mask R-CNN

### ISSUE THREAD

**Issue by pvoigtlaender** [ppwwyyxx/tensorpack#587]
Hi,

thanks for the amazing work!
When using your Mask R-CNN implementation, I encountered this error
```
  File "/home/voigtlaender/vision/tensorpack/examples/FasterRCNN/train.py", line 457, in <module>
    forward(pred, args.forward, args.forward_dataset)
  File "/home/voigtlaender/vision/tensorpack/examples/FasterRCNN/train.py", line 347, in forward
    results = detect_one_image(img_val, pred_func)
  File "/home/voigtlaender/vision/tensorpack/examples/FasterRCNN/eval.py", line 82, in detect_one_image
    for box, mask in zip(boxes, masks[0])]
  File "/home/voigtlaender/vision/tensorpack/examples/FasterRCNN/eval.py", line 82, in <listcomp>
    for box, mask in zip(boxes, masks[0])]
  File "/home/voigtlaender/vision/tensorpack/examples/FasterRCNN/eval.py", line 54, in fill_full_mask
    ret[y0:y1 + 1, x0:x1 + 1] = mask
ValueError: could not broadcast input array from shape (269,138) into shape (269,137)
```

In the comments in the code it says
```
# rounding errors could happen here, because masks were not originally computed for this shape.
# but it's hard to do better, because the network does not know the "original" scale
```
so I think, you are kind of aware that there could be a problem.
Is there an easy way to fix it, or to at least prevent a crash, even if the masks will then be slightly inaccurate?

Note that I slightly changed the train.py file, but nothing related to that error. I might try to create a minimal example for reproducing this if necessary.

**Comment by ppwwyyxx** [comment]
The comment is unrelated. Your changes probably cause the ereor.

**Comment by ppwwyyxx** [comment]
The comment is unrelated. Your changes probably cause the ereor.

**Comment by ppwwyyxx** [comment]
Oh this may be a bug (which rarely happens). Let me think about it.

**Comment by pvoigtlaender** [comment]
It indeed only rarely happened, I was processing a lot of images and it only crashed after around 200.
Please let me know, if you get further insights on this.

**Comment by ppwwyyxx** [comment]
Could you post your changes?

**Comment by ppwwyyxx** [comment]
```diff
--- i/examples/FasterRCNN/eval.py
+++ w/examples/FasterRCNN/eval.py
@@ -15,7 +15,7 @@ from pycocotools.cocoeval import COCOeval
 import pycocotools.mask as cocomask
 
 from coco import COCOMeta
-from common import CustomResize
+from common import CustomResize, clip_boxes
 import config
 
 DetectionResult = namedtuple(
@@ -75,6 +75,7 @@ def detect_one_image(img, model_func):
     scale = (resized_img.shape[0] * 1.0 / img.shape[0] + resized_img.shape[1] * 1.0 / img.shape[1]) / 2
     boxes, probs, labels, *masks = model_func(resized_img)
     boxes = boxes / scale
+    boxes = clip_boxes(boxes, orig_shape)
 
     if masks:
         # has mask
```
Maybe this will fix it.

**Comment by pvoigtlaender** [comment]
The code changes should really not be related, it is mainly just logic on which images to load and where to store the results.
What I did change, though is the config, I set
```
TEST_PRE_NMS_TOPK = 15000
TEST_POST_NMS_TOPK = 1000
FASTRCNN_NMS_THRESH = 0.8
RESULT_SCORE_THRESH = 0.0
RESULTS_PER_IM = 1000
```

I'm currently testing on images from KITTI

**Comment by pvoigtlaender** [comment]
Thanks for your patch! I can verify, that the error does not occur anymore!

**Comment by ppwwyyxx** [comment]
OK. Maybe it's just the dataset difference that makes it happen.
