### ISSUE TITLE
tensorpack batch size scalable

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#589]
In image segmentation, single-GPU batch size may be too small due to GPU memory restricts. multi-GPU training is important in segmentation, in my baseline, it can bring 3% extra gain in mIoU .

for example, Cityscapes dataset, ResNet101 model, input image size 1024*2048, so the max batch size can only be 1 on Titan XP(12 GB) GPU. If I want to train it on 4 GPUs, the max Batch size  theoretically should be 4(1 per GPU), but the fact is even batch_size=4 or 3 or 2 is not ok, it can only be 1.

thus, Cityscapes(image size 1024*2048,resnet101):
1GPU,batch size:1
4GPU,batch size:1(bad scalability)

other try on Cityscapes(image size 768,resnet101):
1GPU,batch size: 5
4GPU,batch size: 8(bad scalability)

same phenomenon on PascalVOC(image size 321, resnet101)
1GPU,batch size:10
4GPU, batch size: 28(bad scalability)

To some extent, this may have nothing to do with tensorpack, I will appreciate, if you can give some insight about this.

**Comment by ppwwyyxx** [comment]
Are you sure were you setting per-gpu batch size or total batch size?

**Comment by dongzhuoyao** [comment]
maybe my implementation is wrong, I contrast with your imagenet-resnet.py.

TOTAL_BATCH_SIZE=256,

in your implementations, it seems that no matter how many GPUS, the total batch size is always 256.

I doubt:  since 1-gpu can hold 256, if you have 4-GPU, why not set batch size as 1024. in your implementation, if 4-gpu, single-gpu batch size is 256/4=64.

**Comment by ppwwyyxx** [comment]
That's just my choice in the model and you can certainly use different strategies in your code.

>  If I want to train it on 4 GPUs, the max Batch size theoretically should be 4(1 per GPU), but the fact is even batch_size=4 or 3 or 2 is not ok

If what you're talking about is total batch size, how can you possibly train a total batch of 3 on 4 GPUs? I can't imagine how this can be implemented in tensorpack.

**Comment by ppwwyyxx** [comment]
If you haven't read: http://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html#multigpu-trainers

**Comment by dongzhuoyao** [comment]
my writing about multi-gpu training is wrong, now fixed, thank you
