### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by theKase** [ppwwyyxx/tensorpack#59]
@ppwwyyxx

We you run something like "./train-atari.py --env Breakout-v0", where does the trained model get placed? It looks like it should be in train_log, but it isn't. Also, does the trained model become available only after training is complete or can you have partially trained models at specific epochs?

**Comment by ppwwyyxx** [comment]
It should be in `train_log/train-atari`. It is saved every 6000 iterations. On a decent machine it should run 6~8 iterations/s.

**Comment by theKase** [comment]
What is the name of the file? I dont see any "*.tfmodel" file. The directory contains the following two files:

events.out.tfevents.1480812949.[Name of machine].local
log.log

Do we have to pass the file path somewhere in the args?

**Comment by ppwwyyxx** [comment]
It should be something like "model-xxx". There won't be `.tfmodel` suffix.
The model will be saved after each epoch.
