### ISSUE TITLE
How to use tf.add_check_numerics_ops()

### ISSUE THREAD

**Issue by junhaenglee** [ppwwyyxx/tensorpack#591]
I got nans and inf during training. I would like to use tf.add_check_numerics_ops() to detect the location caused it in the first place. But, I don't know where I should put the code. 
What is the best way to add tf.add_check_numerics_ops() in tensorpack?

**Comment by ppwwyyxx** [comment]
Maybe 
```
callbacks=[
RunOp(lambda: tf.add_check_numerics_ops(), run_before=False, run_as_trigger=False, run_step=True),
 ...]`.

**Comment by junhaenglee** [comment]
Could yo elaborate a little bit more?
Can I add the code somewhere under _build_graph() as follows?

class Model(ModelDesc):
    def _build_graph(self, inputs):
       ...
      callbacks=[
RunOp(lambda: tf.add_check_numerics_ops(), run_before=False, run_as_trigger=False, run_step=True),
 ...]`.
       ...

**Comment by dongzhuoyao** [comment]
hi, you can check any example in tensorpack, such as [resnet](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L81).

just follow them as convention.

**Comment by junhaenglee** [comment]
Thank you very much.

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you still have questions.
