### ISSUE TITLE
ImportError: No module named 'tensorpack.dataflow.prefetch

### ISSUE THREAD

**Issue by amcinto** [ppwwyyxx/tensorpack#595]
Bug Reports/Feature Requests/Usage Questions Only:

Any unexpected problems with code: PLEASE always include
1. I am running a custom project in anaconda and I was able to clone and install the tensorpack
The issue I am having is that when I run the command `python train.py` I get the import error in the title.
2. `from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from data_feeder import get_ilsvrc_data_alexnet, get_mnist_data, DataFlowToQueue
  File "/home/local/TECHNICALABS/amcintosh/anaconda3/envs/tensorflow/tf-lcnn/data_feeder.py", line 19, in <module>
    from tensorpack.dataflow.prefetch import PrefetchData
ImportError: No module named 'tensorpack.dataflow.prefetch'`

3. I wasn't expecting any tensorpack issues because I was able to install two months ago but now I am having trouble
4. Your environment (1.4, 6, none as of right now but TF is configured for GPU usage), if it matters. 
I am a novice but I tried to export the absolute path to the tensorpack and that didn't solve anything
Any help would be appreciated Thanks in advance!

**Comment by ppwwyyxx** [comment]
I expect people to use `from tensorpack.dataflow import PrefetchData`. The name `prefetch` is actually quite arbitrary, and recently was changed.

**Comment by amcinto** [comment]
Thanks for getting back so quickly! What was it recently changed to?

**Comment by ppwwyyxx** [comment]
It was changed to `parallel` but I don't think you should use it either. You can `from tensorpack.dataflow import PrefetchData`

**Comment by amcinto** [comment]
Okay thanks! I’ll give that a shot and let you know what happens. Have a great day!

**Comment by amcinto** [comment]
Just wanted to let you know that it does in fact work! Thanks
