### ISSUE TITLE
Loading a pretrained model and manipulating its parameters

### ISSUE THREAD

**Issue by realwecan** [ppwwyyxx/tensorpack#597]
I am new to tensorpack, and wonder if it is possible to load a pretrained model and then manipulate some of its parameters. For example, is it possible to load parameters of the last FC layer of a resnet model into a numpy array, change its values manually (and potentially its shape as well, like removing some object classes), and then put it back into the model?

This is different to standard transfer learning I think, which re-trains the changed layers from scratch.

Thanks!

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/en/latest/tutorial/save-load.html the tutorial has everything needed to do this. `DictRestore` allows you to load an arbitrary dict of values .
