### ISSUE TITLE
Question about the number of steps per epoch

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#598]
When I run the shuffle-net example, I removed the "steps_per_epoch=5000" setting, and let it calculate steps_per_epoch by itself. I set the batch size as 128. When I use single GPU, each epoch has 10009 steps. When I use two GPUs, each epoch has 20018 steps. When using multiple GPUs, each batch is equally divided and allocated to each GPU. So in this case, the concept of one step is not a whole batch of samples in two GPUs, but only 64 samples in one GPU?

**Comment by ppwwyyxx** [comment]
The default value for `steps_per_epoch` is `dataset_train.size()`, which is independent of how many gpus you use.
That's why you should not remove the line.

**Comment by JesseYang** [comment]
Thanks. So when using multiple GPUs, the steps_per_epoch should always be set manually?

**Comment by ppwwyyxx** [comment]
It depends on what do you mean by an "epoch", a "step", and how the input data is defined, etc, so there is not an answer to that.
But usually the default value will make one epoch larger than what most people would expect.
