### ISSUE TITLE
Question about the backward of the quantize function

### ISSUE THREAD

**Issue by hitlgy** [ppwwyyxx/tensorpack#599]
Usage Questions Only:
I have a question about quantize function in the dorefa paper.

![_20180118155814](https://user-images.githubusercontent.com/19725474/35086679-6ea44784-fc68-11e7-981d-03cd69819feb.png)

I  have confused to the process about find out the derivative r0/ri

**Comment by ppwwyyxx** [comment]
It's chain rule. Because r_o is a function of r_i.

**Comment by ppwwyyxx** [comment]
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/OgGd7sfu1bE has more discussion about this topic. Github issue of a deep learning library is not a proper place for discussing a paper, even though I happen to be one of the authors.
