### ISSUE TITLE
Intresting work, hope you can write more README, so that we can contribute

### ISSUE THREAD

**Issue by pangolulu** [ppwwyyxx/tensorpack#6]

**Comment by ppwwyyxx** [comment]
Thanks a lot for your interest. Currently the project is usable but still in a very immature stage: there are a lot of design choices to be made, and some performance issues to be solved. APIs might change, and distributed training are not even on the calendar (probably will require more refactoring). These are why it's probably not a good time to write documentations.

Despite that, the `dataflow` module and the `model` module are mostly self-contained and reusable components that probably won't change a lot in the future. I may start working on some documentation on these parts.

**Comment by pangolulu** [comment]
Thanks for replying me. What you said is true and reasonable. I will concentrate on the self-contained parts now and get my hands dirty.
