### ISSUE TITLE
do you have ResNet101-SE model weight?

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#600]
if [http://models.tensorpack.com/ResNet/](http://models.tensorpack.com/ResNet/) can include it , that will be great.

 my gpu resource is limited, no resource and time to train better basic model. 😢

**Comment by ppwwyyxx** [comment]
It's there.

**Comment by dongzhuoyao** [comment]
sorry, typo.. 

I really want is ResNet101-SE.. 😞

**Comment by ppwwyyxx** [comment]
I don't have such model.

**Comment by HiKapok** [comment]
Hi, here is one TensorFlow SE-ResNet with pre-trained weights converted from Caffe. You can try [this](https://github.com/HiKapok/TF_Se_ResNe_t) if you are interested in.
