### ISSUE TITLE
tensorpack/tensorflow incompatibility

### ISSUE THREAD

**Issue by giampierosalvi** [ppwwyyxx/tensorpack#601]
Hi,
I was trying to run the CTC TIMIT example, and I kept on receiving segmentation fault violations. After some digging, I realized that this is due to an incompatibility between tansorpack and tensorflow. If I install both and run "import tensorpack.dataflow", for example, this is enough to get core dumped. (both are required by the train-timit.py script).

Is there a specific version of tensorflow that is known to work with tensorpack?

Thank you!
Giampiero

Here are my settings and what I did:
Ubuntu 16.04, Anaconda2-5.0.1-Linux-x86_64.sh

conda create -n tensorpack python=2.7
source activate tensorpack
pip install -U git+https://github.com/ppwwyyxx/tensorpack.git

python  -c "import tensorpack.dataflow"
_works ok_

pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.1-cp27-none-linux_x86_64.whl

python  -c "import tensorpack.dataflow"
_segmentation fault_

**Comment by giampierosalvi** [comment]
update: running
`conda install tensorflow-gpu`
instead of the above pip install, seems to work.

**Comment by ppwwyyxx** [comment]
This seems to be a opencv-tensorflow incompatibility. Certain prebuilt opencv & tensorflow don't work well together.

**Comment by ppwwyyxx** [comment]
Try using `import tensorflow` as the first line in your program. Most of the times it solves the problem.
