### ISSUE TITLE
SyncMultiGPUTrainerReplicated-shared GPUs hang

### ISSUE THREAD

**Issue by arrowrowe** [ppwwyyxx/tensorpack#605]
In short: two tensorpack processes, both using `SyncMultiGPUTrainerReplicated` and two same GPUs, hang.

To reproduce:
1. Choose an example using `SyncMultiGPUTrainerReplicated`, e.g. `tensorpack/examples/ResNet/imagenet-resnet.py`.
    To make GPUs sharable, prevent one process from consuming all memory by appending the following snippet at the top of the script:
    ```python
    import tensorflow as tf
    tmp_config = tf.ConfigProto()
    tmp_config.gpu_options.allow_growth = True
    tmp_session = tf.Session(config=tmp_config)
    ```
2. Run the script twice.
    2.a. Run once:
    ```bash
    gpu=0,1; CUDA_VISIBLE_DEVICES=${gpu} python imagenet-resnet.py --gpu ${gpu} --fake
    ```
    2.b. Wait until the first process completes a few epochs, then run the same line again.

    As soon as the second process starts its training, both processes hang, making it impossible to kill any of them or free the GPUs' memory and util, without any error report. The only solution is to restart the server.

Don't know if `SyncMultiGPUTrainerReplicated` or the `allow_growth` snippet is misused in the case or it's a bug.

Thanks for any help!

**Comment by ppwwyyxx** [comment]
Does `SyncMultiGPUTrainerParameterServer` work this way?
I think this is a NCCL or tensorflow issue.

**Comment by arrowrowe** [comment]
1. `SyncMultiGPUTrainerParameterServer` works fine.
1. Agree. Will look into this later.

Close for now. Will reopen if new clues found.
Thanks for the reply! :p @ppwwyyxx

**Comment by ppwwyyxx** [comment]
Looks like a NCCL bug: https://discuss.pytorch.org/t/nn-dataparallel-model-cuda-hangs/1204/9
