### ISSUE TITLE
AttributeError: '_FireResetEnv' object has no attribute 'ale'

### ISSUE THREAD

**Issue by ai2010** [ppwwyyxx/tensorpack#609]
I'm using the a3c example so by default the environment is loaded from FrameStack and LimitLength classes. 

I'm playing tensorpack with monezuma revenge and I would like to check each step if the agent is dead or not so I check the lives with self.env.env.ale.lives() from the _step function within FrameStack and LimitLength classes. I got the error:

'File "/home/dstefanidis/atari_wrapper.py", line 229, in _reset
    ob = self.env.reset()
  File "/home/dstefanidis/.virtualenvs/wingman/lib/python3.5/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/home/dstefanidis/atari_wrapper.py", line 61, in _reset
    self.agent.lives = self.env.env.ale.lives()
AttributeError: '_FireResetEnv' object has no attribute 'ale''

and (not sure if related) the code can really run since it's stuck at 'Start Epoch 1':
[0124 18:04:06 @base.py:182] Initializing the session ...
[0124 18:04:06 @base.py:189] Graph Finalized.
[0124 18:04:08 @concurrency.py:36] Starting SimulatorMaster ...
[0124 18:04:08 @base.py:209] Start Epoch 1 ...

configuration:
gpu:  Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
python 3.5.2
tensorflow: 1.4.0
gym: 0.9.4

As far as I understand it's an issue related to 'env.unwrapped'

**Comment by ppwwyyxx** [comment]
There should not be "ale" inside env.

A3C is based on gym and to get lives in gym you need to `print(info)`.
