### ISSUE TITLE
A doubt about regularizer in  mnist-tfslim

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#611]
[https://github.com/ppwwyyxx/tensorpack/blob/master/examples/mnist-tfslim.py](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/mnist-tfslim.py)

it seems that the regularizer in [L37](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/mnist-tfslim.py#L37) doesn't take effect.  because the the code doesn't care about tf.GraphKeys.REGULARIZATION_LOSSES  like [this](https://github.com/NanqingD/DeepLabV3-Tensorflow/blob/master/train_voc12.py#L113).

**Comment by ppwwyyxx** [comment]
It's taken care by this line: https://github.com/ppwwyyxx/tensorpack/blob/b2a396e5ddb8591c8bd7ff813a73d38ed271bd7e/tensorpack/graph_builder/model_desc.py#L142
