### ISSUE TITLE
Rookie Usage Question: Fail to import Tensorpack Class in example code with PyCharm

### ISSUE THREAD

**Issue by JasonHanG** [ppwwyyxx/tensorpack#612]
I'm trying to learn the Mask-RCNN implementation  example in tensorpack，which I think is the best opensource tensorflow based implementation so far.
I'm using PyCharm-pro-2016.3.2 as my IDE to read the example code.
Latest  tensorpack installed using:
sudo -H  pip3 install -U git+https://github.com/ppwwyyxx/tensorpack.git.
After that, I clone the tensorpack repo  then open tensorpack/examples/FasterRCNN folder with PyCharm. However, when I open any file contains tensorpack class importing code( e.g. models.py/train.py...) ,those default tensorpack class importing code fails, I've found a way to work but it seems not the right thing to do. Here is the screenshot(please read comments in the read box) :
![import fail](https://user-images.githubusercontent.com/22115196/35468966-f0f6e77a-0364-11e8-8549-7f51b6a13714.png)
Besides ,when I use jupyter-notebook to run the same code, it turned out to be works just fine, which confused me more.
<img width="1180" alt="jupyter-tensorpack" src="https://user-images.githubusercontent.com/22115196/35468990-f47ffaa2-0365-11e8-9797-fcfb50bc2e70.png">

I know this is more like a IDE usage question or a basic python project importing question rather than a package using question .However, I failed finding an answer elsewhere and thought anyone here maybe encountered the same problem. 
Any help appreciated. Thanks ahead~

**Comment by ppwwyyxx** [comment]
Yes this looks like an IDE usage question. I have no knowledge of pycharm so I'm unable to help.
I guess there is some place in pycharm you can set paths to some external libraries.

As a hack, you can always do `sys.path.insert(0, '/path/to/cloned/tensorpack')` to make import succeed.

**Comment by dongzhuoyao** [comment]
@JasonHanG hi, I current use pycharm, this phenomenon is normal, just dont need to care about it. it really import it, just pycharm doesn't recognise it.

**Comment by JasonHanG** [comment]
Oh, I see!
Thanks for your information.
But the red wavy lines are really annoying.... ^_^
I'm explicitly import every class just for the time being, which works ok.
Maybe I shouldn't waste too much time on this little inconvinent ,It's time to move on.

**Comment by ppwwyyxx** [comment]
This was probably fixed in #656, btw.
