### ISSUE TITLE
imgaug.Saturation

### ISSUE THREAD

**Issue by dpkingma** [ppwwyyxx/tensorpack#614]
1. What I did: Use `fbresnet_augmentor` in `tensorpack/examples/Inception/imagenet_utils.py`.

2. What I observed: when using the `fbresnet_augmentor` in the code, some augmented images contain overly brightly colored artifacts:

![with_imgaug_saturation](https://user-images.githubusercontent.com/2432243/35475299-b5a259e8-0350-11e8-89ec-821dd006a2d2.png)

This is unexpected to me, since the augmented data should resemble natural images.

When I comment out the line `imgaug.Saturation(0.4, rgb=False),` in `fbresnet_augmentor`, then there are no such artifacts:
![without_imgaug_saturation](https://user-images.githubusercontent.com/2432243/35475300-b5b49e78-0350-11e8-93ab-894e8ee5c38c.png)

There might be a problem with the `imgaug.Saturation()` function.

**Comment by ppwwyyxx** [comment]
Indeed! I think it's a uint8 overflow. After the saturation changes, values could go out of 255.

**Comment by dpkingma** [comment]
Yeah, looks like uint8 overflow/underflow.

**Comment by ppwwyyxx** [comment]
Pushed a fix. Clipping was used in most other augmentors but somehow saturation was missing.

**Comment by dpkingma** [comment]
Awesome! Thanks for the quick fix!
