### ISSUE TITLE
running error on DoReFa-Net

### ISSUE THREAD

**Issue by deepsemantic** [ppwwyyxx/tensorpack#62]
Hi, thanks for sharing the codes, I am trying experiment on SVHN dataset with provided "svhn-digit-dorefa.py" in DoReFa-Net.  However, I got following error output. Could you help me out of this? Thanks in advance!

`[1207 10:01:00 @_common.py:72] conv6 input: [None, 5, 5, 128]
[1207 10:01:00 @svhn-digit-dorefa.py:60] Binarizing weight conv6/W
[1207 10:01:00 @_common.py:80] conv6 output: [None, 1, 1, 512]
[1207 10:01:01 @_common.py:72] fc1 input: [None, 1, 1, 512]
[1207 10:01:01 @_common.py:80] fc1 output: [None, 10]
[1207 10:01:01 @regularize.py:17] Apply regularizer for fc1/W:0
WARNING:tensorflow:From /home/xxx/workspace3/tensorpack/tensorpack/tfutils/summary.py:66 in perform.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /home/xxx/workspace3/tensorpack/tensorpack/tfutils/summary.py:75 in perform.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /home/xxx/workspace3/tensorpack/tensorpack/tfutils/summary.py:66 in perform.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.

Traceback (most recent call last):
  File "examples/DoReFa-Net/svhn-digit-dorefa.py", line 190, in <module>
    QueueInputTrainer(config).train()
  File "/home/xxx/workspace3/tensorpack/tensorpack/train/base.py", line 58, in train
    self.setup()
  File "/home/xxx/workspace3/tensorpack/tensorpack/train/base.py", line 103, in setup
    self._setup()
  File "/home/xxx/workspace3/tensorpack/tensorpack/train/queue.py", line 44, in _setup
    cost, grads = self._get_cost_and_grad()
  File "/home/xxx/workspace3/tensorpack/tensorpack/train/trainer.py", line 138, in _get_cost_and_grad
    cost_var, gate_gradients=0)
  File "/home/xxx/workspace3/tensorflow/_python_build/tensorflow/python/training/optimizer.py", line 335, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/xxx/workspace3/tensorflow/_python_build/tensorflow/python/ops/gradients_impl.py", line 459, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'Round_5' (op type: Round)
`

**Comment by ppwwyyxx** [comment]
Thanks. This is a bug of tensorflow: https://github.com/tensorflow/tensorflow/issues/5888
You can use an earlier version (0.11rc2 seems to work, but I'm not sure).

**Comment by ppwwyyxx** [comment]
You can also change `tf.round(xxx)` in `dorefa.py` to `tf.floor(xxx + 0.5)`

**Comment by deepsemantic** [comment]
Hi, thanks for info and quick reply, I will try it later. I have another question regarding the implementation. According to what I understood from your paper, it needs to change the original convolution operation to bitwise operation in e.q (3) in your paper. It would be very interesting to know your implementation of this in forward and backward pass. Could you let me know where can I find the pieces of code in your implementation. Thanks again!

**Comment by ppwwyyxx** [comment]
As in the readme:
```
We're not planning to release those runtime bit-op libraries for now. In this repo, bit operations are run in float32.
```

**Comment by deepsemantic** [comment]
It works, thanks!

**Comment by deepsemantic** [comment]
So, the examples you provided still use original conv-operation, not bit-op?

**Comment by ppwwyyxx** [comment]
Yes. This code was just meant to be a proof of effectiveness of our proposed quantization method.

**Comment by deepsemantic** [comment]
I see, thanks!
