### ISSUE TITLE
validation calculation

### ISSUE THREAD

**Issue by MrWanter** [ppwwyyxx/tensorpack#623]
Hi! When I use `3` gpu, the validation bar is `xxx/589`, when use `4` gpu, it is `xxx/782`, I thought validation should be same as training, that is feed as batch of `256` and split equally to each gpu, so it should always be around `xxx/196`, where am I wrong?

**Comment by ppwwyyxx** [comment]
It does not split a batch. Nor does training. Validation feeds 1 data points to each GPU, and update the progress bar by #GPUS. Training feeds 1 data point to each GPU and update the progress bar by 1.

**Comment by MrWanter** [comment]
Am I right that each data point contain `TOTAL_BATCH_SIZE / nr_tower` images? so in total, all gpus together compute `TOTAL_BATCH_SIZE` of images?

**Comment by ppwwyyxx** [comment]
Depend on how you write the code.
If you're talking about shufflenet example, it's in the code: 

https://github.com/ppwwyyxx/tensorpack/blob/c14d14961fee17116f062680624a04946fca7890/examples/ShuffleNet/shufflenet.py#L146-L147

**Comment by MrWanter** [comment]
Thanks for your quick response, my confusion is that for training with `3` gpu and `4` gpu, training progress bar is `xxx/5000`, but validation bar for `3` gpu is `xxx/589`, while for `4` gpu is `xxx/782`, not the same, for training, `256` batch times `5000` is just `128` million, but what about validation?

**Comment by ppwwyyxx** [comment]
For validation, 64 * 782 ~= 50000

**Comment by MrWanter** [comment]
I see, `782*(256/4) ~= 589*(256/3) ~=50000`, but why not make it the same like training bar, as `(782/4)*256 ~= (589/3)*256 ~= (196)*256`

**Comment by ppwwyyxx** [comment]
Because no one can guarantee that 782 % #GPU == 0. 
For training this is not a problem. For validation you want to evaluate on precisely the whole dataset.

**Comment by MrWanter** [comment]
I see:)
