### ISSUE TITLE
Training error drop down quickly when merely change from using 3 gpu to using 4 gpu

### ISSUE THREAD

**Issue by MrWanter** [ppwwyyxx/tensorpack#624]
I tried your shufflenet example, when I use `3` gpu, it seems training is normal, training and validation drops roughly with same pace, but when merely change to `4` gpu training, the training error drop dramatically(top `1` error, `10` epoches drop to `0.3-0.4`), while validation seems drop very slowly(only to `0.9`), I'm really confused, could you help? Thanks

**Comment by MrWanter** [comment]
by the way, what is the meaning of `TENSORPACK_DATASET` ?

**Comment by MrWanter** [comment]
I suspect may be the training `lmdb` file is not correct, would it be wrong if I generate the `lmdb` file with 
```
class BinaryILSVRC12(dataset.ILSVRC12Files):
    def get_data(self):
        for fname, label in super(BinaryILSVRC12, self).get_data():
            with open(fname, 'rb') as f:
                jpeg = f.read()
            jpeg = np.asarray(bytearray(jpeg), dtype='uint8')
            yield [jpeg, label]

ds0 = BinaryILSVRC12('/temp/wangtao/ILSVRC/Data/CLS-LOC/', 'train', shuffle = False)
ds1 = PrefetchDataZMQ(ds0, nr_proc=1)

dftools.dump_dataflow_to_lmdb(ds1, '/temp/wangtao/ILSVRC-train.lmdb')
```
I dont remember if my correct generate was 
`ds0 = BinaryILSVRC12('/temp/wangtao/ILSVRC/Data/CLS-LOC/', 'train', shuffle = True)`

**Comment by ppwwyyxx** [comment]
For any unexpected problems, please follow the issue template.

TENSORPACK_DATASET is the default path to store downloaded data.

`shuffle=False` is correct to generate LMDB.

**Comment by MrWanter** [comment]
after regenerating the training `lmdb`, the problem solved, but still not clean why it happened
