### ISSUE TITLE
How to understand quantize_k in e.q.(5)

### ISSUE THREAD

**Issue by deepsemantic** [ppwwyyxx/tensorpack#63]
Hi sorry for bothering. I have some difficulties in understanding quantize_k in e.q.(5). 
![image](https://cloud.githubusercontent.com/assets/13123649/20960270/95a4101c-bc9a-11e6-89db-2bdce4102d99.png)

The paper says, this function quantizes a real number input r_i to k-bit number output. To my understanding, for example, if k=2, r_i=0.002 should be quantized to r_o that looks like 00 or 01 that contains two bits. As I know, in XNOR-Net, real weight e.g. x=0.002 will be quantized to 1-bit number x=1. However, I get the output of original and quantized weights in the example of "svhn-digit-dorefa.py", found that both of them are float32 format number. I am not sure if I understand it correctly or not. 
original weights:
![image](https://cloud.githubusercontent.com/assets/13123649/20960577/126e18f8-bc9c-11e6-81e2-fcee8b7b0c0b.png)
quantized weights:
![image](https://cloud.githubusercontent.com/assets/13123649/20960594/2c7f85ec-bc9c-11e6-9208-878529bf1b9f.png)
I use following code to get the value of those weights:
![image](https://cloud.githubusercontent.com/assets/13123649/20960743/d1d2ed36-bc9c-11e6-81cd-d04b5be82ff2.png)

Could you please help me to understand this, thanks in advance.

**Comment by ppwwyyxx** [comment]
If you look at the code of `fw`, it uses binary-weight-network which includes a scaling factor on the binary values. Similar technique is also used in XNOR-Net.

**Comment by deepsemantic** [comment]
Yes, I looked the code and understood when bitW=1 and bitW=32, but I am still wondering how the output looks like when bitW=2, i.e. quantize(x=0.002, k=2)? Is it still float32 number? or 2-bit integer number consist of 0 and 1? Thanks for your time!

**Comment by ppwwyyxx** [comment]
quantize() with 2 bit would return values in {0,1/3,2/3,1}.

**Comment by jacky4323** [comment]
Hi  @ppwwyyxx .

Sorry , I confused about  2 bit would return values in {0,1/3,2/3,1}.
in readme file , I saw the text below , However in hardware implementation it can't use 2 bits two represent 1/3,2/3(binary format can't use 2 bits to represent)


take 2.34669849e-01 for example:
using 2^k-1 :
weight_bit=2 the value is equal to 0.3333333,but actually 0.33 can't use two bits to represent
using 2^k :
weight_bit=2 the value is equal to 0.25, it can use two bits (0.11) to represent
So why don't use 2^k? Did I make a mistake? thanks.


![image](https://user-images.githubusercontent.com/31586393/46425618-b877f780-c76e-11e8-8a70-95472ffc069a.png)

**Comment by ppwwyyxx** [comment]
k bits can represent 2^k different numbers.
2 bits can represent 4 different numbers.
And we choose those numbers to be {0, 1/3, 2/3, 1}.
