### ISSUE TITLE
Is there a bug in FasterRCNN's data augmentation?

### ISSUE THREAD

**Issue by LandyGuo** [ppwwyyxx/tensorpack#630]
Bug Reports/Usage Questions Only:

1. What you did:
        I noticed that data augmentation  in examples/FasterRCNN [https://github.com/ppwwyyxx/tensorpack/blob/0.8.1/examples/FasterRCNN/data.py#L214](url) will cause boxes' coords as negative numbers, is there a need to clip the coords?
	+ If you're using examples:
		+ What's the command you run: 
 `   
 python data.py
`
		+ Have you made and changes to code? Post them if any:

`
       
        boxes_original = boxes
        # augmentation:
        im, params = aug.augment_return_params(im)
        points = box_to_point8(boxes)
        points = aug.augment_coords(points, params)
        boxes = point8_to_box(points)

        if  np.any(boxes<0):
            print("bboxes:",boxes)
            print("before bboxes:",boxes_original)
`

**Comment by ppwwyyxx** [comment]
Any of those values < 0 seem to be caused by floating point rounding.
And since boxes are used for regression, I don't think it will be an issue.
