### ISSUE TITLE
How to train Mask RCNN in own dataset?

### ISSUE THREAD

**Issue by John1231983** [ppwwyyxx/tensorpack#632]
I knew your MaskRCNN when I read the matterport's implementation. Very impressive to your performance. I would like to use it to train in my custom dataset that looks likes: one raw image and `N` label images, in which each label image stored a segmented image without bounding box. I have used  matterport's example to train and run it successful. However, I am new in your code. Could you tell me how can I train my dataset in your code? Thanks so much

**Comment by ppwwyyxx** [comment]
Mentioned in https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/NOTES.md.

**Comment by John1231983** [comment]
Thank you. I have read it. But the importance is that my dataset does not follow the coco style, it means no bounding box available, only masks for each object. It likes shape example in matterport's implementation. Could you tell me what should I do to make my data loader?

**Comment by ppwwyyxx** [comment]
You can compute a bounding box from segmentation mask.

**Comment by John1231983** [comment]
Do I need convert my dataset to coco annotation format to use your code?

**Comment by ppwwyyxx** [comment]
> replace COCODetection.load_many in data.py by your own loader.

It can be any python code that loads data from any format. As long as in the end it returns the same data structure as documented by `COCODetection.load`:
https://github.com/ppwwyyxx/tensorpack/blob/5a9d136251109b2dd981f174efa2cca9d38d5af6/examples/FasterRCNN/coco.py#L85-L88

I forgot to add "segmentation masks" in the above comment, btw.

**Comment by John1231983** [comment]
Thanks so much. I am reading your guide and let you know when it completed. I have one more question about your implementation. As you know, the Batch Norm training is important for segmentation and detection. The paper used the batch size of 16. I found that you used the batch size of 256. During the training, do you consider to train the Batch Norm statistic? In my opinion, it looks that you did not train BN parameters

**Comment by ppwwyyxx** [comment]
My implementation follows the paper. You have misread it somehow.

**Comment by John1231983** [comment]
Sorrry, I forget the lines that you have mentioned
>We only support single image per GPU.
Because of (3), BatchNorm statistics are not supposed to be updated during fine-tuning. This specific kind of BatchNorm will need my kernel which is included since TF 1.4. If using an earlier version of TF, it will be either slow or wrong

It means that the BN statistic will not learn during training. On other hands, it is frozen. Am I right?

**Comment by ppwwyyxx** [comment]
Yes.

**Comment by YanWang2014** [comment]
I am also trying to use own data for training. Although it's not difficult to provide masks etc to train.py (by modify data.py and coco.py),  I see many dependencies on pycocotools in eval.py, which makes further work required to make the code run on other dataset

**Comment by ppwwyyxx** [comment]
Of course. In addition to training on your own dataset, If you also want to evaluate on your dataset, you need to have data loader for your evaluation set and implement the evaluation metrics.

**Comment by John1231983** [comment]
Hi ppwwppxx, could you tell me any reason why your performance (32.3%) is better than keras based (29.5%) using same resnet-50?

**Comment by ppwwyyxx** [comment]
I'm not familiar with other implementations except for Detectron so I don't know what to answer.
If you're talking about matterport implementation, it has a lot of differences from the original paper, some of which are mentioned in their readme. Given all those differences it's hard to say what contribute to the suboptimal performance.

**Comment by John1231983** [comment]
Yes, I am talking about matterport implementation. Actually, I am using your code and matterport to work with DSB2018 dataset challence. I was successful to run it with matterport but I was not successful with your project. My dataset is not similar coco format ( only contains raw image and its masks). In matterport, I based on example of training shape  https://github.com/matterport/Mask_RCNN/blob/master/train_shapes.ipynb
I am very happy if you can make an example like that, because it may be helpful to work in difference dataset. Thanks

**Comment by ppwwyyxx** [comment]
Would be nice to train on other datasets. But I don't have time to do this in the near future.

**Comment by letuantang** [comment]
@John1231983 can I ask you some question? you said that you have successfully run the matterpot code on your own data set and mentioned the link to train_shapes.ipynb? Can you explain more detail about it? It's mean that base on the train_shapes.ipynb you edit the code to train for your own dataset (to recognize an object like a clock and do the segmentation, for example). Is it right? Or you just successfully run the code on train_shapes.ipynb on your computer? I also want to run the Mask RCNN on my own dataset but I don't know exactly what need I do with my trainning images and what format it is or just put the raw image inside. I'm still focusing on this point. Thanks

**Comment by cpoptic** [comment]
@John1231983 @letuantang   Facebook AI Research released Maskrcnn_benchmark, it's allegedly a much faster version of Matterport's Mask_RCNN.  Would recommend trying that out:  https://github.com/facebookresearch/maskrcnn-benchmark

**Comment by luxedo** [comment]
I'm trying to train in my own data that have the COCO format but only two classes, but I'm getting the following error:

`ValueError: Trying to load a tensor of shape (80,) into the variable 'maskrcnn/conv/b' whose shape is (2,).`

**Comment by ppwwyyxx** [comment]
You do not want to load the weights that have 80 COCO classes so you need to remove them from the checkpoint (with `np.load` and `np.savez`)

**Comment by luxedo** [comment]
Thanks! I'm training now!

I made the following script to truncate the output layer. 
https://gist.github.com/luxedo/73de2cc4dd69d6ab88aefd0aefabe9a8



> You do not want to load the weights that have 80 COCO classes so you need to remove them from the checkpoint (with `np.load` and `np.savez`). See more at https://tensorpack.readthedocs.io/tutorial/save-load.html

**Comment by Espade** [comment]
Hi, I am facing the same problem(Trying to load a tensor of shape (80,) into the variable 'maskrcnn/conv/b' whose shape is (1,).), but I am still confused about what to do next with np.load and np.savez.

**Comment by ppwwyyxx** [comment]
There is a script above that modifies the weights.
