### ISSUE TITLE
[Bug] ImageFromFile in image.py

### ISSUE THREAD

**Issue by leix28** [ppwwyyxx/tensorpack#636]
```
    def get_data(self):
        if self.shuffle:
            self.rng.shuffle(self.files)
```

ImageFromFile has no attribute `rng`. Should call `self.reset_state()` first.

**Comment by ppwwyyxx** [comment]
You are responsible to call it, as mentioned in the dataflow tutorial.

**Comment by leix28** [comment]
Thank you for your reply. Seems the issue has been fixed in recently.
