### ISSUE TITLE
global step is wrong after restarting

### ISSUE THREAD

**Issue by raingo** [ppwwyyxx/tensorpack#637]
After restarting from previous runs, the global step is wrong.

Here are the logs:

```
Epoch 16 (global_step 542) finished, time:345.80 sec
Model saved to ..... model-542
```

In this experiment, one epoch has `542` steps, so at `16` epochs, the global_step would be `542*16`

This is after restarting from a crashed run.

**Comment by ppwwyyxx** [comment]
It depends on how you want to "restart".
If you want to load an old model you need to pass it to `session_init`. Otherwise the model will be initialized from scratch.

**Comment by raingo** [comment]
I think I've got it. http://tensorpack.readthedocs.io/en/latest/tutorial/save-load.html

Thanks.
