### ISSUE TITLE
How to use get_slot from tensorpack optimizer

### ISSUE THREAD

**Issue by sicnarf1a** [ppwwyyxx/tensorpack#638]
I tried to modify DoReFa-Net to add additional information.
This was motivated by the paper: [TOWARDS THE LIMIT OF NETWORK QUANTIZATION](https://arxiv.org/abs/1612.01543)

As they mentioned, Hessian can be approximated by using some function of the second moment estimates of gradients from the Adam method.

So I coded something like this:
>
    if bitW == 1:
        with G.gradient_override_map({"Sign": "Identity"}):
            name = x.op.name
            trainables = tf.get_collection('trainable_variables')
            for var in trainables:
                if name in str(var):
                    H = tf.stop_gradient(model.get_optimizer().get_slot(var, 'v'))
However I got this error:
> 
    ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.

The problem is that, slot_variables are created during minimize call. In Tensorpack, however, I can only access the get_optimizer function.

How do I apply get_slot in Tensorpack?

**Comment by ppwwyyxx** [comment]
Please first consider how this can be done in pure tensorflow -- if it's possible then it's usually easy to make it work in tensorpack.

Slots depends on minimize call, minimize depends on knowing all the variables in the models, which requires that the model was built already. Therefore you cannot use slots when you're building the model. They way you're approaching seems impossible in tensorflow, so maybe you need to come up with something else first.

**Comment by sicnarf1a** [comment]
Thank you for your prompt reply. Is it possible to use util such as tfutils.optimizer.PostProcessOptimizer to solve this problem?

**Comment by ppwwyyxx** [comment]
Everything is based on tensorflow so you'd better forget tensorpack and come up with a tensorflow-way of doing it first. 
I don't know the paper and not sure what exactly you want to do, so I don't know whether `tfutils.optimizer.PostProcessOptimizer` will help or not.

**Comment by sicnarf1a** [comment]
Thank you. I will try to do it myself and ask again if another issue arises.
Best Regards.
