### ISSUE TITLE
How to do session profiling withtensorpack.train.Trainer?

### ISSUE THREAD

**Issue by yaroslavvb** [ppwwyyxx/tensorpack#643]
Is there a recommended approach/example of dumping timelines when using tensorpack.train.Trainer?

IE, something like ProfilerHook in TensorFlow's MonitoredSession?

**Comment by ppwwyyxx** [comment]
I would use:
```
EnableCallbackIf(
GraphProfiler(dump_tracing=True, dump_event=True), 
lambda self: self.trainer.global_step > 10 and self.trainer.global_step < 20)
```
http://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.GraphProfiler

**Comment by yaroslavvb** [comment]
I see, thanks

Somewhat related, is there an easy way to add to tensorboard duration of each train step? Perhaps it needs adding something like this inside tensorpack somewhere?

        start_time = time.perf_counter()
        grad_values = ....run(train_op)
        duration = time.perf_counter() - start_time
        trainer.monitors.put_scalar('step_time', duration)

**Comment by ppwwyyxx** [comment]
```python
class A(Callback):
    def _before_run(self, _):
        self._start = time.time()

    def _after_run(self, _, _):
        self.trainer.monitors.put_scalar('step_time', time.time() - self._start)
```
Maybe this?
