### ISSUE TITLE
shutil.rmtree instead of os.rmdir on training directory delete

### ISSUE THREAD

**Issue by yaroslavvb** [ppwwyyxx/tensorpack#644]
Right now choosing "d (delete)" does something like `os.rmdir('/efs/runs/yuxin_numpy/1gpu')`

This fails with `OSError: [Errno 39] Directory not empty: '/efs/runs/yuxin_numpy/1gpu'`

It may be better to use 
`shutil.rmtree('/efs/runs/yuxin_numpy/1gpu')` instead

**Comment by ppwwyyxx** [comment]
It's using shutil.rmtree already.
If files are being opened (e.g. by tensorboard) you'll also see this error. I saw this error quite often actually.

**Comment by yaroslavvb** [comment]
ok looks like shutil called rmtree which gives that error

the actual error was due to NFS/EFS misbehaving. It seems impossible to delete NFS directories sometimes, but it seems possible to move them to /efs/trash as a workaround
```
>>> shutil.rmtree('/efs/runs/yuxin_numpy/1gpu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfsb3d9a8ed434c603a00000002'
```

**Comment by yaroslavvb** [comment]
I kept hitting this error, and it turned out to be due to TensorBoard keeping files open. So the trick is to always kill tensorboard before deleting files. Some tricks for future reference

```
The first command to try is a lazy unmount of the EFS volume. Below is the lazy unmount command.

$ umount -l "EFS mount path" 

The command below will find the process that is using the EFS share and output only the process id. Using "ps aux" you can find out more about the process. When ready to kill the process parse the below command to "kill -9".

$ lsof -t "efs/share"

The command below is another way of finding and killing the process in one command. Remove "k" to view the process without killing it. 

$ fuser -km "EFS mount path"
```

**Comment by ppwwyyxx** [comment]
I'm not quite following. Why do you umount it? Do you need to mount it back so you can use it?

**Comment by yaroslavvb** [comment]
The umount has the same error as rm, those recipes help track down who is
keeping files open
