### ISSUE TITLE
fractional values for QueueInput/queue_size

### ISSUE THREAD

**Issue by yaroslavvb** [ppwwyyxx/tensorpack#645]
Running modified version of mnist-conv.py I see following for queue stat

<img width="400" alt="screenshot 2018-02-08 19 20 50" src="https://user-images.githubusercontent.com/23068/36010223-3186daee-0d05-11e8-85da-da35f0cc177a.png">

Looking at event file, here what the actual values were

```
49.99999237060547
49.999996185302734
49.999996185302734
50.000003814697266
49.999996185302734
49.999996185302734
49.99996566772461
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
49.999961853027344
```

**Comment by ppwwyyxx** [comment]
I would like fractional values as well, but queue does not have an API to get its capacity.

**Comment by yaroslavvb** [comment]
I mean the values don't make sense to me, shouldn't they be integers? Are is it being smoothed outside of tensorboard as well?
<img width="381" alt="screenshot 2018-02-08 20 20 57" src="https://user-images.githubusercontent.com/23068/36011645-a376a96a-0d0d-11e8-8e04-3dcddbee1785.png">

**Comment by ppwwyyxx** [comment]
Yes they've been smoothed first inside the graph.
They idea was that summarizing all scalars in every iteration may have overhead (or maybe not), meanwhile summarizing once a while has variance. So they were smoothed before getting into tensorboard.

**Comment by yaroslavvb** [comment]
OK, makes sense. There's slight possibility that frequent event writing will have higher CPU utilization due to  protobuf encoding.  The actual flush interval is pretty long (30 seconds?), so probably it doesn't add much to slowness on the disk side.

I've had to increase the flush interval sometimes for interactive debugging

```
  from tensorflow.python.summary.writer.writer import FileWriter
  old_init = FileWriter.__init__
  def newinit(*args, **kwargs):
    print("Overriding FileWriter flush_secs to 1")
    kwargs['flush_secs']=1
    old_init(*args, **kwargs)
  FileWriter.__init__=newinit

```
