### ISSUE TITLE
adjusting logging frequency?

### ISSUE THREAD

**Issue by yaroslavvb** [ppwwyyxx/tensorpack#648]
What's the proper way of adjusting logging frequency in TensorPack?

IE, I'm noticing that things get logged every 6 steps, with first logged step being step 6. Actually it might be nice to get logs of step 1 no matter what the frequency, to see if the difference is curves is due to random initialization

<img width="561" alt="screenshot 2018-02-09 19 44 11" src="https://user-images.githubusercontent.com/23068/36058319-cef863fc-0dd1-11e8-9276-c9b3fa7e956f.png">

**Comment by ppwwyyxx** [comment]
I don't understand why you see 6. How did you log total_cost? If you did nothing special about it the default interval is every epoch.

**Comment by yaroslavvb** [comment]
http://34.239.138.159:6006/#scalars
All steps are multiples of 6
Some of those runs are just just the default mnist-conv.py example,  https://github.com/ppwwyyxx/tensorpack/blob/master/examples/mnist-convnet.py

**Comment by ppwwyyxx** [comment]
If I ran mnist-convnet.py in examples, all step number are multiples of 468.

**Comment by yaroslavvb** [comment]
Where does 468 come from? Is it set by tensorpack somewhere?

**Comment by yaroslavvb** [comment]
ah, just found http://tensorpack.readthedocs.io/en/latest/tutorial/summary.html?highlight=add_moving_summary, looks like it's every epoch, I was getting "every 6" because I used larger batch size

**Comment by yaroslavvb** [comment]
OK, for reference for myself, I ended up doing below. Couldn't figure out the setting for adjusting flush frequency, will dig into that later if that becomes a problem

    return TrainConfig(
        model=Model(),
        ....
        extra_callbacks=train.DEFAULT_CALLBACKS()+[
          MergeAllSummaries(period=1),
        ],

**Comment by ppwwyyxx** [comment]
To adjust flush frequency:
```
monitors=[TFEventWriter(flush_secs=1), JSONWriter(), ScalarPrinter()]
```
