### ISSUE TITLE
initialize with only subset of variables in the checkpoint

### ISSUE THREAD

**Issue by MrWanter** [ppwwyyxx/tensorpack#649]
we can initiate only subset of variables by `tf.get_collection()`, and then pass in only the variable names that we want to be initialized from the checkpoint file, this require that graph is built before calling `get_collection`
But seems in `tensorpack` Saver is created earlier than graph building by `get_model_loader`:
https://github.com/ppwwyyxx/tensorpack/blob/a5070b4e1cf00ca58e7e3222fa8f56ca2a0b1685/examples/ShuffleNet/shufflenet.py#L216-L217
So how can do it in tensorpack?

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/en/latest/tutorial/save-load.html has everything about this topic.
Three ways you can do this:
1. rename variables in your graph
2. SaverRestore supports the argument to ignore variables
3. convert the model to a dict and remove some variables from it.

**Comment by MrWanter** [comment]
I see

**Comment by omobayode1** [comment]
> http://tensorpack.readthedocs.io/en/latest/tutorial/save-load.html has everything about this topic.
> Three ways you can do this:
> 
> 1. rename variables in your graph
> 2. SaverRestore supports the argument to ignore variables
> 3. convert the model to a dict and remove some variables from it.

I just attempted to do this. I will like to know if the parameters being initialised from the dict will be trained. thanks

**Comment by omobayode1** [comment]
so you mean the parameters will be trained?

**Comment by ppwwyyxx** [comment]
If they will be trained without loading from dict, they will be trained after loaded from dict.

**Comment by omobayode1** [comment]
thanks for your help.
I want to freeze some weight in the model during training.
Please can you give me an idea on how to do it?

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/tutorial/faq.html#how-to-freeze-some-variables-in-training

**Comment by omobayode1** [comment]
Thanks for your response. Does this "tfutils.collection.freeze_collection(keys)" achieve the same purpose?

**Comment by omobayode1** [comment]
I am training the Resnet34 model as explained in the tensorpack githbub repository. I am initialising some of the weight with some weights using Dict. However, I will like to freeze the weight after transferring them and I dont know how to do it?
Please can you give me some ideas?
Thank you.
