### ISSUE TITLE
low iterations/sec

### ISSUE THREAD

**Issue by ahundt** [ppwwyyxx/tensorpack#65]
I've got things running but it appears the iterations/sec are a bit low. I'm running on a GTX 1080 and getting:

```
./train-atari.py --env Breakout-v0 --gpu 0
[...snip...]
|249/6000[06:58<2:22:15, 0.67it/s]
```

The readme mentions I should expect 6 iter/s per gpu. Do you have any troubleshooting recommendations?

**Comment by ppwwyyxx** [comment]
I'm using 1080 and it could get 9it/s.
Could you double-check it is actually using GPU?
You can look at the log to see if it really detects the gpu, or run nvidia-smi while running, to see if gpu is being used.

**Comment by ahundt** [comment]
looks like python is there and I don't think I'm running any other python code so I think that's the tensorpack example:
```               │
+-----------------------------------------------------------------------------+                   │
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |                   │
|-------------------------------+----------------------+----------------------+                   │
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |                   │
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |                   │
|===============================+======================+======================|                   │
|   0  GeForce GTX 1080    Off  | 0000:02:00.0     Off |                  N/A |                   │
| 27%   31C    P8    10W / 180W |    885MiB /  8112MiB |     13%      Default |                   │
+-------------------------------+----------------------+----------------------+                   │
                                                                                                  │
+-----------------------------------------------------------------------------+                   │
| Processes:                                                       GPU Memory |                   │
|  GPU       PID  Type  Process name                               Usage      |                   │
|=============================================================================|                   │
|    0      1758    G   /usr/lib/xorg/Xorg                             452MiB |                   │
|    0      2727    G   compiz                                         132MiB |                   │
|    0      3294    G   ...CTForProblematicRoots/disabled/ExtensionD    73MiB |                   │
|    0      5873    G   unity-control-center                            34MiB |                   │
|    0     11643    C   python                                         222MiB |                   │
+-----------------------------------------------------------------------------+
```

**Comment by ahundt** [comment]
At startup it actually does say it is going to run on the gpu as well:
```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
[2016-12-08 15:33:51,572] Making new env: Breakout-v0
[1208 15:33:52 @train-atari.py:248] [BA3C] Train on gpu 0 and infer on gpu 0
[1208 15:33:52 @logger.py:69] WRN Directory train_log/train-atari exists! Please either backup/delete it, or use a new directory.
[1208 15:33:52 @logger.py:71] WRN If you're resuming from a previous run you can choose to keep it.
[1208 15:33:52 @logger.py:72] Select Action: k (keep) / b (backup) / d (delete) / n (new):
d
[1208 15:34:04 @logger.py:57] Argv: ./train-atari.py --env Breakout-v0 --gpu 0
```

**Comment by ppwwyyxx** [comment]
You should look for logs from tensorflow about which device it's actually using, such as the following:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y

```

**Comment by ppwwyyxx** [comment]
Another thing that's probably related. nvidia-smi shows that your GPU is in P8 state. Normally (if autoboost properly configured) the GPU would automatically change to high-performance state when some heavy jobs started. P8 is the lowest-performance state.

**Comment by ahundt** [comment]
Cool, I had the config wrong! Reinstall with CUDA version 6.1 flag set fixed it, looks like I'm getting 9-10 it/s now. I really appreciate the info about GPU performance levels, I didn't know those details.

Now that I'm able to match your results I'm curious about another difference in iter/sec compared to a similar implementation. It looks like [traai/async-deep-rl](https://github.com/traai/async-deep-rl) can achieve 80 million iterations in 48 hours which is 463 iterations per second just on 8 cpu cores and no GPU. Is this perhaps an architectural difference of some sort?

**Comment by ppwwyyxx** [comment]
By steps it means 1 action in the game. But here 1 iteration is a batch of 128, that is 128 steps.

**Comment by ahundt** [comment]
Ah so with comparable units then tensorpack is at ~1152 steps/sec on a GPU compared to 419 steps/sec on [traai/async-deep-rl](https://github.com/traai/async-deep-rl)  with CPU. Yeah I figured there might be some key design/implementation differences too.
