### ISSUE TITLE
PeriodicTrigger+ProcessTensors callback combination unexpected behaviour

### ISSUE THREAD

**Issue by yselivonchyk** [ppwwyyxx/tensorpack#651]
I created an operation to copy weights into duplicate variables 'update_drift_copies' which i want to run once in a while. To do that I used next callback:

tp.PeriodicTrigger(
     tp.ProcessTensors(['tower0/update_drift_copies'], lambda x: 0), every_k_epochs=9000
)

After starting the model I observed, that operation 'update_drift_copies' runs more often then once in 9000 epochs, namely, every step.

print(tensorflow.__version__)   # 1.3.1
print(tensorpack.__version__) # 0.7.1

**Comment by ppwwyyxx** [comment]
`ProcessTensors` uses `_before/after_run` rather than `_trigger`. You need to use `PeriodicRunHooks` to schedule it.

**Comment by ppwwyyxx** [comment]
That said, it seems possible to integrate the two and have a single `PeriodicCallback` that works for every method. Marking this as a potential feature.

**Comment by yselivonchyk** [comment]
Figured, that i can achieve what i want with tp.PeriodicTrigger(RunOp(...)).

**Comment by ppwwyyxx** [comment]
You can use RunOp as well. There is a difference though -- RunOp is an extra `session.run` call , that's why it uses `_trigger` instead of `_before_run`. If your op only operates on weights, an extra call doesn't hurt anyway.
