### ISSUE TITLE
import  halted; None in sys.modules

### ISSUE THREAD

**Issue by bilipa** [ppwwyyxx/tensorpack#653]
debug.py                                                                                                                                         
import torch
import torch.nn.functional as F
from torch.autograd import Variable
import torch.nn as nn
import numpy as np
import os
import time
import config as cfg
from debug_2 import *
import cv2
import torch.backends.cudnn as cudnn
cudnn.benchmark = True

debug_2.py
File 2
import numpy as np
from tensorpack.dataflow import *
import multiprocessing
import cv2

When run File 1, it output 
Traceback (most recent call last):
  File "debug.py", line 13, in <module>
    import torch.backends.cudnn as cudnn
ImportError: import of 'torch' halted; None in sys.modules

When I delete this **from tensorpack.dataflow import *** from file 2, it work.
It is bug in tensorpack ? 
Thanks

pytorch version: 0.4.0a0+408c84d
tensorpack version: 0.8.1
python: 3.5

**Comment by ppwwyyxx** [comment]
I mean, you should be able to import it before pytorch.

**Comment by bilipa** [comment]
Thanks, I know

**Comment by vfdev-5** [comment]
Should it be like this (`import pyarrow` before `sys.modules['torch'] = None`) ?
```
try:
    # https://github.com/apache/arrow/pull/1223#issuecomment-359895666
    import sys

    import pyarrow as pa

    old_mod = sys.modules.get('torch', None)
    sys.modules['torch'] = None
    # import pyarrow as pa
    if old_mod is not None:
        sys.modules['torch'] = old_mod
    else:
        del sys.modules['torch']
except ImportError:
pa = None
``` 
In case of no pyarrow package `sys.modules['torch']` is `None`

**Comment by ppwwyyxx** [comment]
It was correct. The goal is to hide torch so that pyarrow cannot see it.

**Comment by vfdev-5** [comment]
Yes, but if no pyarrow package installed ?

**Comment by ppwwyyxx** [comment]
I see. I should deal with torch outside of the try block.
