### ISSUE TITLE
Dynamic imports and IDE friendliness

### ISSUE THREAD

**Issue by Arturus** [ppwwyyxx/tensorpack#656]
Thank you for great framework, I have a question about editing tensorpack-based code.

I'm using PyCharm IDE, its code navigation and code auto-completion greatly simplifies working with a model code. These IDE features works flawlessly with a Tensorflow/Keras, but did'nt work at all with a tensorpack-based models, because tensorpack uses dynamic imports everywhere. Intellectual IDE just turns into dumb text editor, because it can't perform static analysis of tensorpack modules. 

Do you have any ideas or plans how to to improve tensorpack IDE friendliness? May be some code generation to emit static import statements during library setup?

**Comment by Arturus** [comment]
This is non-trivial amount of imports just to make barebone example IDE-friendly:
```python
from tensorpack.graph_builder.model_desc import ModelDesc
from tensorpack.graph_builder.model_desc import InputDesc
from tensorpack.dataflow.raw import FakeData
from tensorpack.dataflow.common import BatchData
from tensorpack.dataflow.parallel import PrefetchDataZMQ
from tensorpack.train.config import TrainConfig
from tensorpack.input_source.input_source import QueueInput
from tensorpack.callbacks.saver import ModelSaver
from tensorpack.callbacks.inference_runner import InferenceRunner
from tensorpack.callbacks.inference import ScalarStats
from tensorpack.tfutils.sessinit import SaverRestore
from tensorpack.train.trainers import SimpleTrainer
from tensorpack.train.interface import launch_train_with_config
import tensorpack.utils.logger as logger
import tensorpack.tfutils.summary as summary
```

**Comment by PatWie** [comment]
In particular [these files](https://github.com/ppwwyyxx/tensorpack/blob/68edaa0c04a52edc6d8ae54e36b6e0b647e88eeb/tensorpack/models/__init__.py) just do

```python
__all__ = ['BatchNorm', 'BatchRenorm', 'layer_register', 'VariableHolder', 'Conv2D', 
'Deconv2D', 'FullyConnected', 'ImageSample', 'LayerNorm', 'InstanceNorm', 'LinearWrap', 
'Maxout', 'PReLU', 'LeakyReLU', 'BNReLU', 'MaxPooling', 'FixedUnPooling', 'AvgPooling', 
'GlobalAvgPooling', 'BilinearUpSample', 'regularize_cost', 
'l2_regularizer', 'l1_regularizer',
 'Dropout', 'ConcatWith', 'SoftMax']
```

A git-pre-commit-hook could produce these files directly. As far as the other pull-requests are discussed I could fix this issue. I always need to look up the correct name for "FixedSizeData, FixedDataSize, ...". This would help!

**Comment by ppwwyyxx** [comment]
Before figuring out how to make IDE happy, please note that `from tensorpack.graph_builder.model_desc import ModelDesc` is not guaranteed to work in the future. The official name for this class, as written in the documentation, is [graph_builder.ModelDesc](http://tensorpack.readthedocs.io/en/latest/modules/graph_builder.html#tensorpack.graph_builder.ModelDesc), and it's better to import it with `from tensorpack.graph_builder import ModelDesc`.

**Comment by Skylion007** [comment]
Alternatively, are there anyway to get PyCharm to deal with Tensorpack in a friendly manner? From my preliminary research it looks PyCharm can correctly deal with __all__ correctly. Does PyCharm really need static imports? The other option is to provide some kind of short hand to access Tensorpack like Tensorflow uses. Import tp and use tp.graph_builder.ModelDesc and such. That doesn't seem clean either though. I don't think generating all those static imports are the answer even if it's done dynamically.

**Comment by PatWie** [comment]
I have the same issues in sublime text. Further, it is a waste of computational resources to compute the imports over and over again for autocompletion (even when there is a cache). (I see it as a waste of used brain cells to remember the concrete function names.
I even saw the mess of writing all imports to make autocompletion work in the atom editor by a colleague. 

These unsupported wrong imports would not happen if the __init__ files would be human-readable and "IDE readable". Overall the framework has a very clean design. However, this is a recurrent issue in the entire framework.

**Comment by Skylion007** [comment]
Ah, so is the issue with the HAS_TF variable in the main __init__ file? Seems like it is doing more harm than good. Surely there is a better way to separate out dataflow if that's the case or are there are constructs like try catch that editors can accurately interpret?

**Comment by Skylion007** [comment]
One solution to this would be to use the [statica hack](https://github.com/celery/kombu/blob/master/kombu/__init__.py#L24-L35) along with [Werkzerg's lazy loading](https://github.com/pallets/werkzeug/blob/master/werkzeug/__init__.py) to have the IDE both be satisfied and also allow for the benefits of dynamic importing: inspired by this [Reddit thread](https://www.reddit.com/r/Python/comments/1bbbwk/whats_your_opinion_on_what_to_include_in_init_py/).

**Comment by ppwwyyxx** [comment]
So I tried [jedi](https://github.com/davidhalter/jedi). In my tests, putting names of objects into `__all__` explicitly doesn't help it to find out where the objects are defined, and as a result it cannot autocomplete the docs & methods of the objects. Seems like it has to import everything line by line in all `__init__` file to make autocompleter happy.

**Comment by ppwwyyxx** [comment]
These are two separate issues here:
1. The dynamic import in `__init__.py`  under each subfolder. Now it simply does `import *` of each file under the folder. I think it's OK to replace it with a bunch of explicit imports:
```python
from .model_desc import *
from .training import *
from .distributed import *
from .predict import *
from .utils import *
```

2. The global `__init__.py` conditions on `HAS_TF`. The [static hack](https://github.com/celery/kombu/blob/master/kombu/__init__.py#L24-L35) seems fine. Does it work with pycharm?

**Comment by ppwwyyxx** [comment]
For 1, I found that `__all__` is necessary for sphinx to work. As a result, the current code (dynamically populate `__all__`) has to be kept. 
However, the static hack can probably tell parser how to find each name. 
I found that adding
```python
if False:
    from .model_desc import *
    from .training import *
    from .distributed import *
    from .predict import *
    from .utils import *
```
is enough for jedi to autocomplete everything. So I'll push this first.

**Comment by Skylion007** [comment]
Hmm, I think you might need to use the more specific trick of deleting programmatically setting a boolean to false to fool some of the other IDEs. They may ignore constant false blocks. If it was that easy, I would expect more projects to use that instead of the statica hack.

**Comment by ppwwyyxx** [comment]
Pushed the static hacks.
Basically all methods are hacks because no IDEs can be smart enough to understand python. I can push some of these hacks to perhaps make things better. But I don't know whether it would actually work for people with different IDEs. 
Now I assume a static analyzer can at least figure out all the dynamic imports. If people are interested, please try them out and make suggestions on improving it (because I don't really know how to hack these IDEs).

**Comment by Arturus** [comment]
This static hack really made my PyCharm happy. Single line ``from tensorpack import *`` is enough. 

Thank you!
