### ISSUE TITLE
shufflenet example mismatch the paper's setting

### ISSUE THREAD

**Issue by MrWanter** [ppwwyyxx/tensorpack#659]
According to the paper, the second group should have 8 blocks, but here in the shufflenet example, it is set to 6:
https://github.com/ppwwyyxx/tensorpack/blob/68edaa0c04a52edc6d8ae54e36b6e0b647e88eeb/examples/ShuffleNet/shufflenet.py#L101

Just wondering if there is some purpose for set it to 6?

**Comment by MrWanter** [comment]
I see.

**Comment by MrWanter** [comment]
By

**Comment by MrWanter** [comment]
By the way, have you reproduced the result of `140` Mflop, I only got `34.6`, around `2` points away from the paper's results, I used linear decay schedule with other settings as described in the paper.

**Comment by ppwwyyxx** [comment]
I don't have any other results.
