### ISSUE TITLE
Conv2D name usage confusion

### ISSUE THREAD

**Issue by MrWanter** [ppwwyyxx/tensorpack#661]
In the function def of Conv2d, there is no name field:
https://github.com/ppwwyyxx/tensorpack/blob/a5dc2dd807aa4ab6df50b73469d68bd167ff7d50/tensorpack/models/conv2d.py#L23-L38

but in example, the first argument is assigned with a string of name:
https://github.com/ppwwyyxx/tensorpack/blob/a5dc2dd807aa4ab6df50b73469d68bd167ff7d50/examples/ShuffleNet/shufflenet.py#L73-L77

my IDE indicates that's an error, although it runs properly, but not clear about this, could you pls explain a bit?

**Comment by PatWie** [comment]
See https://github.com/ppwwyyxx/tensorpack/blob/0ffdcc44a9288057be69ef9328a16dcc9526fa69/tensorpack/models/registry.py#L77-L101

The function wrapper adds this argument. This has some other subtle side effects like error messages like:
> function expects 5 arguments, but 5 are given

which happens if you forget the name. This basically means:
> function expects **6** arguments, but 5 are given

**Comment by ppwwyyxx** [comment]
Please point people first to docs, not code.
There is a name argument in docs: http://tensorpack.readthedocs.io/en/latest/modules/models.html?highlight=conv2d#tensorpack.models.Conv2D

So there should be no confusion.

**Comment by MrWanter** [comment]
@PatWie @ppwwyyxx , thank you both. but showing code is also more precise, and help us learning programming skills
