### ISSUE TITLE
Checkpoint Frequency Dump

### ISSUE THREAD

**Issue by ai2010** [ppwwyyxx/tensorpack#662]
Wondering a way to decide an interval of time to dump a checkpoint on the ModelSaver() callback I tried to set the keep_checkpoint_every_n_hours parameter but it doens't do the job. Is there a way to set the frequency of saving checkpoints? Thanks

**Comment by ppwwyyxx** [comment]
```
PeriodicTrigger(ModelSaver(...), every_k_epochs=10)
```
The meaning of `keep_checkpoint_every_n_hours` is in tensorflow document.

**Comment by ai2010** [comment]
Thanks. Right I can only set the interval of checkpoints in terms of numbers of epochs... right?

**Comment by ppwwyyxx** [comment]
You can use `every_k_steps` as well.

**Comment by ai2010** [comment]
thanks!
