### ISSUE TITLE
printing tensors

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#663]
Usage question.

When printing output tensors, I was using DumpTensors['conv0/output:0']. But this does not work during training as there are 4 towers (in my case) and I need to append the tower# id to the tensor name. 

Any simple way the DumpTensor appends these output feature maps and prints a single tensor concatenated (or averaged) across all towers instead of one per tower?

**Comment by ppwwyyxx** [comment]
Think of the 4 tensors as 4 independent tensors that happen to have similar names. 
They are not necessarily concat-able at all. 

You can implement this feature by writing a callback, either fetching all tensors to numpy and concat them there or create a concatenated tensor in the graph and fetch it.

**Comment by a-maci** [comment]
Got it.

**Comment by a-maci** [comment]
Is there no such thing as **tower0**/bnorm0/output:0, ie bnorm for tower0? 
This is with respect to resnet topology (very first layer there).

When I dump tower0/bnorm0/output:0 i get an error but not when I print tower1/bnorm0/output:0.

**Comment by a-maci** [comment]
Ok, so its called InferenceTower instead of tower0.

One question to understand the framework: Each tower has a copy of the model and gets some number of inputs (=TotalBatchSize/NumGPUs), during inference or when checkpointing, do you store the average of all the model tensors across the towers?

**Comment by a-maci** [comment]
Actually, no, its called tower0/bnorm0/FusedBatchnorm:0 for some reason.

**Comment by ppwwyyxx** [comment]
`DumpTensors` callback runs in every __training step__ so I don't see why it makes sense to evaluate inference tensors in it. That's up to you, though.

The tensor name is supposed to end with "output:0". Getting "FusedBatchnorm:0" is a bug. I'll fix it soon.

> do you store the average of all the model tensors across the towers?

No. And as I said tensors on different towers, though have similar names, are not necessarily of the same shape at all.

**Comment by a-maci** [comment]
> DumpTensors callback runs in every training step 
> 
Yes. That’s my mistake. 

Any option to print tensor ops outputs during inference phase?

**Comment by ppwwyyxx** [comment]
Using `self.trainer.get_predictor()` in a callback is the easiest way to do it. See http://tensorpack.readthedocs.io/en/latest/tutorial/inference.html.

You can also write:
```python
class A(Inferencer):
    def _get_fetches(self):
        return ['conv0/output:0']

    def _on_fetches(self, outputs):
        print(outputs)
```
