### ISSUE TITLE
Train part of all variables

### ISSUE THREAD

**Issue by chenchen718** [ppwwyyxx/tensorpack#664]
My network comprises of two parts: a pre-trained model and some newly added layers. Now I want to train this network, with the pre-trained parameters unchanged. I figured there might be two ways to do it:
1. I set the variables corresponding to the pre-trained network to be non-trainable. But it seems that this cannot be done.
2. I specify the variable list that I need to update in the optimizer. This is easy to do in pure tensorflow, but I am not clear of how to do this in tensorpack. 

So my question is how I can optimize w.r.t a certain group of variables in tensorpack.
Thank you so much!

**Comment by ppwwyyxx** [comment]
Read the tutorial here: http://tensorpack.readthedocs.io/en/latest/tutorial/faq.html#how-to-freeze-some-variables-in-training

**Comment by chenchen718** [comment]
Is there a way to set some variables to be non-trainable from the very beginning?

**Comment by ppwwyyxx** [comment]
What do you mean by "very beginning"?

**Comment by chenchen718** [comment]
I mean how I can set some variables to be non-trainable when I build the graph with the functions like ".Conv2D".

**Comment by chenchen718** [comment]
Tensorpack's builtin trainer minimizes variables in the collection "TRAINABLE_VARIABLES", doesn't it? Can I modify the variable collection to minimize without re-writing the trainer?

**Comment by ppwwyyxx** [comment]
> Tensorpack's builtin trainer minimizes variables in the collection "TRAINABLE_VARIABLES", doesn't it? 
It does.

> Can I modify the variable collection to minimize without re-writing the trainer?

You can. As I said you can edit the collection or use a custom getter for the variable scope so that the variables never gets into the collection.

Check tensorflow docs on `tf.get_collection_ref`, `tf.variable_scope` for the usage.

**Comment by ppwwyyxx** [comment]
Above commit adds "skip_collection" support in `freeze_variables`. 
Though we provide such functions, in general how to build the layers is not the job of tensorpack. If you need more control over what and how variables are freezed, it's better to learn the usage of tensorflow custom_getter and implement something similar to `freeze_variables` by yourself.
