### ISSUE TITLE
a3c example ModelSaver stuck

### ISSUE THREAD

**Issue by ai2010** [ppwwyyxx/tensorpack#666]
I'm running a simulation with the a3c example setting  the ModelSaver to dump a checkpoint after every_k_steps=5000. The simulation is stuck at 4999 iteration for more than 16hrs (I assume it's saving).... I'm using google cloud 4 cpu virtual machine with Tesla K80.
Parameters:
LOCAL_TIME_MAX = 5
STEPS_PER_EPOCH = 10000
EVAL_EPISODE = 50
BATCH_SIZE = 128
PREDICT_BATCH_SIZE = 15    # batch for efficient forward
SIMULATOR_PROC = 30#number of processes at the same time
PREDICTOR_THREAD_PER_GPU = 1#THREADS #number of agents
PREDICTOR_THREAD = None

Any idea is appreciated...

**Comment by ppwwyyxx** [comment]
For unexpected problems, please post issues following the issue template. In particular, include what you did (changes you made, command you run) and what you observed (logs).
