### ISSUE TITLE
Better ways to clean-up processes on Linux

### ISSUE THREAD

**Issue by ppwwyyxx** [ppwwyyxx/tensorpack#668]
https://stackoverflow.com/questions/284325/how-to-make-child-process-die-after-parent-exits/36945270#36945270

http://pythonhosted.org/python-prctl/

**Comment by Skylion007** [comment]
Can't we just use an atexit hook to do this? Don't see why another linux specific dependency would be necessary.

**Comment by ppwwyyxx** [comment]
atexit only get executed when the process exits in a clean way.

**Comment by Skylion007** [comment]
Wouldn't [signals](https://docs.python.org/2/library/signal.html?#signal.signal) be a more precise cross-platform way of handling it though?

**Comment by ppwwyyxx** [comment]
How?

**Comment by Skylion007** [comment]
https://stackoverflow.com/questions/40866576/run-atexit-when-python-process-is-killed

**Comment by ppwwyyxx** [comment]
Cannot catch sigkill.

**Comment by Skylion007** [comment]
Can that library catch it though? I was under the impression that NOTHING can catch SIGKILL. That's the point of SIGKILL isn't it?

**Comment by Skylion007** [comment]
NVM, I understand it's a hook on the child. Still this would only solve the issue on Linux. There is a way of dealing with this on Windows, but it's far more complicated. The only reliable way would be to pole the parent from the [subprocesses](https://stackoverflow.com/questions/23434842/python-how-to-kill-child-processes-when-parent-dies). The signal solution would solve pretty much ever other case though with the exception of SIGKILL and without the need for a Linux specific non-UNIX call for an edge case. Thoughts?

**Comment by ppwwyyxx** [comment]
If prctl solves the problem for Linux I'll use it. You're welcomed to add better support for windows if you like.

> Another really clever method is the following:

This assumes the child is still able to run code when parent dies, which is not necessarily true. The child can be stuck in IO.

**Comment by ppwwyyxx** [comment]
For example when parent dies and a child is waiting data from the parent.

**Comment by Skylion007** [comment]
Wouldn't the child receive an EOF? All file descriptors are closed when a process is terminated by any means right? Therefore the child would receive an EOF.

**Comment by ppwwyyxx** [comment]
It could be waiting data from a queue, from a named pipe, from shared memory, etc.
