### ISSUE TITLE
Question about crop_and_resize in Faster RCNN

### ISSUE THREAD

**Issue by jiang1st** [ppwwyyxx/tensorpack#670]
Hi, I have a simple question about your implementation of crop_and_resize. When you are deciding the initial sampling point, you used:

>  nx0 = x0_box + spacing/2 - 0.5

https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/model.py#L338

What I don't understand is that why did you minus 0.5 here? One bad case I have encountered is that, when the size of ROI is quite small and the ROI locates near the boundary of the feature map (e.g., a ROI with x0=0, y0=0, w=0.5, h=0.5), -0.5 will result in a negative nx0, hence the output of the ROIAlign could be filled with zeros (tf.image.crop_and_resize will extrapolate the input feature map with zeros if the ROI is outside the feature map).

Although you commented that 

> "-0.5 because bilinear sample assumes floating point coordinate (0.0, 0.0) is the same as pixel value (0, 0)"

I didn't fully understand it. Could you please explain why is it beneficial to minus 0.5 here? 

Thank you, looking forward to your reply.

**Comment by ppwwyyxx** [comment]
There was an issue about it #542. The short answer is "this is how tensorflow works".
I don't want to explain it more because it's complicated and you need to read tensorflow source code to figure out everything. And this is one reason why all other tensorflow implementations are wrong.
To convince you, run this snippet:
```python
    import numpy as np
    import tensorflow.contrib.eager as tfe
    tfe.enable_eager_execution()

    image = np.arange(25).astype('float32')
    boxes = np.asarray([[0, 0, 4, 4]], dtype='float32')

    print(crop_and_resize(
        image.reshape(1, 1, 5, 5),
        boxes, [0], 4))
    """
    Expected values:
    0, 1, 2, 3
    5, 6, 7, 8
    10, 11, 12, 13
    15, 16, 17, 18

    You cannot easily get the same results with tf.image.crop_and_resize.
    Try some of the possibilities here:
    """
    print(tf.image.crop_and_resize(
        image.reshape(1, 5, 5, 1),
        boxes / (5 - 1.0), [0], [4, 4]))

```

**Comment by ppwwyyxx** [comment]
Oh but one thing you're correct: tensorflow pads zeros on borders, which makes my implementation of roi_align also wrong. But it's only wrong on the borders, so it's not a big deal.
I'll prepare a script that demonstrates the alignment problem.

**Comment by ppwwyyxx** [comment]
UPDATE: now our implementation of roialign is correct on borders as well.

**Comment by crazysal** [comment]
Could you please comment on "this is how tensorflow works" ? 
I understood you want to take a relative floating point coordinate with an origin wrt the current cell, but how does tf know the relative cell from the original position in the grid ?  Or just direct me to the part of the source code. Do you mean the `void CropAndResizePerBox()` in the C src ? 
I'm a bit confused on how the geometry works in calculating the `y_in` and `x_in` [values in the nested loop](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/crop_and_resize_op.cc#L240).

**Comment by ppwwyyxx** [comment]
As mentioned above I do not want to comment more. I cannot understand your question because terms like "an origin wrt the current cell", "relative cell from the original position" are not mathematically defined and I do not know what they mean. This is why the issue is complicated: I do not believe it can be explained well with plain words.

The source code is CropAndResizePerBox.

**Comment by ppwwyyxx** [comment]
Opened an issue in tensorflow (https://github.com/tensorflow/tensorflow/issues/26278) since there is a chance it gets fixed in TF 2.
