### ISSUE TITLE
problem encountered when I conduct distributed training

### ISSUE THREAD

**Issue by anthony123** [ppwwyyxx/tensorpack#671]
I encountered a problem when  i run my distributed training code, the  error traces are as follows:

![distributederror](https://user-images.githubusercontent.com/4050099/36638940-cee8895c-1a3b-11e8-801d-dafa56cb3390.png)

my code is [here](https://github.com/anthony123/learnit/blob/master/cifar10-sparse-densenet-bc-exp.py)

I launch my code as:
`python cifar10-sparse-densenet-bc-exp.py --gpu=0,1,2,3 --job worker --task 0`

when I use trainer 
```
trainer = SyncMultiGPUTrainerParameterServer(len(args.gpu.split(',')))
launch_train_with_config(config, trainer)
```
there will be no problem

Any suggestion is appreciated.

**Comment by ppwwyyxx** [comment]
1. You're using a very old tensorpack. Please upgrade and try again.
2. Tensorflow does not have a native fast distributed trainer. Only [horovod trainer](https://github.com/tensorpack/benchmarks/tree/master/ResNet-Horovod) can get a reasonable speedup.

**Comment by anthony123** [comment]
When i upgrade tensorpack to 0.8.1, there is another error has appeared. the error traces are as follows:

![tperror2](https://user-images.githubusercontent.com/4050099/36650334-d77a5c06-1add-11e8-9c74-6d3339ee5040.png)

**Comment by ppwwyyxx** [comment]
The above commit should fix the problem. Another way to fix the problem is to upgrade your tensorflow to 1.5
