### ISSUE TITLE
Infinite loop with MultiProcessMapDataZMQ

### ISSUE THREAD

**Issue by vfdev-5** [ppwwyyxx/tensorpack#673]
There is an infinite loop with the following code:
```
from tensorpack.dataflow import MultiProcessMapDataZMQ, FakeData

ds = FakeData(((50, 50, 3), (1,)))

import numpy as np

def proc(dp):
    img = np.random.randint(0, 255, size=(1012, 1012, 3))
    img[img < 120] = 0
    return dp

mp_ds = MultiProcessMapDataZMQ(ds, map_func=proc, nr_proc=10, strict=True)

mp_ds.reset_state()

for i, (_, _) in enumerate(mp_ds.get_data()):
    if i % 100 == 0:
        print(i, end=" . ", flush=True)
```

Important part is `strict=True` and small size of `FakeData`. If change size to (512, 512, 3), then loop ends properly. Probably, there is something with buffer filling and dequeing...
Execution stucks [here](https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/dataflow/parallel_map.py#L81).

**Comment by ppwwyyxx** [comment]
Cannot reproduce. Please update

**Comment by vfdev-5** [comment]
Actually, I have already updated to the master.

**Comment by vfdev-5** [comment]
@ppwwyyxx could you reproduce the issue ?

**Comment by ppwwyyxx** [comment]
I can not. Maybe upgrade/reinstall msgpack?

**Comment by vfdev-5** [comment]
Could you try please this code too:
```
from tensorpack.dataflow import MultiProcessMapDataZMQ, RNGDataFlow, MultiThreadMapData


dataset = [("file_%i" % i, i % 3) for i in range(500)]

class TestDataset(RNGDataFlow):
    
    def __init__(self, dataset):
        super(TestDataset, self).__init__()
        self.dataset = dataset
        
    def size(self):
        return len(self.dataset)
        
    def get_data(self):
        for k in range(len(self.dataset)):
            yield self.dataset[k]            

test_dataset = TestDataset(dataset)
test_dataset.size()

def data_transform(dp):
    return dp

mp_test_dataset = MultiProcessMapDataZMQ(test_dataset, nr_proc=10, map_func=data_transform, strict=True)

mp_test_dataset.reset_state()


for i, (fp, _) in enumerate(mp_test_dataset.get_data()):
    if i % 100 == 0:
        print(i, end=" . ", flush=True)
```

Okay, I'll try to upgrade msgpack, which version do you use ?

**Comment by ppwwyyxx** [comment]
The code successfully exits. I use the latest version of msgpack & msgpack-numpy. Maybe also try upgrading pyzmq.

**Comment by vfdev-5** [comment]
Strange configuration I have. Here is a list of versions of some of packages I have:
```
msgpack (0.5.6)
msgpack-numpy (0.4.3)
msgpack-python (0.5.5)
numpy (1.14.1)
pickleshare (0.7.4)
pip (9.0.1)
pyzmq (17.0.0)
tensorpack (0.8.1)
```

**Comment by ppwwyyxx** [comment]
https://github.com/msgpack/msgpack-python#pypi-package-name
Maybe related.

**Comment by vfdev-5** [comment]
I could reproduce the issue using this docker file. Could you try it please?

[Dockerfile.txt](https://github.com/ppwwyyxx/tensorpack/files/1757877/Dockerfile.txt)
[test_tensorpack_inf_loop.txt](https://github.com/ppwwyyxx/tensorpack/files/1757878/test_tensorpack_inf_loop.txt)
Please remove .txt extensions from Dockerfile and replace it for `test_tensorpack_inf_loop.txt` by `py`
Github do not allow include py and dockerfile as is.

**Comment by ppwwyyxx** [comment]
I can reproduce the issue in docker. Looks like I'm using zmq socket in a wrong way where messages can get lost if the sockets aren't created with a desired order.

**Comment by vfdev-5** [comment]
Awesome ! 🎉
