### ISSUE TITLE
No gradient defined for operation "BatchNorm"

### ISSUE THREAD

**Issue by junsukchoe** [ppwwyyxx/tensorpack#674]
Hi,

I work with your examples "Improved-WGAN.py".

I want to get gradients by using tf.gradients.
It works when I used LayerNorm for discriminator.
But, it does not work when I change LayerNorm to BatchNorm.

The error message is 

> No gradient defined for operation 'gradients/discrim/discrim_1/bn1/FusedBatchNorm_grad/FusedBatchNormGrad' (op type: FusedBatchNormGrad).

The full error logs is as follows:

> Traceback (most recent call last):
>   File "DCGANGP_cifar.py", line 388, in <module>
>     model=M).train_with_defaults(
>   File "/srv/repository/object_localization/GAN.py", line 90, in __init__
>     d_min = opt.minimize(model.d_loss, var_list=model.d_vars, name='d_op')
>   File "/home/junsuk/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 315, in minimize
>     grad_loss=grad_loss)
>   File "/home/junsuk/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
>     colocate_gradients_with_ops=colocate_gradients_with_ops)
>   File "/home/junsuk/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 516, in gradients
>     (op.name, op.type))
> LookupError: No gradient defined for operation 'gradients/discrim/discrim_1/bn1/FusedBatchNorm_grad/FusedBatchNormGrad' (op type: FusedBatchNormGrad)

It seems that there is no implementation for providing gradient information in BatchNorm op.

I use Python 3.6, Tensorpack 0.8.0, Tensorflow 1.3.

Thank you.
Junsuk.

**Comment by ppwwyyxx** [comment]
are you using CPUs?

**Comment by ppwwyyxx** [comment]
Oh you're using improved-wgan, which requires 2nd order gradient. 
2nd order gradient for fused batch norm is only supported since TF 1.4: https://github.com/tensorflow/tensorflow/commit/4f3b13cc650ec08a246c16d31f9a10cf5bb96d65#diff-09d0717441656db7d7338b7febc2251a

Closing as this is not a tensorpack issue.

**Comment by junsukchoe** [comment]
I update my tensorflow, and it works well.
Thanks you!
