### ISSUE TITLE
Issues with exporting trained models for inference

### ISSUE THREAD

**Issue by pandasMX** [ppwwyyxx/tensorpack#676]
Hi,

I trained a resnet50 model using your keras-resnet script, after that I got the .meta, .index and .data files which look like a standard tensorflow checkpoint. However, when I tried to load it, freeze it for inference. The checkpoint files seem to have some problems. Please take a look at the following code.

```
output_node_names = 'fc1000/kernel'
output_graph = './data/resnet50_0221/output_graph.pb'

with tf.Session(graph=tf.Graph()) as sess:
    new_saver = tf.train.import_meta_graph('./data/resnet50_0221/model/graph-0221-040251.meta',clear_devices=True)
    new_saver.restore(sess, './data/resnet50_0221/model/model-31575')

    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        tf.get_default_graph().as_graph_def(),
        output_node_names.split(','))
        
    with tf.gfile.GFile(output_graph, "wb") as f:
        f.write(frozen_graph_def.SerializeToString())
    print("%d ops in the final graph." % len(frozen_graph_def.node))
```

It finally print out this: 
`INFO:tensorflow:Restoring parameters from ./data/resnet50_0221/model/model-31575
INFO:tensorflow:Froze 1 variables.
Converted 1 variables to const ops.
1 ops in the final graph.`
which is wrong because there should be 161 variables.

The same code worked fine with my other models, therefore I'm sure it's something wrong with the checkpoint files generated by tensorpack.

Do you have any idea? Thanks

**Comment by ppwwyyxx** [comment]
Because you set the output node name to the variable, only the variable will be left.

**Comment by pandasMX** [comment]
Ohhh, thanks! I just realise that 'fc1000/kernel' is a variable. So the output node should be 'fc1000'? But it says `AssertionError: fc1000 is not in graph` after trying.

**Comment by ppwwyyxx** [comment]
The name would depend how keras implement the layer so I don't know -- and it may change across versions. Look at the graph or print the nodes to find it out.

**Comment by pandasMX** [comment]
Thanks for your advices. However, I found more than 50k node names in the graph and I have no idea which are the input and output node names.

**Comment by ppwwyyxx** [comment]
That's why I would recommend you to build the inference graph by yourself. See http://tensorpack.readthedocs.io/en/latest/tutorial/inference.html#inference-after-training
