### ISSUE TITLE
inconsistant parameter number about resnet101 

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#683]
the resnet101 training output is:
```
Total #vars=446, #params=49326872, size=188.17MB
```
it shows that resnet101 have 49326872/1024/1024=**47.04M params.**

however, in resnet paper, resnet101 have **1.7M params.**

**Comment by ppwwyyxx** [comment]
![0302-10 11 46](https://user-images.githubusercontent.com/1381301/36914437-27838b56-1e02-11e8-9277-246615781a2c.png)
If this is the number you're referring to, you're talking about completely unrelated things.

**Comment by dongzhuoyao** [comment]
@michaelklachko 

hi,  the params should include weight, bias(in conv), beta, gamma(in bn), those parameter number is unrelated to the dataset. 

please kindly correct me if my understanding is wrong.

**Comment by ppwwyyxx** [comment]
Those are two different network architectures.

**Comment by dongzhuoyao** [comment]
😥 thank you @ppwwyyxx @michaelklachko
