### ISSUE TITLE
The step 'ds = BatchData(ds, batch_size, remainder=False)' is very slow, how can I fix it

### ISSUE THREAD

**Issue by souxun2015** [ppwwyyxx/tensorpack#684]
I use the code imagenet_utils.py of ResNet to TestDataSpeed(df).
The batch_size is 256. 
The following code is what I want to test on ImageNet dataset.
`    
if isTrain: 
        ds = LMDBData(datadir+'/'+'ILSVRC-train.lmdb', shuffle=False)
        ds = LocallyShuffleData(ds, 50000)
        ds = PrefetchData(ds, 5000, 1)
        ds = LMDBDataPoint(ds)
        ds = MapDataComponent(ds, lambda x: cv2.imdecode(x, cv2.IMREAD_COLOR), 0)
        ds = AugmentImageComponent(ds, augmentors, copy=False)
        ds = PrefetchDataZMQ(ds, 20)
        ds = BatchData(ds, batch_size, remainder=False)`
The output is:
![image](https://user-images.githubusercontent.com/12790408/36931640-69e7137a-1ef5-11e8-9a34-4c2bf1e67c9b.png)

when I comment the ds = BatchData(ds, batch_size, remainder=False), the output is 
![image](https://user-images.githubusercontent.com/12790408/36931628-040fbe4e-1ef5-11e8-8d37-98485965772b.png)

I don't understand why this step is so slow. Is there any solution?

**Comment by ppwwyyxx** [comment]
The issue template has the instruction:
tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment]
Some examples to benchmark:
```python
ds = LMDBData('/path/to/ILSVRC-train.lmdb', shuffle=False)
ds = BatchData(ds, 256, use_list=True)
```

```python
ds = LMDBData(db, shuffle=False)
ds = LocallyShuffleData(ds, 50000)
ds = PrefetchData(ds, 5000, 1)
ds = LMDBDataPoint(ds)
ds = PrefetchDataZMQ(ds, 25) # set to your cpu count
ds = BatchData(ds, 256, use_list=True)
```

```python
ds = LMDBData(db, shuffle=False)
ds = LocallyShuffleData(ds, 50000)
ds = PrefetchData(ds, 5000, 1)
ds = LMDBDataPoint(ds)
ds = MapDataComponent(ds, lambda x: cv2.imdecode(x, cv2.IMREAD_COLOR), 0)
ds = AugmentImageComponent(ds, [imgaug.Resize(224)])
ds = PrefetchDataZMQ(ds, 25)
ds = BatchData(ds, 256)
```

**Comment by souxun2015** [comment]
Sorry for such issue. I have tested the code as you mentioned above.
`
ds = LMDBData('/path/to/ILSVRC-train.lmdb', shuffle=False)

ds = BatchData(ds, 256, use_list=True)
`
The output is:
![image](https://user-images.githubusercontent.com/12790408/36943245-df1c0486-1fc0-11e8-9112-e638a3bed86b.png)
My cpu is: one CPU E5-1620 v4, 3.5Ghz, memory is 64G.

Does this result indicate that my hardware is the bottleneck?

**Comment by ppwwyyxx** [comment]
This is measuring disk speed and it means you can read 2.97*256 images per second from disk into memory. It's up to you whether you'll call it a bottleneck.

**Comment by ppwwyyxx** [comment]
Oh I found E5-1620 v4 only has 4 cores? This CPU definitely cannot do all the preprocessing faster than 2.97*256 im/s.

**Comment by souxun2015** [comment]
Ok, I get it. Thank you very much.
Are there some suggestion for accelerating the code in this situation?

**Comment by ppwwyyxx** [comment]
Then do fewer preprocessing steps.

https://github.com/ppwwyyxx/tensorpack/blob/9972b15036c851ce82e63721cfe0905e68115475/examples/ResNet/imagenet_utils.py#L61-L74

May slightly affect accuracy.

**Comment by souxun2015** [comment]
I have done these. It seems that the cpu in my computer is the bottleneck.
What is suitable CPU configuration for this situation? Can you give me some advice?

**Comment by ppwwyyxx** [comment]
A typical server machine in my experience has 2 CPUs each with 10 cores or more.

**Comment by souxun2015** [comment]
Ok, thanks very much. It is very helpful.
