### ISSUE TITLE
usage of `tfutils.sessinit.ChainInit(sess_inits)`

### ISSUE THREAD

**Issue by chenchen718** [ppwwyyxx/tensorpack#686]
Could you please give a concrete example of how to use `tfutils.sessinit.ChainInit(sess_inits)`? I am trying to load two pre-trained models into a single network using this function, but not clear how to use it. I know that for loading a single model, I simply need to pass the model path to `tfutils.sessinit.SaverRestore`. But where do I specify the model path and in what way do I create a list of `SessionInit` instances to pass to `tfutils.sessinit.ChainInit(sess_inits)`?

Thanks a lot!

**Comment by ppwwyyxx** [comment]
`ChainInit([SaverRestore(path1), SaverRestore(path2)])`
