### ISSUE TITLE
Uneffective normalization

### ISSUE THREAD

**Issue by yselivonchyk** [ppwwyyxx/tensorpack#687]
https://github.com/ppwwyyxx/tensorpack/blob/2770ede844fbbd89058e7fcc88c5f44d40b1e782/examples/ResNet/cifar10-preact18-mixup.py#L52

Existing pipeline subtracts mean pixel values after applying random cropping. This means that mean value is also subtracted from the blank (zero filled) space added by CenterPaste. It, therefore, skews the distribution. 

Idea: apply normalization before input augmentation. 

Will fix it myself in a day or two, but still want to drag your attention to the problem.

**Comment by ppwwyyxx** [comment]
This seems to be used by the authors: https://github.com/hongyi-zhang/mixup/blob/master/cifar/easy_mixup.py#L45-L50

Shouldn't be a big deal anyway. An easy change is to use `CenterPaste(background_filler=ConstantBackgroundFiller(128))`.
