### ISSUE TITLE
how to use LMDBData()

### ISSUE THREAD

**Issue by liuxiaowei199345** [ppwwyyxx/tensorpack#691]
I want to know how to use LMDBData('/path/to/ILSVRC-train.lmdb', shuffle=False)

The imagenet dataflow is written as: link

    if isTrain:
        ds = dataset.ILSVRC12(datadir, name, shuffle=True)
        ds = AugmentImageComponent(ds, augmentors, copy=False)
        ds = PrefetchDataZMQ(ds, cpu)
        ds = BatchData(ds, batch_size, remainder=False)

I use the following code to replace:

ds = LMDBData('/path/to/ILSVRC-train.lmdb', shuffle=False)
ds = BatchData(ds, 256, use_list=True)

but,when I run the alexnet-dorefa.py , it happen some error:

NameError:global name 'LMDBData' is not defined.

So ,I want to know whether missing some file .

**Comment by liuxiaowei199345** [comment]
I add 'from tensorpack.dataflow import LMDBData' ,but it still have error:
ValueError:invalid literal for float():00000000_n02088632_1176.JPEG
Training was stopped.
EnqueueThread QueueInput/input_queue Exited.
PrefetDataZMQ successfully cleaned-up.

so ,what I should do?

**Comment by ppwwyyxx** [comment]
Please paste what you did and more logs following the issue template.

**Comment by liuxiaowei199345** [comment]
I don't know how to use other data format. Can you help me ?

**Comment by ppwwyyxx** [comment]
To load data in custom format, you need to write a dataflow for that format:
http://tensorpack.readthedocs.io/en/latest/tutorial/extend/dataflow.html
