### ISSUE TITLE
npz to tf checkpoint ?

### ISSUE THREAD

**Issue by cjerry1243** [ppwwyyxx/tensorpack#693]
I'm using ShuffleNet on imagenet and I'm going to do shufflenet-SSD on tensorflow
So, I want to convert shufflenet.npz to tf checkpoint.

I've seen a script converting tf checkpoint to .npz file in scripts/dump-model-params.py

How to convert shufflenet.npz to tf checkpoint?

**Comment by ppwwyyxx** [comment]
You can load a npz  by `np.load`. 
After that, how to create a tf checkpoint is not a tensorpack question, and I don't know the answer either.
At least you can manually create variables in the graph, load the values and use tf saver to save the checkpoint.
