### ISSUE TITLE
Question about HED implementation

### ISSUE THREAD

**Issue by VladMiryaha** [ppwwyyxx/tensorpack#695]
Hi,
could you please explain why in current  [HED implementation](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/HED/hed.py) we set number of steps by epoch in
such way: [steps_per_epoch = dataset_train.size() * 40](https://github.com/ppwwyyxx/tensorpack/blob/e44e9c04d85f7f265234cc3130fd112799bc32c6/examples/HED/hed.py#L197)

Why 40?
Am I right that it's the same as:
steps_per_epoch = dataset_train.size() (default value)
and increase number of epoches in 40 times?

**Comment by ppwwyyxx** [comment]
You can set it to whatever you want.

**Comment by VladMiryaha** [comment]
But am I right that:
_steps_per_epoch = dataset_train.size() (default value)
and increase number of epoches in 40 times?_
is the same as code in current HED implementation?
Thank you.

**Comment by ppwwyyxx** [comment]
Then you'll also need to change the learning rate schedule

**Comment by VladMiryaha** [comment]
I see. Thank you so much.
