### ISSUE TITLE
The impact of the gradient for low bit cnn

### ISSUE THREAD

**Issue by JiandongMu** [ppwwyyxx/tensorpack#697]
Hello!
I am a new user of DoReFa. Thanks a lot for your tools!
We would like to train cnn with 8-bit featuremap 8-bit weight and 32-bit gradient and we aim to achieve an accuracy loss less than 1% than the full precision Alexnet. I've noticed that the accuracy loss for 8-8-8 is 3% as you claimed in your paper. How much will I gain if I use 32-bit gradient?  Usually how many bits are sufficient for gradient? Thank you very much!

Jiandong

**Comment by ppwwyyxx** [comment]
We don't know. DoReFa-Net was designed mainly for ultra-low bit (<8). We haven't done many experiments on 8 bits or more.

**Comment by JiandongMu** [comment]
DoReFa was designed for ultra-low bits. But I believe it also works for 8-8-32 right? By the way, dorefa will generate some checkpoints, however, how can I resume training from the checkpoints? Thanks,

**Comment by ppwwyyxx** [comment]
> But I believe it also works for 8-8-32 right? 

Yes

> By the way, dorefa will generate some checkpoints, however, how can I resume training from the checkpoints? Thanks,

https://github.com/ppwwyyxx/tensorpack/blob/550988138574d903798ab47ee82202fff8ac3c03/examples/DoReFa-Net/alexnet-dorefa.py#L265-L266
