### ISSUE TITLE
Question on imagenet dataset

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#70]
Which version of Imagenet do you use for evaluation? ILSVRC2012?
I think the latest IN data comes in test, train and val datasets. The 2012 version has only train and val datasets.

**Comment by ppwwyyxx** [comment]
It is ILSVRC12. It has train,val and test

**Comment by a-maci** [comment]
The folders downloaded from Imagenet website look something like this:

train/
    n01440764/ 
        n01440764_10026.JPEG
        n01440764_10027.JPEG
        ...
    n01443537/
        n01443537_10007.JPEG
        n01443537_10014.JPEG
        ...

test/
   ILSVRC2012_test_00000001.JPEG
   ILSVRC2012_test_00000002.JPEG
   ...

val/ 
   n01440764/
      ILSVRC2012_val_00000293.JPEG
      ILSVRC2012_val_00002138.JPEG
      ...
   n01443537/
      ILSVRC2012_val_00000236.JPEG
      ILSVRC2012_val_00000262.JPEG
      ...


In alexnet-dorefa and elsewhere why do you club all the val images into one big folder? Just for convenience or some other reason?

Also, do you use the **test** data sets anywhere in your experiments?

Thanks.

**Comment by ppwwyyxx** [comment]
The val images from ImageNet website are in one big folder originally. 
Other repo also confirms this, e.g. https://github.com/soumith/imagenet-multiGPU.torch.

I didn't use the test set.

**Comment by a-maci** [comment]
I was following this tutorial and I missed one item (https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh), thats why my val datasets were organized in a folder!
