### ISSUE TITLE
error : runing imagenet-resnet.py

### ISSUE THREAD

**Issue by Minotaur-CN** [ppwwyyxx/tensorpack#703]
the error occur when runing image-resnet.py.
ILSVRC2012 has train/val/test folder according to the dataflow.dataset.ILSVRC12
dir/
  train/
    n02134418/
      n02134418_198.JPEG
      ...
    ...
  val/
    n01440764/
      ILSVRC2012_val_00000293.JPEG
      ...
    ...
  test/
    ILSVRC2012_test_00000001.JPEG
    ...

**python imagenet-resnet.py --data /home/DataSet/ILSVRC2012/ --gpu 1**

---
Traceback (most recent call last):
  File "imagenet-resnet.py", line 132, in <module>
    model = Model(args.depth, args.data_format, args.mode)
TypeError: Can't instantiate abstract class Model with abstract methods _get_inputs

**Comment by ppwwyyxx** [comment]
You're not using latest tensorpack.

**Comment by Minotaur-CN** [comment]
cool,
Problem solved.
