### ISSUE TITLE
Resuming training and weight initialization in Similarity Learning example

### ISSUE THREAD

**Issue by MaggiePas** [ppwwyyxx/tensorpack#704]
Hello! :)

I am using the Similarity Learning example and I have made a couple minor changes, so it can work for CIFAR10,  instead of MNIST.
Mainly I changed the network architecture, using a ResNet model instead of the one provided for MNIST, but I wrote the architecture in exactly the same format as the existing one.

I have two questions:
1. When I want to resume training I call:
`./cifar10-embeddings.py --algorithm triplet --gpu 0 --load ./train_log/cifar10-embeddings:triplet_resnet/model-9506`
And I chose to keep the model with (k).

Then I get the following messages:

> [0322 11:48:41 @logger.py:67] Log file 'train_log/cifar10-embeddings:triplet_resnet/log.log' backuped to 'train_log/cifar10-embeddings:triplet_resnet/log.log.0322-114841'
> [0322 11:48:41 @logger.py:74] Argv: ./cifar10-embeddings.py --algorithm triplet --gpu 0 --load ./train_log/cifar10-embeddings:triplet_resnet/model-9506
> [0322 11:48:41 @fs.py:89] WRN Env var $TENSORPACK_DATASET not set, using /home/myname/tensorpack_data for datasets.
> [0322 11:48:41 @cifar.py:33] Found cifar10 data in /home/myname/tensorpack_data/cifar10_data.

And then nothing else happens. It immediately quits the script without resuming anything or giving me any errors. Do you have any idea why this happens? I am pretty sure it's not a path problem since my model exists in that path and I don't get any errors regarding that.

My second question is this:
2. Unfortunately with the CIFAR10 triplet loss I can't seem to reach state-of-the-art performance and I have only reached 80% on the test set with a common ResNet but not more. (I am using k-nn to get that result)
I would like to initialize my model with ImageNet weights, hoping it will increase the performance of my model, but I haven't found a way to do it.
Could you tell me how to initialize the weights in the Similarity Learning example?

Thanks a lot in advance! :)

**Comment by ppwwyyxx** [comment]
1. I don't know. Maybe I'll be able to tell more if you give more information, such as those in the issue template.
2. [Save and Load models](http://tensorpack.readthedocs.io/en/latest/tutorial/save-load.html)
