### ISSUE TITLE
DoReFa-Net speed turns out not fast

### ISSUE THREAD

**Issue by Anguliachao** [ppwwyyxx/tensorpack#710]
Hi , thank you for the excellent project. 
I tested the speed using the original ResNet and Alexnet model implemented by tensorpack, by right the compressed DoReFa-Net **should be much faster** in their inference time since it compressed 32-bit float number into smaller bits. 
I tested Resnet and DoReFa-Resnet, Alexnet and DoReFa-Alexnet on the same ImageNet validation dataset. However ,my testing results turns out DoReFa series net work inference slower than the original network. which the result is weird. 
I have tested on single one TitanX card , the detailed speed is 

- DoReFa-Alexnet     445ms
- Alexnet       415ms
- ResNet-Dorefa    0,9ms
- ResNet         0.5ms

would mind simply explain this? I noticed the architecture between the two categories is slightly different, but as mentioned in the paper, the speed shall not be slower than original network.
look forward to your comments,.

**Comment by ppwwyyxx** [comment]
It's mentioned in the readme that: 
>  We're not planning to release our C++ runtime for bit-operations. In this repo, bit operations are performed through tf.float32.
