### ISSUE TITLE
New TRAINABLE_VARIABLES shouldn't be created

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#712]
in my class Model(ModelDescBase), i have
```
def build_graph(self, input, output):
        ...         
        my_var = tf.Variable(0.0)
        ...
```

I have a custom callback where I do:
`pred = self.trainer.get_predictor(input, output)`

I get:
AssertionError: New TRAINABLE_VARIABLES shouldn't be created in tower-pred-0: tower-pred-0/my_var:0

what am I doing wrong?

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html

**Comment by eyaler** [comment]
thanks! changing to get_variable() solved my issue
