### ISSUE TITLE
Abstract sockets breaks A3C for mac osx

### ISSUE THREAD

**Issue by planetceres** [ppwwyyxx/tensorpack#715]
commit a46de3426250651c6b8fb993f1c27faac9533a2a breaks A3C on mac os specifically at https://github.com/ppwwyyxx/tensorpack/commit/a46de3426250651c6b8fb993f1c27faac9533a2a#diff-4689f70438745b5328b50f745da00d4e

The changes in `examples/A3C-Gym/train-atari.py` where:

```
PIPE_DIR = os.environ.get('TENSORPACK_PIPEDIR', '.').rstrip('/')
namec2s = 'ipc://{}/sim-c2s-{}'.format(PIPE_DIR, name_base)
names2c = 'ipc://{}/sim-s2c-{}'.format(PIPE_DIR, name_base)
```

Is changed to:

```
namec2s = 'ipc://@sim-c2s-{}'.format(name_base)
names2c = 'ipc://@sim-s2c-{}'.format(name_base)
```

And in `examples/A3C-Gym/simulator.py` where:

```
name = 'ipc://whatever'
```

is changed to:

```
name = 'ipc://@whatever'
```

Result in a zmd error:

```
Traceback (most recent call last):
  File "./train-atari.py", line 303, in <module>
    train()
  File "./train-atari.py", line 240, in train
    master = MySimulatorMaster(namec2s, names2c, predict_tower)
  File "./train-atari.py", line 140, in __init__
    super(MySimulatorMaster, self).__init__(pipe_c2s, pipe_s2c)
  File "/Users/Username/tensorpack/examples/A3C-Gym/simulator.py", line 117, in __init__
    self.c2s_socket.bind(pipe_c2s)
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: No such file or directory
```

Reverting the changes mentioned above allows A3C to run as expected on Mac OSX.

**Comment by ppwwyyxx** [comment]
The training wasn't meant to run on osx at the beginning.
An easy fix would be to use different types of sockets conditioned on the OS.

**Comment by planetceres** [comment]
Since the current version does not condition for the os, would it be reasonable to specify somewhere in the docs or readme that training isn't meant for osx?
