### ISSUE TITLE
Discrepancy of validation error

### ISSUE THREAD

**Issue by coolbay** [ppwwyyxx/tensorpack#718]
When I train my model, I use Callbacks `DataParallelInferenceRunner` to evaluate the performance on the validation data and get an error rate. After I finish training, I test the same model on the same validation data using `PredictConfig`. But the error rate I get this time is different from I get while training. How is that? Shouldn't they be exactly the same?

Thank you very much!

**Comment by ppwwyyxx** [comment]
If your dataflow is not randomized (either explicitly or implicitly by paralleism), and has the correct size, then both methods should give you the same error rate.

**Comment by chenchen718** [comment]
I am using a fixed lmdb file. What do you mean by "has the correct size"?

**Comment by ppwwyyxx** [comment]
It means after `dataflow.size()` datapoints, the `dataflow.get_data()` method reaches the end and stops producing more datapoints.

**Comment by ppwwyyxx** [comment]
What does your validation dataflow look like?

**Comment by chenchen718** [comment]
I am using the following procedures to retrieve the validation data.

`        ds = LMDBData(data_dir, shuffle=False)
        ds = PrefetchData(ds, 5000, 1)
        aug = imgaug.AugmentorList(augmentors)


        def mapf(dp):
            fname, cls = dp
            im = cv2.imdecode(fname, cv2.IMREAD_COLOR)
            im = aug.augment(im)
            return im, cls

        ds = LMDBDataPoint(ds)
        ds = ThreadedMapData(ds, cpu, mapf, buffer_size=2000, strict=True)
        ds = PrefetchDataZMQ(ds, 1)
        ds = BatchData(ds, batch_size, remainder=True)`

**Comment by PatWie** [comment]
How does "augmentors" looks like? If you introduce randomness there --like random crop etc-- the evaluation error will naturally varies.

**Comment by chenchen718** [comment]
@PatWie  My "augmentors" for the validation data is just the following

```
        augmentors = [
            imgaug.ResizeShortestEdge(size1, cv2.INTER_CUBIC),
            imgaug.CenterCrop((size2, size2)),
        ]
```
I don't think this causes any randomness.

**Comment by ppwwyyxx** [comment]
Not sure what is going on in your case. 
After training the imagenet-resnet examples I can get exactly the same validation number using offline evaluation, if evaluated in the same environment (same software & hardware). The example is using image files instead of LMDB, but I don't think this will lead to issues.

You can also check whether there is any environment difference or preprocessing difference.

**Comment by ppwwyyxx** [comment]
Another method I used to test similar issues before was to use two DataParallelInferenceRunner callbacks -- they should not use the same dataflow, but use two dataflows created in the same way. And will produce the same error rate. This can rule out certain types of problems with data or the model.
