### ISSUE TITLE
Grouped conv data_format bug and efficiency issue

### ISSUE THREAD

**Issue by EchoWho** [ppwwyyxx/tensorpack#720]
Bug:

Line 79 of tensorpack/models/conv2d.py

        channel_axis = 3 if data_format == 'NHWC' else 1

'NHWC' is assuming the data_format is of the tf.nn version. Instead, since you changed to tf.layers style of data_format, it should be 'channels_last'. 

--------------------

PS. An efficiency issue on group conv2d implementation / (Maybe a feature request?):

It seems that tensorflow dev is in the process of implementing group conv using cuda/cudnn native
https://github.com/tensorflow/tensorflow/issues/3332
https://github.com/tensorflow/tensorflow/pull/10482

However, before they eventually make it happen, implementing group conv with a for-loop is less efficient than using depthwise_conv plus some transpose/reshape/sum. 

There are probably few people using group conv with tensorpack so that the bug above is not exposed, but if you would like to improve the speed of running things like ResNeXt, you might want to try this.

**Comment by EchoWho** [comment]
I realized that in the group conv case, you are assuming the data_format is of the tf.nn 'NHWC' style consistently. However, the interface can still be more clear, since now you need to change the data_format input based on split=1 or split>1.

**Comment by ppwwyyxx** [comment]
It's an implementation detail that is not visible to users at all. An user can use either NCHW or channels_first.

**Comment by EchoWho** [comment]
Unless a user read the implementation, he will get the wrong operations if they give 'channels_last'. 
Furthermore, since you changed shape4d and other argtools to take only 'channels_first/last' as well, NCHW will be incorrect for those argtools functions. Finally, 'channels_last/first' are not acceptable input for tf.nn.conv and tf.nn.bias_add.

So split > 1 with channel_last will not run, but with NHWC, you will get a wrong operation due to shape4d.
