### ISSUE TITLE
Where to put image_preprocess 

### ISSUE THREAD

**Issue by pandasMX** [ppwwyyxx/tensorpack#724]
Hi,
I'm trying to use the dataflow only for my own model training. If there's only cv2.imread() in the dataflow implementation. Then where should I put the image_preprocess to subtract the mean pixel values for the image? Should it be done before image augmentation or after? Or both are ok? Thanks!

**Comment by ppwwyyxx** [comment]
What you want to do is up to your own choice.
Not a tensorpack question - closing -- unless you already know what you want to do but don't know how to do it in tensorpack.
