### ISSUE TITLE
Supporting TF datatypes from tensorpack frontend

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#725]
Feature Requests/Usage Question:

TF has many supported data types - FP16, 32, 64, etc. These are datatypes for convolution layer, fully connected layer, pooling layer, etc. It will be good if there a way to specify this from the tensorpack frontend, at least for the CONV layer.

Use case - this is allow experimenting with FP16 on Volta.

**Comment by PatWie** [comment]
I do not see the issue here. Are you referring to the Conv2D layer in tensorpack.model? It was communicated that the preferred way of writing models is using the official TF layer implementations like tf.layers.Conv2D. Conv2D is more or less a wrapper for TF.layers.
So this seems to be an unsupported feature there.

And you can always remap the get-variable calls with the var-utils.

**Comment by ppwwyyxx** [comment]
1. Tensorpack is a training interface agnostic of symbolic models. You can use whatever models - so different data types are already supported.

2. `tensorpack.models` is a small set of model implementation that exists mainly for historical reasons -- so don't expect any feature update there. You can use whatever other model implementation, such as `tf.layers`.

3. `tensorpack.models` uses `tf.layers` for many implementations already -- as a result it supports some other data types. I don't know what types `tf.layers` supports, but it supports fp16 at least. To use `tf.layers` with fp16 weights, just give it fp16 inputs. I've trained a lot of fp16 models with tensorpack.

**Comment by Skylion007** [comment]
Can't we just adapt a way to pass all remaining keyword args straight to the tf.layers implementation? Would future proof it as well and we wouldn't have this issue arise again.

**Comment by ppwwyyxx** [comment]
@Skylion007 I think that's a reasonable thing to do. I just hope to review those args and understand what they do before supporting them. I added this as a TODO in #627
