### ISSUE TITLE
Error when training Faster-R-CNN: Default MaxPoolingOp only supports NHWC.

### ISSUE THREAD

**Issue by ChaoWangHS** [ppwwyyxx/tensorpack#731]
Tensorflow :1.4.1
Tensorpack: 0.85
Python: 3.5.2

Here error log are  :
command:
`python train.py --load '/path/to/ImageNet-ResNet50.npz'`

> 

> Traceback (most recent call last):
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
>     return fn(*args)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
>     status, run_metadata)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC.
> 	 [[Node: tower0/pool0/MaxPool = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower0/Pad_1)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 410, in <module>
>     launch_train_with_config(cfg, trainer)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/interface.py", line 91, in launch_train_with_config
>     extra_callbacks=config.extra_callbacks)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/base.py", line 331, in train_with_defaults
>     steps_per_epoch, starting_epoch, max_epoch)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/base.py", line 303, in train
>     self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 182, in wrapper
>     return func(*args, **kwargs)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/base.py", line 268, in main_loop
>     self.run_step()  # implemented by subclass
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/base.py", line 181, in run_step
>     self.hooked_sess.run(self.train_op)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
>     run_metadata=run_metadata)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
>     run_metadata=run_metadata)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
>     raise six.reraise(*original_exc_info)
>   File "/home/xxx/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
>     run_metadata=run_metadata)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
>     run_metadata_ptr)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
>     options, run_metadata)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC.
> 	 [[Node: tower0/pool0/MaxPool = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower0/Pad_1)]]
> 
> Caused by op 'tower0/pool0/MaxPool', defined at:
>   File "train.py", line 410, in <module>
>     launch_train_with_config(cfg, trainer)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/interface.py", line 82, in launch_train_with_config
>     model._build_graph_get_cost, model.get_optimizer)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 182, in wrapper
>     return func(*args, **kwargs)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/tower.py", line 165, in setup_graph
>     train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/trainers.py", line 167, in _setup_graph
>     self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 213, in build
>     use_vs=[False] + [True] * (len(self.towers) - 1))
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 107, in build_on_towers
>     ret.append(func())
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/train/tower.py", line 192, in get_grad_fn
>     cost = get_cost_fn(*input.get_input_tensors())
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/tfutils/tower.py", line 207, in __call__
>     output = self._tower_fn(*args)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/graph_builder/model_desc.py", line 234, in _build_graph_get_cost
>     ret = self.build_graph(*inputs)
>   File "train.py", line 99, in build_graph
>     featuremap = pretrained_resnet_conv4(image, config.RESNET_NUM_BLOCK[:3])
>   File "/home/xxx/Faster-R-CNN/FasterRCNN/basemodel.py", line 102, in pretrained_resnet_conv4
>     l = MaxPooling('pool0', l, 3, strides=2, padding='VALID')
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/models/registry.py", line 124, in wrapped_func
>     outputs = func(*args, **actual_args)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/models/tflayer.py", line 65, in decorated_func
>     return func(inputs, **ret)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorpack/models/pool.py", line 35, in MaxPooling
>     ret = layer.apply(inputs, scope=tf.get_variable_scope())
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 671, in apply
>     return self.__call__(inputs, *args, **kwargs)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
>     outputs = self.call(inputs, *args, **kwargs)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/layers/pooling.py", line 266, in call
>     data_format=utils.convert_data_format(self.data_format, 4))
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1958, in max_pool
>     name=name)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2806, in _max_pool
>     data_format=data_format, name=name)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
>     op_def=op_def)
>   File "/home/xxx/tensorflowpython352/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> **InvalidArgumentError (see above for traceback): Default MaxPoolingOp only supports NHWC.**
> 	 [[Node: tower0/pool0/MaxPool = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower0/Pad_1)]]
> 
> PrefetchDataZMQ successfully cleaned-up.
> 

Thanks a lot.

**Comment by ppwwyyxx** [comment]
Gpu is required

**Comment by ChaoWangHS** [comment]
Thanks for your reply.
And I change command :
`python train.py --load '/path/to/ImageNet-ResNet50.npz' --gpu 0`
Error is same as above.

> Default MaxPoolingOp only supports NHWC.

**Comment by ppwwyyxx** [comment]
Either you don't have a nvidia GPU or your tensorflow is not built with GPU support.
Please run
```python
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
And make sure you can see a GPU device.

**Comment by ChaoWangHS** [comment]
Sorry,There is a problem with my GPU.
Thanks again. 👍
