### ISSUE TITLE
Is epoch number available in Dataflow?

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#732]
I want to do some curriculum learning, and the samples will change as the epoch number increases. Thanks!

**Comment by ppwwyyxx** [comment]
Dataflow is just a python generator - it should have no built-in concept about "training" or "machine learning".

You can write a callback which, after every epoch, change some attributes of your dataflow.

Be careful with some of the parallelism, though. Some parallel dataflow (e.g. PrefetchDataZMQ) create forks of a dataflow, so setting attributes on the original dataflow will not be effective.

**Comment by JesseYang** [comment]
Thanks!
