### ISSUE TITLE
The usage of dataflow

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#733]
Will the get_data() and the reset_state() method be called only once or at the beginning of each epoch?

I want to do some curriculum learning. If the get_data() method is called every epoch, then I can record the epoch index in it and change the data as epoch number increases. Currently I have a data set consists of millions of samples. I set the steps_per_epoch to 3000 and the batch size is 8. Thus each epoch only 24k samples are used. I want to use the simplest samples in the first epoch and increase the difficulty as the training goes. But it seems that in the beginning of the second epoch, get_data() is not called again.

**Comment by ppwwyyxx** [comment]
`reset_state` is called only once for each dataflow.
`get_data` is called after the iterator from the previous call reaches the end.

**Comment by JesseYang** [comment]
If PrefetchDataZMQ is used to start multiple processes to fetch data, will the `get_data` be called multiple times?

**Comment by ppwwyyxx** [comment]
`get_data` will be called in each process independently. In each process it is called the same way (called again after the iterator from the previous call reaches the end).
