### ISSUE TITLE
Is sess available in a Callback?

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#734]
I have written a callback Class inherited from Inferencer to calculate miou for a semantic segmentation model. I use the tf.metrics.mean_iou interface. Each time the graph is run, tf.metrics.mean_iou calculates the miou based on running variables and accumulates the running variables based on the new samples. Thus, the metric needs to be calculated after all samples are fed in. The following is an example copied from a blog:

```
tf_metric, tf_metric_update = tf.metrics.mean_iou(tf_label,
                                                      tf_prediction,
                                                      name="my_metric")

with tf.Session(graph=graph) as session:
    session.run(tf.global_variables_initializer())

    # initialize/reset the running variables
    session.run(running_vars_initializer)

    for i in range(n_batches):
        # Update the running variables on new batch of samples
        feed_dict={tf_label: labels[i], tf_prediction: predictions[i]}
        session.run(tf_metric_update, feed_dict=feed_dict)

    # Calculate the score
    miou = session.run(tf_metric)
```

I want to do the miou calculation in the _after_inference method. Is the sess available there?

**Comment by ppwwyyxx** [comment]
You can use `tf.get_default_session()`.

**Comment by ppwwyyxx** [comment]
Yes
