### ISSUE TITLE
increase layers in mixup implementation

### ISSUE THREAD

**Issue by deeplearningmachine** [ppwwyyxx/tensorpack#735]
How can I increase the layers in cifar10-preact18-mixup.py? For example, having the same layers as that of n=30 in cifar10-resnet.py.

**Comment by ppwwyyxx** [comment]
The model is pure tensorflow code and you change it in the same way you change a tensorflow model. For example you may want to change MODULE_SIZES in the for loop.

The two scripts are not comparable at all even with the same number of layers because the architecture have many other differences.

**Comment by deeplearningmachine** [comment]
Thanks!
