### ISSUE TITLE
keras-offlinepredictor

### ISSUE THREAD

**Issue by yzpick** [ppwwyyxx/tensorpack#739]
Can you please provide an example for how to use offlinepredictor in imagenet-resnet-keras.py? Thanks!

**Comment by ppwwyyxx** [comment]
PredictConfig can take a tower function and InputDesc. Both are already arguments of KerasModel in the example.

**Comment by yzpick** [comment]
Yes, I tried, but I don't specifically know what to put in the "output_names", since the variables are in Keras mode.

**Comment by ppwwyyxx** [comment]
Names are defined by Keras so I have no control. You can use `print` to see the name of a tensor, or use `tf.identity` to give a tensor an alias name.

**Comment by yzpick** [comment]
so I used the mnist-keras-v2.py to do the test, i print the model summary:
=================================================================
conv2d_1 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 32)        9248      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 14, 14, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 7, 7, 32)          0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 7, 7, 32)          9248      
_________________________________________________________________
flatten_1 (Flatten)          (None, 1568)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               803328    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
=================================================================
Total params: 836,522
Trainable params: 836,522
Non-trainable params: 0

-------------------------------------------------------------------------------------------------------------------
Then I directly use the "activation_1" layer name as the output name, but I still got the error:
KeyError: "The name 'activation_1:0' refers to a Tensor which does not exist. The operation, 'activation_1', does not exist in the graph."

But you can see activation_1 is in the model.

Any ideas why?

**Comment by ppwwyyxx** [comment]
Oh if you're using the mnist-keras-v2.py example -- it's not written with Keras's functional API (unlike imagenet-resnet-keras.py example). It is not very obvious to me how to get tensor's name with Keras's container API.

**Comment by yzpick** [comment]
sorry I am a bit confused, so you mean print(M.summary()) does not necessarily print the corresponding tensor name? I can use print(M.layers[10].name) but it still outputs "activation_1", what do you mean by print the tensor name? can you please directly give an offlinepredictor example that can be used in the mnist-v2?

**Comment by ppwwyyxx** [comment]
By "tensor" I mean `tf.Tensor`. A layer is not a tensor. Therefore a layer's name is not a tensor's name.
I just went through Keras's container API, and it looks like you can access a tensor with something like `M.layers[10].output`. There you can see the name of the tensor.

**Comment by ppwwyyxx** [comment]
I found some other issues using offlinepredictor for Keras models. I'll try to do a quick fix.

**Comment by ppwwyyxx** [comment]
There were some changes in the the arguments of "tower function" that was not updated in the Keras example.
Now you should be able to build a predictor in mnist-keras-v2.py like this:
```python
    pred = PredictConfig(
        tower_func=model_func, 
        inputs_desc=[
            InputDesc(tf.float32, [None, IMAGE_SIZE, IMAGE_SIZE, 1], 'images')
        ],
        input_names=['images'],
        output_names=['activation/Softmax']
    )
    pred = OfflinePredictor(pred)
```
To get tensor names from Keras, use something like `print(M.layers[10].output`.

**Comment by yzpick** [comment]
Thanks a lot Yuxin!
