### ISSUE TITLE
code for A3C stuck at iteration 0

### ISSUE THREAD

**Issue by yenchenlin** [ppwwyyxx/tensorpack#74]
Hello, thanks for the implementation!
However, when I typed:
`./train-atari.py --env Breakout-v0 --gpu 0`

It seems that the model didn't start to train:

<img width="1280" alt="screen shot 2016-12-27 at 11 31 06 am" src="https://cloud.githubusercontent.com/assets/7057863/21489658/0bdbdcd2-cc28-11e6-9a8e-84bdea9a6438.png">

Do you have any idea?
I'm using
```
tensorflow 0.12
cv2 3.1.0
```

**Comment by yenchenlin** [comment]
Oops I make it work!

**Comment by ppwwyyxx** [comment]
What was the problem?

**Comment by yenchenlin** [comment]
My original tf version is 0.11, and cv2 version is 2.4 (according to the dependencies on README)

**Comment by ppwwyyxx** [comment]
Version is the only change?
How did you install opencv?

**Comment by yenchenlin** [comment]
Hello @ppwwyyxx ,
I use `conda install -c https://conda.binstar.org/menpo opencv`

**Comment by ppwwyyxx** [comment]
So it is cv 2.4? Is it 2.4.11?
In the first message you said that your cv is 3.1.0

Anaconda packages are built by third-party and could have problems. 
This one is similar to #68. But here I assume you didn't modify any source code, so it's not a problem of exception.

**Comment by yenchenlin** [comment]
Yes, I just reinstalled it and your code works! (maybe it's problem on my side)

BTW, may I send a PR to specify that code [here](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/OpenAIGym)
needs

```
tensorflow 0.12
cv2 3.1
```

It's different with the prerequisites in tensorpack's README.

**Comment by ppwwyyxx** [comment]
TF0.11 and cv2.4 works fine for me. It's probably just a problem of anaconda.

**Comment by yenchenlin** [comment]
Oh I thought you used some summary features which are not included in TF 0.11?
Such as [this line](https://github.com/ppwwyyxx/tensorpack/blob/99362bfdbe2c52cf26abb5edec54e570b102d72d/tensorpack/tfutils/summary.py#L43), `tf.summary.histogram` can't be found in [TF0.11's summary API document page](https://www.tensorflow.org/versions/r0.11/api_docs/python/summary/).

**Comment by ppwwyyxx** [comment]
I see.. Now I updated the version.
