### ISSUE TITLE
How to initialize local variables in a callback?

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#740]
I need to calculate miou for test dataset. I have written a callback inherited from Inferencer. I use the tf.metrics.mean_iou interface. Since it is for streaming data, the related local variables need to be reset before the callback is called at each time. I define the operations in the graph as follow:

```
miou, miou_update_op = tf.metrics.mean_iou(label_flatten,
                                           pred_flatten,
                                           cfg.num_classes,
                                           weights=mask,
                                           name="metric_scope")
running_vars = tf.get_collection(tf.GraphKeys.LOCAL_VARIABLES, scope="metric_scope")
miou_reset_op = tf.variables_initializer(var_list=running_vars, name='miou_reset_op')
miou = tf.identity(miou, name='miou')
miou_update_op = tf.identity(miou_update_op, name='miou_update_op')
```

In the _before_inference/_after_inference methods in callback, I use
 ```
graph = tf.get_default_session().graph
reset_op = graph.get_operation_by_name('InferenceTower/miou_reset_op')
miou = .graph.get_tensor_by_name('InferenceTower/miou:0')
``` 
to get the operation and the miou tensor. But even if I do` tf.get_default_session().run(reset_op)`, the value of `tf.get_default_session().run(miou)` does not go back to 0. It seems that the local variables have not been initialized successfully.

**Comment by JesseYang** [comment]
I also tried to initialize all local variables by `sess.run(tf.local_variables_initializer())`. But it did not work.

**Comment by ppwwyyxx** [comment]
The ops definitely will run when you call sess.run
So the only explanation I see is that the op does not do what you expected it to do.

**Comment by JesseYang** [comment]
You are right! I just find out the reason, the initializer is defined to initialize variables with scope 'metric_scope'. But the correct scope should be 'InferenceTower/metric_scope'
