### ISSUE TITLE
Ten crop image augmentor

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#75]
Feature request: api for a ten crop image augmentor. 

Many papers report ten-crop test and validation error rates.

**Comment by ppwwyyxx** [comment]
An augmentor takes one item and produces one item only.

It can be made a simple utility function, or a dataset adapter.

**Comment by flydance0217** [comment]
Will it be possible to provide some suggestions on how you would implement that with minimal disruption to the original model in tensorpack. It seems to do the 10-crop test/validation, we need to support a 4D tensor where the tensor consists of the same validation image cropped at different location to the model, then average out the softmax output. 

However, it seems that imgaug.ImageAugmentor requiring the output to be a 3D array.
