### ISSUE TITLE
Predict with CycleGAN / DiscoGAN

### ISSUE THREAD

**Issue by mtoto** [ppwwyyxx/tensorpack#750]
What's the correct way to generate a new image with one of these style transfer algo's?  During training time I can see the transformed images in tensorboard, but is there a simple way to use a trained model and generate images for unseen data?

**Comment by ppwwyyxx** [comment]
https://github.com/ppwwyyxx/tensorpack/blob/712fd299805f04c4095ad80509f94ff7db245ff6/examples/GAN/DCGAN.py#L122-L134

**Comment by Skylion007** [comment]
I have some code to this lying around somewhere. I can add it in at some point.
