### ISSUE TITLE
ResNet too big to fit into one GPU

### ISSUE THREAD

**Issue by deeplearningmachine** [ppwwyyxx/tensorpack#751]
I tailored the ResNet model a bit by increasing the number of filters, but it seems the model becomes too big to fit into one GPU (I got the OOM error). Any advice on fit the model into one GPU or multi GPUs?

**Comment by ppwwyyxx** [comment]
You can use small batch size per GPU.

**Comment by deeplearningmachine** [comment]
If I use four GPUs each with batch size of 16. Will that be similar to run the network on one GPU with batch size of 64?

**Comment by ppwwyyxx** [comment]
Similar. See http://tensorpack.readthedocs.io/tutorial/trainer.html#multigpu-trainers
