### ISSUE TITLE
where does print_tensor() be visible

### ISSUE THREAD

**Issue by XiangyuWu** [ppwwyyxx/tensorpack#767]
Hi, ppwwyyxx!
    I see your response for [#12](https://github.com/ppwwyyxx/tensorpack/issues/12) about how to get the output of each layer. However, when I used .print_tensor() after a layer, it seems to make nothing different compared to without using it. Is it visible in the terminal? Or what can I do to get the activate of one layer.
    Thank you for your answering!

**Comment by XiangyuWu** [comment]
![image](https://user-images.githubusercontent.com/38173114/40176773-187ca3c4-5a0f-11e8-8cd6-e34e1c39d148.png)
And this is where I implement .print_tensor().

**Comment by ppwwyyxx** [comment]
Paste full logs please

**Comment by XiangyuWu** [comment]
![image](https://user-images.githubusercontent.com/38173114/40212185-49694524-5a81-11e8-8e6d-29635b66d7cd.png)
The initialization logs of gpu were ignored. As you can see, the project would begin to process the epochs after I run _python svhn-digit-dorefa-bias.py_, but no tensor values were printed. What's more, though I added _sys.exit()_ sentence in your definition of _print_tensor()_ in tensorpack/models/linearwrap.py, it also seemed to make no sense.
![image](https://user-images.githubusercontent.com/38173114/40212389-36f4ae00-5a82-11e8-9945-7249e35dd530.png)
I am not familiar with your framework, so thanks for your help.

**Comment by ppwwyyxx** [comment]
`print_tensor()` is not for printing the value of the tensor. According to #12 it is for printing the name of the tensor. To print values during training, see [FAQ](http://tensorpack.readthedocs.io/tutorial/faq.html#how-to-print-dump-intermediate-results-in-training).

It's impossible that adding `sys.exit()` has no effect -- I think you're not running the code you're modifying.

**Comment by XiangyuWu** [comment]
I got it!
What indeed help to print tensor values easily in your framework is _ProcessTensors()_. 

And for _sys.exit()_ problem, probably I made some mistakes.
