### ISSUE TITLE
question about train-error and val-error

### ISSUE THREAD

**Issue by ChaoWangHS** [ppwwyyxx/tensorpack#769]
I train ImageNetModels/vgg16.py from scratch. However, train-error-top5 and val-error-top5 's difference is large.
train log:

![tim 20180519142758](https://user-images.githubusercontent.com/36892165/40265743-e8dd38c8-5b70-11e8-82b8-3881e45ac95d.png)
![tim 20180519142807](https://user-images.githubusercontent.com/36892165/40265744-e9174338-5b70-11e8-9f66-684134a9681d.png)

Is this normal? Thanks a lot.

**Comment by ppwwyyxx** [comment]
It is.
