### ISSUE TITLE
initialized weights/params

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#77]
In the DoReFa paper, there are experiments where the training starts with initialized parameters (e.g. 32b weights).

Is there a clean way to do this currently in tensorpack without having to save/restore the model parameters?
The way I am currently doing this is (step-1) Train with dorefa 32,32,32 for 15 epochs and save the model (step-2) restore the model and start training with dorefa 1,2,6.

**Comment by ppwwyyxx** [comment]
It's already quite easy to do transfer learning, compared to other frameworks. It's just a `--load`.

There are automatic ways within the framework, e.g. you can define both models and use an input to choose which model to use. But this is not easier.

If you just don't want to stop in the middle, you can write them together, with something like:
```python
Trainer(config1).train()  # max_epoch=15
Trainer(config2).train()  # sess_init=....
```

**Comment by a-maci** [comment]
Thanks. 

Will I have any name-scope clashing if I do and would the weights be shared between these two configs:?

config1 = get_config()
config2 = get_config() # again
Trainer(config1).train() # max_epoch=15 Trainer(config2).train() #


The goal is to train a network with full precision for (say) 15 iterations and then switch to BWN after this. During this process I don't want to save/restore the model weights after the 15th iteration. 

Thanks.

**Comment by ppwwyyxx** [comment]
The idea is that config2 is different from config1 (it's a different graph). And config2 contains the loader of the model saved by trainer1.

**Comment by a-maci** [comment]
Thanks.
