### ISSUE TITLE
multiple GPUs for ResNet

### ISSUE THREAD

**Issue by deeplearningmachine** [ppwwyyxx/tensorpack#775]
How can I train the ResNet + mixup model in cifar10-preact18-mixup.py with multiple GPUs?

**Comment by ppwwyyxx** [comment]
Change `SimpleTrainer` to something else.
http://tensorpack.readthedocs.io/modules/train.html

**Comment by deeplearningmachine** [comment]
doing so, the permutation for the mixup could be incorrect? That is, you will have smaller BATCH_SIZE for the permutation?

**Comment by ppwwyyxx** [comment]
The permutation will be per-datapoint, i.e. a datapoint is a unit that's sent to one GPU.
If you want to permute over larger batches you can write a dataflow that mixes more images than it yields every time.

**Comment by deeplearningmachine** [comment]
If the batch size is 128 and 2 GPUs are used, then each GPU will has a batchsize of 64. That is, the permutation of mixup will use a batch of 64 images. Is that correct? Any example of "write a dataflow that mixes more images than it yields every time"? Thanks a lot!

**Comment by ppwwyyxx** [comment]
I don't know what do you mean by "batch size" because the term is ambiguous under the context of multi gpu training. But the tutorial should have an answer to your question: http://tensorpack.readthedocs.io/tutorial/trainer.html#multigpu-trainers 

To write a dataflow, see http://tensorpack.readthedocs.io/tutorial/extend/dataflow.html . You can first use `BatchData` with a larger batch and then a custom dataflow to split them and yield.

**Comment by deeplearningmachine** [comment]
Did you mean the following?

ds = BatchData(ds, batch, remainder=not isTrain)
ds=split(ds)

**Comment by ppwwyyxx** [comment]
Exactly.

**Comment by deeplearningmachine** [comment]
Any build-in function for the split? Also, is it possible to have two batches during test phase: one from BatchData(testing data) and the other from BatchData(training data)?

**Comment by ppwwyyxx** [comment]
> Any build-in function for the split? 

No. It should be like 10 lines of code.

> Also, is it possible to have two batches during test phase

I don't understand what this means. Could you describe in details what you want to do?

**Comment by deeplearningmachine** [comment]
During the test phase, when I have a batch of data points for testing, I would like to randomly add some data points from the training set (ideally, a small batch from the training data).

**Comment by ppwwyyxx** [comment]
You can write a dataflow that does this, like `ds = mix(test_ds, train_ds)`

**Comment by deeplearningmachine** [comment]
Can I code something like this?

def get_data(train_or_test, isMixup, alpha):
    ds_test = dataset.Cifar10(test)
    ds_train = dataset.Cifar10(train)
   ds_test = BatchData(ds_test, batch, remainder=not isTrain)
   ds_train = BatchData(ds_train, batch, remainder=not isTrain)
   mix(ds_test,ds_train)

**Comment by ppwwyyxx** [comment]
Sure! This looks right

**Comment by deeplearningmachine** [comment]
Thanks!  Any chance I can have two batches of data points when calling BatchData? 
That is, when I call  ds = BatchData(ds, batch, remainder=not isTrain), I would like the ds returns two random batches of data points.

**Comment by deeplearningmachine** [comment]
Can I retrieve two batches of data points from BatchData(ds, batch)?

**Comment by ppwwyyxx** [comment]
```python
itr = ds.get_data()
data1 = next(itr)
data2 = next(itr)
```
will retrieve two datapoints from ds.

**Comment by deeplearningmachine** [comment]
Thanks a lot!!

**Comment by deeplearningmachine** [comment]
Can I define that "itr" within the get_data() function?

def get_data(train_or_test, isMixup, alpha):
    ds = dataset.Cifar10(train_or_test)
    batch = BATCH_SIZE
    ds = BatchData(ds, batch, remainder=not isTrain)

**Comment by ppwwyyxx** [comment]
The top level `get_data()` function in the script defines and returns a dataflow. It does not take data from a dataflow -- that will happen when training starts.

The tutorial has a section about writing such dataflow: http://tensorpack.readthedocs.io/tutorial/extend/dataflow.html#more-data-processing .
Please refer to `JoinData` or `ConcatData` if it's not clear enough, e.g. http://tensorpack.readthedocs.io/_modules/tensorpack/dataflow/common.html#ConcatData

**Comment by deeplearningmachine** [comment]
Many thanks!
